import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
test('banking navigation mounts accounts, transactions, reconciliation and settings in the dashboard workspace',()=>{const nav=readFileSync('src/Navigation.jsx','utf8'),app=readFileSync('src/App.jsx','utf8');for(const value of ['Bank Accounts','Bank Transactions','Bank Reconciliation','Banking Settings'])assert.ok(nav.includes(value));assert.ok(app.includes("<Banking key={a} page={a}"));assert.ok(!nav.includes("<Banking key={active}"))});
test('reconciliation has saved creation, import, matching, exception, locking and centralized help workflows',()=>{const page=readFileSync('src/BankReconciliation.jsx','utf8'),settings=readFileSync('src/BankingSettings.jsx','utf8'),service=readFileSync('src/banking-service.js','utf8'),knowledge=readFileSync('src/page-knowledge.js','utf8');for(const value of ['New Reconciliation','Create Reconciliation','Import CSV / Excel','Auto match','Create receipt','Create expense','Complete reconciliation','Reconciliation history','HelpDrawer','PageGuide','DisabledActionReason'])assert.ok(page.includes(value),value);assert.ok(knowledge.includes("'Bank Reconciliation'"));for(const value of ['Matching Rules','Create matching rule'])assert.ok(settings.includes(value),value);for(const value of ['Unlock Reconciliation','Export Report'])assert.ok(service.includes(value),value)});
test('contextual help drawer is isolated from the fixed dashboard sidebar',()=>{const css=readFileSync('src/contextual-help.css','utf8'),component=readFileSync('src/ContextualHelp.jsx','utf8');for(const token of ['inset:58px 0 0 250px!important','justify-content:flex-end!important','margin:0 0 0 auto!important','position:relative!important'])assert.ok(css.includes(token),token);for(const token of ['About This Page','StatusExplanation','AccountingImpactCard','Related Settings','Common Issues','Related Pages'])assert.ok(component.includes(token),token)});
test('banking grid exposes statement and matching context',()=>{const page=readFileSync('src/Banking.jsx','utf8');for(const label of ['Transaction date','Value date','Bank account','Reference','Description','Debit','Credit','Balance','Category','Match status','Linked transaction','Reconciliation','Actions'])assert.ok(page.includes(label),label)});
test('banking follows review, match or categorize, and reconcile workflow',()=>{const page=readFileSync('src/Banking.jsx','utf8');for(const label of ['For review','Matched','Excluded','Bank feed','Reconciliation status','Must be ₹0.00'])assert.ok(page.includes(label),label)});
test('banking layout avoids overlap and provides labelled mobile transaction cards',()=>{const base=readFileSync('src/banking.css','utf8'),shell=readFileSync('src/banking-shell.css','utf8'),page=readFileSync('src/Banking.jsx','utf8');assert.ok(base.includes('.bankTable{overflow-x:auto}'));assert.ok(shell.includes('@media (max-width: 700px)'));assert.ok(shell.includes('content: attr(data-label)'));assert.ok(page.includes('data-label="Description"'))});
test('banking dialogs use isolated standard form, button, icon, and accessibility contracts',()=>{const shell=readFileSync('src/banking-shell.css','utf8'),page=readFileSync('src/Banking.jsx','utf8');for(const token of ['.bankOverlay .bankDialog > header','.bankDialogBody','.bankFormGrid input:focus','.bankDialog > footer .bankSecondary'])assert.ok(shell.includes(token),token);for(const token of ['role="dialog"','aria-modal="true"','aria-labelledby="bank-account-title"','aria-labelledby="bank-transfer-title"','IconEdit','IconCheck'])assert.ok(page.includes(token),token)});
test('banking page header and account actions cannot inherit legacy browser controls',()=>{const shell=readFileSync('src/banking-shell.css','utf8');for(const token of ['.bankPage > .bankHead','position: static !important','.bankSearch:focus-within','.bankAccountGrid footer button','.bankPage > .bankHead .primary'])assert.ok(shell.includes(token),token)});
test('banking desktop and mobile headers remain inside the dashboard content boundary',()=>{const shell=readFileSync('src/banking-shell.css','utf8');for(const token of ['inset: auto !important','border-top: 3px solid #3478f6','.bankPage > .bankHead button:not(.primary)', 'grid-template-columns: repeat(auto-fit, minmax(360px, 540px))'])assert.ok(shell.includes(token),token)});
test('banking settings tabs override legacy global navigation sizing',()=>{const css=readFileSync('src/banking-settings.css','utf8');for(const token of ['.bankSettingsNav{display:flex;width:100%;height:auto;min-height:50px','overflow-y:hidden','.bankSettingsNav button{width:auto;height:38px','white-space:nowrap'])assert.ok(css.includes(token),token)});
test('banking demo exposes account reconciliation context and completed history',()=>{const page=readFileSync('src/Banking.jsx','utf8');for(const token of ['Unreconciled amount','Last reconciled','Reconciliation history','Statement balance','Reconciled by'])assert.ok(page.includes(token),token)});
test('bank transactions default to an all-account feed without losing account filtering',()=>{const page=readFileSync('src/Banking.jsx','utf8');for(const token of ["page==='Bank Transactions'?'all'","<option value=\"all\">All bank accounts</option>","[feedFilter,setFeedFilter]=useState('All')",'scopeAccounts.flatMap','accountName:bank.accountName'])assert.ok(page.includes(token),token)});

