import test from 'node:test';
import assert from 'node:assert/strict';
import {initial} from '../src/invoice-engine.js';
import {autoMatchReconciliation,bookBalance,bookTransactions,completeReconciliation,createBankingDemo,createReconciliation,createStatementEntry,excludeStatement,importStatement,initialBanking,matchStatement,parseStatementCsv,reconciliationDetails,reconciliationSummary,saveBankAccount,transferMoney,unlockReconciliation} from '../src/banking-service.js';

const state=()=>{const value=initial();value.accounts=[{code:'1000',name:'Cash',type:'Assets',nature:'Debit',active:true,isGroup:false}];return value};
const bank=(banking,accounting,name='HDFC Current')=>saveBankAccount(banking,accounting,{bankName:'HDFC Bank',accountName:name,accountType:'Current Account',currency:'INR',status:'Active'});

test('bank account creates and links one Chart of Accounts posting ledger',()=>{const out=bank(initialBanking(),state());assert.equal(out.banking.bankAccounts[0].accountCode,out.accounting.accounts.at(-1).code);assert.equal(out.accounting.accounts.at(-1).type,'Assets');assert.equal(bookBalance(out.accounting,out.record.accountCode),0)});
test('bank transfer posts a balanced internal journal and updates both book balances',()=>{let first=bank(initialBanking(),state(),'HDFC Current'),second=bank(first.banking,first.accounting,'ICICI Current'),out=transferMoney(second.banking,second.accounting,{fromAccountId:first.record.id,toAccountId:second.record.id,date:'2026-09-07',amount:'1000',reference:'TRF-1'});assert.equal(out.journal.source,'Bank Transfer');assert.equal(out.journal.lines.reduce((n,row)=>n+row.debit-row.credit,0),0);assert.equal(bookBalance(out.accounting,first.record.accountCode),-100000);assert.equal(bookBalance(out.accounting,second.record.accountCode),100000)});
test('statement import is non-posting, duplicate-safe, and supports matching without another journal',()=>{const out=bank(initialBanking(),state()),rows=parseStatementCsv('Date,Transaction Reference,Description,Debit,Credit,Balance\n2026-09-07,UTR-1,Customer,0,500,500'),imported=importStatement(out.banking,out.record.id,rows),duplicate=importStatement(imported.banking,out.record.id,rows);assert.equal(imported.imported,1);assert.equal(duplicate.imported,0);assert.equal(out.accounting.journals.length,0);const book={id:'book-1',journalId:'journal-1',date:'2026-09-07',moneyIn:50000,moneyOut:0},matched=matchStatement(imported.banking,imported.banking.bankTransactions[0].id,book);assert.equal(matched.banking.bankTransactions[0].status,'Matched');assert.equal(out.accounting.journals.length,0)});
test('unmatched bank charge creates one journal, matches statement, and reconciliation keeps book and bank balances distinct',()=>{let out=bank(initialBanking(),state()),imported=importStatement(out.banking,out.record.id,[{date:'2026-09-07',reference:'CHG-1',description:'Bank charge',debit:'50',credit:'',balance:'950'}]),created=createStatementEntry(imported.banking,out.accounting,imported.banking.bankTransactions[0].id,'Bank charge'),summary=reconciliationSummary(created.banking,created.accounting,out.record.id,{to:'2026-09-07'});assert.equal(created.accounting.journals.length,1);assert.equal(created.banking.bankTransactions[0].status,'Matched');assert.equal(summary.bookBalance,-5000);assert.equal(summary.bankBalance,95000);assert.equal(summary.difference,100000);assert.equal(bookTransactions(created.accounting,out.record).length,1)});
test('inactive accounts reject new transfers and unmatched transactions can be excluded',()=>{let first=bank(initialBanking(),state(),'One'),second=bank(first.banking,first.accounting,'Two');second.banking.bankAccounts[0].status='Inactive';assert.throws(()=>transferMoney(second.banking,second.accounting,{fromAccountId:first.record.id,toAccountId:second.record.id,date:'2026-09-07',amount:'1'}),/Inactive/);const imported=importStatement(first.banking,first.record.id,[{date:'2026-09-07',description:'Ignore',debit:'1',credit:''}]),excluded=excludeStatement(imported.banking,imported.banking.bankTransactions[0].id);assert.equal(excluded.bankTransactions[0].status,'Excluded')});
test('demo flow is balanced, connected, useful for matching, and idempotent',()=>{const out=createBankingDemo(initialBanking(),state()),again=createBankingDemo(out.banking,out.accounting),hdfc=out.banking.bankAccounts.find(row=>row.accountCode==='1010'),icici=out.banking.bankAccounts.find(row=>row.accountCode==='1020'),summary=reconciliationSummary(out.banking,out.accounting,hdfc.id,{to:'2026-09-07'});assert.equal(out.created,true);assert.equal(again.created,false);assert.equal(out.accounting.journals.every(entry=>entry.lines.reduce((n,line)=>n+line.debit-line.credit,0)===0),true);assert.equal(out.banking.bankTransactions.filter(row=>row.status==='Matched').length,4);assert.equal(out.banking.bankTransactions.filter(row=>row.status==='Unmatched').length,2);assert.equal(out.banking.reconciliations.length,2);assert.equal(out.banking.reconciliations.every(row=>row.status==='Reconciled'&&row.difference===0),true);assert.equal(out.banking.bankTransactions.some(row=>row.bankAccountId===icici.id&&row.reference==='TRF-DEMO-001'&&row.status==='Matched'),true);assert.equal(summary.difference,150000)});
test('demo enrichment preserves an existing bank ledger and avoids its account code',()=>{const base=initialBanking(),books=state();books.accounts.push({code:'1010',name:'Existing Bank',type:'Assets',nature:'Debit',active:true,isGroup:false});base.bankAccounts.push({id:'existing-bank',bankName:'Existing',accountName:'Existing Bank',accountType:'Current Account',currency:'INR',status:'Active',accountCode:'1010'});const out=createBankingDemo(base,books),demo=out.banking.bankAccounts.filter(row=>row.demo);assert.equal(demo.length,2);assert.equal(demo.some(row=>row.accountCode==='1010'),false);assert.equal(new Set(out.banking.bankAccounts.map(row=>row.accountCode)).size,out.banking.bankAccounts.length);assert.equal(out.accounting.journals.every(entry=>entry.lines.reduce((n,row)=>n+row.debit-row.credit,0)===0),true)});
test('saved reconciliation imports, auto matches, completes, locks and permission-controls unlock',()=>{let base=bank(initialBanking(),state()),books=base.accounting;books.journals.push({id:'j1',number:'R1',reference:'R1',date:'2026-09-07',createdAt:'2026-09-07T10:00:00Z',status:'Posted',source:'Receipt',lines:[{account:base.record.accountCode,debit:50000,credit:0,description:'Customer receipt'},{account:'1000',debit:0,credit:50000}]});let made=createReconciliation(base.banking,books,{bankAccountId:base.record.id,financialYear:'FY 2026–27',periodFrom:'2026-09-01',periodTo:'2026-09-07'}),loaded=importStatement(made.banking,base.record.id,[{date:'2026-09-07',reference:'R1',description:'Customer receipt',debit:'',credit:'500',balance:'500'}],{reconciliationId:made.reconciliation.id}),matched=autoMatchReconciliation(loaded.banking,books,made.reconciliation.id),detail=reconciliationDetails(matched.banking,books,made.reconciliation.id);assert.equal(matched.matched,1);assert.equal(detail.difference,0);const completed=completeReconciliation(matched.banking,books,made.reconciliation.id);assert.equal(completed.reconciliation.status,'Locked');assert.throws(()=>importStatement(completed.banking,base.record.id,[{date:'2026-09-07',description:'Late',debit:'1',credit:''}],{reconciliationId:made.reconciliation.id}),/Unlock/);assert.throws(()=>unlockReconciliation(completed.banking,made.reconciliation.id,{reason:'Correction'}),/permission/);assert.equal(unlockReconciliation(completed.banking,made.reconciliation.id,{canUnlock:true,reason:'Correction'}).reconciliation.status,'In Progress')});
