import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initial,seedAccounts,command,reports,outstanding} from '../src/invoice-engine.js';
import {creditCommand,creditLine,available,adjustmentStatus,customerCreditSummary,customerStatement,gstDocuments,creditInvoiceEligibility} from '../src/credit-note-service.js';
const seed={Assets:[['ar','Receivable'],['bank','Bank']],Income:[['sales','Sales'],['returns','Sales adjustment']],Liabilities:[['gst','GST']]};
function setup(){let s=seedAccounts(initial(),seed);s.config={...s.config,ar:'ar',sales:'sales',cgst:'gst',sgst:'gst',igst:'gst',cess:'gst',creditMappings:{salesAdjustment:'returns',salesReturn:'returns',otherAdjustment:'returns'}};let d=command(s,'save',{date:'2026-09-04',dueDate:'2026-10-04',customerId:'xyz',customerName:'XYZ Solutions',place:'Kerala',lines:[{description:'Service',qty:'1',unit:'service',rate:'100000',discount:'0',discountType:'%',tax:'18',cess:'0'}]});s=command(d.state,'post',{id:d.result.id}).state;return {s,i:s.invoices[0]}}
function create(s,i,rate='20000',reason='Price Adjustment'){return creditCommand(s,'save',{customerId:i.customerId,originalInvoiceId:i.id,date:'2026-09-04',reason,place:i.place,lines:[{...creditLine(i,0),rate}]})}
function issue(s,c){s=creditCommand(s,'submit',{id:c.id}).state;s=creditCommand(s,'approve',{id:c.id}).state;return creditCommand(s,'issue',{id:c.id}).state}
test('credit lifecycle posts once, reports and statement reconcile; allocations do not double post',()=>{let {s,i}=setup();let d=create(s,i);assert.equal(d.result.totals.total,2360000);assert.equal(d.result.totals.cgst+d.result.totals.sgst,360000);assert.equal(d.state.journals.length,1);s=issue(d.state,d.result);const c=s.creditNotes[0];assert.equal(customerCreditSummary(s,'xyz').outstanding,9440000);assert.equal(reports(s).assets,9440000);assert.equal(reports(s).revenue,8000000);assert.equal(reports(s).debit,reports(s).credit);assert.equal(customerStatement(s,'xyz').at(-1).balance,9440000);assert.equal(gstDocuments(s).filter(x=>x.kind==='Credit Note').length,1);assert.equal(creditCommand(s,'issue',{id:c.id}).state.journals.length,2);const p={id:c.id,date:'2026-09-04',token:'first',allocations:[{invoiceId:i.id,amount:'10000'}]};s=creditCommand(s,'apply',p).state;assert.equal(available(s,c),1360000);assert.equal(adjustmentStatus(s,c),'Partially Applied');assert.equal(outstanding(s,i),10800000);assert.equal(customerCreditSummary(s,'xyz').outstanding,9440000);assert.equal(s.journals.length,2);assert.equal(creditCommand(s,'apply',p).state.creditApplications.length,1);s=creditCommand(s,'apply',{...p,token:'second',allocations:[{invoiceId:i.id,amount:'13600'}]}).state;assert.equal(adjustmentStatus(s,c),'Fully Applied');assert.equal(outstanding(s,i),9440000);assert.equal(s.journals.length,2);s=creditCommand(s,'cancel',{id:c.id,reason:'Duplicate'}).state;assert.equal(outstanding(s,i),11800000);assert.equal(customerCreditSummary(s,'xyz').outstanding,11800000);assert.equal(s.journals.length,3);assert.equal(s.creditApplications.filter(a=>!a.voided).length,0)});
test('excess credits, duplicate number, quantity and missing mappings are rejected atomically',()=>{let {s,i}=setup();assert.throws(()=>create(s,i,'100001'),/exceeds|remaining/);const d=create(s,i);assert.throws(()=>creditCommand(d.state,'save',{...d.result,id:undefined}),/already exists/);s=issue(d.state,d.result);assert.throws(()=>create(s,i,'90000'),/exceeds/);assert.throws(()=>creditCommand(s,'save',{...s.creditNotes[0],notes:'edit'}),/draft/);assert.throws(()=>creditCommand(s,'apply',{id:d.result.id,date:'2026-09-04',token:'excess',allocations:[{invoiceId:i.id,amount:'30000'}]}),/available/);const d2=create(s,i,'10000');s=creditCommand(d2.state,'submit',{id:d2.result.id}).state;s=creditCommand(s,'approve',{id:d2.result.id}).state;s.config.creditMappings={};assert.throws(()=>creditCommand(s,'issue',{id:d2.result.id}),/Configure/);assert.equal(s.journals.length,2);assert.throws(()=>creditCommand(s,'save',{customerId:i.customerId,originalInvoiceId:i.id,date:'2026-09-04',place:i.place,reason:'Sales Return',lines:[{...creditLine(i,0),qty:'2',rate:'1000'}]}),/quantity/)});
test('tax-only adjustment reduces tax not revenue; cancellation prevents application',()=>{let {s,i}=setup();const d=create(s,i,'20000','Tax Adjustment');assert.equal(d.result.totals.taxable,0);assert.equal(d.result.totals.total,360000);s=issue(d.state,d.result);assert.equal(reports(s).revenue,10000000);s=creditCommand(s,'cancel',{id:d.result.id,reason:'Correction'}).state;assert.throws(()=>creditCommand(s,'apply',{id:d.result.id,date:'2026-09-04',token:'x',allocations:[{invoiceId:i.id,amount:'10'}]}),/issued/)});
test('price and return credits inherit source invoice tax rates',()=>{const {s,i}=setup(),line={...creditLine(i,0),rate:'1000',taxes:{cgst:18,sgst:18,igst:0,cess:0}},saved=creditCommand(s,'save',{customerId:i.customerId,originalInvoiceId:i.id,date:i.date,reason:'Price Adjustment',place:i.place,lines:[line]});assert.equal(saved.result.totals.cgst,9000);assert.equal(saved.result.totals.sgst,9000);assert.equal(saved.result.totals.total,118000)});
test('credit applies to another invoice for the same customer, never across customers',()=>{let {s,i}=setup();const d=create(s,i);s=issue(d.state,d.result);const next=command(s,'save',{date:i.date,dueDate:i.dueDate,customerId:i.customerId,customerName:i.customerName,place:i.place,lines:[{...i.lines[0],rate:'40000'}]});s=command(next.state,'post',{id:next.result.id}).state;const count=s.journals.length;s=creditCommand(s,'apply',{id:d.result.id,date:i.date,token:'other-invoice',allocations:[{invoiceId:next.result.id,amount:'10000'}]}).state;assert.equal(outstanding(s,s.invoices.find(x=>x.id===next.result.id)),3720000);assert.equal(available(s,s.creditNotes.find(c=>c.id===d.result.id)),1360000);assert.equal(s.journals.length,count);assert.equal(customerStatement(s,'xyz').at(-1).source,'Credit Application');const wrong=command(s,'save',{date:i.date,dueDate:i.dueDate,customerId:'different',customerName:'Different customer',place:i.place,lines:i.lines});s=command(wrong.state,'post',{id:wrong.result.id}).state;assert.equal(creditInvoiceEligibility(s,s.creditNotes[0],wrong.result).reason,'Different customer');assert.throws(()=>creditCommand(s,'apply',{id:d.result.id,date:i.date,token:'wrong',allocations:[{invoiceId:wrong.result.id,amount:'100'}]}),/Different customer/);assert.throws(()=>command(s,'cancel',{id:i.id,reason:'Delete source'}),/credit notes/);s=creditCommand(s,'cancel',{id:d.result.id,reason:'Correction'}).state;const rows=gstDocuments(s).filter(x=>x.id===d.result.id||x.sourceDocumentId===d.result.id);assert.equal(rows.length,2);assert.equal(rows.reduce((n,x)=>n+x.sign*x.totals.total,0),0)});
