import test from 'node:test';
import assert from 'node:assert/strict';
import {initial} from '../src/invoice-engine.js';
import {createAsset,createBudget,createCategory,createExpense,postDepreciation,seedOperations} from '../src/operations-store.js';

const accounting=()=>{const state=initial();state.accounts=[];return state};
test('expense posting creates one balanced journal through the shared engine',()=>{const out=createExpense(seedOperations(),accounting(),{date:'2026-09-07',name:'Hosting',category:'Software',amount:'11800',account:'5600',paidThrough:'1010',payee:'Cloud Co'});assert.equal(out.record.status,'Posted');assert.equal(out.journal,undefined);const entry=out.accounting.journals.at(-1);assert.equal(entry.source,'Expense');assert.equal(entry.lines.reduce((n,x)=>n+x.debit-x.credit,0),0)});
test('category, asset, and budget masters persist user-facing values',()=>{let store=seedOperations();store=createCategory(store,{name:'Repairs',account:'5900',tax:'GST 18%',status:'Active'});store=createAsset(store,{name:'Printer',category:'Computer equipment',purchaseDate:'2026-09-07',cost:'25000'});store=createBudget(store,{name:'Repairs budget',account:'Operating Expenses',amount:'100000',period:'Yearly'});assert.equal(store.categories[0].name,'Repairs');assert.equal(store.assets[0].bookValue,2500000);assert.equal(store.budgets[0].amount,10000000)});
test('depreciation updates asset values and posts a balanced journal',()=>{const store=seedOperations(),asset=store.assets[0],before=asset.bookValue,out=postDepreciation(store,accounting(),asset.id,'1000');assert.equal(out.store.assets.find(x=>x.id===asset.id).bookValue,before-100000);assert.equal(out.journal.lines.reduce((n,x)=>n+x.debit-x.credit,0),0);assert.equal(out.store.assetTransactions[0].type,'Depreciation')});
test('asset acquisition posts fixed asset against bank or payable through the shared ledger',()=>{const cash=createAsset(seedOperations(),{name:'Printer',category:'Computer equipment',purchaseDate:'2026-09-07',cost:'25000',assetAccount:'1300',purchaseMode:'Paid now',paymentAccount:'1010'},accounting()),credit=createAsset(seedOperations(),{name:'Server',category:'Computer equipment',purchaseDate:'2026-09-07',cost:'50000',assetAccount:'1300',purchaseMode:'On credit',payableAccount:'2000'},accounting());for(const out of [cash,credit]){assert.equal(out.journal.source,'Asset Acquisition');assert.equal(out.journal.lines.reduce((n,x)=>n+x.debit-x.credit,0),0);assert.equal(out.store.assetTransactions[0].status,'Posted');assert.equal(out.store.assetTransactions[0].journalId,out.journal.id)}assert.ok(cash.journal.lines.some(x=>x.account==='1010'&&x.credit===2500000));assert.ok(credit.journal.lines.some(x=>x.account==='2000'&&x.credit===5000000))});
