import test from 'node:test';
import assert from 'node:assert/strict';
import {calculatePurchase,savePurchaseOrder,savePurchaseBill,convertPurchaseOrder,postPurchaseBill,advancePurchaseOrder,createGoodsReceipt,recordPurchasePayment,cancelPurchaseBill,saveDebitNote,submitDebitNote,approveDebitNote,issueDebitNote,applyDebitNote,voidDebitNote,vendorOutstanding,vendorLedger,purchaseTaxDocuments} from '../src/purchase-service.js';

const line={id:'l1',itemId:'item-1',description:'Laptop',qty:'5',unit:'pcs',rate:'50000',discount:'0',taxRate:'18',cessRate:'0',priceTaxMode:'exclusive',purchaseAccount:'5000'};
const vendor={vendorId:'ven-1',vendorName:'ABC Technologies',date:'2026-09-05',dueDate:'2026-10-05',paymentTerms:'30 Days',lines:[line],payableAccount:'2000',inputTaxAccount:'1400'};
const accounting={version:1,invoices:[],payments:[],purchaseBills:[],vendorPayments:[],journals:[],audit:[],accounts:[{code:'1010',name:'Bank',type:'Assets',active:true},{code:'5000',name:'Purchase',type:'Expenses',active:true},{code:'1400',name:'Input GST',type:'Assets',active:true},{code:'2000',name:'Accounts Payable',type:'Liabilities',active:true}],config:{}};

test('purchase order calculates totals but creates no accounting entry',()=>{const output=savePurchaseOrder([],{...vendor,number:'',expectedDate:'2026-09-10'},'Draft');assert.equal(output.order.number,'PO-00001');assert.equal(output.order.total,29500000);assert.equal('journalId' in output.order,false)});
test('purchase bill rejects a duplicate vendor invoice number',()=>{const first=savePurchaseBill([],{...vendor,number:'',vendorInvoice:'ABC/100'},'Draft');assert.throws(()=>savePurchaseBill(first.rows,{...vendor,number:'',vendorInvoice:'abc/100'},'Draft'),/already exists/)});
test('purchase workflow requires open and receipt before bill conversion',()=>{const order=savePurchaseOrder([],{...vendor,number:'',expectedDate:'2026-09-10'},'Approved').order;assert.throws(()=>convertPurchaseOrder([order],[],order),/Receive goods/);const opened=advancePurchaseOrder([order],order,'open'),received=createGoodsReceipt(opened.rows,[],{orderId:order.id,date:'2026-09-05',lines:[{orderLineId:order.lines[0].id,receivedQty:5}]});const result=convertPurchaseOrder(received.orders,[],received.order);assert.equal(result.bill.sourceOrderId,order.id);assert.equal(result.bill.posted,false);assert.equal(result.orders[0].status,'Completed')});
test('posting a bill creates one balanced journal and is idempotent',()=>{const bill=savePurchaseBill([],{...vendor,number:'',vendorInvoice:'ABC/101'},'Draft').bill;const first=postPurchaseBill(accounting,bill);assert.equal(first.journal.lines.reduce((n,row)=>n+row.debit-row.credit,0),0);assert.equal(first.bill.status,'Unpaid');const second=postPurchaseBill(first.state,first.bill);assert.equal(second.state.journals.length,1)});
test('posting repairs the reserved 5000 Purchase account in legacy browser data',()=>{const bill=savePurchaseBill([],{...vendor,vendorInvoice:'LEGACY-5000'},'Draft').bill,legacy={...accounting,accounts:accounting.accounts.map(a=>a.code==='5000'?{...a,active:false,isGroup:true}:a)};const posted=postPurchaseBill(legacy,bill),purchase=posted.state.accounts.find(a=>a.code==='5000');assert.equal(purchase.active,true);assert.equal(purchase.isGroup,false);assert.equal(purchase.type,'Expenses');assert.ok(posted.journal.lines.some(l=>l.account==='5000'&&l.debit>0))});
test('posting repairs the reserved 2000 Accounts Payable account in legacy browser data',()=>{const bill=savePurchaseBill([],{...vendor,vendorInvoice:'LEGACY-2000'},'Draft').bill,legacy={...accounting,accounts:accounting.accounts.map(a=>a.code==='2000'?{...a,active:false,isGroup:true,type:'Expenses'}:a)};const posted=postPurchaseBill(legacy,bill),payable=posted.state.accounts.find(a=>a.code==='2000');assert.equal(payable.active,true);assert.equal(payable.isGroup,false);assert.equal(payable.type,'Liabilities');assert.equal(payable.nature,'Credit');assert.equal(payable.controlAccount,true);assert.ok(posted.journal.lines.some(l=>l.account==='2000'&&l.credit===bill.total))});
test('purchase calculation supports tax-inclusive item prices',()=>{const total=calculatePurchase([{...line,qty:'1',rate:'118',priceTaxMode:'inclusive'}]);assert.equal(total.taxable,10000);assert.equal(total.tax,1800);assert.equal(total.total,11800)});
test('vendor payment updates bill balance and posts a balanced journal',()=>{const bill=savePurchaseBill([],{...vendor,number:'',vendorInvoice:'ABC/102'},'Draft').bill,posted=postPurchaseBill(accounting,bill),paid=recordPurchasePayment(posted.state,posted.bill,{amount:'100000',date:'2026-09-05',reference:'UTR-1'});assert.equal(paid.bill.status,'Partially Paid');assert.equal(paid.journal.lines.reduce((n,row)=>n+row.debit-row.credit,0),0);assert.equal(paid.state.vendorPayments.length,1)});
test('vendor payment repairs the reserved 1010 Bank account in legacy browser data',()=>{const bill=savePurchaseBill([],{...vendor,vendorInvoice:'LEGACY-1010'},'Draft').bill,posted=postPurchaseBill(accounting,bill),legacy={...posted.state,accounts:posted.state.accounts.map(a=>a.code==='1010'?{...a,active:false,isGroup:true,type:'Expenses'}:a)},paid=recordPurchasePayment(legacy,posted.bill,{amount:'100',date:'2026-09-05',reference:'BANK-REPAIR'}),bank=paid.state.accounts.find(a=>a.code==='1010');assert.equal(bank.active,true);assert.equal(bank.isGroup,false);assert.equal(bank.type,'Assets');assert.equal(bank.nature,'Debit');assert.ok(paid.journal.lines.some(l=>l.account==='1010'&&l.credit===10000))});
test('partial receipts create multiple billable quantities without overbilling',()=>{const order=savePurchaseOrder([],{...vendor,number:'',expectedDate:'2026-09-10'},'Approved').order,opened=advancePurchaseOrder([order],order,'open'),firstReceipt=createGoodsReceipt(opened.rows,[],{orderId:order.id,date:'2026-09-05',lines:[{orderLineId:'l1',receivedQty:3}]}),firstBill=convertPurchaseOrder(firstReceipt.orders,[],firstReceipt.order),secondReceipt=createGoodsReceipt(firstBill.orders,firstReceipt.receipts,{orderId:order.id,date:'2026-09-06',lines:[{orderLineId:'l1',receivedQty:2}]}),secondBill=convertPurchaseOrder(secondReceipt.orders,firstBill.bills,secondReceipt.order);assert.equal(firstBill.bill.lines[0].qty,'3');assert.equal(secondBill.bill.lines[0].qty,'2');assert.throws(()=>convertPurchaseOrder(secondBill.orders,secondBill.bills,secondBill.orders[0]),/already been billed/)});
test('GST split follows place of supply and uses separate input accounts',()=>{const intra=calculatePurchase([line],{companyState:'Kerala',placeOfSupply:'Kerala'}),inter=calculatePurchase([line],{companyState:'Kerala',placeOfSupply:'Karnataka'});assert.equal(intra.cgst+intra.sgst,intra.tax);assert.equal(intra.igst,0);assert.equal(inter.igst,inter.tax);assert.equal(inter.cgst+inter.sgst,0);const bill=savePurchaseBill([],{...vendor,placeOfSupply:'Karnataka',vendorInvoice:'GST-1'},'Draft').bill,posted=postPurchaseBill(accounting,bill);assert.ok(posted.journal.lines.some(l=>l.account==='1430'&&l.debit===inter.igst));assert.equal(posted.journal.lines.reduce((n,l)=>n+l.debit-l.credit,0),0)});
test('posted bill cancellation reverses its accounting',()=>{const bill=savePurchaseBill([],{...vendor,vendorInvoice:'REV-1'},'Draft').bill,posted=postPurchaseBill(accounting,bill),cancelled=cancelPurchaseBill(posted.state,posted.bill,{reason:'Duplicate',date:'2026-09-05'});assert.equal(cancelled.bill.status,'Cancelled');assert.equal(cancelled.state.journals.length,2);assert.equal(cancelled.state.journals.flatMap(j=>j.lines).reduce((n,l)=>n+l.debit-l.credit,0),0)});
test('paid bill cancellation refunds payments before reversing the bill',()=>{const bill=savePurchaseBill([],{...vendor,vendorInvoice:'PAID-CANCEL'},'Draft').bill,posted=postPurchaseBill(accounting,bill),paid=recordPurchasePayment(posted.state,posted.bill,{amount:'100',date:'2026-09-05',reference:'paid'}),cancelled=cancelPurchaseBill(paid.state,paid.bill,{reason:'Vendor refunded payment',date:'2026-09-06'}),payment=cancelled.state.vendorPayments[0];assert.equal(cancelled.bill.status,'Cancelled');assert.equal(cancelled.bill.paidAmount,0);assert.equal(payment.status,'Reversed');assert.equal(cancelled.paymentReversals.length,1);assert.equal(cancelled.state.journals.length,4);assert.equal(cancelled.state.journals.flatMap(j=>j.lines).reduce((n,l)=>n+l.debit-l.credit,0),0);assert.equal(vendorLedger(cancelled.state,'ven-1').at(-1).balance,0)});
test('vendor payment retry is idempotent and vendor balances derive from journals',()=>{const bill=savePurchaseBill([],{...vendor,vendorInvoice:'PAY-1'},'Draft').bill,posted=postPurchaseBill(accounting,bill),first=recordPurchasePayment(posted.state,posted.bill,{amount:'100',date:'2026-09-05',reference:'same'}),retry=recordPurchasePayment(first.state,first.bill,{amount:'100',date:'2026-09-05',reference:'same'});assert.equal(retry.state.vendorPayments.length,1);assert.equal(retry.bill.paidAmount,10000);assert.equal(vendorOutstanding(first.state,'ven-1'),bill.total-10000);assert.equal(vendorLedger(first.state,'ven-1').at(-1).balance,bill.total-10000);assert.equal(purchaseTaxDocuments(first.state).length,1)});
test('purchase debit note reverses payable, purchase and input tax and applies to its bill',()=>{const bill=savePurchaseBill([],{...vendor,vendorInvoice:'DN-BILL'},'Draft').bill,posted=postPurchaseBill(accounting,bill),input={billId:bill.id,vendorId:bill.vendorId,date:'2026-09-06',reason:'Purchase return',lines:[{...line,qty:'1'}]},draftResult=saveDebitNote([], [posted.bill],input),submitted=submitDebitNote(draftResult.rows,draftResult.note),approved=approveDebitNote(submitted.rows,submitted.note),issued=issueDebitNote({...posted.state,debitNotes:[approved.note],purchaseBills:[posted.bill]},approved.note),applied=applyDebitNote(issued.state,issued.note);assert.equal(issued.note.status,'Posted');assert.equal(applied.note.status,'Adjusted');assert.equal(issued.journal.lines.reduce((n,row)=>n+row.debit-row.credit,0),0);assert.equal(issued.journal.lines.find(row=>row.account==='2000').debit,issued.note.total);assert.equal(applied.bill.creditApplied,issued.note.total);assert.equal(vendorOutstanding(issued.state,'ven-1'),bill.total-issued.note.total);assert.equal(purchaseTaxDocuments(issued.state).at(-1).sign,-1)});
test('standalone debit note saves without a purchase bill and posts a balanced vendor adjustment',()=>{const input={vendorId:'ven-1',vendorName:'ABC Technologies',date:'2026-09-06',placeOfSupply:'Kerala',reason:'Price Adjustment',payableAccount:'2000',lines:[{...line,qty:'1'}]},saved=saveDebitNote([],[],input),approved={...saved.note,status:'Approved'},posted=issueDebitNote({...accounting,debitNotes:[approved]},approved);assert.equal(saved.note.status,'Draft');assert.equal(saved.note.billId,undefined);assert.equal(posted.note.status,'Posted');assert.equal(posted.journal.purchaseBillId,null);assert.equal(posted.journal.lines.reduce((sum,row)=>sum+row.debit-row.credit,0),0)});
test('debit note cannot exceed bill balance and voiding posts an immutable reversal',()=>{const bill=savePurchaseBill([],{...vendor,vendorInvoice:'DN-VOID'},'Draft').bill,posted=postPurchaseBill(accounting,bill),input={billId:bill.id,vendorId:bill.vendorId,date:'2026-09-06',reason:'Damaged goods',lines:[{...line,qty:'1'}]},draft={...saveDebitNote([], [posted.bill],input).note,status:'Approved'},issued=issueDebitNote({...posted.state,debitNotes:[draft],purchaseBills:[posted.bill]},draft),applied=applyDebitNote(issued.state,issued.note);assert.throws(()=>recordPurchasePayment(applied.state,applied.bill,{amount:String(issued.bill.total/100),date:'2026-09-07',reference:'OVERPAY'}),/cannot exceed/);const voided=voidDebitNote(applied.state,applied.note,{reason:'Vendor rejected return',date:'2026-09-07'});assert.equal(voided.note.status,'Voided');assert.equal(voided.bill.creditApplied,0);assert.equal(voided.state.journals.length,3);assert.equal(voided.state.journals.flatMap(j=>j.lines).reduce((n,row)=>n+row.debit-row.credit,0),0)});
