import test from 'node:test';
import assert from 'node:assert/strict';
import {initial,command,outstanding,reports} from '../src/invoice-engine.js';
import {receiptCommand,receiptRows,receiptAvailable,receiptCustomerLedger} from '../src/receipt-engine.js';
import {daybookRows} from '../src/daybook-service.js';
import {customerStatement} from '../src/credit-note-service.js';
import {ingestReceiptEvent,parseBankCSV} from '../src/receipt-import.js';
const ctx={actor:'Test manager',canApprove:true,customers:[{id:'c',name:'Customer',account:'1100'}]};
test('CSV handles quoted references and rejects missing columns',()=>{assert.equal(parseBankCSV('id,date,amount,bank,reference\nb,2026-09-04,100,1010,"UPI, ABC"')[0].reference,'UPI, ABC');assert.throws(()=>parseBankCSV('date,amount\n2026-09-04,100'),/headers/)});
test('verified integration boundary deduplicates events and preserves approval requirements',()=>{const s=setup(),event={provider:'test',id:'evt1',status:'succeeded',currency:'INR',invoiceId:s.invoices[0].id,customerId:'c',amount:'100',date:'2026-09-04',bank:'1010',mode:'UPI'};assert.throws(()=>ingestReceiptEvent(s,event,ctx),/verified/);const o=ingestReceiptEvent(s,event,{...ctx,verifiedPayment:true});assert.equal(o.result.status,'Posted');assert.equal(ingestReceiptEvent(o.state,event,{...ctx,verifiedPayment:true}).state.journals.length,2);assert.throws(()=>ingestReceiptEvent(o.state,{...event,amount:'200'},{...ctx,verifiedPayment:true}),/reused/);assert.equal(customerStatement(o.state,'other-customer').length,0);assert.equal(customerStatement(o.state,'c').at(-1).balance,11790000)});
function setup(){let s=initial();s.accounts=[['1100','Receivables','Assets'],['1010','Bank','Assets'],['4100','Sales','Income'],['2100','GST','Liabilities'],['2200','Customer advances','Liabilities']].map(([code,name,type])=>({code,name,type,active:true}));s.config.receipts={advanceAccount:'2200',threshold:5000000};let out=command(s,'save',{customerId:'c',customerName:'Customer',date:'2026-09-01',dueDate:'2026-09-30',place:'Kerala',lines:[{description:'Service',qty:1,unit:'service',rate:'100000',discount:0,tax:'18',cess:0}]});s=command(out.state,'post',{id:out.result.id}).state;return s;}
function draft(s,amount='50000',kind='Normal',allocations=[]){return receiptCommand(s,'save',{date:'2026-09-04',customerId:'c',amount,kind,bank:'1010',mode:'UPI',allocations},ctx)}
function post(out){out=receiptCommand(out.state,'submit',{id:out.result.id},ctx);if(out.result.status==='Submitted')out=receiptCommand(out.state,'approve',{id:out.result.id},ctx);return receiptCommand(out.state,'post',{id:out.result.id},ctx)}
test('receipt is independent; partial and multi-step allocations never duplicate money',()=>{let s=setup(),i=s.invoices[0];let o=draft(s,'50000','Normal',[{invoiceId:i.id,amount:'20000'}]);assert.equal(o.state.journals.length,1);o=post(o);assert.equal(o.state.journals.length,2);assert.equal(outstanding(o.state,i),9800000);assert.equal(receiptAvailable(o.state,o.result),3000000);o=receiptCommand(o.state,'allocate',{id:o.result.id,date:'2026-09-04',token:'a',allocations:[{invoiceId:i.id,amount:'30000'}]},ctx);assert.equal(o.state.journals.length,2);assert.equal(outstanding(o.state,i),6800000);assert.equal(reports(o.state).debit,reports(o.state).credit);assert.equal(daybookRows(o.state).filter(r=>r.type==='Receipt').length,1);assert.equal(receiptCustomerLedger(o.state,'c').at(-1).balance,6800000);});
test('advance posts liability, allocation transfers to receivables and reversal restores history',()=>{let s=setup(),i=s.invoices[0],o=post(draft(s,'150000','Advance'));assert.equal(o.state.journals.at(-1).lines[1].account,'2200');o=receiptCommand(o.state,'allocate',{id:o.result.id,date:'2026-09-04',token:'advance',allocations:[{invoiceId:i.id,amount:'118000'}]},ctx);assert.equal(outstanding(o.state,i),0);assert.equal(receiptAvailable(o.state,o.result),3200000);assert.equal(o.state.journals.length,3);o=receiptCommand(o.state,'reverse',{id:o.result.id,date:'2026-09-05',reason:'Wrong payment'},ctx);assert.equal(o.state.journals.length,5);assert.equal(outstanding(o.state,i),11800000);assert.equal(o.result.status,'Reversed');assert.equal(reports(o.state).debit,reports(o.state).credit);assert.equal(receiptCommand(o.state,'reverse',{id:o.result.id,date:'2026-09-05',reason:'retry'},ctx).state.journals.length,5)});
test('approval, excess, closed period, duplicate and draft immutability protections',()=>{let o=draft(setup());o=receiptCommand(o.state,'submit',{id:o.result.id},ctx);assert.equal(o.result.status,'Submitted');assert.throws(()=>receiptCommand(o.state,'post',{id:o.result.id},ctx),/Approve/);assert.throws(()=>receiptCommand(o.state,'approve',{id:o.result.id},{...ctx,canApprove:false}),/manager/);assert.throws(()=>post(draft(setup(),'118001')),/exceeds/);o=post(draft(setup(),'100'));assert.throws(()=>receiptCommand(o.state,'save',{...o.result,amount:'100'},ctx),/draft/);assert.throws(()=>receiptCommand(o.state,'save',{date:'2026-09-04',customerId:'c',amount:'10',kind:'Normal',bank:'1010',mode:'UPI',number:o.result.number},ctx),/already exists/);o.state.config.receipts.closedThrough='2026-09-05';assert.throws(()=>receiptCommand(o.state,'reverse',{id:o.result.id,date:'2026-09-05',reason:'test'},ctx),/closed/)});
test('legacy payments remain visible and reversible without reposting',()=>{let s=setup(),i=s.invoices[0];s=command(s,'pay',{id:i.id,amount:'100',date:'2026-09-04',bank:'1010',token:'old'}).state;const r=receiptRows(s)[0];assert.equal(r.legacy,true);const o=receiptCommand(s,'reverse',{id:r.id,date:'2026-09-05',reason:'Correction'},ctx);assert.equal(o.state.journals.length,3);assert.equal(outstanding(o.state,i),11800000);assert.equal(receiptRows(o.state).length,1)});
test('multiple invoice allocation, paid-invoice protection and customer isolation',()=>{const s=setup(),first=s.invoices[0];s.invoices.push({...first,id:'second',number:'INV-SECOND'});let o=post(draft(s,'200000','Normal',[{invoiceId:first.id,amount:'118000'},{invoiceId:'second',amount:'82000'}]));assert.equal(outstanding(o.state,first),0);assert.equal(outstanding(o.state,o.state.invoices[1]),3600000);const advance=post(draft(o.state,'100','Advance'));assert.throws(()=>receiptCommand(advance.state,'allocate',{id:advance.result.id,date:'2026-09-04',token:'paid',allocations:[{invoiceId:first.id,amount:'1'}]},ctx),/outstanding/);advance.state.invoices[1].customerId='other';assert.throws(()=>receiptCommand(advance.state,'allocate',{id:advance.result.id,date:'2026-09-04',token:'cross',allocations:[{invoiceId:'second',amount:'1'}]},ctx),/customer/)});
test('bank matching validates amounts and reversal cannot bypass reconciliation',()=>{let o=post(draft(setup(),'100'));o=receiptCommand(o.state,'import-bank',{lines:[{id:'bank1',date:'2026-09-04',amount:'100',bank:'1010'}]},ctx);const id=o.state.receipts[0].id;o=receiptCommand(o.state,'match',{id,bankLineId:'bank1',amount:'100'},ctx);assert.equal(o.result.reconciliation,'Matched');o=receiptCommand(o.state,'reconcile',{id},ctx);assert.equal(o.result.reconciliation,'Reconciled');assert.throws(()=>receiptCommand(o.state,'reverse',{id,date:'2026-09-05',reason:'test'},ctx),/Remove the bank match/);o=receiptCommand(o.state,'unmatch',{id,reason:'Incorrect bank match'},ctx);assert.equal(o.result.reconciliation,'Unmatched')});
