import test from 'node:test';import assert from 'node:assert/strict';
import {applyAccountingSettings,defaultSettings,numberingPreview,readSettings,resolveSetting,validateSettings,writeSettings} from '../src/settings-store.js';
const memory=()=>{const values=new Map();return{getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value)}};
test('settings defaults are versioned and persist without dropping nested defaults',()=>{const store=memory();const saved=writeSettings({...defaultSettings,organization:{...defaultSettings.organization,companyName:'Wayvida Demo'}},store);assert.equal(saved.organization.companyName,'Wayvida Demo');assert.equal(readSettings(store).transactions.maxDiscount,20)});
test('dependency and accounting control validation is enforced',()=>{assert.match(validateSettings({...defaultSettings,accounting:{...defaultSettings.accounting,costCentres:false},transactions:{...defaultSettings.transactions,requireCostCentre:true}})[0],/Cost Centres/);assert.match(validateSettings({...defaultSettings,transactions:{...defaultSettings.transactions,maxDiscount:101}})[0],/discount/)});
test('document numbering supports accounting tokens and padded sequence',()=>{assert.equal(numberingPreview({pattern:'INV/{FY}/{BRANCH_CODE}/####',nextNumber:7}), 'INV/2026-27/KOCHI/0007')});
test('scope precedence resolves user through system default',()=>{assert.equal(resolveSetting({system:'system',company:'company',branch:'branch',role:'role',user:'user'}),'user');assert.equal(resolveSetting({system:'system',company:'company'}),'company')});
test('accounting settings include journals, approvals, tax and document controls',()=>{assert.equal(defaultSettings.journals.approvalRequired,true);assert.equal(defaultSettings.approvals.inventoryAdjustments,true);assert.equal(defaultSettings.tax.defaultGstRate,18);assert.match(defaultSettings.numbering.reversalJournal.pattern,/REV-JE/)});
test('saving accounting defaults updates future posting mappings without changing journals',()=>{const store=memory(),accounting={accounts:[{code:'4000',name:'Sales',type:'Income',active:true},{code:'1100',name:'Receivables',type:'Assets',active:true},{code:'2100',name:'GST payable',type:'Liabilities',active:true},{code:'5900',name:'Other expenses',type:'Expenses',active:true}],journals:[{id:'JE-1'}],config:{sales:'old',state:'Tamil Nadu'}};store.setItem('wayvida-accounting-v1',JSON.stringify(accounting));const result=applyAccountingSettings(defaultSettings,store);assert.equal(result.config.sales,'4000');assert.equal(result.config.ar,'1100');assert.equal(result.config.state,'Kerala');assert.deepEqual(result.journals,[{id:'JE-1'}])});
