import {useState} from 'react';
import {GST_KEYS} from './account-settings.js';
import {money,today} from './invoice-engine.js';
export default function AccountAdvancedSettings({form,setForm,db,onOpening}){
  const [opening,setOpening]=useState({date:today(),amount:'',side:'Debit',offset:'',reference:'',branch:'',costCentre:'',token:crypto.randomUUID()}),[review,setReview]=useState(false),[error,setError]=useState('');
  const set=(k,v)=>setForm({...form,[k]:v}),tds=form.tds||{enabled:false,section:'',rate:'',account:''};
  const savedOpening=(db.openings||[]).find(o=>o.account===form.code);
  const liabilities=db.accounts.filter(a=>a.active&&!a.isGroup&&a.type==='Liabilities');
  const updateOpening=(k,v)=>{setOpening({...opening,[k]:v});setReview(false);setError('')};
  return <div className="am-settings">
    <h3>Tax configuration</h3><div className="am-fields"><label className="am-field">GST validation<select value={form.taxMode||'transaction'} onChange={e=>set('taxMode',e.target.value)}><option value="transaction">Use transaction tax selection</option><option value="none">Require zero GST / Cess</option><option value="validate">Validate a configured GST rate</option></select></label>{form.taxMode==='validate'&&<label className="am-field">Expected total GST rate (%)<input type="number" min="0" max="100" step="0.01" value={form.gstRate??''} onChange={e=>set('gstRate',e.target.value)}/></label>}</div><p className="am-note">Validates future invoice lines using this revenue account. Does not override invoice tax selection or recalculate posted transactions. Cess is separate from the total GST rate.</p>
    <h3>Output GST ledger mappings</h3><p className="am-note">Shared invoice-posting settings. Changes apply to future postings, across accounts. Existing journal entries stay unchanged.</p><div className="am-fields">{GST_KEYS.map(k=><label key={k} className="am-field">{k.toUpperCase()} payable account<select value={form.gstMappings?.[k]||''} onChange={e=>set('gstMappings',{...form.gstMappings,[k]:e.target.value})}><option value="">Select liability ledger</option>{liabilities.map(a=><option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select></label>)}</div>
    <h3>TDS configuration</h3><label className="am-checkbox"><input type="checkbox" role="switch" checked={tds.enabled} onChange={e=>set('tds',{...tds,enabled:e.target.checked})}/>Enable TDS mapping</label>{tds.enabled&&<div className="am-fields"><label className="am-field">Section / provision<input value={tds.section} placeholder="Enter the applicable provision" onChange={e=>set('tds',{...tds,section:e.target.value})}/></label><label className="am-field">Configured rate (%)<input type="number" min="0" max="100" step="0.01" value={tds.rate} onChange={e=>set('tds',{...tds,rate:e.target.value})}/></label><label className="am-field">TDS receivable / payable ledger<select value={tds.account} onChange={e=>set('tds',{...tds,account:e.target.value})}><option value="">Select ledger</option>{db.accounts.filter(a=>a.active&&!a.isGroup&&['Assets','Liabilities'].includes(a.type)).map(a=><option key={a.code} value={a.code}>{a.code} · {a.name} ({a.type})</option>)}</select></label></div>}<p className="am-note">Saved mapping only. Automatic TDS deduction, thresholds and statutory reporting are not implemented. Confirm the applicable provision and rate with your finance team.</p>
    <h3>Control account</h3><label className="am-checkbox"><input type="checkbox" role="switch" checked={!!form.controlAccount} onChange={e=>set('controlAccount',e.target.checked)}/>Restrict ordinary manual journal posting</label><p className="am-note">Allows source-generated entries and reviewed openings. A used control account cannot be unlocked. System account protections remain in place.</p>
    <h3>Opening balance</h3>{!form.id?<p className="am-note">Save this account first, then return here to post its opening balance.</p>:savedOpening?<div className="am-review"><div><b>{savedOpening.number} · Posted</b><p>{money(savedOpening.amount)} {savedOpening.side} · {savedOpening.date}</p><small>Offset: {savedOpening.offset}. The journal is retained in the ledger; it cannot be edited here.</small></div></div>:<><p className="am-note">Separate posting action, not part of Save account. Use the migration opening date and a finance-approved equity offset. Customer/vendor balances need subledger allocation and are blocked here.</p><div className="am-fields">{[['date','Opening date','date'],['amount','Amount (₹)','number']].map(([k,label,type])=><label key={k} className="am-field">{label}<input type={type} min={type==='number'?'0.01':undefined} step={type==='number'?'0.01':undefined} value={opening[k]} onChange={e=>updateOpening(k,e.target.value)}/></label>)}<label className="am-field">Balance type<select value={opening.side} onChange={e=>updateOpening('side',e.target.value)}><option>Debit</option><option>Credit</option></select></label><label className="am-field">Equity offset account<select value={opening.offset} onChange={e=>updateOpening('offset',e.target.value)}><option value="">Select offset</option>{db.accounts.filter(a=>a.active&&!a.isGroup&&!a.controlAccount&&a.type==='Equity'&&a.code!==form.code).map(a=><option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select></label><label className="am-field">Reference / migration reason<input value={opening.reference} onChange={e=>updateOpening('reference',e.target.value)}/></label>{(form.branchRequired||db.accounts.find(a=>a.code===opening.offset)?.branchRequired)&&<label className="am-field">Branch<input value={opening.branch} onChange={e=>updateOpening('branch',e.target.value)}/></label>}{(form.costCentreRequired||db.accounts.find(a=>a.code===opening.offset)?.costCentreRequired)&&<label className="am-field">Cost centre<input value={opening.costCentre} onChange={e=>updateOpening('costCentre',e.target.value)}/></label>}</div><p className="am-note">{opening.side==='Debit'?'Debit':'Credit'} {form.name}: ₹{opening.amount||'0'} · {opening.side==='Debit'?'Credit':'Debit'} offset: ₹{opening.amount||'0'}</p><label className="am-checkbox"><input type="checkbox" checked={review} onChange={e=>setReview(e.target.checked)}/>I reviewed the date, amount and offset account.</label>{error&&<p className="am-error" role="alert">{error}</p>}<button type="button" disabled={!review} onClick={()=>{try{onOpening({...opening,id:form.id,revision:form.revision});setError('')}catch(e){setError(e.message)}}}>Post opening balance</button></>}
  </div>;
}
