import {useState} from 'react';
import {IconCheck,IconExternalLink,IconInfoCircle} from '@tabler/icons-react';
import {LOCK_FREQUENCIES,PERIOD_ROLE_OPTIONS,normalisePeriodSettings,readPeriodSettings,writePeriodSettings} from './period-locking.js';
import './accounting-settings.css';

const mappingLabels={salesRevenue:'Sales income',serviceRevenue:'Service income',accountsReceivable:'Customer balances',customerAdvances:'Customer advances',outputGst:'Output GST',purchaseExpense:'Purchases',accountsPayable:'Supplier balances',vendorAdvances:'Vendor advances',inputGst:'Input GST',expenseAccount:'General expenses',inventoryAsset:'Inventory asset',costOfGoodsSold:'Cost of goods sold',bankAccount:'Default bank',bankCharges:'Bank charges',rounding:'Rounding adjustment',retainedEarnings:'Retained earnings',openingBalanceEquity:'Opening balance equity'};
const accountChoices=['1000 · Cash','1010 · Bank','1100 · Accounts Receivable','1200 · Inventory','1300 · Vendor Advances','2000 · Accounts Payable','2100 · GST Payable','2110 · GST Input Credit','2200 · Customer Advances','3000 · Capital','4000 · Sales','4100 · Service Income','4200 · Other Income','5000 · Purchase','5100 · Salary','5900 · Other Expenses'];
const Field=({label,help,children})=><label className="swField"><span>{label}</span>{children}{help&&<small>{help}</small>}</label>;
const Toggle=({label,description,value,onChange,disabled=false})=><label className={`swToggle ${disabled?'disabled':''}`}><span><b>{label}</b><small>{description}</small></span><input type="checkbox" checked={value} disabled={disabled} onChange={event=>onChange(event.target.checked)}/><i/></label>;
const Section=({title,description,children})=><section className="swSection"><header><h2>{title}</h2>{description&&<p>{description}</p>}</header><div className="swSectionBody">{children}</div></section>;
const PERIOD_ROLE_HELP={Admin:'Full access to close, approve and configure periods.','Business Owner':'View periods, close books and approve unlock requests.','Accountant':'View periods and raise unlock requests.'};
function PeriodControlSettings(){
 const [value,setValue]=useState(readPeriodSettings),[saved,setSaved]=useState(false),toggle=key=>{setSaved(false);setValue({...value,[key]:!value[key]})};
 const lockingOn=value.lockingMode!=='Off',automatic=value.lockingMode==='Automatic';
 const setLockingMode=mode=>{setSaved(false);setValue(current=>normalisePeriodSettings({...current,lockingMode:mode}))};
 const setSchedule=(key,next)=>{setSaved(false);setValue(current=>normalisePeriodSettings({...current,schedule:{...current.schedule,[key]:next}}))};
 const toggleRole=name=>{const current=value.allowedRoles||PERIOD_ROLE_OPTIONS,next=current.includes(name)?current.filter(item=>item!==name):[...current,name];if(!next.includes('Admin'))return;setSaved(false);setValue({...value,allowedRoles:next})};
 const save=()=>{writePeriodSettings(value);setSaved(true)};
 return <><div className="swToggleGrid"><Toggle label="Period locking" description="One switch for every module in Wayvida Books. When it is off no period can be locked and every lock control is hidden." value={lockingOn} onChange={()=>setLockingMode(lockingOn?'Off':'Manual')}/><Toggle label="Automatic period closing" description="Lock every period on the closing schedule. Switch it off to lock each period by hand." value={automatic} onChange={()=>setLockingMode(automatic?'Manual':'Automatic')} disabled={!lockingOn}/><Toggle label="Unlock approval requirement" description="Require another approver before a closed period can be changed." value={value.approval} onChange={()=>toggle('approval')}/><Toggle label="Automatically relock" description="Close temporary access when the approved duration ends." value={value.autoRelock} onChange={()=>toggle('autoRelock')}/></div><div className="swGrid"><Field label="Closing frequency"><select disabled={!automatic} value={value.schedule.frequency} onChange={event=>setSchedule('frequency',event.target.value)}>{LOCK_FREQUENCIES.map(name=><option key={name} value={name}>{name}</option>)}</select></Field><Field label="Close after days" help="Time allowed to finish last month’s work."><input type="number" min="0" max="31" disabled={!automatic} value={value.schedule.lockAfterDays} onChange={event=>setSchedule('lockAfterDays',Number(event.target.value))}/></Field><Field label="Default unlock duration"><select value={value.defaultUnlockDuration} onChange={event=>{setSaved(false);setValue({...value,defaultUnlockDuration:event.target.value})}}><option>1 Hour</option><option>Today</option></select></Field></div><fieldset className="swRoles"><legend>Allowed roles</legend>{PERIOD_ROLE_OPTIONS.map(name=><label className="swRole" key={name}><input type="checkbox" checked={(value.allowedRoles||PERIOD_ROLE_OPTIONS).includes(name)} onChange={()=>toggleRole(name)}/><span><b>{name}</b><small>{PERIOD_ROLE_HELP[name]}</small></span></label>)}</fieldset><div className="swSettingsLinks"><button onClick={save}>Save period control</button>{saved&&<span className="swSaved"><IconCheck size={14}/>Period control settings saved</span>}</div></>;
}

export default function AccountingSettingsPanel({draft,set,setDraft,onNavigate,footer}){
 const update=(area,key,value)=>set(area,key,value),ready=[['Financial year',Boolean(draft.organization.financialYearStart&&draft.organization.financialYearEnd)],['Base currency',Boolean(draft.organization.currency)],['Chart of Accounts',Boolean(draft.accountMappings.accountsReceivable&&draft.accountMappings.accountsPayable)],['Tax setup',!draft.tax.gstEnabled||Boolean(draft.tax.gstin)],['Journal controls',draft.journals.enabled],['Period controls',true]];
 return <><header className="swHead"><span>Settings</span><h1>Accounting setup</h1><p>Control how future transactions become journals, ledgers and financial reports.</p></header>
 <div className="swReadiness">{ready.map(([label,ok])=><div className={ok?'ready':'attention'} key={label}><IconCheck/><span><b>{label}</b><small>{ok?'Ready':'Needs attention'}</small></span></div>)}</div>
 <Section title="Accounting foundation" description="Core rules for this organisation. Structural changes should be restricted after posting begins."><div className="swGrid"><Field label="Accounting basis"><select value={draft.accounting.basis} onChange={e=>update('accounting','basis',e.target.value)}><option>Accrual</option><option>Cash</option></select></Field><Field label="Base currency"><select value={draft.organization.currency} onChange={e=>update('organization','currency',e.target.value)}><option>INR</option><option>USD</option></select></Field><Field label="Financial year start"><input type="date" value={draft.organization.financialYearStart} onChange={e=>update('organization','financialYearStart',e.target.value)}/></Field><Field label="Financial year end"><input type="date" value={draft.organization.financialYearEnd} onChange={e=>update('organization','financialYearEnd',e.target.value)}/></Field></div><div className="swToggleGrid"><Toggle label="Account numbers" description="Show ledger codes throughout accounting." value={draft.accounting.accountNumbers} onChange={v=>update('accounting','accountNumbers',v)}/><Toggle label="Branch accounting" description="Keep branch ownership on every posting." value={draft.accounting.branchAccounting} onChange={v=>update('accounting','branchAccounting',v)}/><Toggle label="Cost centres" description="Track responsibility centres on eligible entries." value={draft.accounting.costCentres} onChange={v=>update('accounting','costCentres',v)}/><Toggle label="Bill-wise tracking" description="Track customer and supplier balances by document." value={draft.accounting.billWise} onChange={v=>update('accounting','billWise',v)}/></div></Section>
 <Section title="Default accounts" description="Wayvida Books uses these accounts automatically. Changes affect future transactions only."><div className="swGrid">{Object.entries(mappingLabels).map(([key,label])=><Field key={key} label={label}><select value={draft.accountMappings[key]} onChange={e=>update('accountMappings',key,e.target.value)}>{[draft.accountMappings[key],...accountChoices].filter((value,index,list)=>value&&list.indexOf(value)===index).map(value=><option key={value}>{value}</option>)}</select></Field>)}</div><div className="swSettingsLinks"><button onClick={()=>onNavigate('Chart of Accounts')}>Manage Chart of Accounts <IconExternalLink/></button></div></Section>
 <Section title="Journals & posting" description="Manual adjustments remain controlled; operational modules continue posting automatically."><div className="swToggleGrid"><Toggle label="Enable manual journals" description="Allow accountants to create controlled adjustments." value={draft.journals.enabled} onChange={v=>update('journals','enabled',v)}/><Toggle label="Require journal approval" description="Approval must happen before posting." value={draft.journals.approvalRequired} onChange={v=>update('journals','approvalRequired',v)}/><Toggle label="Prevent self-approval" description="The creator cannot approve the same journal." value={!draft.journals.selfApproval} onChange={v=>update('journals','selfApproval',!v)}/><Toggle label="Require narration" description="Every manual journal needs a business explanation." value={draft.journals.narrationRequired} onChange={v=>update('journals','narrationRequired',v)}/><Toggle label="Require branch" description="Journal lines must identify their branch." value={draft.journals.requireBranch} onChange={v=>update('journals','requireBranch',v)}/><Toggle label="Require cost centre" description="Available when cost centres are enabled." disabled={!draft.accounting.costCentres} value={draft.journals.requireCostCentre} onChange={v=>update('journals','requireCostCentre',v)}/><Toggle label="Reversal approval" description="Require review before reversing posted entries." value={draft.journals.reversalApproval} onChange={v=>update('journals','reversalApproval',v)}/><Toggle label="Journal templates" description="Allow reusable adjustment templates." value={draft.journals.templatesEnabled} onChange={v=>update('journals','templatesEnabled',v)}/></div><div className="swGrid"><Field label="Maximum backdated days"><input type="number" min="0" max="3650" value={draft.journals.maxBackdatedDays} onChange={e=>update('journals','maxBackdatedDays',Number(e.target.value))}/></Field><Field label="Attachment required above"><input type="number" min="0" value={draft.journals.attachmentThreshold} onChange={e=>update('journals','attachmentThreshold',Number(e.target.value))}/></Field></div></Section>
 <Section title="Approvals" description="Apply one consistent approval policy across accounting workflows."><div className="swToggleGrid">{[['sales','Sales'],['purchases','Purchases'],['expenses','Expenses'],['journals','Manual journals'],['banking','Banking'],['inventoryAdjustments','Inventory adjustments']].map(([key,label])=><Toggle key={key} label={label} description="Require approval before final posting." value={draft.approvals[key]} onChange={v=>update('approvals',key,v)}/>)}</div><div className="swGrid"><Field label="Amount requiring approval"><input type="number" min="0" value={draft.approvals.amountThreshold} onChange={e=>update('approvals','amountThreshold',Number(e.target.value))}/></Field></div></Section>
 <Section title="Tax accounting" description="Normal sales and purchases calculate tax automatically from transaction details."><div className="swToggleGrid"><Toggle label="Enable GST" description="Use GST on qualifying transactions." value={draft.tax.gstEnabled} onChange={v=>update('tax','gstEnabled',v)}/><Toggle label="Enable reverse charge" description="Support qualifying reverse-charge purchases." value={draft.tax.reverseCharge} onChange={v=>update('tax','reverseCharge',v)}/><Toggle label="Enable TDS" description="Allow configured withholding-tax flows." value={draft.tax.tdsEnabled} onChange={v=>update('tax','tdsEnabled',v)}/><Toggle label="Enable TCS" description="Allow configured tax-collected-at-source flows." value={draft.tax.tcsEnabled} onChange={v=>update('tax','tcsEnabled',v)}/></div>{draft.tax.gstEnabled&&<div className="swGrid"><Field label="GST registration type"><select value={draft.tax.registrationType} onChange={e=>update('tax','registrationType',e.target.value)}><option>Regular</option><option>Composition</option><option>Unregistered</option></select></Field><Field label="GSTIN"><input value={draft.tax.gstin} onChange={e=>update('tax','gstin',e.target.value.toUpperCase())}/></Field><Field label="Registered state"><input value={draft.tax.registeredState} onChange={e=>update('tax','registeredState',e.target.value)}/></Field><Field label="Default GST rate"><select value={draft.tax.defaultGstRate} onChange={e=>update('tax','defaultGstRate',Number(e.target.value))}>{[0,5,12,18,28].map(rate=><option key={rate} value={rate}>{rate}%</option>)}</select></Field><Field label="Default price treatment"><select value={draft.tax.priceTreatment} onChange={e=>update('tax','priceTreatment',e.target.value)}><option>Tax exclusive</option><option>Tax inclusive</option></select></Field><Field label="Effective date"><input type="date" value={draft.tax.effectiveDate} onChange={e=>update('tax','effectiveDate',e.target.value)}/></Field></div>}</Section>
 <Section title="Period lock & opening balances" description="Use the dedicated controlled workflows; settings do not rewrite posted history."><div className="swActionCards"><button onClick={()=>onNavigate('Period Lock')}><b>Period Lock</b><small>Locks, closing checks and unlock approvals</small><IconExternalLink/></button><button onClick={()=>onNavigate('Chart of Accounts')}><b>Opening balances</b><small>Balanced account opening entries and history</small><IconExternalLink/></button><button onClick={()=>onNavigate('Journal Entries')}><b>Journal register</b><small>Manual and automatic accounting entries</small><IconExternalLink/></button></div><p className="swHint"><IconInfoCircle/> Settings apply prospectively. Existing documents, taxes, journals and balances remain unchanged.</p></Section>
 <Section title="Period control" description="Policy for closing, protecting and reopening accounting periods. Shared with Period Lock → Settings."><PeriodControlSettings/></Section>{footer}</>;
}
