import {useDeferredValue,useEffect,useMemo,useState} from 'react';
import {IconAdjustments,IconAlertTriangle,IconCheck,IconFileSpreadsheet,IconFileTypePdf,IconRefresh,IconSearch} from '@tabler/icons-react';
import {readAccounts} from './account-store.js';
import {ALL,AGING_BUCKETS,agingExportRows,customerAging,supplierAging} from './aging.js';
import {downloadReport,excelReport} from './daybook-export.js';
import {money,today} from './invoice-engine.js';
import {demoOrganizations} from './demo-organisations.js';
import {VENDOR_KEY} from './vendor-store.js';
import EmptyState from './EmptyState.jsx';
import './cash-banking.css';
import './report-pages.css';
import {AsOfDateSelect,ReportExportMenu} from './ReportToolbar.jsx';

/* Customer Aging and Supplier Aging are the same report on the two sides of the ledger, so they are
   the same page: one row per party, one column per aging bucket, and a total that always equals the
   balance Customer Outstanding or Supplier Outstanding states for that party. The projection itself
   lives in src/aging.js; this file owns only the shell, and it renders through the shared report shell
   in src/cash-banking.css with the column widths from src/report-pages.css. */
const CUSTOMERS_KEY='wayvida-customers';
const DASH='\u2014';

/* The party master is a browser store written by its own register. A missing store is not an error:
   the report still states every open document, because each one carries its own party name. */
const read=key=>{try{const rows=JSON.parse(localStorage.getItem(key));return Array.isArray(rows)?rows:[]}catch{return []}};

export default function AgingReport({kind='customer',onNavigate=()=>{}}){
 const isCustomer=kind!=='supplier';
 const build=isCustomer?customerAging:supplierAging;
 const partyLabel=isCustomer?'Customer':'Supplier';
 const documentLabel=isCustomer?'Invoice':'Bill';
 const [revision,setRevision]=useState(0),[asOf,setAsOf]=useState(today()),[branch,setBranch]=useState(ALL),[party,setParty]=useState(ALL),[aging,setAging]=useState(ALL),[search,setSearch]=useState(''),[filtersOpen,setFiltersOpen]=useState(false),[stamp,setStamp]=useState(()=>new Date());
 const deferredSearch=useDeferredValue(search),busy=deferredSearch!==search;
 const organization=demoOrganizations.find(item=>item.id===localStorage.getItem('wayvida-demo-company'))||demoOrganizations[0];

 const refresh=()=>setRevision(value=>value+1);
 useEffect(()=>{window.addEventListener('wayvida-accounts-updated',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('wayvida-accounts-updated',refresh);window.removeEventListener('storage',refresh)}},[]);
 useEffect(()=>{setParty(ALL);setAging(ALL);setSearch('')},[kind]);

 const {book,parties,error}=useMemo(()=>{try{return {book:readAccounts(),parties:read(isCustomer?CUSTOMERS_KEY:VENDOR_KEY),error:''}}catch(reason){return {book:null,parties:[],error:reason.message}}},[revision,isCustomer]);
 const report=useMemo(()=>{
  const filters={asOf,branch,aging,search:deferredSearch,[isCustomer?'customer':'supplier']:party};
  try{return build(book||{},parties,filters)}
  catch{return build({},[],filters)}
 },[book,parties,asOf,branch,party,aging,deferredSearch,isCustomer,build]);

 const clear=()=>{setAsOf(today());setBranch(ALL);setParty(ALL);setAging(ALL);setSearch('')};
 const activeFilters=(branch!==ALL?1:0)+(party!==ALL?1:0)+(aging!==ALL?1:0);
 const failed=report.checks.filter(check=>!check.ok);
 const reconciliation=report.source.reconciliation||{};

 function exportExcel(){
  const content=agingExportRows(report,{organisation:organization.name,party,generatedBy:'Local user',generatedAt:stamp.toISOString()});
  downloadReport(excelReport(content),'wayvida-'+(isCustomer?'customer':'supplier')+'-aging.xml','application/xml;charset=utf-8');
 }
 function print(){setStamp(new Date());setTimeout(()=>window.print(),50)}
 function printMeta(){
  return [['Wayvida Books - '+partyLabel+' Aging',isCustomer?'How long your customers have owed you, by due date.':'How long you have owed your suppliers, by due date.'],
   ['Organisation',organization.name],['Branch',branch===ALL?'All branches':branch],['As of',asOf],
   [partyLabel,party===ALL?'All '+partyLabel.toLowerCase()+'s':party],['Aging filter',aging===ALL?'All aging buckets':(AGING_BUCKETS.find(bucket=>bucket.key===aging)||{}).label||aging],
   ['Generated by Local user',stamp.toLocaleString()]];
 }
 const partyRow=row=>{
  const selected=party!==ALL&&party===row.id;
  return <tr key={row.id+(row.code||'')} className={selected?'cbSelectedRow':''}>
   <td className="agPartyCol"><b>{row.name||DASH}</b>{row.code?<span className="cbWord"> {row.code}</span>:null}</td>
   <td className="agDocsCol cbMoney">{row.documents}</td>
   {AGING_BUCKETS.map(bucket=><td key={bucket.key} className="agBucketCol cbMoney">{row.buckets[bucket.key]?money(row.buckets[bucket.key]):DASH}</td>)}
   <td className="agTotalCol cbMoney"><b>{money(row.total)}</b></td>
  </tr>;
 };
 const columns=AGING_BUCKETS.length+3;
 return <section className={'cbPage cbAging'+(isCustomer?' cbAgingCustomer':' cbAgingSupplier')} aria-busy={busy}>
  <header className="cbHead">
   <div className="cbHeadText"><h1>{partyLabel+' Aging'}</h1><p>{isCustomer?'See how long each customer has owed you, bucketed by due date.':'See how long each supplier has been owed, bucketed by due date.'}</p></div>
   <div className="cbHeadActions">
    <AsOfDateSelect date={asOf} onChange={value=>setAsOf(value)} onCustom={()=>setFiltersOpen(true)}/>
    <details className="cbFiltersMore" open={filtersOpen} onToggle={event=>setFiltersOpen(event.currentTarget.open)}>
     <summary aria-label="Open filters"><IconAdjustments size={17}/>Filters{activeFilters>0&&<span>{activeFilters}</span>}</summary>
     <div className="cbFilters">
      <label>As of Date<input type="date" aria-label="As of Date" value={asOf} onChange={event=>setAsOf(event.target.value)}/></label>
      <label>Branch<select aria-label="Branch" value={branch} onChange={event=>setBranch(event.target.value)}><option value={ALL}>All branches</option>{report.branchOptions.map(value=><option key={value} value={value}>{value}</option>)}</select></label>
      <label>Aging<select aria-label="Aging" value={aging} onChange={event=>setAging(event.target.value)}><option value={ALL}>All aging buckets</option>{AGING_BUCKETS.map(bucket=><option key={bucket.key} value={bucket.key}>{bucket.label}</option>)}</select></label>
      <label>{partyLabel}<select aria-label={partyLabel} value={party} onChange={event=>setParty(event.target.value)}><option value={ALL}>All {partyLabel.toLowerCase()}s</option>{report.partyOptions.map(item=><option key={item.id} value={item.id}>{item.code?item.code+' \u00b7 '+item.name:item.name}</option>)}</select></label>
      <div className="cbFilterActions"><button type="button" onClick={()=>{refresh();setStamp(new Date())}}><IconRefresh size={15}/>Refresh</button><button type="button" onClick={clear}>Clear Filters</button></div>
     </div>
    </details>
    <ReportExportMenu items={[{key:'excel',label:'Export Excel',icon:<IconFileSpreadsheet size={17}/>,onClick:exportExcel,disabled:!report.rows.length},{key:'pdf',label:'Export PDF',icon:<IconFileTypePdf size={17}/>,onClick:print,disabled:!report.rows.length}]}/>
   </div>
  </header>
  {error&&<div className="cbError" role="alert"><IconAlertTriangle size={18}/><span>{error}</span></div>}
  <div className="cbPrintMeta">{printMeta().map(([label,value])=><p key={label}><b>{label}:</b> {value}</p>)}</div>
  <div className="cbSummary">
   <div><span>Total Outstanding</span><strong>{money(report.totals.total)}</strong></div>
   <div className="cbOutflow"><span>Overdue</span><strong>{money(report.totals.overdueAmount)}</strong></div>
   <div className="cbInflow"><span>Not Yet Due</span><strong>{money(report.totals.notYetDue)}</strong></div>
   <div className="cbClosing"><span>Largest Bucket</span><strong>{money(report.totals.largestAmount)}</strong></div>
  </div>
  <div className="cbCard"><div className="cbTableScroll"><table>
   <caption className="cbCaption">{partyLabel+' aging as of '+asOf+' \u00b7 '+report.totals.parties+' '+(report.totals.parties===1?partyLabel.toLowerCase():partyLabel.toLowerCase()+'s')+' \u00b7 '+report.totals.documents+' '+documentLabel.toLowerCase()+'s'+(report.totals.largestLabel?' \u00b7 largest bucket '+report.totals.largestLabel:'')}{busy?' \u00b7 recalculating':''}</caption>
   <thead><tr>
    <th className="agPartyCol">{partyLabel}</th>
    <th className="agDocsCol cbMoney">{documentLabel}s</th>
    {AGING_BUCKETS.map(bucket=><th key={bucket.key} className="agBucketCol cbMoney">{bucket.label}</th>)}
    <th className="agTotalCol cbMoney">Total</th>
   </tr></thead>
   <tbody>
   {report.rows.map(partyRow)}
   {!report.rows.length&&<tr className="emptyStateRow"><td colSpan={columns} className="emptyStateCell"><EmptyState variant={isCustomer?'customer':'default'} title={report.hasData?'No open balance matches these filters.':'No outstanding '+partyLabel.toLowerCase()+' balance found.'} description={report.hasData?'Try another aging bucket or branch, or clear the filters.':'Open '+documentLabel.toLowerCase()+'s that are still unpaid will appear here once they are posted.'} actionLabel={report.hasData?'Clear Filters':undefined} onAction={report.hasData?clear:undefined}/></td></tr>}
   </tbody>
   {report.rows.length>0&&<tfoot><tr className="cbGrandTotal">
    <th className="cbLabel" colSpan="2" scope="row">{report.totals.parties} {report.totals.parties===1?partyLabel.toLowerCase():partyLabel.toLowerCase()+'s'}</th>
    {AGING_BUCKETS.map(bucket=><th key={bucket.key} className="agBucketCol cbMoney">{money(report.totals.buckets[bucket.key])}</th>)}
    <th className="agTotalCol cbMoney">{money(report.totals.total)}</th>
   </tr></tfoot>}
  </table></div></div>
  <div className={'cbEquation cbStickyBalance '+(failed.length?'mismatch':reconciliation.reconciled===false?'mismatch':reconciliation.difference===null?'unknown':'balanced')} role="status">
   {failed.length?<IconAlertTriangle size={19}/>:<IconCheck size={19}/>}
   <b>{failed.length?partyLabel+' Aging needs review':reconciliation.difference===null?'No control account is configured to reconcile against':reconciliation.reconciled?'Reconciles with the '+(isCustomer?'receivable':'payable')+' control account':partyLabel+' Aging does not reconcile with the control account'}</b>
   <span>{failed.length?failed.map(check=>check.key).join(' \u00b7 '):'Bucket columns '+money(report.totals.total)+' \u00b7 control '+(reconciliation.control===null?'not configured':money(reconciliation.control))+(reconciliation.difference===null?'':' \u00b7 difference '+money(Math.abs(reconciliation.difference)))}</span>
  </div>
  <div className="cbNote">
   <ul>
    <li>A bucket is a range of days PAST DUE, counted from the document&apos;s own due date - never the age of the document. An invoice on 30-day terms is not overdue on the day it is raised.</li>
    <li>The buckets are the ones Customer Outstanding and Supplier Outstanding already assign, so the six columns of a party always add up to exactly the balance those reports state for it.</li>
    <li>Only posted documents are counted and a cancelled document is dropped, so a draft never ages.</li>
    <li>Choosing an aging bucket lists the parties that hold money in it; the bucket columns still state each party&apos;s whole open balance, so the filtered bucket is never mistaken for the balance owed.</li>
   </ul>
  </div>
 </section>;
}
