import './crypto-uuid.js';
export const AUDIT_KEY='wayvida-global-audit-v1';
const labels={'wayvida-accounting-v1':'Accounting','wayvida-accounts-v2':'Chart of Accounts','wayvida-customers':'Customers','finance-erp-items':'Items','wayvida-sales-orders':'Sales Orders','wayvida-vendors-v1':'Vendors','wayvida-purchase-orders-v1':'Purchase Orders','wayvida-goods-receipts-v1':'Goods Receipts','wayvida-purchase-bills-v1':'Purchase Bills','wayvida-debit-notes-v1':'Debit Notes','wayvida-banking-v1':'Banking','wayvida-operations-v1':'Operations','wayvida-period-control-v1':'Period Closing','wayvida-settings-v1':'Settings','wayvida-companies-v2':'Companies'};
const areas={invoices:'Invoices',receipts:'Receipts',creditNotes:'Credit Notes',creditApplications:'Credit Applications',journals:'Journal Entries',payments:'Payments',accounts:'Chart of Accounts',purchaseOrders:'Purchase Orders',purchaseBills:'Purchase Bills',goodsReceipts:'Goods Receipts',debitNotes:'Debit Notes',vendorPayments:'Vendor Payments',bankAccounts:'Bank Accounts',bankTransactions:'Bank Transactions',reconciliations:'Bank Reconciliation',expenses:'Expenses',assets:'Assets',budgets:'Budgets'};
const parse=value=>{try{return JSON.parse(value)}catch{return null}},id=(row,index)=>String(row?.id??row?.code??row?.number??index),name=row=>row?.invoiceNumber||row?.receiptNumber||row?.orderNumber||row?.billNumber||row?.journalNumber||row?.number||row?.name||row?.displayName||row?.code||row?.reference||row?.id||'Record';
function sets(key,value){if(Array.isArray(value))return [[labels[key],value]];if(!value||typeof value!=='object')return [];return Object.entries(value).filter(([,rows])=>Array.isArray(rows)&&rows.some(row=>row&&typeof row==='object')).map(([key,rows])=>[areas[key]||key.replace(/([A-Z])/g,' $1'),rows])}
export function auditChanges(key,before,after){const oldSets=new Map(sets(key,before)),newSets=new Map(sets(key,after)),result=[];for(const area of new Set([...oldSets.keys(),...newSets.keys()])){const oldRows=new Map((oldSets.get(area)||[]).map((row,index)=>[id(row,index),row])),newRows=new Map((newSets.get(area)||[]).map((row,index)=>[id(row,index),row]));for(const [recordId,row] of newRows){const previous=oldRows.get(recordId);if(!previous)result.push({module:area,action:'Created',record:name(row),recordId});else if(JSON.stringify(previous)!==JSON.stringify(row)){const fields=[...new Set([...Object.keys(previous),...Object.keys(row)])].filter(field=>JSON.stringify(previous[field])!==JSON.stringify(row[field])&&!['updatedAt','modifiedAt'].includes(field));result.push({module:area,action:fields.includes('status')?'Status changed':'Updated',record:name(row),recordId,changedFields:fields.slice(0,12),fromStatus:previous.status,toStatus:row.status})}oldRows.delete(recordId)}for(const [recordId,row] of oldRows)result.push({module:area,action:'Removed',record:name(row),recordId})}if(!result.length&&JSON.stringify(before)!==JSON.stringify(after))result.push({module:labels[key],action:'Configuration updated',record:labels[key],recordId:key});return result}
export const readAuditLog=()=>parse(localStorage.getItem(AUDIT_KEY))||[];
export function installAuditLog(){if(globalThis.__wayvidaAuditInstalled)return;globalThis.__wayvidaAuditInstalled=true;const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(this!==localStorage||key===AUDIT_KEY||!labels[key])return original.call(this,key,value);const before=parse(this.getItem(key)),output=original.call(this,key,value),events=auditChanges(key,before,parse(value));if(events.length){const at=new Date().toISOString(),actor='Admin',company=this.getItem('wayvida-demo-company')||'Active company',branch=this.getItem('wayvida-demo-branch')||'Active branch';original.call(this,AUDIT_KEY,JSON.stringify([...events.map(event=>({id:crypto.randomUUID(),at,actor,company,branch,sourceKey:key,...event})),...readAuditLog()].slice(0,5000)));window.dispatchEvent(new CustomEvent('wayvida-audit-updated'))}return output}}
