import {useEffect,useMemo,useState} from 'react';
import {IconCheck,IconAlertTriangle,IconChevronRight,IconChevronDown,IconFileTypePdf,IconSearch,IconAdjustments} from '@tabler/icons-react';
import {readAccounts} from './account-store.js';
import {money,today} from './invoice-engine.js';
import {balanceSheet} from './balance-sheet.js';
import {demoOrganizations} from './demo-organisations.js';
import './balance-sheet.css';

const reportSeed={Assets:[['1000','Cash'],['1010','Bank'],['1100','Accounts Receivable'],['1200','Inventory'],['1300','Equipment'],['1310','Furniture']],Liabilities:[['2000','Accounts Payable'],['2100','GST Payable'],['2300','Loans']],Equity:[['3000','Capital'],['3200','Retained Earnings']],Income:[['4000','Sales'],['4100','Service Income']],Expenses:[['5000','Purchases'],['5100','Salary'],['5200','Rent']]};

export default function BalanceSheet({seed,notify,onNavigate}){
  const [revision,setRevision]=useState(0),[date,setDate]=useState(today()),[branch,setBranch]=useState('All'),[search,setSearch]=useState(''),[filtersOpen,setFiltersOpen]=useState(false),[expanded,setExpanded]=useState({});
  const organization=demoOrganizations.find(x=>x.id===localStorage.getItem('wayvida-demo-company'))||demoOrganizations[0];
  const branches=organization.branches||[];
  useEffect(()=>{const refresh=()=>setRevision(x=>x+1);window.addEventListener('wayvida-accounts-updated',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('wayvida-accounts-updated',refresh);window.removeEventListener('storage',refresh)}},[]);
  const report=useMemo(()=>balanceSheet(readAccounts(seed||reportSeed),{date,branch}),[seed,date,branch,revision]);
  const selected=(()=>{try{return sessionStorage.getItem('wayvida-balance-sheet-account')||''}catch{return ''}})();
  useEffect(()=>()=>{try{sessionStorage.removeItem('wayvida-balance-sheet-account')}catch{}},[]);
  const visibleRows=report.rows.filter(row=>[row.name,row.code,row.accountNature,row.section].join(' ').toLowerCase().includes(search.trim().toLowerCase()));
  const sectionRows=(type,section)=>visibleRows.filter(row=>row.type===type&&row.section===section);
  const subgroup=row=>{const value=(row.name+' '+row.accountNature).toLowerCase();if(row.type==='Assets')return /cash|petty/.test(value)?'Cash & Cash Equivalents':/bank/.test(value)?'Bank Accounts':/receivable/.test(value)?'Accounts Receivable':/inventory/.test(value)?'Inventory':'Other Current Assets';if(row.type==='Liabilities')return /payable/.test(value)?'Accounts Payable':/tax|gst|tds/.test(value)?'Tax Payable':/advance|unearned/.test(value)?'Customer Advances & Unearned Revenue':'Other Current Liabilities';return /capital|drawing/.test(value)?'Owner Capital':/retained/.test(value)?'Retained Earnings':'Owner Equity'};
  const accountRow=row=><tr key={row.code} className={selected===row.code?'selected':''}><td><button onClick={()=>{sessionStorage.setItem('wayvida-open-account',row.code);onNavigate('Chart of Accounts')}}>{row.name}<IconChevronRight size={15}/></button></td><td>{row.code}</td><td>{money(row.debit)}</td><td>{money(row.credit)}</td><td>{money(row.amount)}</td></tr>;
  const group=(title,rows,key)=><><tr className="bsStatementGroup"><th colSpan="5"><button type="button" aria-expanded={expanded[key]!==false} onClick={()=>setExpanded(x=>({...x,[key]:x[key]===false}))}>{expanded[key]===false?<IconChevronRight size={16}/>:<IconChevronDown size={16}/>}<span>{title}</span><b>{money(rows.reduce((sum,row)=>sum+row.amount,0))}</b></button></th></tr>{expanded[key]!==false&&rows.map(accountRow)}<tr className="bsGroupTotal"><th colSpan="4">Total for {title}</th><th>{money(rows.reduce((sum,row)=>sum+row.amount,0))}</th></tr></>;
  const statement=(type,title,sections)=><section className="bsStatement"><h2>{title}</h2><div className="bsTableScroll"><table><thead><tr><th>Account Name</th><th>Account Code</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>{sections.map(section=>{const rows=sectionRows(type,section),buckets=[...new Set(rows.map(subgroup))];return <>{<tr className="bsStatementSection"><th colSpan="5">{section}</th></tr>}{buckets.length?buckets.map(name=>group(name,rows.filter(row=>subgroup(row)===name),type+'-'+section+'-'+name)):<tr className="bsEmpty"><td colSpan="5">No balances available</td></tr>}</>})}{type==='Equity'&&<><tr className="bsStatementGroup"><th colSpan="5"><span>Current Year Profit / Loss</span><b>{money(Math.abs(report.currentEarnings))}</b></th></tr><tr className="bsGroupTotal"><th colSpan="4">Total Equity</th><th>{money(report.equity)}</th></tr></>}</tbody></table></div></section>;
  return <section className="bsPage"><header className="bsHead"><div><h1>Balance Sheet</h1><p>Track your business financial position as of a selected date.</p></div><div className="bsHeadActions"><label className="bsSearch"><IconSearch size={17}/><input aria-label="Search balance sheet accounts" placeholder="Search account or group" value={search} onChange={e=>setSearch(e.target.value)}/></label><details className="bsFiltersMore" open={filtersOpen} onToggle={e=>setFiltersOpen(e.currentTarget.open)}><summary aria-label="Open filters"><IconAdjustments size={17}/>Filters</summary><div className="bsFilters"><label>As on date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Report basis<select defaultValue="Accrual"><option>Accrual</option><option>Cash</option></select></label><label>Organisation<select value={organization.id} disabled><option>{organization.name}</option></select></label><label>Branch<select value={branch} onChange={e=>setBranch(e.target.value)}><option>All</option>{branches.map(item=><option key={item.id} value={item.name}>{item.name}</option>)}</select></label><label>Financial year<select defaultValue="FY 2026–27"><option>FY 2026–27</option></select></label><label>Compare with<select defaultValue="None"><option>None</option><option>Previous Period</option><option>Previous Year</option></select></label><button type="button" onClick={()=>{setDate(today());setBranch('All');setSearch('')}}>Clear filters</button></div></details><button onClick={()=>window.print()}><IconFileTypePdf size={17}/>Export PDF</button></div></header><div className="bsSummary"><div><span>Total Assets</span><strong>{money(report.assets)}</strong></div><div><span>Total Liabilities</span><strong>{money(report.liabilities)}</strong></div><div><span>Total Equity</span><strong>{money(report.equity)}</strong></div><div><span>Balance Difference</span><strong>{money(Math.abs(report.difference))}</strong></div></div><div className="bsReportIdentity"><small>{organization.name}</small><h2>Balance Sheet</h2><p>Basis: Accrual</p><b>As of {date}</b></div><div className="bsStatementCard">{statement('Assets','Assets',['Current Assets','Fixed Assets'])}{statement('Liabilities','Liabilities',['Current Liabilities','Long-term Liabilities'])}{statement('Equity','Equity',['Equity'])}</div><div className={'bsEquation bsStickyBalance '+(report.balanced?'balanced':'mismatch')} role="status">{report.balanced?<IconCheck size={19}/>:<IconAlertTriangle size={19}/>}<b>{report.balanced?'Balance Sheet Balanced':'Balance sheet difference detected'}</b><span>Difference: {money(Math.abs(report.difference))}</span></div></section>;
}
