import {useEffect,useMemo,useState} from 'react';
import {IconCheck,IconAlertTriangle,IconChevronRight,IconDownload,IconFileTypePdf,IconPrinter} from '@tabler/icons-react';
import {readAccounts} from './account-store.js';
import {money,today} from './invoice-engine.js';
import {balanceSheet} from './balance-sheet.js';
import {demoOrganizations} from './HeaderOrgSelectors.jsx';
import './balance-sheet.css';

const reportSeed={Assets:[['1000','Cash'],['1010','Bank'],['1100','Accounts Receivable'],['1200','Inventory'],['1300','Equipment'],['1310','Furniture']],Liabilities:[['2000','Accounts Payable'],['2100','GST Payable'],['2300','Loans']],Equity:[['3000','Capital'],['3200','Retained Earnings']],Income:[['4000','Sales'],['4100','Service Income']],Expenses:[['5000','Purchases'],['5100','Salary'],['5200','Rent']]};
const csvCell=value=>'"'+String(value??'').replaceAll('"','""')+'"';
const saveCsv=(name,rows)=>{const blob=new Blob(['\uFEFF'+rows.map(row=>row.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};

export default function BalanceSheet({seed,notify,onNavigate}){
  const [revision,setRevision]=useState(0),[date,setDate]=useState(today()),[branch,setBranch]=useState('All');
  const organization=demoOrganizations.find(x=>x.id===localStorage.getItem('wayvida-demo-company'))||demoOrganizations[0];
  const branches=organization.branches||[];
  useEffect(()=>{const refresh=()=>setRevision(x=>x+1);window.addEventListener('wayvida-accounts-updated',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('wayvida-accounts-updated',refresh);window.removeEventListener('storage',refresh)}},[]);
  const report=useMemo(()=>balanceSheet(readAccounts(seed||reportSeed),{date,branch}),[seed,date,branch,revision]);
  const selected=(()=>{try{return sessionStorage.getItem('wayvida-balance-sheet-account')||''}catch{return ''}})();
  useEffect(()=>()=>{try{sessionStorage.removeItem('wayvida-balance-sheet-account')}catch{}},[]);
  const rowsFor=(type,section)=>report.rows.filter(row=>row.type===type&&row.section===section);
  const exportRows=()=>[['Balance Sheet',organization.name,branch,date],['Section','Account','Code','Amount'],...report.rows.map(row=>[row.section,row.name,row.code,(row.amount/100).toFixed(2)]),['Equity','Current year earnings','',(report.currentEarnings/100).toFixed(2)],['','Total Assets','',(report.assets/100).toFixed(2)],['','Total Liabilities and Equity','',((report.liabilities+report.equity)/100).toFixed(2)]];
  const group=(title,rows)=><section className="bsGroup"><h3>{title}<strong>{money(rows.reduce((sum,row)=>sum+row.amount,0))}</strong></h3>{rows.length?rows.map(row=><button key={row.code} className={selected===row.code?'selected':''} onClick={()=>{sessionStorage.setItem('wayvida-open-account',row.code);onNavigate('Chart of Accounts')}}><span>{row.name}<small>{row.code} · {row.accountNature}</small></span><b>{money(row.amount)}</b><IconChevronRight/></button>):<p>No balances in this section.</p>}</section>;
  return <section className="bsPage"><header className="bsHead"><div><span>FINANCIAL STATEMENTS</span><h1>Balance Sheet</h1><p>View your business financial position at a selected date.</p></div><div className="bsActions"><button onClick={()=>{saveCsv('wayvida-balance-sheet.csv',exportRows());notify('Excel-ready report exported')}}><IconDownload/>Export Excel</button><button onClick={()=>window.print()}><IconFileTypePdf/>Export PDF</button><button onClick={()=>window.print()}><IconPrinter/>Print</button></div></header><div className="bsFilters"><label>Organisation<select value={organization.id} disabled><option>{organization.name}</option></select></label><label>Branch<select value={branch} onChange={e=>setBranch(e.target.value)}><option>All</option>{branches.map(item=><option key={item.id} value={item.name}>{item.name}</option>)}</select></label><label>As of date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Financial year<select defaultValue="FY 2026–27"><option>FY 2026–27</option></select></label></div><div className="bsEquation"><div><span>Total Assets</span><strong>{money(report.assets)}</strong></div><i>=</i><div><span>Liabilities + Equity</span><strong>{money(report.liabilities+report.equity)}</strong></div><em className={report.balanced?'balanced':'mismatch'}>{report.balanced?<IconCheck/>:<IconAlertTriangle/>}{report.balanced?'Balanced':'Mismatch '+money(Math.abs(report.difference))}</em></div><div className="bsColumns"><article><h2>Assets</h2>{group('Current Assets',rowsFor('Assets','Current Assets'))}{group('Fixed Assets',rowsFor('Assets','Fixed Assets'))}<footer><span>Total Assets</span><strong>{money(report.assets)}</strong></footer></article><article><h2>Liabilities & Equity</h2>{group('Current Liabilities',rowsFor('Liabilities','Current Liabilities'))}{group('Long-term Liabilities',rowsFor('Liabilities','Long-term Liabilities'))}{group('Equity',rowsFor('Equity','Equity'))}<div className="bsEarnings"><span>Current year earnings<small>Income less expenses through {date}</small></span><b>{money(report.currentEarnings)}</b></div><footer><span>Total Liabilities & Equity</span><strong>{money(report.liabilities+report.equity)}</strong></footer></article></div></section>;
}
