import {Fragment,useDeferredValue,useEffect,useMemo,useState} from 'react';
import {IconAdjustments,IconAlertTriangle,IconCheck,IconFileSpreadsheet,IconFileTypePdf,IconRefresh,IconSearch} from '@tabler/icons-react';
import {readAccounts} from './account-store.js';
import {money,today} from './invoice-engine.js';
import {cashFlow,cashFlowExportRows,financialYearStart} from './cash-flow.js';
import {downloadReport,excelReport} from './daybook-export.js';
import {demoOrganizations} from './demo-organisations.js';
import EmptyState from './EmptyState.jsx';
import './cash-flow.css';
import {DateRangeSelect,ReportExportMenu} from './ReportToolbar.jsx';

/* The same chart fallback the other statements carry, so an empty browser store still renders a
   readable statement instead of a broken table. Real balances only ever come from the posted
   journal: the report reads the cash and bank accounts the Chart of Accounts already classifies. */
const reportSeed={Assets:[['1000','Cash'],['1010','Bank']]};
const ALL='All';

export default function CashFlowStatement({seed,notify,onNavigate}){
  const [revision,setRevision]=useState(0),[from,setFrom]=useState(financialYearStart),[to,setTo]=useState(today),[branch,setBranch]=useState(ALL),[cashAccount,setCashAccount]=useState(ALL),[type,setType]=useState(ALL),[accountGroup,setAccountGroup]=useState(ALL),[search,setSearch]=useState(''),[includeZero,setIncludeZero]=useState(false),[filtersOpen,setFiltersOpen]=useState(false),[stamp,setStamp]=useState(()=>new Date());
  const deferredSearch=useDeferredValue(search),busy=deferredSearch!==search;
  const organization=demoOrganizations.find(x=>x.id===localStorage.getItem('wayvida-demo-company'))||demoOrganizations[0];
  useEffect(()=>{const refresh=()=>setRevision(x=>x+1);window.addEventListener('wayvida-accounts-updated',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('wayvida-accounts-updated',refresh);window.removeEventListener('storage',refresh)}},[]);
  const {book,error}=useMemo(()=>{try{return {book:readAccounts(seed||reportSeed),error:''}}catch(e){return {book:{accounts:[],journals:[]},error:e.message}}},[seed,revision]);
  const report=useMemo(()=>cashFlow(book,{from,to,branch,cashAccount,account:type,accountGroup,search:deferredSearch,includeZero}),[book,from,to,branch,cashAccount,type,accountGroup,deferredSearch,includeZero]);
  const selected=(()=>{try{return sessionStorage.getItem('wayvida-open-account')||''}catch{return ''}})();
  const counterpartAccounts=report.chart.filter(item=>!report.selectedCash.some(cash=>String(cash.code)===String(item.code)));
  const groups=[...new Set(counterpartAccounts.map(item=>item.group))].sort();
  const branchLabel=value=>organization.branches?.find(item=>item.id===value)?.name||value;
  function reset(){setFrom(financialYearStart());setTo(today());setBranch(ALL);setCashAccount(ALL);setType(ALL);setAccountGroup(ALL);setSearch('');setIncludeZero(false)}
  function refresh(){setRevision(x=>x+1);setStamp(new Date())}
  function openLedger(row){try{sessionStorage.setItem('wayvida-open-account',row.code)}catch{}onNavigate('General Ledger')}
  function exportExcel(){downloadReport(excelReport(cashFlowExportRows(report,{from,to,branch:branch===ALL?'All branches':branchLabel(branch),cashAccount:cashAccount===ALL?'All cash and bank accounts':`${cashAccount} \u00b7 ${report.selectedCash.find(item=>String(item.code)===String(cashAccount))?.name||''}`,account:type===ALL?'All accounts':type,accountGroup:accountGroup===ALL?'All account groups':accountGroup,search:search||'None',includeZero})),'wayvida-cash-flow-statement.xml','application/xml;charset=utf-8')}
  function print(){setStamp(new Date());setTimeout(()=>window.print(),50)}
  function printMeta(){return [['Wayvida Books \u00b7 Cash Flow Statement',`For ${from} to ${to}`],['Organisation',organization.name],['Branch',branch===ALL?'All branches':branchLabel(branch)],['Accounting basis','Accrual'],['Cash / bank accounts',cashAccount===ALL?'All cash and bank accounts':`${cashAccount} \u00b7 ${report.selectedCash.find(item=>String(item.code)===String(cashAccount))?.name||''}`],['Account',type===ALL?'All accounts':type],['Account group',accountGroup===ALL?'All account groups':accountGroup],['Search',search||'None'],['Include zero-balance accounts',includeZero?'Yes':'No'],['Accounts shown',String(report.accounts)],['Opening cash',money(report.openingCash)],['Cash inflows',money(report.cashInflows)],['Cash outflows',money(report.cashOutflows)],['Net cash flow',money(report.netCashFlow)],['Closing cash',money(report.closingCash)],['Difference',money(report.difference)],['Generated by Local user',stamp.toLocaleString()]]}
  const activeFilters=[branch!==ALL,cashAccount!==ALL,type!==ALL,accountGroup!==ALL,includeZero].filter(Boolean).length;
  
  const row=(item,index)=>(
    <tr key={item.code||index} className={'cfAccount'+(selected===item.code?' selected':'')}>
      <td className="cfAccountCell">
        <button type="button" className="cfAccountBtn" onClick={()=>openLedger(item)} aria-label={`Open General Ledger for ${item.name}`}>
          {item.code && <span className="cfAccountCode">{item.code}</span>}
          {item.code && <span className="cfAccountDot">·</span>}
          <span className="cfAccountName">{item.name}</span>
        </button>
      </td>
      <td className="cfGroupCell">{item.group||'—'}</td>
      <td className="cfMoney">{money(item.amount)}</td>
    </tr>
  );

  const lineBlock=line=><Fragment key={line.key}><tr className="cfGroup"><th colSpan="3" scope="rowgroup">{line.label}</th></tr>{line.rows.map(row)}<tr className="cfGroupTotal"><th colSpan="3" scope="row"><span className="cfRowLine"><span>Total for {line.label}</span><b className="cfMoney">{money(line.total)}</b></span></th></tr></Fragment>;
  const statementRow=item=>item.kind==='derived'
    ?<tr key={item.key} className={'cfDerived'+(item.net?' cfNet':'')+(item.closing?' cfClosing':'')}><th colSpan="3" scope="row"><span className="cfRowLine"><span>{item.label}</span><b className="cfMoney">{money(item.amount)}</b></span></th></tr>
    :<Fragment key={item.key}><tr className="cfSection"><th colSpan="3" scope="rowgroup">{item.label}</th></tr>{item.lines.map(lineBlock)}<tr className="cfSectionTotal"><th colSpan="3" scope="row"><span className="cfRowLine"><span>{item.totalLabel}</span><b className="cfMoney">{money(item.total)}</b></span></th></tr></Fragment>;
  
  /* The empty state replaces the activity rows but the opening and closing balances stay stated, so
     a period with no cash movement still answers the question the report was opened to answer. */
  const emptyRow=<tr className="emptyStateRow"><td colSpan="3" className="emptyStateCell"><EmptyState variant="journal" title={report.periodActivity?'No accounts match the current filters.':'No cash or bank movements were posted for this period.'} description={report.periodActivity?'Clear the account, account group or search filter to see every cash movement.':'Opening and closing cash are still stated above and below.'} actionLabel="Reset filters" onAction={reset}/></td></tr>;
  
  return <section className="cfPage" aria-busy={busy}>
    <header className="cfHead"><div><h1>Cash Flow Statement</h1><p>Track cash inflows and outflows for the selected period.</p></div><div className="cfHeadActions">
      <DateRangeSelect from={from} to={to} onChange={(start,end)=>{setFrom(start);setTo(end)}} onCustom={()=>setFiltersOpen(true)}/>
      <details className="cfFiltersMore" open={filtersOpen} onToggle={e=>setFiltersOpen(e.currentTarget.open)}><summary aria-label="Open filters"><IconAdjustments size={17}/>Filters{activeFilters>0&&<span>{activeFilters}</span>}</summary><div className="cfFilters">
        <label>From date<input type="date" aria-label="From date" value={from} onChange={e=>setFrom(e.target.value)}/></label>
        <label>To date<input type="date" aria-label="To date" value={to} onChange={e=>setTo(e.target.value)}/></label>
        <label>Branch<select aria-label="Branch" value={branch} onChange={e=>setBranch(e.target.value)}><option value={ALL}>All branches</option>{report.branchOptions.map(item=><option key={item} value={item}>{branchLabel(item)}</option>)}</select></label>
        <label>Cash / Bank account<select aria-label="Cash or bank account" value={cashAccount} onChange={e=>setCashAccount(e.target.value)}><option value={ALL}>All cash and bank accounts</option>{report.cashChart.map(item=><option key={item.code} value={item.code}>{item.code} \u00b7 {item.name}</option>)}</select></label>
        <label>Account<select aria-label="Account" value={type} onChange={e=>setType(e.target.value)}><option value={ALL}>All accounts</option>{counterpartAccounts.map(item=><option key={item.code} value={item.code}>{item.code} \u00b7 {item.name}</option>)}</select></label>
        <label>Account group<select aria-label="Account group" value={accountGroup} onChange={e=>setAccountGroup(e.target.value)}><option value={ALL}>All account groups</option>{groups.map(item=><option key={item} value={item}>{item}</option>)}</select></label>
        <label className="cfCheck"><input type="checkbox" checked={includeZero} onChange={e=>setIncludeZero(e.target.checked)}/>Include zero-balance accounts</label>
        <div className="cfFilterActions"><button type="button" onClick={refresh}><IconRefresh size={15}/>Refresh</button><button type="button" onClick={reset}>Clear filters</button></div>
      </div></details>
      <ReportExportMenu items={[{key:'excel',label:'Export Excel',icon:<IconFileSpreadsheet size={17}/>,onClick:exportExcel,disabled:!report.cashChart.length},{key:'pdf',label:'Export PDF',icon:<IconFileTypePdf size={17}/>,onClick:print,disabled:!report.cashChart.length}]}/>
    </div></header>
    {error&&<div className="cfError" role="alert"><IconAlertTriangle size={18}/><span>{error}</span></div>}
    <div className="cfPrintMeta">{printMeta().map(([label,value])=><p key={label}><b>{label}:</b> {value}</p>)}</div>
    <div className="cfSummary">
      <div><span>Opening Cash</span><strong>{money(report.openingCash)}</strong></div>
      <div className="cfInflow"><span>Cash Inflows</span><strong>{money(report.cashInflows)}</strong></div>
      <div className="cfOutflow"><span>Cash Outflows</span><strong>{money(report.cashOutflows)}</strong></div>
      <div className={report.netCashFlow<0?'cfOutflow':'cfNet'}><span>Net Cash Flow</span><strong>{money(report.netCashFlow)}</strong></div>
      <div className="cfClosing"><span>Closing Cash</span><strong>{money(report.closingCash)}</strong></div>
    </div>
    <div className="cfStatementCard">
      <div className="cfTableScroll">
        <table>
          <thead>
            <tr>
              <th scope="col" className="cfAccountHead">ACCOUNT</th>
              <th scope="col" className="cfGroupHead">ACCOUNT GROUP</th>
              <th scope="col" className="cfAmountHead">AMOUNT</th>
            </tr>
          </thead>
          <tbody>
            {report.statement.map((item,index)=><Fragment key={item.key||item.label}>{statementRow(item)}{!report.accounts&&index===0?emptyRow:null}</Fragment>)}
          </tbody>
        </table>
      </div>
    </div>
    <div className={'cfEquation cfStickyBalance '+(report.valid?'balanced':'mismatch')} role="status">{report.valid?<IconCheck size={19}/>:<IconAlertTriangle size={19}/>}<b>{report.valid?'Cash Flow Statement reconciles':'Cash Flow Statement does not reconcile'}</b><span>{report.difference!==0?`Difference: ${money(report.difference)} \u00b7 `:''}Closing cash: {money(report.closingCash)}</span></div>
    <div className="cfNotes">
      <p>Based on posted accounting entries for the selected period. Draft and cancelled transactions are excluded.</p>
      <p>Only movements of cash and bank accounts are stated, so a credit sale or a credit purchase creates no cash flow until it is settled.</p>
      {report.counterpartFilter&&<p>The account, account group and search filters narrow which movements are classified; the movements they leave out are stated on their own line, so closing cash still agrees with the ledger.</p>}
      <p>Opening cash + net cash from operating, investing and financing activities = closing cash.{report.difference!==0?` This selection is out by ${money(report.difference)}, which is stated rather than forced to zero.`:''}</p>
    </div>
  </section>;
}
