import {useState} from 'react';
import {IconArrowLeft,IconArrowRight,IconBuilding,IconCheck,IconLoader2,IconShieldCheck} from '@tabler/icons-react';
import './company-setup.css';

const steps=['Company Information','Business Type','Address','Financial Year','Currency','Tax Registration','Accounting Preferences','Confirmation'];
const initial={name:'',legalName:'',businessType:'Private Limited',country:'India',state:'Kerala',address:'',currency:'INR · Indian Rupee',financialYear:'April – March',gstRegistered:'No',gstin:'',pan:'',phone:'',email:'',accrual:true,inventory:true};
const states=['Kerala','Karnataka','Tamil Nadu','Maharashtra','Delhi','Gujarat','Telangana','West Bengal'];
const businessTypes=['Private Limited','Public Limited','LLP','Partnership','Proprietorship','Non-profit','Other'];
const currencies=['INR · Indian Rupee','USD · US Dollar','AED · UAE Dirham','GBP · Pound Sterling','EUR · Euro'];
const Input=({label,error,wide=false,...props})=><label className={wide?'csWide':''}><span>{label}</span><input {...props}/>{error&&<small role="alert">{error}</small>}</label>;

export default function CompanySetup({onCancel,onComplete,notify}){
 const [step,setStep]=useState(0),[data,setData]=useState(initial),[errors,setErrors]=useState({}),[saving,setSaving]=useState(false),[failure,setFailure]=useState('');
 const set=(key,value)=>{setData({...data,[key]:value});setErrors({...errors,[key]:''})};
 function validate(){const e={};if(step===0){if(!data.name.trim())e.name='Enter the company name.';if(!data.legalName.trim())e.legalName='Enter the registered legal name.';if(data.email&&!/^[^@]+@[^@]+\.[^@]+$/.test(data.email))e.email='Enter a valid email address.'}if(step===2){if(!data.country)e.country='Select a country.';if(!data.state)e.state='Select a state.';if(!data.address.trim())e.address='Enter the registered address.'}if(step===5&&data.gstRegistered==='Yes'&&!/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]$/.test(data.gstin))e.gstin='Enter a valid 15-character GSTIN.';if(data.pan&&!/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(data.pan))e.pan='Enter a valid PAN.';setErrors(e);return !Object.keys(e).length}
 function next(){if(validate())setStep(Math.min(steps.length-1,step+1))}
 async function finish(){setSaving(true);setFailure('');try{await new Promise(r=>setTimeout(r,650));const id=crypto.randomUUID(),code=(data.name.replace(/[^A-Za-z]/g,'').slice(0,4)||'COMP').toUpperCase()+'01',record={id,code,...data,status:'Active',createdAt:new Date().toISOString(),isRootEntity:true};const records=JSON.parse(localStorage.getItem('wayvida-companies-v2')||'[]');localStorage.setItem('wayvida-companies-v2',JSON.stringify([...records,record]));localStorage.setItem('wayvida-active-company',id);localStorage.setItem('wayvida-company-bootstrap:'+id,JSON.stringify({financialYear:data.financialYear,periods:data.financialYear==='April – March'?12:12,documentNumbering:['Invoice','Sales Order','Credit Note','Receipt','Journal'],chartTemplate:data.businessType,tax:{country:data.country,gstRegistered:data.gstRegistered==='Yes'},roles:['Super Admin','Finance Manager','Accountant','Sales User','Viewer'],createdAt:new Date().toISOString()}));notify('Company setup completed');onComplete(record)}catch{setFailure('Company setup could not be saved. Please try again.')}finally{setSaving(false)}}
 const field=(label,key,props={})=><Input label={label} value={data[key]} error={errors[key]} onChange={e=>set(key,e.target.value)} {...props}/>;
 return <section className="companySetup"><button className="backlink" onClick={onCancel}><IconArrowLeft/>Back to companies</button><header className="csHeader"><div className="csMark"><IconBuilding/></div><div><h1>Set up your company</h1><p>Tell us about your business. Wayvida Books will prepare the accounting structure.</p></div><span>Step {step+1} of {steps.length}</span></header><div className="csProgress" aria-label="Setup progress">{steps.map((name,i)=><button type="button" key={name} className={i===step?'active':i<step?'done':''} onClick={()=>i<step&&setStep(i)}><i>{i<step?<IconCheck/>:i+1}</i><span>{name}</span></button>)}</div><main className="csCard"><div className="csSectionHead"><small>{String(step+1).padStart(2,'0')} / {String(steps.length).padStart(2,'0')}</small><h2>{steps[step]}</h2><p>{['Start with the details customers will recognize.','Choose the closest business structure. We use it only to select sensible defaults.','Enter the registered business location.','Choose how your accounting year is organized.','Select the currency used for books and reports.','Add only the registrations that apply to this company.','Choose simple operating preferences. Advanced controls remain available later.','Review your setup. Nothing is posted to the ledger during company creation.'][step]}</p></div>{failure&&<div className="csError" role="alert">{failure}</div>}<div className="csFields">
 {step===0&&<>{field('Company name *','name',{autoFocus:true,placeholder:'e.g. Wayvida Technologies'})}{field('Legal name *','legalName',{placeholder:'Registered legal name'})}{field('Phone','phone',{type:'tel',placeholder:'+91 98765 43210'})}{field('Email','email',{type:'email',placeholder:'accounts@company.com'})}</>}
 {step===1&&<label className="csWide"><span>Business type *</span><select value={data.businessType} onChange={e=>set('businessType',e.target.value)}>{businessTypes.map(x=><option key={x}>{x}</option>)}</select><small className="csHelp">This selects a suitable Chart of Accounts template. You can customize accounts later.</small></label>}
 {step===2&&<><label><span>Country *</span><select value={data.country} onChange={e=>set('country',e.target.value)}><option>India</option></select></label><label><span>State *</span><select value={data.state} onChange={e=>set('state',e.target.value)}>{states.map(x=><option key={x}>{x}</option>)}</select></label><label className="csWide"><span>Registered address *</span><textarea value={data.address} onChange={e=>set('address',e.target.value)} placeholder="Building, street, city and PIN code"/>{errors.address&&<small role="alert">{errors.address}</small>}</label></>}
 {step===3&&<label className="csWide"><span>Financial year *</span><select value={data.financialYear} onChange={e=>set('financialYear',e.target.value)}><option>April – March</option><option>January – December</option></select><small className="csHelp">Twelve monthly accounting periods will be created automatically.</small></label>}
 {step===4&&<label className="csWide"><span>Base currency *</span><select value={data.currency} onChange={e=>set('currency',e.target.value)}>{currencies.map(x=><option key={x}>{x}</option>)}</select><small className="csHelp">This becomes the reporting currency for the company.</small></label>}
 {step===5&&<><label><span>GST registered? *</span><select value={data.gstRegistered} onChange={e=>set('gstRegistered',e.target.value)}><option>No</option><option>Yes</option></select></label>{data.gstRegistered==='Yes'&&field('GSTIN *','gstin',{placeholder:'32ABCDE1234F1Z5',maxLength:15})}{field('PAN (if applicable)','pan',{placeholder:'ABCDE1234F',maxLength:10})}</>}
 {step===6&&<div className="csPreferences csWide"><Preference title="Accrual accounting" text="Recognize income and expenses when they are earned or incurred." checked={data.accrual} onChange={v=>set('accrual',v)}/><Preference title="Track inventory" text="Enable stock-aware defaults for products and purchases." checked={data.inventory} onChange={v=>set('inventory',v)}/><div className="csAuto"><IconShieldCheck/><span><b>Configured automatically</b><small>Document numbering, Chart of Accounts, tax defaults, accounting periods, roles and permissions.</small></span></div></div>}
 {step===7&&<div className="csReview csWide"><Review label="Company" value={data.name}/><Review label="Business" value={data.businessType}/><Review label="Location" value={`${data.state}, ${data.country}`}/><Review label="Financial year" value={data.financialYear}/><Review label="Currency" value={data.currency}/><Review label="Tax registration" value={data.gstRegistered==='Yes'?`GST registered · ${data.gstin}`:'Not GST registered'}/><div className="csReady"><IconCheck/><span><b>Ready to create</b><small>Your company and its accounting foundation will be created together.</small></span></div></div>}
 </div></main><footer className="csActions"><button type="button" onClick={()=>step?setStep(step-1):onCancel()}><IconArrowLeft/>{step?'Back':'Cancel'}</button>{step<steps.length-1?<button className="primary" type="button" onClick={next}>Continue<IconArrowRight/></button>:<button className="primary" type="button" disabled={saving} onClick={finish}>{saving?<><IconLoader2 className="csSpin"/>Creating company…</>:<><IconCheck/>Create company & open dashboard</>}</button>}</footer></section>
}
function Preference({title,text,checked,onChange}){return <label className="csPreference"><span><b>{title}</b><small>{text}</small></span><input role="switch" type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/></label>}
function Review({label,value}){return <div><span>{label}</span><b>{value||'Not provided'}</b></div>}
