import {IconAlertTriangle,IconArrowRight,IconBook2,IconExternalLink,IconInfoCircle,IconX} from '@tabler/icons-react';
import {getPageKnowledge,statusKnowledge} from './page-knowledge.js';
import './contextual-help.css';

export function PageGuide({page,onOpen}){const item=getPageKnowledge(page);if(!item)return null;return <div className="pageGuide"><IconBook2/><span><b>{item.page}</b><small>{item.purpose}</small></span><button onClick={onOpen}>How this works <IconArrowRight/></button></div>}
export function WorkflowStepper({steps=[]}){return <div className="guideWorkflow">{steps.map((step,index)=><div key={step}><b>{index+1}</b><span>{step}</span>{index<steps.length-1&&<IconArrowRight/>}</div>)}</div>}
export function AccountingImpactCard({impact=[],summary}){return <section className="guideImpact"><h3>Accounting Impact</h3>{summary&&<p>{summary}</p>}<ul>{impact.map(line=><li key={line} className={line.startsWith('Dr')?'debit':line.startsWith('Cr')?'credit':''}>{line}</li>)}</ul></section>}
export function StatusExplanation({status}){const item=statusKnowledge[status];if(!item)return null;return <section className="guideStatus"><span>Current status</span><h3>{status}</h3><p>{item.meaning}</p><dl><dt>Accounting</dt><dd>{item.accountingImpact}</dd><dt>Allowed</dt><dd>{item.allowedActions.join(', ')||'View'}</dd><dt>Restricted</dt><dd>{item.blockedActions.join(', ')||'None'}</dd><dt>Next</dt><dd>{item.nextPossibleStatus.join(', ')||'Workflow complete'}</dd></dl></section>}
export function DisabledActionReason({children,reasons=[]}){return <span className="disabledReason" tabIndex="0">{children}<span role="tooltip"><b>Cannot continue because:</b>{reasons.map(reason=><small key={reason}>• {reason}</small>)}</span></span>}
export function HelpDrawer({page,status,onClose,onNavigate=()=>{}}){const item=getPageKnowledge(page);if(!item)return null;return <div className="guideBackdrop" onClick={onClose}><aside className="guideDrawer" role="dialog" aria-modal="true" aria-labelledby="guide-title" onClick={event=>event.stopPropagation()}><header><div><span>{item.module} · Page Guide</span><h2 id="guide-title">{item.title}</h2></div><button aria-label="Close page guide" onClick={onClose}><IconX/></button></header><div className="guideBody"><section><h3>About This Page</h3><p>{item.purpose}</p></section><section><h3>Workflow</h3><WorkflowStepper steps={item.workflow}/></section>{status&&<StatusExplanation status={status}/>}<AccountingImpactCard impact={item.accountingImpact}/><section><h3>Available actions</h3><div className="guideTags">{item.actions.map(action=><span key={action}>{action}</span>)}</div></section><section><h3>Related Settings</h3>{item.relatedSettings.map(setting=><button className="guideLink" key={setting} onClick={()=>onNavigate(setting==='Bank Matching Rules'?'Banking Settings':'Settings Center')}>{setting}<IconExternalLink/></button>)}</section><section><h3>Common Issues</h3>{item.commonIssues.map(issue=><p className="guideIssue" key={issue}><IconAlertTriangle/>{issue}</p>)}</section><section><h3>Related Pages</h3>{item.relatedPages.map(related=><button className="guideLink" key={related} onClick={()=>onNavigate(related)}>{related}<IconArrowRight/></button>)}</section><p className="guideNote"><IconInfoCircle/>Help content describes the current prototype. Source code and posting validation remain authoritative.</p></div></aside></div>}
