import {useDeferredValue,useEffect,useMemo,useState} from 'react';
import {IconAdjustments,IconAlertTriangle,IconCheck,IconFileSpreadsheet,IconFileTypePdf,IconRefresh,IconSearch} from '@tabler/icons-react';
import {readAccounts} from './account-store.js';
import {initial,money,today} from './invoice-engine.js';
import {AGING_BUCKETS,AGING_LABELS,INVOICE_STATUSES,customerOutstanding,customerOutstandingExportRows} from './customer-outstanding.js';
import {downloadReport,excelReport} from './daybook-export.js';
import {demoOrganizations} from './demo-organisations.js';
import EmptyState from './EmptyState.jsx';
import './customer-outstanding.css';
import {AsOfDateSelect,ReportExportMenu} from './ReportToolbar.jsx';

const CUSTOMERS_KEY='wayvida-customers';
const ALL='All';
const DASH='—';

const readCustomers=()=>{try{const rows=JSON.parse(localStorage.getItem(CUSTOMERS_KEY));return Array.isArray(rows)?rows:[]}catch{return []}};

export default function CustomerOutstanding({notify,onNavigate}){
  const [revision,setRevision]=useState(0),[asOf,setAsOf]=useState(today()),[branch,setBranch]=useState(ALL),[customer,setCustomer]=useState(ALL),[status,setStatus]=useState(ALL),[aging,setAging]=useState(ALL),[search,setSearch]=useState(''),[filtersOpen,setFiltersOpen]=useState(false),[stamp,setStamp]=useState(()=>new Date());
  const deferredSearch=useDeferredValue(search),busy=deferredSearch!==search;
  const organization=demoOrganizations.find(item=>item.id===localStorage.getItem('wayvida-demo-company'))||demoOrganizations[0];

  useEffect(()=>{const refresh=()=>setRevision(x=>x+1);window.addEventListener('wayvida-accounts-updated',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('wayvida-accounts-updated',refresh);window.removeEventListener('storage',refresh)}},[]);

  const {book,customers,error}=useMemo(()=>{try{return {book:readAccounts(),customers:readCustomers(),error:''}}catch(e){return {book:initial(),customers:[],error:e.message}}},[revision]);
  const report=useMemo(()=>customerOutstanding(book,customers,{asOf,branch,customer,status,aging,search:deferredSearch}),[book,customers,asOf,branch,customer,status,aging,deferredSearch]);
  const branches=[...new Set([...(organization.branches||[]).map(item=>item.name),...report.branchOptions])];

  function reset(){setAsOf(today());setBranch(ALL);setCustomer(ALL);setStatus(ALL);setAging(ALL);setSearch('')}
  function refresh(){setRevision(x=>x+1);setStamp(new Date())}
  function exportExcel(){const content=excelReport(customerOutstandingExportRows(report,{organisation:organization.name,generatedBy:'Local user',generatedAt:stamp.toISOString()}));downloadReport(content,'wayvida-customer-outstanding.xml','application/xml;charset=utf-8')}
  function print(){setStamp(new Date());setTimeout(()=>window.print(),50)}
  function printMeta(){return [['Wayvida Books · Customer Outstanding','See what your customers currently owe you.'],['Organisation',organization.name],['Branch',branch===ALL?'All branches':branch],['As of',asOf],['Customer',customer===ALL?'All customers':(report.customers.find(entry=>entry.id===customer)?.name||customer)],['Status',status===ALL?'All':status],['Aging',aging===ALL?'All':AGING_LABELS[aging]||aging],['Search',search||'None'],['Documents',status===ALL?'Outstanding only':status],['Total receivable',money(report.totals.outstanding)],['Accounts Receivable control',report.reconciliation.control===null?'Not configured':money(report.reconciliation.control)],['Difference',report.reconciliation.difference===null?'Unknown':money(Math.abs(report.reconciliation.difference))],['Generated by Local user',stamp.toLocaleString()]]}

  const activeFilters=[branch!==ALL,customer!==ALL,status!==ALL,aging!==ALL].filter(Boolean).length;

  const customerRow=entry=>(
    <tr key={entry.id} className="coCustomer">
      <th scope="row" className="coNameCell"><span>{entry.name}</span></th>
      <td className="coCodeCol">{entry.code||DASH}</td>
      <td className="coMoney coCountCol">{entry.invoices}</td>
      <td className="coMoney coStrong coOutCol">{money(entry.outstanding)}{aging!==ALL&&<em className="coAgingHint">{AGING_LABELS[aging]}: {money(entry.agingAmount)}</em>}</td>
      <td className="coMoney coDueCol">{money(entry.overdue)}</td>
      <td className="coMoney coDueCol">{money(entry.notYetDue)}</td>
    </tr>
  );

  const reconciliation=report.reconciliation;

  return (
    <section className="coPage" aria-busy={busy}>
      <header className="coHead">
        <div><h1>Customer Outstanding</h1><p>See what your customers currently owe you.</p></div>
        <div className="coHeadActions">
          <AsOfDateSelect date={asOf} onChange={value=>setAsOf(value)} onCustom={()=>setFiltersOpen(true)}/>
          <details className="coFiltersMore" open={filtersOpen} onToggle={e=>setFiltersOpen(e.currentTarget.open)}>
            <summary aria-label="Open filters"><IconAdjustments size={17}/>Filters{activeFilters>0&&<span>{activeFilters}</span>}</summary>
            <div className="coFilters">
              <label>As of Date<input type="date" aria-label="As of Date" value={asOf} onChange={e=>setAsOf(e.target.value)}/></label>
              <label>Branch<select aria-label="Branch" value={branch} onChange={e=>setBranch(e.target.value)}><option value={ALL}>All branches</option>{branches.map(item=><option key={item} value={item}>{item}</option>)}</select></label>
              <label>Status<select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option value={ALL}>All</option>{INVOICE_STATUSES.map(item=><option key={item} value={item}>{item}</option>)}</select></label>
              <label>Aging<select aria-label="Aging" value={aging} onChange={e=>setAging(e.target.value)}><option value={ALL}>All</option>{AGING_BUCKETS.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></label>
              <label>Customer<select aria-label="Customer" value={customer} onChange={e=>setCustomer(e.target.value)}><option value={ALL}>All customers</option>{report.customerOptions.map(item=><option key={item.id} value={item.id}>{item.code?item.code+' · '+item.name:item.name}</option>)}</select></label>
              <div className="coFilterActions"><button type="button" onClick={refresh}><IconRefresh size={15}/>Refresh</button><button type="button" onClick={reset}>Clear filters</button></div>
            </div>
          </details>
          <ReportExportMenu items={[{key:'excel',label:'Export Excel',icon:<IconFileSpreadsheet size={17}/>,onClick:exportExcel,disabled:!report.customers.length},{key:'pdf',label:'Export PDF',icon:<IconFileTypePdf size={17}/>,onClick:print,disabled:!report.customers.length}]}/>
        </div>
      </header>

      {error&&<div className="coError" role="alert"><IconAlertTriangle size={18}/><span>{error}</span></div>}
      <div className="coPrintMeta">{printMeta().map(([label,value])=><p key={label}><b>{label}:</b> {value}</p>)}</div>

      <div className="coSummary">
        <div><span>Total Receivable</span><strong>{money(report.totals.outstanding)}</strong></div>
        <div><span>Overdue</span><strong>{money(report.totals.overdue)}</strong></div>
        <div><span>Due Today</span><strong>{money(report.totals.dueToday)}</strong></div>
        <div><span>Not Yet Due</span><strong>{money(report.totals.notYetDue)}</strong></div>
      </div>

      <div className="coStatementCard">
        <div className="coTableScroll">
          <table>
            <thead><tr><th className="coNameCol">Customer</th><th className="coCodeCol">Customer ID</th><th className="coCountCol">Invoices</th><th className="coOutCol">Outstanding</th><th className="coDueCol">Overdue</th><th className="coDueCol">Not Yet Due</th></tr></thead>
            <tbody>
              {report.customers.map(customerRow)}
              {!report.customers.length&&<tr className="emptyStateRow"><td colSpan="6" className="emptyStateCell"><EmptyState variant="customer" title="No outstanding customer balances found." description="Try changing the date or filters." actionLabel="Reset filters" onAction={reset}/></td></tr>}
            </tbody>
            {report.customers.length>0&&(
              <tfoot>
                <tr className="coGrandTotal">
                  <th colSpan="2" className="coNameCol" scope="row">Total</th>
                  <th className="coMoney coCountCol">{report.totals.invoices}</th>
                  <th className="coMoney coOutCol">{money(report.totals.outstanding)}</th>
                  <th className="coMoney coDueCol">{money(report.totals.overdue)}</th>
                  <th className="coMoney coDueCol">{money(report.totals.notYetDue)}</th>
                </tr>
              </tfoot>
            )}
          </table>
        </div>
      </div>

      <div className={'coEquation coStickyBalance '+(reconciliation.difference===null?'unknown':reconciliation.reconciled?'balanced':'mismatch')} role="status">
        {reconciliation.difference===null?<IconAlertTriangle size={19}/>:reconciliation.reconciled?<IconCheck size={19}/>:<IconAlertTriangle size={19}/>}
        <b>{reconciliation.difference===null?'No Accounts Receivable control account is configured':(reconciliation.reconciled?'Reconciles':'Does not reconcile')}</b>
        <span>{reconciliation.difference===null?'Control: not configured':'Difference: '+money(Math.abs(reconciliation.difference))}</span>
      </div>
    </section>
  );
}
