import {useEffect,useMemo,useState} from 'react';
import {IconPrinter,IconFileInvoice,IconArrowLeft,IconCheck,IconHelp,IconPlus,IconFilter,IconSearch,IconTrash,IconX} from '@tabler/icons-react';
import {KEY,initial,money} from './invoice-engine.js';
import {DEBIT_NOTE_KEY,PURCHASE_BILL_KEY,applyDebitNote,approveDebitNote,calculatePurchase,cancelDebitNote,issueDebitNote,saveDebitNote,submitDebitNote,voidDebitNote} from './purchase-service.js';
import {QUICK_CREATE_KEY} from './quick-create.js';
import DocumentPreview from './DocumentPreview.jsx';
import StatusPill from './StatusPill.jsx';
import DebitNoteRowActions from './DebitNoteRowActions.jsx';
import {readVendors} from './vendor-store.js';
import './purchases.css';
import './debit-notes.css';
const read=(key,fallback=[])=>{try{const value=JSON.parse(localStorage.getItem(key));return Array.isArray(value)?value:fallback}catch{return fallback}};
const today=()=>new Date().toLocaleDateString('en-CA'),reasons=['Purchase Return','Price Adjustment','Additional Charges','Tax Adjustment','Invoice Correction','Other'];
const accountLine=()=>({id:crypto.randomUUID(),itemId:'account-adjustment',description:'Purchase adjustment',qty:'1',unit:'service',rate:'0',discount:'0',taxRate:'0',cessRate:'0',priceTaxMode:'exclusive',purchaseAccount:'5000'});
export default function DebitNotes({onNavigate=()=>{}}){
 const [rows,setRows]=useState(()=>read(DEBIT_NOTE_KEY)),[bills,setBills]=useState(()=>read(PURCHASE_BILL_KEY)),[form,setForm]=useState(null),[view,setView]=useState(null),[preview,setPreview]=useState(false),[menu,setMenu]=useState(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('All statuses'),[error,setError]=useState(''),[stab,setStab]=useState('Overview'),[vendorFilter,setVendorFilter]=useState(''),[reasonFilter,setReasonFilter]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const vendors=readVendors().filter(v=>v.status==='Active'),eligible=bills.filter(b=>b.posted&&b.status!=='Cancelled'&&b.total-(b.paidAmount||0)-(b.creditApplied||0)>0),visible=useMemo(()=>{const list=rows.filter(row=>[row.number,row.billNumber,row.vendorName,row.reason].join(' ').toLowerCase().includes(query.toLowerCase())&&(filter==='All statuses'||row.status===filter)&&(!vendorFilter||row.vendorId===vendorFilter)&&(!reasonFilter||row.reason===reasonFilter)&&(!from||(row.date||'')>=from)&&(!to||(row.date||'')<=to));return [...list].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))},[rows,query,filter,vendorFilter,reasonFilter,from,to]);
 const activeFilters=[filter!=='All statuses',vendorFilter,reasonFilter,from,to].filter(Boolean).length;
 const clearFilters=()=>{setFilter('All statuses');setVendorFilter('');setReasonFilter('');setFrom('');setTo('');setQuery('')};
 const totals=(()=>{try{return form?calculatePurchase(form.lines,{placeOfSupply:form.placeOfSupply}):null}catch{return null}})();
 function selectBill(id){const bill=eligible.find(row=>row.id===id);if(!bill)return;setForm({id:null,number:'',billId:bill.id,billNumber:bill.number,vendorId:bill.vendorId,vendorName:bill.vendorName,vendorInvoiceReference:bill.vendorInvoice||'',placeOfSupply:bill.placeOfSupply||'Kerala',date:today(),branch:bill.branch||'Kochi Branch',costCentre:bill.costCentre||'Operations',currency:bill.currency||'INR',reason:'Purchase Return',reasonDescription:'',entryMode:'Item Based',attachments:[],lines:bill.lines.map(line=>({...structuredClone(line),id:crypto.randomUUID(),maxQty:line.qty,qty:String(line.qty)})),status:'Draft',payableAccount:bill.payableAccount||'2000'});}
 function openNew(){setError('');setForm({id:null,number:'',billId:'',billNumber:'',vendorId:'',vendorName:'',vendorInvoiceReference:'',placeOfSupply:'Kerala',date:today(),branch:'Kochi Branch',costCentre:'Operations',currency:'INR',reason:'Purchase Return',reasonDescription:'',entryMode:'Account Based',attachments:[],lines:[accountLine()],status:'Draft',payableAccount:'2000'});}
 function selectVendor(id){const vendor=vendors.find(row=>row.id===id);setForm(current=>({...current,vendorId:id,vendorName:vendor?.displayName||vendor?.name||'',vendorGstin:vendor?.gstin||'',placeOfSupply:vendor?.billing?.state||'Kerala',payableAccount:vendor?.payableAccountId||'2000'}))}
 useEffect(()=>{if(sessionStorage.getItem(QUICK_CREATE_KEY)==='debit-note'){sessionStorage.removeItem(QUICK_CREATE_KEY);openNew()}},[]);
 const persist=(next,note)=>{setRows(next);localStorage.setItem(DEBIT_NOTE_KEY,JSON.stringify(next));if(note)setView(note)};
 function save(event,status='Draft'){event.preventDefault();try{const out=saveDebitNote(rows,bills,form,status);persist(out.rows);setForm(null);setError('')}catch(e){setError(e.message)}}
 function transition(note,action){try{const out=action==='submit'?submitDebitNote(rows,note):approveDebitNote(rows,note);persist(out.rows,out.note)}catch(e){setError(e.message)}}
 function post(note){try{const state=JSON.parse(localStorage.getItem(KEY)||'null')||initial(),out=issueDebitNote({...state,debitNotes:rows,purchaseBills:bills},note),next=rows.map(row=>row.id===note.id?out.note:row);localStorage.setItem(KEY,JSON.stringify(out.state));persist(next,out.note)}catch(e){setError(e.message)}}
 function apply(note){try{const state=JSON.parse(localStorage.getItem(KEY)||'null')||initial(),out=applyDebitNote({...state,debitNotes:rows,purchaseBills:bills},note),next=rows.map(row=>row.id===note.id?out.note:row),nextBills=bills.map(row=>row.id===out.bill.id?out.bill:row);localStorage.setItem(KEY,JSON.stringify(out.state));localStorage.setItem(PURCHASE_BILL_KEY,JSON.stringify(nextBills));setBills(nextBills);persist(next,out.note)}catch(e){setError(e.message)}}
 function cancel(note){try{const out=cancelDebitNote(rows,note);persist(out.rows,out.note)}catch(e){setError(e.message)}}
 function reverse(note){try{const state=JSON.parse(localStorage.getItem(KEY)||'null')||initial(),out=voidDebitNote({...state,debitNotes:rows,purchaseBills:bills},note,{reason:'Debit note reversed by authorized user',date:today()}),updated={...out.note,status:'Reversed'},next=rows.map(row=>row.id===note.id?updated:row),nextBills=out.bill?bills.map(row=>row.id===out.bill.id?out.bill:row):bills;localStorage.setItem(KEY,JSON.stringify(out.state));localStorage.setItem(PURCHASE_BILL_KEY,JSON.stringify(nextBills));setBills(nextBills);persist(next,updated)}catch(e){setError(e.message)}}
 const duplicate=note=>{setForm({...structuredClone(note),id:null,number:'',status:'Draft',posted:false,journalId:null,appliedAmount:0,date:today(),lines:note.lines.map(row=>({...row,id:crypto.randomUUID()}))});setMenu(null)},set=(key,value)=>setForm(x=>({...x,[key]:value})),line=(i,key,value)=>setForm(x=>({...x,lines:x.lines.map((row,index)=>index===i?{...row,[key]:value}:row)}));
 if(view)return <section className="invoiceWorkspace purchaseWorkspace ivDetailOpen">
  {preview&&<DocumentPreview kind="Purchase Debit Note" doc={view} onClose={()=>setPreview(false)}/>}
  <div className="ivDetailHead"><button type="button" className="ivDetailBack" aria-label="Back to Debit Notes" onClick={()=>setView(null)}><IconArrowLeft size={19}/></button><div className="ivDetailHeadText"><h2>Debit note details</h2><small>{view.number} · {view.vendorName}</small></div></div>
  <div className="ivDetailBody"><section className="ivDetailSheet">
   {error&&<Error text={error} close={()=>setError('')}/>}
   <div className="ivDetailIdentityRow"><div className="ivDetailIdentity"><div className="ivDetailNumber"><h3>{view.number}</h3><StatusPill status={view.status} tone={DEBIT_TONES(view.status)}/></div><p>{view.vendorName}{view.billNumber?' · Against '+view.billNumber:''} · {view.date}</p></div>
    <div className="ivDocumentActions"><button onClick={()=>setPreview(true)}><IconPrinter size={16}/>Preview</button>{view.status==='Draft'&&<button className="primary" onClick={()=>transition(view,'submit')}><IconCheck size={16}/>Submit</button>}{view.status==='Pending Approval'&&<button className="primary" onClick={()=>transition(view,'approve')}><IconCheck size={16}/>Approve</button>}{view.status==='Approved'&&<button className="primary" onClick={()=>post(view)}><IconCheck size={16}/>Post</button>}{view.status==='Posted'&&view.billId&&<button className="primary" onClick={()=>apply(view)}><IconCheck size={16}/>Apply to bill</button>}{!view.posted&&view.status!=='Cancelled'&&<button onClick={()=>cancel(view)}>Cancel</button>}{view.posted&&!['Reversed','Voided'].includes(view.status)&&<button onClick={()=>reverse(view)}>Reverse</button>}</div>
   </div>
   <div className="ivDetailStats">{[['Status',view.status],['Vendor',view.vendorName],['Reference bill',view.billNumber||'No linked bill'],['Debit note date',view.date],['Total',money(view.total)],['Applied to bill',money(view.appliedAmount||0)]].map(([k,v])=><span key={k}><small>{k}</small><strong>{v}</strong></span>)}</div>
   <nav className="itemDetailTabs ivDetailTabs" aria-label="Debit note sections">{['Overview','Accounting','Activity'].map(t=><button key={t} type="button" className={stab===t?'active':''} aria-current={stab===t?'page':undefined} onClick={()=>setStab(t)}>{t}</button>)}</nav>
   {stab==='Overview'?<div className="ivOverviewPage"><div className="ivOverviewGrid"><section className="itemDetailCard"><div className="itemDetailSectionTitle"><IconFileInvoice size={18}/><h2>Vendor and reference</h2></div><dl className="itemDetailFacts">{[['Vendor',view.vendorName],['Purchase bill',view.billNumber],['Vendor invoice ref.',view.vendorInvoiceReference],['Date',view.date],['Reason',view.reason],['Reason detail',view.reasonDescription],['Entry mode',view.entryMode],['Branch',view.branch],['Cost centre',view.costCentre]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Not recorded'}</dd></div>)}</dl></section><section className="itemDetailCard"><div className="itemDetailSectionTitle"><IconFileInvoice size={18}/><h2>Accounting impact</h2></div><dl className="itemDetailFacts">{[['Debit · Accounts Payable',money(view.total)],['Credit · Purchase Adjustment',money(view.totals?.taxable)],['Credit · Input GST',money((view.totals?.tax||0)+(view.totals?.cess||0))],['Journal',view.journalId||'Created only after posting'],['Applied to bill',money(view.appliedAmount||0)]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Not recorded'}</dd></div>)}</dl></section></div><section className="itemDetailCard"><div className="itemDetailSectionTitle"><IconFileInvoice size={18}/><h2>Adjustment lines</h2></div><div className="ivScroll"><table className="ivInvoiceTable purchaseDetailLines"><thead><tr>{['Item / account','Description','Quantity','Rate','Tax','Total'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{(view.totals?.lines||[]).map(row=><tr key={row.id}><td>{row.purchaseAccount||row.itemId}</td><td>{row.description}</td><td>{row.qty} {row.unit}</td><td>{money(Number(row.rate)*100)}</td><td>{money(row.tax+row.cess)}</td><td>{money(row.total)}</td></tr>)}</tbody></table></div></section></div>:stab==='Accounting'?<div className="purchaseTabBody"><p className="ivMutedNote">{view.posted?'Posting created the journal below from the accounts mapped on the debit note.':'No journal exists until this debit note is posted.'}</p><dl className="itemDetailFacts">{[['Journal',view.journalId||'Not posted'],['Posted at',view.postedAt||'Not recorded'],['Posted by',view.postedBy||'Not recorded'],['Applied to bill',money(view.appliedAmount||0)],['Payable account',view.payableAccount||'2000'],['Place of supply',view.placeOfSupply||'Kerala']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Not recorded'}</dd></div>)}</dl></div>:<div className="purchaseTabBody"><dl className="itemDetailFacts">{[['Created',view.createdAt||'Not recorded'],['Created by',view.createdBy||'Not recorded'],['Last modified',view.updatedAt||'Not recorded'],['Status',view.status]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div>}
  </section></div>
 </section>;
 if(form)return <section className="invoiceWorkspace purchaseWorkspace soCreatePage ivCreatePage">
  <div className="soCreateHead"><div className="soHeadIdentity"><button type="button" className="soBack" aria-label="Back to Debit Notes" onClick={()=>setForm(null)}><IconArrowLeft size={19}/></button><div className="soHeadText"><h2>{form.id?'Edit':'Create'} Debit Note</h2><small className="soHeadHint">Save and approve this correction before an accounting entry is created.</small></div></div></div>
  <form className="ivCreateForm" onSubmit={e=>save(e,'Draft')}>
   {error&&<Error text={error} close={()=>setError('')}/>}
   <div className="ivCard soFormSection"><div className="soSectionHead"><div className="soSectionHeadText"><h3>Vendor information</h3></div></div><div className="ivFields">
    <Field label="Reference purchase bill (optional)"><select value={form.billId||''} onChange={e=>e.target.value?selectBill(e.target.value):set('billId','')}><option value="">No linked bill</option>{eligible.map(b=><option key={b.id} value={b.id}>{b.number} - {b.vendorName}</option>)}</select></Field>
    <Field label="Vendor *"><select value={form.vendorId||''} onChange={e=>selectVendor(e.target.value)}><option value="">Select vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.displayName||v.name}</option>)}</select></Field>
    <Field label="Vendor invoice reference"><input value={form.vendorInvoiceReference||''} onChange={e=>set('vendorInvoiceReference',e.target.value)}/></Field>
    <Field label="Debit note date *"><input type="date" value={form.date} onChange={e=>set('date',e.target.value)}/></Field>
    <Field label="Branch"><select value={form.branch} onChange={e=>set('branch',e.target.value)}><option>Kochi Branch</option><option>Bengaluru Branch</option></select></Field>
    <Field label="Cost centre"><select value={form.costCentre} onChange={e=>set('costCentre',e.target.value)}><option>Operations</option><option>Administration</option></select></Field>
    <Field label="Currency"><input value={form.currency} disabled/></Field>
    <Field label="Debit note number"><input value={form.number||''} onChange={e=>set('number',e.target.value)} placeholder="Auto generated"/></Field>
   </div></div>
   <div className="ivCard soFormSection"><div className="soSectionHead"><div className="soSectionHeadText"><h3>Reason and entry mode</h3></div></div><div className="ivFields">
    <Field label="Reason *"><select value={form.reason} onChange={e=>set('reason',e.target.value)}>{reasons.map(x=><option key={x}>{x}</option>)}</select></Field>
    {form.reason==='Other'&&<Field label="Reason description *"><input value={form.reasonDescription} onChange={e=>set('reasonDescription',e.target.value)}/></Field>}
    <Field label="Entry mode"><select value={form.entryMode} onChange={e=>setForm(x=>({...x,entryMode:e.target.value,lines:e.target.value==='Account Based'?[accountLine()]:x.lines}))}><option>Item Based</option><option>Account Based</option></select></Field>
   </div></div>
   <div className="ivCard"><div className="ivHeading"><h3>{form.entryMode} adjustment</h3><button type="button" disabled={form.entryMode==='Account Based'} onClick={()=>set('lines',[...form.lines,accountLine()])}><IconPlus size={16}/>Add line</button></div>
    <div className="ivScroll"><table className="ivLineTable"><thead><tr>{['Item / account','Quantity','Unit','Rate','Discount','Tax','Amount',''].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{form.lines.map((row,i)=><tr key={row.id}><td>{form.entryMode==='Account Based'?<select aria-label={'account '+(i+1)} value={row.purchaseAccount} onChange={e=>line(i,'purchaseAccount',e.target.value)}><option value="5000">5000 - Purchase Adjustment</option><option value="5600">5600 - Professional Fees</option></select>:<input value={row.description} disabled/>}</td><td><input aria-label={'qty '+(i+1)} type="number" min=".01" step=".01" max={row.maxQty} value={row.qty} onChange={e=>line(i,'qty',e.target.value)}/></td><td><input aria-label={'unit '+(i+1)} value={row.unit} onChange={e=>line(i,'unit',e.target.value)}/></td><td><input aria-label={'rate '+(i+1)} type="number" min="0" step=".01" value={row.rate} onChange={e=>line(i,'rate',e.target.value)}/></td><td><input aria-label={'discount '+(i+1)} type="number" min="0" max="100" value={row.discount||0} onChange={e=>line(i,'discount',e.target.value)}/></td><td><select aria-label={'tax '+(i+1)} value={row.taxRate||0} onChange={e=>line(i,'taxRate',e.target.value)}>{['0','5','12','18','28'].map(rate=><option key={rate} value={rate}>GST {rate}%</option>)}</select></td><td><strong>{money(calculatePurchase([row],{placeOfSupply:form.placeOfSupply}).total)}</strong></td><td><button type="button" aria-label="Remove line" disabled={form.lines.length===1} onClick={()=>set('lines',form.lines.filter((_,index)=>index!==i))}><IconTrash size={16}/></button></td></tr>)}</tbody></table></div>
    <section className="soBillingSummary"><div className="soSummaryHead"><h3>Billing summary</h3></div><Totals value={totals}/></section>
   </div>
   <details className="ivCard soMoreCard" open><summary><span className="soMoreTitle">Accounting preview</span><span className="soMoreHint">No journal until Post</span></summary><div className="soMoreBody"><div className="debitJournalPreview"><p><b>Debit</b><span>Accounts Payable</span><strong>{money(totals?.total)}</strong></p><p><b>Credit</b><span>Purchase Adjustment</span><strong>{money(totals?.taxable)}</strong></p><p><b>Credit</b><span>Input GST Adjustment</span><strong>{money((totals?.tax||0)+(totals?.cess||0))}</strong></p></div></div></details>
   <details className="ivCard soMoreCard"><summary><span className="soMoreTitle">Attachments</span><span className="soMoreHint">Optional</span></summary><div className="soMoreBody"><div className="ivFields">{['Vendor document','Supporting document','Invoice copy'].map(label=><Field key={label} label={label}><input type="file" onChange={e=>set('attachments',[...(form.attachments||[]),e.target.files[0]?.name].filter(Boolean))}/></Field>)}</div></div></details>
   <div className="ivFooter soActionBar"><dl className="soBarTotals"><div><dt>Total amount</dt><dd>{money(totals?.total)}</dd></div></dl><div className="soBarActions"><button type="button" onClick={()=>setForm(null)}>Cancel</button><button type="button" onClick={e=>save(e,'Draft')}>Save draft</button><button type="button" className="primary" onClick={e=>save(e,'Pending Approval')}><IconCheck size={16}/>Submit</button></div></div>
  </form>
 </section>;
 return <section className="invoiceWorkspace purchaseWorkspace">
  {error&&<Error text={error} close={()=>setError('')}/>}
  <div className="ivHeading"><div><h2>Debit Notes</h2><p>Create and manage vendor adjustments and purchase corrections.</p></div><div className="ivActions"><button onClick={()=>onNavigate('Help Center')}><IconHelp size={16}/>How Debit Notes Work</button><button className="primary" onClick={openNew}><IconPlus size={16}/>New Debit Note</button></div></div>
  <div className="ivCard ivRegisterCard">
   <div className="ivTools"><label className="ivToolSearch"><IconSearch size={17}/><input aria-label="Search debit notes" placeholder="Search number, vendor, bill or reason" value={query} onChange={e=>setQuery(e.target.value)}/></label><details className="soFiltersMore"><summary aria-label="Open filters"><IconFilter size={17}/>Filters{activeFilters>0&&<i>{activeFilters}</i>}</summary><div className="soFiltersPanel"><label>Status<select aria-label="Filter status" value={filter} onChange={e=>setFilter(e.target.value)}>{['All statuses','Draft','Pending Approval','Approved','Posted','Adjusted','Closed','Cancelled','Reversed'].map(x=><option key={x}>{x}</option>)}</select></label><label>Vendor<select aria-label="Filter vendor" value={vendorFilter} onChange={e=>setVendorFilter(e.target.value)}><option value="">All vendors</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.displayName||v.name}</option>)}</select></label><label>Reason<select aria-label="Filter reason" value={reasonFilter} onChange={e=>setReasonFilter(e.target.value)}><option value="">All reasons</option>{reasons.map(x=><option key={x}>{x}</option>)}</select></label><label>From<input type="date" aria-label="Filter from" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" aria-label="Filter to" value={to} onChange={e=>setTo(e.target.value)}/></label><button type="button" className="soClearFilters" onClick={clearFilters}>Clear filters</button></div></details></div>
   <div className="ivScroll"><table className="ivInvoiceTable"><thead><tr>{['Debit note & date','Vendor','Reference bill','Reason','Amount','Status','Actions'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{visible.map(row=><tr key={row.id}><td><button className="ivLink" onClick={()=>setView(row)}>{row.number}</button><small>{row.date}</small></td><td>{row.vendorName}<small>{row.createdBy||'Admin'}</small></td><td>{row.billNumber||'No linked bill'}<small>{row.vendorInvoiceReference||'-'}</small></td><td>{row.reason}</td><td>{money(row.total)}</td><td><StatusPill status={row.status} tone={DEBIT_TONES(row.status)}/></td><td><div className="ivRowActions"><button onClick={()=>setView(row)}>View</button><DebitNoteRowActions note={row} onView={()=>setView(row)} onEdit={()=>setForm(structuredClone(row))} onDuplicate={()=>duplicate(row)} onPrint={()=>{setView(row);setPreview(true)}} onDownload={()=>{setView(row);setPreview(true)}} onJournal={()=>onNavigate('Journal Entries')} onLedger={()=>onNavigate('General Ledger')} onCancel={()=>cancel(row)} onReverse={()=>reverse(row)}/></div></td></tr>)}</tbody></table>{!visible.length&&<div className="ivEmpty"><h3>No debit notes found</h3><p>{rows.length?'Adjust the search or filters to find a note.':'Create one from a posted purchase bill when a vendor correction is required.'}</p></div>}</div>
   <div className="ivActions purchaseRegisterFoot"><span>{visible.length} of {rows.length} records</span></div>
  </div>
 </section>;
}
const Field=({label,children})=><label>{label}{children}</label>;
const DEBIT_TONES=value=>{const s=String(value||'').toLowerCase();if(/cancel|reversed|voided|reject/.test(s))return 'danger';if(/pending|awaiting/.test(s))return 'warn';if(/draft/.test(s))return 'neutral';if(/adjusted|closed/.test(s))return 'ok';if(/posted|approved/.test(s))return 'info';return 'neutral'};
const Error=({text,close})=><div role="alert" className="ivError">{text}<button type="button" aria-label="Dismiss error" onClick={close}><IconX size={16}/></button></div>;
function Totals({value}){return <dl className="ivTotals"><div><dt>Taxable amount</dt><dd>{money(value?.taxable)}</dd></div><div><dt>CGST</dt><dd>{money(value?.cgst)}</dd></div><div><dt>SGST</dt><dd>{money(value?.sgst)}</dd></div><div><dt>IGST</dt><dd>{money(value?.igst)}</dd></div><div><dt>CESS</dt><dd>{money(value?.cess)}</dd></div><div><dt>Total amount</dt><dd>{money(value?.total)}</dd></div></dl>}
