import {useEffect,useRef,useState} from 'react';
import {IconPrinter,IconX,IconDeviceFloppy,IconEye,IconFileText,IconPalette,IconCheck,IconArrowLeft,IconShare} from '@tabler/icons-react';
import {money} from './invoice-engine.js';
import {defaultTemplate,layouts,loadTemplate,saveTemplate,printModel,documentLabels,amountInWords} from './document-templates.js';
import './document-preview.css';
import './document-preview-fix.css';

export function DocumentSheet({kind,doc,db,template}){
 const m=printModel(kind,doc,db),t=m.totals,label=documentLabels[kind]||documentLabels.Invoice;
 const purchase=['Purchase Order','Purchase Bill','Purchase Debit Note'].includes(kind),partyName=purchase?(doc.vendorName||'Vendor'):(doc.customerName||'Customer'),partyAddress=purchase?(doc.vendorAddress||doc.billing):doc.billing,partyGstin=purchase?doc.vendorGstin:doc.customerGstin;
 const rgb=template.accent.match(/[a-f\d]{2}/gi)?.map(v=>parseInt(v,16))||[0,0,0],light=rgb[0]*.299+rgb[1]*.587+rgb[2]*.114>160;
 return <article className={'dpPaper dp'+template.layout} style={{'--dp-accent':template.accent,'--dp-on-accent':light?'#172b44':'#ffffff','--dp-title-ink':light?'#172b44':template.accent}}>
  <div className="dpDocumentCategory"><span>{label.section}</span><span>{purchase?'Vendor copy':'Customer copy'} · INR</span></div><header className="dpLetterhead"><div>{template.logo&&<img src={template.logo} alt="Business logo"/>}<h2>{template.businessName||'Business name not configured'}</h2><p>{template.businessAddress}</p><p>{template.contact}</p>{doc.companyGstin&&<p>GSTIN: {doc.companyGstin}</p>}</div><div className="dpDocumentTitle"><span className="dpEyebrow">{kind==='Credit Note'?'Customer adjustment':kind==='Sales Order'?'Order confirmation':kind==='Purchase Order'?'Vendor order':kind==='Purchase Bill'?'Vendor invoice':kind==='Purchase Debit Note'?'Vendor credit adjustment':kind==='Receipt'?'Payment acknowledgement':'Sales document'}</span><h1>{label.title}</h1><strong>{doc.number}</strong><p><span className="dpStatusPill">{doc.status}</span></p></div></header>
  {(m.provisional||m.voided)&&<div className="dpWatermark">{m.voided?doc.status:'DRAFT / NOT POSTED'}</div>}
  {kind==='Sales Order'&&<p className="dpNotice">Sales order only · Not an invoice or proof of payment.</p>}
  {kind==='Purchase Order'&&<p className="dpNotice">Purchase order only · No payable or accounting entry has been created.</p>}
  {m.receipt&&m.provisional&&<p className="dpNotice">Unposted receipt · Not confirmation of a posted payment.</p>}
  <div className="dpAddresses"><div><h3>{m.receipt?'Received from':purchase?'Vendor':'Bill to'}</h3><strong>{partyName}</strong><p>{partyAddress}</p>{partyGstin&&<p>GSTIN: {partyGstin}</p>}</div>{template.showShipping&&(doc.shipping||doc.deliveryAddress)&&<div><h3>{purchase?'Deliver to':'Ship to'}</h3><p>{doc.shipping||doc.deliveryAddress}</p></div>}<dl>{[['Date',doc.date],['Due date',!m.receipt&&doc.dueDate],['Expected delivery',doc.expectedDate||doc.shipment],['Delivery method',doc.delivery],['Salesperson',doc.salesperson],['Vendor invoice',doc.vendorInvoice],['Reference',doc.reference||doc.referenceOrder],['Credit note type',kind==='Credit Note'?doc.type:null],['Reason',kind==='Credit Note'?[doc.reason,doc.reasonNote].filter(Boolean).join(' · '):null],['Place of supply',doc.place],['Original invoice',m.original],['Payment terms',purchase?doc.paymentTerms:!m.receipt&&doc.terms!==undefined?(Number(doc.terms)?`Net ${doc.terms} days`:'Due on receipt'):null]].filter(([,v])=>v).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div>
  {m.receipt?<><div className="dpReceiptAmount"><span>{m.voided?'Original receipt amount':'Amount received'}</span><strong>{money(m.total)}</strong></div><div className="dpPayment"><p>Payment mode: <strong>{doc.mode||'Not recorded'}</strong></p><p>Received into: <strong>{m.bank||'Not recorded'}</strong></p></div>{m.allocations.length>0&&<table><thead><tr><th>Invoice</th><th>Allocation status</th><th>Amount applied</th></tr></thead><tbody>{m.allocations.map((a,i)=><tr key={i}><td>{a.number}</td><td>{a.voided?'Voided':'Applied'}</td><td>{money(a.amount)}</td></tr>)}</tbody></table>}<p>{doc.kind==='Advance'?'Customer advance':'Customer payment'}{!m.voided&&doc.posted?` · Unallocated: ${money(m.total-m.allocations.filter(a=>!a.voided).reduce((n,a)=>n+a.amount,0))}`:''}</p></>:
  <><table className="dpItemsTable"><thead><tr>{['#','Item','Qty / Unit','Rate','Discount','Tax','Amount'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{m.lines.map((l,i)=><tr key={i}><td>{String(i+1).padStart(2,'0')}</td><td><strong>{l.description||l.name||'Item'}</strong></td><td>{l.qty}<small>{l.unit||'—'}</small></td><td>{money(Math.round(Number(l.rate||0)*100))}</td><td>{l.off!==undefined?money(l.off):'—'}</td><td>{l.cgst!==undefined?money((l.cgst||0)+(l.sgst||0)+(l.igst||0)+(l.cessAmount||0)):'—'}</td><td>{money(l.total??Math.round(Number(l.qty||0)*Number(l.rate||0)*100))}</td></tr>)}</tbody></table><div className="dpSettlement"><div className="dpAmountWords"><h3>Total in words</h3><p>{amountInWords(m.total)}</p>{doc.notes&&<><h3>Notes</h3><p>{doc.notes}</p></>}</div><dl className="dpTotals">{(t?[['Subtotal',t.subtotal],['Discount',t.discount],['Taxable amount',t.taxable],['CGST',t.cgst],['SGST',t.sgst],['IGST',t.igst],['Cess',t.cess],['Round off',t.roundOff]]:[]).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{money(v)}</dd></div>)}<div className="dpGrandTotal"><dt>{label.amount}</dt><dd>{money(m.total)}</dd></div></dl></div>{!t&&<p>Legacy document: detailed tax breakdown is unavailable. The saved total is preserved.</p>}</>}
  {doc.reason&&<p><strong>Reason:</strong> {doc.reason}</p>}{m.receipt&&<div className="dpAmountWords"><h3>Total in words</h3><p>{amountInWords(m.total)}</p>{doc.notes&&<p className="dpText">{doc.notes}</p>}</div>}
  {(doc.termsAndConditions||template.terms)&&<section className="dpTerms"><h3>Terms & conditions</h3><p>{doc.termsAndConditions||template.terms}</p></section>}
  {template.showSignature&&<div className="dpSignature"><span>{template.signature}</span></div>}
  <footer className="dpFooter">{template.footer}</footer>
 </article>;
}

export function PreviewOnly({kind,doc,db,template,onClose,onPrint,onShare,onCustomize,drawer,message,error,rootRef}){return <div className="dpOverlay dpPreviewShell dpEmbedded" role="region" aria-label={`${kind} print preview`} ref={rootRef}><header className="dpPreviewBar"><div><strong>{documentLabels[kind]?.title||kind}</strong><span>{doc.number}</span></div><nav aria-label="Document preview actions"><button onClick={onPrint}><IconPrinter size={17}/>Print</button><button title="Share document summary" onClick={onShare}><IconShare size={17}/>Share</button><button aria-expanded={!!drawer} onClick={onCustomize}><IconPalette size={17}/>Customize</button><button onClick={onClose} aria-label="Close print preview"><IconX size={18}/>Close</button></nav></header>{(message||error)&&<div className={'dpPreviewFeedback '+(error?'dpError':'')} role={error?'alert':'status'}>{error||message}</div>}<div className="dpPreviewBody"><main className="dpCleanCanvas"><DocumentSheet kind={kind} doc={doc} db={db} template={template}/></main>{drawer}</div></div>}

export default function DocumentPreview({kind,doc,db={},onClose,initialMode='preview'}){
 const [mode,setMode]=useState(initialMode);
 const [template,setTemplate]=useState(()=>{try{return loadTemplate(kind,doc.id)}catch{return {...defaultTemplate}}}),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[zoom,setZoom]=useState('100');
 const label=documentLabels[kind]||documentLabels.Invoice,m=printModel(kind,doc,db);
 const root=useRef(null);
 useEffect(()=>{root.current?.querySelector('button')?.focus()},[mode]);
 // Pin the current default when a document is first previewed, including after creation.
 useEffect(()=>{try{saveTemplate(kind,doc.id,template)}catch(e){setError(e.message)}},[]);
 useEffect(()=>{const previous=document.activeElement;const handler=e=>{if(e.key==='Escape'&&root.current?.contains(document.activeElement)){if(root.current.querySelector('.dpSettings'))setMode('preview');else onClose()}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);if(previous?.isConnected)previous.focus()}},[]);

 function update(k,v){setTemplate(x=>({...x,[k]:v}));setMessage('Unsaved template changes');setError('')}
 function save(all=false){try{saveTemplate(kind,doc.id,template,all);setMessage(all?`Default saved for new ${kind.toLowerCase()} documents`:'Template saved for this document');setError('');return true}catch(e){setError(e.message);return false}}
 async function print(){if(!template.businessName.trim()){setError('Enter the issuing business name under Business & branding before printing.');setMode('builder');return}if(!save())return;await document.fonts?.ready;await Promise.all([...root.current.querySelectorAll('img')].map(img=>img.decode?.().catch(()=>{})));window.print()}
 async function upload(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>512000){setError('Choose a PNG, JPG or WebP logo up to 500 KB.');return}setBusy(true);try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});update('logo',data)}catch{setError('Could not read the logo.')}finally{setBusy(false)}}
 async function share(){const party=doc.vendorName?'Vendor: '+doc.vendorName:'Customer: '+(doc.customerName||'');const text=[template.businessName,documentLabels[kind]?.title+' '+doc.number,party,'Date: '+doc.date,'Status: '+doc.status,'Total: '+money(m.total)].filter(Boolean).join('\n');try{if(navigator.share){await navigator.share({title:doc.number,text});setMessage('Document summary shared. To send the printout, save it as PDF and attach it.')}else{await navigator.clipboard.writeText(text);setMessage('Document summary copied. To send the printout, save it as PDF and attach it.')}setError('')}catch(e){if(e.name!=='AbortError')setError('Sharing is unavailable. Use Print to save a PDF and attach it to your message.')}}
 const drawer=mode==='builder'?(<aside className="dpSettings dpRightDrawer" aria-label="Customize template"><div className="dpDrawerHeading"><strong>Customize template</strong><button aria-label="Close customization" onClick={()=>setMode('preview')}><IconX size={18}/></button></div><div className="dpSettingsTitle"><IconPalette size={19}/><h2>Appearance</h2></div><p>Choose your customer-facing layout.</p><div className="dpLayouts">{layouts.map(layout=><button key={layout} aria-pressed={template.layout===layout} className={template.layout===layout?'selected':''} onClick={()=>update('layout',layout)}><span className={'dpSwatch '+layout}/><strong>{layout}</strong><small>{{Classic:'Structured & timeless',Modern:'Bold & branded',Minimal:'Clean & understated'}[layout]}</small>{template.layout===layout&&<IconCheck size={15}/>} </button>)}</div><details className="dpBuilderGroup"><summary>Business & branding</summary><label>Accent colour<input type="color" value={template.accent} onChange={e=>update('accent',e.target.value)}/></label>{[['businessName','Business name'],['businessAddress','Business address'],['contact','Contact details']].map(([k,label])=><label key={k}>{label}<textarea rows={k==='businessAddress'?3:2} maxLength={1000} value={template[k]} onChange={e=>update(k,e.target.value)}/></label>)}<label>Business logo<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={upload}/></label>{template.logo&&<button onClick={()=>update('logo',defaultTemplate.logo)}>Use Wayvida logo</button>}</details><details className="dpBuilderGroup"><summary>Footer, terms & signature</summary>{[['footer','Footer message'],['terms','Default terms'],['signature','Signature label']].map(([k,label])=><label key={k}>{label}<textarea maxLength={2000} rows={3} value={template[k]} onChange={e=>update(k,e.target.value)}/></label>)}{[['showShipping','Show shipping address'],['showSignature','Show signature line']].map(([k,label])=><label className="dpToggle" key={k}><input type="checkbox" role="switch" checked={template[k]} onChange={e=>update(k,e.target.checked)}/>{label}</label>)}</details><button className="primary dpApply" onClick={()=>{if(save())setMode('preview')}}>Save changes</button><button className="dpDefault" onClick={()=>save(true)}>Use as default for {kind.toLowerCase()}s</button><p>Saved on this device. Defaults apply to new documents; existing saved layouts stay unchanged.</p><p>PDF: choose “Save as PDF” in the print dialog. A4 layout; disable browser headers and footers for a clean copy.</p></aside>):null;
 return <PreviewOnly kind={kind} doc={doc} db={db} template={template} onClose={onClose} onPrint={print} onShare={share} onCustomize={()=>setMode(mode==='builder'?'preview':'builder')} drawer={drawer} error={error} message={message==='Unsaved template changes'?'':message} rootRef={root}/>;
}
