import {useMemo,useState} from 'react';
import {IconAdjustments,IconArrowLeft,IconBook,IconBuildingBank,IconCheck,IconChevronDown,IconDownload,IconEye,IconFileInvoice,IconFilter,IconHistory,IconMail,IconPrinter,IconRefresh,IconSearch,IconX} from '@tabler/icons-react';
import {KEY,ledger as postedLedger} from './invoice-engine.js';
import './general-ledger.css';

const TX=[
 {id:'lt1',date:'2026-09-01',type:'Opening Balance',voucher:'OB-2026-001',reference:'FY 2026–27',description:'Opening balance brought forward',account:'1010',debit:100000,credit:0,branch:'Kochi',cost:'Operations',status:'Posted',journal:'JE-OPEN-001',source:'Journal Entries',reconciled:true},
 {id:'lt2',date:'2026-09-02',type:'Receipt',voucher:'RCPT-00041',reference:'UTR90874561',description:'Payment received from ABC Retail Ltd',account:'1010',debit:50000,credit:0,branch:'Kochi',cost:'Sales',status:'Posted',journal:'JE-000112',source:'Receipts',reconciled:true},
 {id:'lt3',date:'2026-09-02',type:'Payment',voucher:'PAY-00028',reference:'NEFT-76018',description:'Vendor payment to Kerala Office Supplies',account:'1010',debit:0,credit:20000,branch:'Kochi',cost:'Operations',status:'Posted',journal:'JE-000113',source:'Payments',reconciled:false},
 {id:'lt4',date:'2026-09-03',type:'Expense',voucher:'EXP-00019',reference:'CARD-4492',description:'Monthly cloud infrastructure charges',account:'1010',debit:0,credit:15000,branch:'Bangalore',cost:'Operations',status:'Posted',journal:'JE-000118',source:'Expenses',reconciled:false},
 {id:'lt5',date:'2026-09-04',type:'Sales Invoice',voucher:'INV-000001',reference:'PO-ABC-882',description:'Website development services',account:'1100',debit:118000,credit:0,branch:'Kochi',cost:'Sales',status:'Posted',journal:'JE-000121',source:'Invoices',reconciled:false},
 {id:'lt6',date:'2026-09-04',type:'Sales Invoice',voucher:'INV-000001',reference:'PO-ABC-882',description:'Service revenue recognised',account:'4100',debit:0,credit:100000,branch:'Kochi',cost:'Sales',status:'Posted',journal:'JE-000121',source:'Invoices',reconciled:false},
 {id:'lt7',date:'2026-09-04',type:'Sales Invoice',voucher:'INV-000001',reference:'PO-ABC-882',description:'Output GST liability',account:'2100',debit:0,credit:18000,branch:'Kochi',cost:'Sales',status:'Posted',journal:'JE-000121',source:'Invoices',reconciled:false},
 {id:'lt8',date:'2026-09-05',type:'Credit Note',voucher:'CN-000014',reference:'INV-000001',description:'Service credit issued to customer',account:'1100',debit:0,credit:23600,branch:'Kochi',cost:'Sales',status:'Posted',journal:'JE-000126',source:'Credit Notes',reconciled:false},
 {id:'lt9',date:'2026-09-05',type:'Journal Entry',voucher:'JV-2026-45648',reference:'ADJ-SEP',description:'Month-end adjustment',account:'5200',debit:12000,credit:0,branch:'Bangalore',cost:'Operations',status:'Posted',journal:'JV-2026-45648',source:'Journal Entries',reconciled:false}
];
const FALLBACK=[
 {code:'1010',name:'HDFC Bank',type:'Assets',group:'Bank Accounts',opening:100000,normal:'Debit',created:'01 Apr 2026'},
 {code:'1100',name:'Accounts Receivable',type:'Assets',group:'Current Assets',opening:0,normal:'Debit',created:'01 Apr 2026'},
 {code:'2100',name:'GST Payable',type:'Liabilities',group:'Current Liabilities',opening:0,normal:'Credit',created:'01 Apr 2026'},
 {code:'4100',name:'Service Income',type:'Income',group:'Operating Income',opening:0,normal:'Credit',created:'01 Apr 2026'},
 {code:'5200',name:'Rent',type:'Expenses',group:'Operating Expenses',opening:0,normal:'Debit',created:'01 Apr 2026'}
];
const money=n=>'₹'+Math.abs(Number(n)||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const dateText=v=>new Date(v+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
const timeText=(createdAt,date)=>new Date(createdAt||date+'T09:00:00').toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'});
const sourcePage=source=>({
 'Sales Invoice':'Invoices','Customer Payment':'Payments Received','Customer Receipt':'Payments Received',
 'Credit Note':'Credit Notes','Journal Entry':'Journal Entries','Manual Journal':'Journal Entries',
 'Invoice Reversal':'Invoices','Receipt Reversal':'Payments Received'
}[source]||source||'Journal Entries');

export default function GeneralLedgerPro({accounts=[],notify,onNavigate}){
 const transactionRows=useMemo(()=>{try{const state=JSON.parse(localStorage.getItem(KEY)||'null');if(!state?.journals?.length)return TX;return postedLedger(state).map((line,index)=>({id:line.id||`ledger-${index}`,date:line.date,createdAt:line.createdAt,type:line.source||'Journal Entry',voucher:line.reference||line.number,reference:line.description||line.reference||'—',description:line.description||`${line.source||'Journal'} posting`,account:line.account,debit:(line.debit||0)/100,credit:(line.credit||0)/100,branch:line.branch||'Unassigned',cost:line.costCentre||'Unassigned',status:line.status||'Posted',journal:line.number,source:sourcePage(line.source),reconciled:Boolean(line.reconciled)}))}catch{return TX}},[]);
 const accountList=useMemo(()=>{const raw=Array.isArray(accounts)?accounts:Object.entries(accounts||{}).flatMap(([type,rows])=>(rows||[]).map(row=>Array.isArray(row)?{code:row[0],name:row[1],type}:row));const mapped=raw.filter(a=>!a.isGroup).map(a=>({code:a.code,name:a.name,type:a.type,group:a.parentName||a.type,opening:Number(a.openingBalance)||0,normal:a.normalBalance||(['Assets','Expenses'].includes(a.type)?'Debit':'Credit'),created:'01 Apr 2026'}));const merged=[...FALLBACK,...mapped];return [...new Map(merged.map(a=>[a.code,a])).values()]},[accounts]);
 const preferred=sessionStorage.getItem('wayvida-open-account')||'1010';
 const [account,setAccount]=useState(accountList.some(a=>a.code===preferred)?preferred:'1010'),[range,setRange]=useState('This Financial Year'),[branch,setBranch]=useState('All Branches'),[cost,setCost]=useState('All Cost Centres'),[voucher,setVoucher]=useState('All Voucher Types'),[status,setStatus]=useState('Posted'),[query,setQuery]=useState(''),[filters,setFilters]=useState(false),[detail,setDetail]=useState(null),[accountPage,setAccountPage]=useState(false),[tab,setTab]=useState('Ledger'),[reconcile,setReconcile]=useState(false);
 const active=accountList.find(a=>a.code===account)||accountList[0];
 const filtered=transactionRows.filter(x=>(!account||x.account===account)&&(branch==='All Branches'||x.branch===branch)&&(cost==='All Cost Centres'||x.cost===cost)&&(voucher==='All Voucher Types'||x.type===voucher)&&(status==='All Statuses'||x.status===status)&&[x.voucher,x.reference,x.description,x.journal].join(' ').toLowerCase().includes(query.toLowerCase()));
 const signed=x=>active?.normal==='Credit'?x.credit-x.debit:x.debit-x.credit;
 const openingRow=filtered.find(x=>x.type==='Opening Balance');
 const opening=Number(active?.opening)||Math.max(0,openingRow?signed(openingRow):0);
 const movements=filtered.filter(x=>x.type!=='Opening Balance');
 let running=opening;const rows=filtered.map(x=>({...x,running:x.type==='Opening Balance'?running:(running+=signed(x))}));
 const debit=movements.reduce((n,x)=>n+x.debit,0),credit=movements.reduce((n,x)=>n+x.credit,0),closing=opening+movements.reduce((n,x)=>n+signed(x),0);
 const appliedFilters=[range,branch!=='All Branches'&&branch,cost!=='All Cost Centres'&&cost,voucher!=='All Voucher Types'&&voucher,status!=='All Statuses'&&status].filter(Boolean);
 function reset(){setBranch('All Branches');setCost('All Cost Centres');setVoucher('All Voucher Types');setStatus('Posted');notify('Ledger filters reset')}
 function openSource(row){setDetail(row)}
 if(accountPage)return <AccountLedgerDetail account={active} rows={rows} tab={tab} setTab={setTab} onBack={()=>setAccountPage(false)} onSource={openSource} onNavigate={onNavigate} notify={notify}/>;
 return <section className="gl"><header className="gl-heading"><div><span className="gl-eyebrow"><IconBook size={15}/>Accounting report</span><h1>General Ledger</h1><p>Trace every posted movement from source document to journal and account balance.</p></div><div className="gl-heading-actions"><details><summary><IconDownload size={17}/>Export<IconChevronDown size={15}/></summary><div><button onClick={()=>notify('Excel export prepared')}><IconDownload size={16}/>Export Excel</button><button onClick={()=>notify('PDF export prepared')}><IconFileInvoice size={16}/>Export PDF</button><button onClick={()=>window.print()}><IconPrinter size={16}/>Print ledger</button><button onClick={()=>notify('Ledger report email prepared')}><IconMail size={16}/>Email report</button></div></details></div></header>
 <div className="gl-primary-filters gl-filter-toolbar"><label className="gl-account-picker"><span>Account</span><select value={account} onChange={e=>setAccount(e.target.value)} aria-label="Select ledger account">{accountList.map(a=><option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select></label><label className="gl-search"><IconSearch size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search voucher, reference or description" aria-label="Search ledger transactions"/></label><button className={filters?'active':''} onClick={()=>setFilters(true)} aria-expanded={filters}><IconFilter size={17}/>Filters<span className="gl-filter-count">{appliedFilters.length}</span></button></div>
 {filters&&<><button className="gl-scrim" onClick={()=>setFilters(false)} aria-label="Close filters"/><aside className="gl-filter-panel" aria-label="General Ledger filters"><div><IconAdjustments size={18}/><span><b>Filter General Ledger</b><small>Choose a period and transaction filters.</small></span><button onClick={()=>setFilters(false)} aria-label="Close filters"><IconX size={18}/></button></div><section><label>Date range<select value={range} onChange={e=>setRange(e.target.value)}>{['This Month','This Quarter','This Financial Year','Custom Range'].map(x=><option key={x}>{x}</option>)}</select></label><label>Branch<select value={branch} onChange={e=>setBranch(e.target.value)}>{['All Branches','Kochi','Bangalore'].map(x=><option key={x}>{x}</option>)}</select></label><label>Cost centre<select value={cost} onChange={e=>setCost(e.target.value)}>{['All Cost Centres','Sales','Operations'].map(x=><option key={x}>{x}</option>)}</select></label><label>Voucher type<select value={voucher} onChange={e=>setVoucher(e.target.value)}>{['All Voucher Types','Sales Invoice','Purchase Bill','Receipt','Payment','Expense','Journal Entry','Credit Note','Debit Note'].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{['All Statuses','Posted','Draft','Cancelled'].map(x=><option key={x}>{x}</option>)}</select></label></section><footer><button onClick={reset}><IconRefresh size={16}/>Reset</button><button className="primary" onClick={()=>setFilters(false)}><IconCheck size={16}/>Apply filters</button></footer></aside></>}
 <div className="gl-viewbar"><div className="gl-chips"><span>{active?.code} · {active?.name}</span>{appliedFilters.map(x=><span key={x}>{x}</span>)}</div><small>{rows.length} entries</small></div>
 <section className="gl-summary"><button className="gl-account-card" onClick={()=>setAccountPage(true)} aria-label={`View ${active?.name} account details`}><i><IconBuildingBank/></i><span><small>Selected account</small><b>{active?.name}</b><em>{active?.code} · {active?.type}</em><em>{active?.group} · Normal {active?.normal}</em></span><IconEye size={18}/></button>{[['Opening balance',opening,'neutral',active?.normal==='Credit'?'Cr':'Dr'],['Debit movement',debit,'debit',''],['Credit movement',credit,'credit',''],['Closing balance',closing,'closing',active?.normal==='Credit'?'Cr':'Dr']].map(([label,value,tone,suffix])=><article key={label} className={tone}><small>{label}</small><strong>{money(value)} {suffix&&<em>{suffix}</em>}</strong></article>)}</section>
 <section className="gl-card"><div className="gl-card-head"><div><h2>{active?.name} ledger</h2><p>{dateText('2026-04-01')} – {dateText('2026-09-05')} · Posted transactions only</p></div>{['Bank Accounts','Customers','Vendors'].includes(active?.group)&&<button onClick={()=>setReconcile(true)}><IconRefresh size={16}/>Reconcile</button>}</div><div className="gl-table-scroll" aria-label="Ledger transactions"><table className="gl-ledger-table gl-ledger-simple gl-ledger-compact"><thead><tr><th>Date &amp; time</th><th>Voucher</th><th>Debit</th><th>Credit</th><th>Balance</th><th>Status</th><th>View details</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><span className="gl-hover-description gl-date-time" title={row.description}><b>{dateText(row.date)}</b><small>{timeText(row.createdAt,row.date)}</small></span></td><td><button className="gl-link gl-hover-description" title={row.description} onClick={()=>openSource(row)}>{row.voucher}</button><small className="gl-voucher-type">{row.type}</small></td><td className="gl-money">{row.debit?money(row.debit):<span className="gl-empty-value">—</span>}</td><td className="gl-money">{row.credit?money(row.credit):<span className="gl-empty-value">—</span>}</td><td className="gl-money balance">{money(row.running)} {active?.normal==='Credit'?'Cr':'Dr'}</td><td><span className="gl-status"><IconCheck size={13}/>{row.status}</span></td><td><button className="gl-view-detail" onClick={()=>openSource(row)}><IconEye size={16}/>View details</button></td></tr>)}</tbody></table>{!rows.length&&<div className="gl-empty"><IconBook/><h3>No posted transactions found</h3><p>Try changing the date range or filters.</p><button onClick={reset}>Reset filters</button></div>}</div><footer><span>Opening {money(opening)} + period debits {money(debit)} − period credits {money(credit)}</span><strong>Closing balance {money(closing)} {active?.normal==='Credit'?'Cr':'Dr'}</strong></footer></section>
 {detail&&<SourceDrawer row={detail} onClose={()=>setDetail(null)} onJournal={()=>{onNavigate('Journal Entries');notify('Opening '+detail.journal)}} onSource={()=>{onNavigate(detail.source);notify('Opening '+detail.voucher)}}/>}{reconcile&&<ReconcileDialog rows={rows} onClose={()=>setReconcile(false)} notify={notify}/>}</section>
}

function SourceDrawer({row,onClose,onJournal,onSource}){return <><button className="gl-scrim" onClick={onClose} aria-label="Close transaction details"/><aside className="gl-drawer"><header><div><small>Ledger transaction</small><h2>{row.voucher}</h2></div><button onClick={onClose} aria-label="Close transaction details"><IconX size={18}/></button></header><span className="gl-posted"><IconCheck size={14}/>Posted</span><div className="gl-trace"><span>Source document</span><i>→</i><span>{row.journal}</span><i>→</i><span>Ledger entry</span></div><dl>{[['Date',dateText(row.date)],['Journal entry',row.journal],['Voucher type',row.type],['Reference',row.reference],['Description',row.description],['Branch',row.branch],['Cost centre',row.cost],['Reconciliation',row.reconciled?'Reconciled':'Unreconciled']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><section><p>Accounting impact</p><strong>{row.debit?'Debit '+money(row.debit):'Credit '+money(row.credit)}</strong></section><footer><button onClick={onJournal}><IconBook size={16}/>View journal</button><button onClick={()=>window.print()}><IconDownload size={16}/>Download PDF</button><button className="primary" onClick={onSource}><IconEye size={16}/>View source</button></footer></aside></>}

function AccountLedgerDetail({account,rows,tab,setTab,onBack,onSource,onNavigate,notify}){return <section className="gl gl-detail"><header className="gl-detail-head"><button onClick={onBack}><IconArrowLeft size={18}/></button><i><IconBuildingBank/></i><div><small>{account.code} · {account.type}</small><h1>{account.name}</h1><p>Current balance <b>{money(rows.at(-1)?.running??account.opening)} {account.normal==='Credit'?'Cr':'Dr'}</b></p></div><button onClick={()=>onNavigate('Chart of Accounts')}>Open account master</button></header><nav className="gl-tabs">{['Ledger','Transactions','Account Information','Audit Trail'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav><div className="gl-detail-card">{tab==='Ledger'&&<div className="gl-table-scroll"><table><thead><tr><th>Date</th><th>Voucher</th><th>Description</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{dateText(r.date)}</td><td><button className="gl-link" onClick={()=>onSource(r)}>{r.voucher}</button></td><td>{r.description}</td><td>{r.debit?money(r.debit):'—'}</td><td>{r.credit?money(r.credit):'—'}</td><td>{money(r.running)}</td></tr>)}</tbody></table></div>}{tab==='Transactions'&&<div className="gl-source-list">{rows.map(r=><button key={r.id} onClick={()=>onSource(r)}><IconFileInvoice/><span><b>{r.voucher}</b><small>{r.type} · {dateText(r.date)}</small></span><strong>{money(r.debit||r.credit)}</strong><IconEye/></button>)}</div>}{tab==='Account Information'&&<dl className="gl-facts">{[['Account code',account.code],['Account type',account.type],['Account group',account.group],['Opening balance',money(account.opening)],['Normal balance',account.normal],['Created date',account.created]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}{tab==='Audit Trail'&&<div className="gl-audit"><p><IconHistory/>Account created by Admin · {account.created}</p><p><IconCheck/>Last ledger posting by Accounting Engine · 05 Sep 2026</p><p><IconRefresh/>Balance recalculated and verified against Trial Balance</p></div>}</div></section>}

function ReconcileDialog({rows,onClose,notify}){const [picked,setPicked]=useState(rows.filter(r=>r.reconciled).map(r=>r.id));const difference=rows.filter(r=>picked.includes(r.id)).reduce((n,r)=>n+r.debit-r.credit,0);return <div className="gl-modal"><section><header><div><h2>Account reconciliation</h2><p>Match statement activity with posted ledger transactions.</p></div><button onClick={onClose}><IconX/></button></header><div className="gl-reconcile-summary"><span><small>Selected transactions</small><b>{picked.length}</b></span><span><small>Matched value</small><b>{money(difference)}</b></span><span><small>Difference</small><b>₹0.00</b></span></div><div className="gl-reconcile-list">{rows.map(r=><label key={r.id}><input type="checkbox" checked={picked.includes(r.id)} onChange={()=>setPicked(picked.includes(r.id)?picked.filter(x=>x!==r.id):[...picked,r.id])}/><span><b>{r.description}</b><small>{dateText(r.date)} · {r.voucher}</small></span><strong>{money(r.debit||r.credit)}</strong></label>)}</div><footer><button onClick={onClose}>Cancel</button><button className="primary" onClick={()=>{notify('Selected transactions marked reconciled');onClose()}}><IconCheck/>Mark reconciled</button></footer></section></div>}
