import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {IconBuilding,IconBuildingStore,IconCheck,IconChevronRight,IconSearch,IconX} from '@tabler/icons-react';
import './header-org-selectors.css';
import {getScopeOrganisations} from './organisation-context.js';

export const demoOrganizations=[
 {id:'abc',name:'ABC Technologies Pvt Ltd',code:'ABC01',type:'Private Limited',branches:[{id:'abc-kochi',name:'Kochi Branch',code:'KOC01'},{id:'abc-bengaluru',name:'Bengaluru Branch',code:'BLR02'},{id:'abc-trivandrum',name:'Trivandrum Branch',code:'TVM03'}]},
 {id:'northstar',name:'Northstar Retail LLP',code:'NSR02',type:'LLP',branches:[{id:'northstar-chennai',name:'Chennai Branch',code:'CHE01'},{id:'northstar-coimbatore',name:'Coimbatore Branch',code:'CBE02'}]},
 {id:'malabar',name:'Malabar Trading Co.',code:'MTC03',type:'Partnership',branches:[{id:'malabar-calicut',name:'Calicut Branch',code:'CLT01'},{id:'malabar-kannur',name:'Kannur Branch',code:'CNN02'}]},
 {id:'bluewave',name:'Bluewave Services Pvt Ltd',code:'BWS04',type:'Private Limited',branches:[{id:'bluewave-mumbai',name:'Mumbai Branch',code:'MUM01'},{id:'bluewave-pune',name:'Pune Branch',code:'PUN02'}]}
];
const read=(key,fallback)=>{try{return localStorage.getItem(key)||fallback}catch{return fallback}};
const readList=(key,fallback)=>{try{const value=JSON.parse(localStorage.getItem(key));return Array.isArray(value)&&value.length?value:fallback}catch{return fallback}};

export default function HeaderOrgSelectors(){
 const initialCompany=read('wayvida-demo-company','abc'),initialBranch=read('wayvida-demo-branch','abc-kochi');
 const [target,setTarget]=useState(null),[open,setOpen]=useState(false),[companyIds,setCompanyIds]=useState(()=>readList('wayvida-context-companies',[initialCompany])),[branchIds,setBranchIds]=useState(()=>readList('wayvida-context-branches',[initialBranch]));
 const [draftCompanies,setDraftCompanies]=useState(companyIds),[draftBranches,setDraftBranches]=useState(branchIds),[orgQuery,setOrgQuery]=useState(''),[branchQuery,setBranchQuery]=useState('');
 useEffect(()=>{setTarget(document.body)},[]);
 const accessibleOrganizations=useMemo(()=>getScopeOrganisations(),[]);
 const company=accessibleOrganizations.find(item=>item.id===companyIds[0])||accessibleOrganizations[0],allBranches=useMemo(()=>accessibleOrganizations.filter(item=>draftCompanies.includes(item.id)).flatMap(item=>item.branches.map(branch=>({...branch,companyId:item.id}))),[accessibleOrganizations,draftCompanies]),branch=accessibleOrganizations.flatMap(item=>item.branches).find(item=>item.id===branchIds[0])||company.branches[0];
 const selectedOrganizationNames=accessibleOrganizations.filter(item=>companyIds.includes(item.id)).map(item=>item.name),selectedBranchNames=accessibleOrganizations.flatMap(item=>item.branches).filter(item=>branchIds.includes(item.id)).map(item=>item.name),modeLabel=`${branchIds.length} ${branchIds.length===1?'branch':'branches'}`;
 function launch(){setDraftCompanies(companyIds);setDraftBranches(branchIds);setOrgQuery('');setBranchQuery('');setOpen(true)}
 function toggle(list,setList,id){setList(list.includes(id)?list.filter(value=>value!==id):[...list,id])}
 function toggleCompany(id){const organization=accessibleOrganizations.find(item=>item.id===id);if(draftCompanies.includes(id)){setDraftCompanies(draftCompanies.filter(value=>value!==id));setDraftBranches(draftBranches.filter(value=>!organization.branches.some(branch=>branch.id===value)))}else setDraftCompanies([...draftCompanies,id])}
 function apply(){const companies=draftCompanies,branches=draftBranches;if(!companies.length||!branches.length)return;const mode='Multi Selection';setCompanyIds(companies);setBranchIds(branches);localStorage.setItem('wayvida-context-companies',JSON.stringify(companies));localStorage.setItem('wayvida-context-branches',JSON.stringify(branches));localStorage.setItem('wayvida-context-mode',mode);localStorage.setItem('wayvida-demo-company',companies[0]);localStorage.setItem('wayvida-demo-branch',branches[0]);setOpen(false);const selectedCompany=accessibleOrganizations.find(item=>item.id===companies[0]),selectedBranch=selectedCompany?.branches.find(item=>item.id===branches[0]);window.dispatchEvent(new CustomEvent('wayvida-organization-change',{detail:{company:selectedCompany,branch:selectedBranch,companyIds:companies,branchIds:branches,mode}}));window.dispatchEvent(new CustomEvent('wayvida-working-context-change',{detail:{companyIds:companies,branchIds:branches,mode}}))}
 if(!target)return null;
 const visibleOrganizations=accessibleOrganizations.filter(item=>[item.name,item.code].join(' ').toLowerCase().includes(orgQuery.toLowerCase())),visibleBranches=allBranches.filter(item=>[item.name,item.code].join(' ').toLowerCase().includes(branchQuery.toLowerCase()));
 return createPortal(<><div className="orgContextBar" aria-label="Working Context"><div className="wcIdentity"><span className="wcHoverSummary" data-summary={selectedOrganizationNames.join(', ')}><IconBuilding/><b>{companyIds.length===1?company.name:`${companyIds.length} organisations`}</b></span><i/><span className="wcHoverSummary" data-summary={selectedBranchNames.join(', ')}><IconBuildingStore/><b>{branchIds.length===1?branch.name:`${branchIds.length} branches`}</b></span><i/><small>{modeLabel}</small></div><button className="wcChange" onClick={launch}>Change / Customize<IconChevronRight/></button></div>{open&&<div className="wcOverlay" onMouseDown={event=>event.target===event.currentTarget&&setOpen(false)}><aside className="wcDrawer" role="dialog" aria-modal="true" aria-labelledby="wc-title"><header><div><h2 id="wc-title">Choose organisations and branches</h2><p>Select one or more accessible contexts for dashboards, transactions, and reports.</p></div><button aria-label="Close working context" onClick={()=>setOpen(false)}><IconX/></button></header><div className="wcBody"><Picker title="Organisations" query={orgQuery} setQuery={setOrgQuery} all={visibleOrganizations} selected={draftCompanies} onChange={toggleCompany} onAll={()=>{const clearing=draftCompanies.length===accessibleOrganizations.length;setDraftCompanies(clearing?[]:accessibleOrganizations.map(item=>item.id));if(clearing)setDraftBranches([])}}/><Picker title="Branches" query={branchQuery} setQuery={setBranchQuery} all={visibleBranches} selected={draftBranches} onChange={id=>toggle(draftBranches,setDraftBranches,id)} onAll={()=>setDraftBranches(draftBranches.length===allBranches.length?[]:allBranches.map(item=>item.id))}/></div><footer><span>{draftCompanies.length} organisations · {draftBranches.length} branches selected</span><div><button onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={!draftCompanies.length||!draftBranches.length} onClick={apply}>Apply Context</button></div></footer></aside></div>}</>,target)
}

function Picker({title,query,setQuery,all,selected,onChange,onAll}){return <section className="wcPicker"><div className="wcPickerTitle"><div><h3>{title}</h3><small>{selected.length} selected</small></div><button onClick={onAll}>{selected.length===all.length?'Clear all':'Select all'}</button></div><label><IconSearch/><input aria-label={`Search ${title.toLowerCase()}`} value={query} onChange={event=>setQuery(event.target.value)} placeholder={`Search ${title.toLowerCase()}`}/></label><div className="wcOptions">{all.map(item=><button type="button" role="checkbox" aria-checked={selected.includes(item.id)} className={selected.includes(item.id)?'selected':''} key={item.id} onClick={()=>onChange(item.id)}><span className="wcBox">{selected.includes(item.id)&&<IconCheck/>}</span><span><b>{item.name}</b><small>{item.code}</small></span></button>)}</div></section>}
