import {pageKnowledge} from './page-knowledge.js';
export const helpStatuses=[
 ['Draft','Saved but not finalized.','No accounting entry.','Edit, submit or delete if permitted.'],['Pending Approval','Waiting for an authorized reviewer.','No posting until approval.','Review, approve or reject.'],['Approved','Business approval completed.','Ready to post; approval alone may not create a journal.','Post or send.'],['Posted','Accounting entry finalized.','Journal, ledger and reports are updated.','View impact; correct through reversal.'],['Sent','Document shared with the counterparty.','No additional accounting effect.','Follow up or record settlement.'],['Partially Paid','Some amount is settled.','Receivable or payable remains open for the balance.','Allocate another payment.'],['Paid','Full amount is settled.','Receivable or payable balance is closed.','View receipt/payment and ledger.'],['Overdue','Open balance passed its due date.','Posting is unchanged; ageing reports flag it.','Follow up or record payment.'],['Cancelled','Document stopped before completion or reversed by policy.','Posted documents require a reversal, not deletion.','Review audit and linked reversal.'],['Reversed','An opposite journal neutralized a posting.','Original and reversal remain in the ledger.','Create the corrected transaction if needed.'],['Closed','Workflow is complete.','No further operational action is expected.','View history.'],['Locked','Transaction date is inside a locked period.','New posting or changes are restricted.','Request unlock or use an open period.'],['Archived','Hidden from active work without deleting history.','No accounting change.','Restore if authorized.']
].map(([name,meaning,accounting,actions])=>({name,meaning,accounting,actions}));
export const helpCategories=['Dashboard','Accounting','Sales','Purchases','Banking','Expenses','Assets','Inventory','GST & TDS','Budgeting','Reports','Settings'];
const article=(id,category,title,summary,workflow,impact,settings,faq,keywords,related)=>({id,category,title,summary,workflow,impact,settings,faq,keywords,related,status:'Published'});
export const helpArticles=[
 article('invoice-workflow','Sales','How Sales Invoices Work','Create a customer invoice, approve and post it, then collect and allocate payment.',['Customer','Draft invoice','Approval','Post invoice','Send','Receive payment','Receivable closed'],['Dr Accounts Receivable','Cr Sales Income','Cr Output GST / Cess'],['Invoice numbering','Payment terms','GST','Approval workflow','Period locking'],[['Why can’t I edit it?','Posted invoices preserve audit history. Cancel or reverse them according to policy.'],['Why is it overdue?','The due date passed while an outstanding balance remains.']],['invoice','customer','cannot edit','overdue','receivable','posting'],['Customers','Receipts','General Ledger']),
 article('purchase-bill','Purchases','How Purchase Bills Work','Record a vendor invoice after the purchase and post the payable.',['Vendor','Purchase order','Receive goods','Purchase bill','Approval','Post','Vendor payment'],['Dr Purchase / Expense','Dr Input GST','Cr Accounts Payable'],['Purchase defaults','Approval limits','GST','Period locking'],[['Why can’t I post?','Check approval, posting accounts, vendor invoice number and period status.'],['Can I bill without a PO?','Only when Purchase Settings allow it.']],['purchase bill','vendor','payable','missing account','cannot post'],['Vendors','Purchase Orders','Vendor Payments']),
 article('purchase-debit-note','Purchases','How Purchase Debit Notes Work','Record goods returned or a vendor credit against a posted purchase bill.',['Open a posted bill','Create debit note','Confirm returned items and tax','Save for review','Issue','Apply to bill'],['Dr Accounts Payable','Cr Purchase / Expense','Cr Input GST reversal'],['Posted active purchase bill','Available bill balance','Period locking'],[['Why can’t I create one?','A posted bill with an available balance is required.'],['Can I edit an issued note?','No. Issued notes are immutable; voiding posts an equal and opposite reversal.']],['debit note','vendor credit','purchase return','input tax reversal'],['Purchase Bills','Vendor Payments','GST Reports']),
 article('journal-entry','Accounting','Understanding Journal Entries','Review automatic entries and create controlled accountant adjustments.',['Choose date','Add balanced lines','Approval if required','Post','Review ledger'],['Total debit must equal total credit','Posted journals update every linked ledger'],['Require narration','Cost centres','System-controlled accounts','Period locking'],[['Why is Post disabled?','The journal may be unbalanced, unapproved, locked, or use a restricted account.']],['journal','debit','credit','unbalanced','posting account'],['Chart of Accounts','General Ledger','Trial Balance']),
 article('general-ledger','Accounting','Understanding the General Ledger','See every posted debit and credit for one account with a running balance.',['Select account','Choose date range','Review entries','Open source or journal'],['Read-only view of posted journal lines','Running balance follows the account normal balance'],['Account numbers','Branch accounting','Financial year'],[['Why is a transaction missing?','Confirm it is posted, within the date range, and affects the selected account.']],['ledger','balance','voucher','account history'],['Journal Entries','Trial Balance','Day Book']),
 article('period-locking','Accounting','Period Locking and Unlock Requests','Protect finalized accounting dates from later changes.',['Complete reconciliation','Select day, week or month','Lock period','Posting restricted','Request unlock','Approve and audit'],['No journal is created','Posting commands inside the period are blocked or require override approval'],['Backdated transactions','Roles and permissions','Financial year'],[['Why can’t I post an old date?','The date may be locked or outside the backdated limit.']],['locked period','closing','backdated','unlock'],['Day Book','Audit & Activity','Settings']),
 article('chart-of-accounts','Accounting','Chart of Accounts Basics','Understand the reusable hierarchy behind journals, ledgers and reports.',['Account type','Parent group','Posting account','Operational mapping','Journal and reports'],['Assets and Expenses normally carry debit balances','Liabilities, Equity and Income normally carry credit balances'],['Account numbers','Default accounts','System-controlled accounts'],[['Why can’t I delete an account?','Accounts with posted history must be deactivated.']],['account','parent','normal balance','deactivate','posting ledger'],['Journal Entries','General Ledger','Settings']),
 article('gst-workflow','GST & TDS','How GST Flows Through Accounting','Calculate CGST/SGST or IGST and track input/output tax liabilities.',['GST registration','Tax rate','Place of supply','Transaction tax calculation','Post','GST reports'],['Intra-state: CGST + SGST','Inter-state: IGST','Sales creates output liability; purchases create eligible input tax'],['GST enabled','GSTIN','Tax rates','Reverse charge'],[['Why is IGST used?','Supplier/company state and place of supply indicate an inter-state transaction.']],['gst','cgst','sgst','igst','cess','place of supply'],['Invoices','Purchase Bills','GST Reports']),
 article('bank-reconciliation','Banking','Bank Reconciliation Explained','Match bank-statement activity to transactions already recorded in the books.',['Import statement','Review suggestions','Match or categorize','Resolve difference','Complete reconciliation'],['Matching does not create a duplicate journal','New charges or interest create controlled accounting entries'],['Statement import','Reconciliation','Bank rules'],[['What does Book mean?','The transaction exists in the accounting register; it may still need a bank-statement match.']],['bank','reconciliation','book','statement','match'],['Bank Accounts','General Ledger','Receipts']),
 article('expense-posting','Expenses','How Expense Posting Works','Capture business costs, evidence and approval before accounting.',['Create expense','Attach receipt','Approval','Post','Payment / reimbursement'],['Dr Expense','Dr Input GST when eligible','Cr Cash, Bank or Payable'],['Expense category','Approval amount','Receipt required','Default payment account'],[['Why is approval required?','The amount exceeds the configured limit or the category requires review.']],['expense','receipt attachment','reimbursement','approval'],['Expense Categories','Banking','General Ledger']),
 article('asset-depreciation','Assets','Asset Depreciation Workflow','Allocate an asset’s depreciable amount across its useful life.',['Create or capitalize asset','Set method and useful life','Generate schedule','Review','Post depreciation'],['Dr Depreciation Expense','Cr Accumulated Depreciation'],['Depreciation method','Useful life','Frequency','Asset accounts'],[['Can I change the method later?','Future schedules may change by policy; historical posted depreciation must not be rewritten.']],['asset','depreciation','straight line','written down value'],['Asset Register','Asset Transactions','Financial Reports'])
];
export const moduleDirectory=['Dashboard','Chart of Accounts','Journal Entries','General Ledger','Trial Balance','Day Book','Sales','Customers','Quotations','Sales Orders','Invoices','Credit Notes','Receipts','Purchases','Vendors','Purchase Orders','Goods Receipts','Purchase Bills','Debit Notes','Vendor Payments','Banking','Bank Accounts','Bank Reconciliation','Expenses','Expense Categories','Assets','Asset Register','Depreciation','Inventory','GST Reports','TDS Reports','Budgeting','Reports','Settings Center'];
export const knowledgeArticles=pageKnowledge.filter(item=>!helpArticles.some(article=>article.id===item.id)).map(item=>({id:item.id,category:item.module,title:item.title,summary:item.purpose,workflow:item.workflow,impact:item.accountingImpact,settings:item.relatedSettings,faq:item.commonIssues.map(issue=>['What can block this workflow?',issue]),keywords:item.keywords,related:item.relatedPages,status:'Published'}));
export function searchHelp(query){const catalog=[...helpArticles,...knowledgeArticles],words=query.trim().toLowerCase().split(/\s+/).filter(word=>word.length>1);if(!words.length)return catalog;return catalog.map(article=>{const text=JSON.stringify(article).toLowerCase(),score=words.filter(word=>text.includes(word)).length;return{article,score}}).filter(x=>x.score===words.length).sort((a,b)=>b.score-a.score).map(x=>x.article)}
