import {useMemo,useState} from 'react';
import {IconSearch,IconBook2,IconRocket,IconCalculator,IconFileInvoice,IconTruck,IconChevronRight,IconArrowLeft,IconExternalLink,IconInfoCircle,IconAlertTriangle,IconX} from '@tabler/icons-react';
import {helpArticles,helpCategories,helpStatuses,moduleDirectory,searchHelp} from './help-content.js';
import './help-center.css';
const categoryDescription={Dashboard:'Business overview and tasks',Accounting:'Accounts, journals and ledgers',Sales:'Customers, invoices and receipts',Purchases:'Vendors, bills and payments',Banking:'Bank activity and reconciliation',Expenses:'Costs, evidence and approval',Assets:'Assets and depreciation',Inventory:'Items, stock and valuation','GST & TDS':'Indian tax workflows',Budgeting:'Plans, actuals and variance',Reports:'Financial and operational reports',Settings:'ERP configuration and controls'};
export default function HelpCenter({onNavigate}){
 const [query,setQuery]=useState(''),[view,setView]=useState('home'),[selected,setSelected]=useState(null),[recent,setRecent]=useState([]);
 const results=useMemo(()=>searchHelp(query),[query]);
 function open(article){setSelected(article);setView('article');setRecent(x=>[article,...x.filter(a=>a.id!==article.id)].slice(0,4))}
 if(view==='article'&&selected)return <Article article={selected} onBack={()=>setView('home')} onNavigate={onNavigate} open={open}/>;
 if(view==='statuses')return <StatusGuide onBack={()=>setView('home')}/>;
 return <section className="hc"><header className="hcHero"><span>WAYVIDA BOOKS HELP CENTER</span><h1>How can we help?</h1><p>Learn workflows, understand statuses and resolve common accounting blockers.</p><label><IconSearch/><input autoFocus={false} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search modules, workflows, statuses, settings…"/><kbd>/</kbd></label></header>
 <main>{query?<section className="hcResults"><div className="hcTitle"><div><h2>Search results</h2><p>{results.length} articles found for “{query}”</p></div><button onClick={()=>setQuery('')}><IconX/>Clear</button></div>{results.length?<div className="hcArticleList">{results.map(a=><ArticleRow key={a.id} article={a} open={open}/>)}</div>:<div className="hcEmpty"><IconSearch/><h3>No matching help found</h3><p>Try a module name, status, account, setting or workflow step.</p></div>}</section>:<>
 <section><div className="hcTitle"><div><h2>Quick start</h2><p>Start with the workflow closest to your task.</p></div></div><div className="hcQuick"><button onClick={()=>setView('statuses')}><i><IconRocket/></i><span><b>Getting started</b><small>Statuses and safe workflows</small></span><IconChevronRight/></button><button onClick={()=>open(helpArticles.find(a=>a.id==='chart-of-accounts'))}><i><IconCalculator/></i><span><b>Accounting basics</b><small>Accounts, debit and credit</small></span><IconChevronRight/></button><button onClick={()=>open(helpArticles.find(a=>a.id==='invoice-workflow'))}><i><IconFileInvoice/></i><span><b>Create your first invoice</b><small>Invoice to receipt</small></span><IconChevronRight/></button><button onClick={()=>open(helpArticles.find(a=>a.id==='purchase-bill'))}><i><IconTruck/></i><span><b>Create a purchase bill</b><small>Bill to vendor payment</small></span><IconChevronRight/></button></div></section>
 <section><div className="hcTitle"><div><h2>Browse by module</h2><p>Help is organized like the Wayvida Books navigation.</p></div><button onClick={()=>setView('statuses')}>Status guide <IconExternalLink/></button></div><div className="hcCategories">{helpCategories.map(name=>{const count=helpArticles.filter(a=>a.category===name).length;return <button key={name} onClick={()=>{setQuery(name);window.setTimeout(()=>document.querySelector('.hcResults')?.scrollIntoView({behavior:'smooth'}),10)}}><IconBook2/><span><b>{name}</b><small>{categoryDescription[name]}</small><em>{count||moduleDirectory.filter(x=>x.includes(name)).length||1} {count===1?'article':'topics'}</em></span><IconChevronRight/></button>})}</div></section>
 <section className="hcPopular"><div><h2>Popular questions</h2><p>Fast answers to common workflow blockers.</p></div><div className="hcArticleList">{helpArticles.slice(0,5).map(a=><ArticleRow key={a.id} article={a} open={open}/>)}</div></section>{recent.length>0&&<section><div className="hcTitle"><div><h2>Recently viewed</h2></div></div><div className="hcArticleList">{recent.map(a=><ArticleRow key={a.id} article={a} open={open}/>)}</div></section>}</>}</main></section>
}
const ArticleRow=({article,open})=><button className="hcArticleRow" onClick={()=>open(article)}><i><IconBook2/></i><span><b>{article.title}</b><small>{article.summary}</small><em>{article.category}</em></span><IconChevronRight/></button>;
function Article({article,onBack,onNavigate,open}){return <section className="hc hcArticle"><button className="hcBack" onClick={onBack}><IconArrowLeft/>Back to Help Center</button><header className="hcArticleHead"><span>{article.category} · Help article</span><h1>{article.title}</h1><p>{article.summary}</p></header><div className="hcArticleGrid"><main><section className="hcBlock"><h2>How it works</h2><div className="hcWorkflow">{article.workflow.map((step,i)=><div key={step}><b>{i+1}</b><span>{step}</span>{i<article.workflow.length-1&&<IconChevronRight/>}</div>)}</div></section><section className="hcBlock"><h2>Accounting impact</h2><p className="hcNotice"><IconInfoCircle/>Accounting entries occur only when the transaction is posted.</p><ul className="hcImpact">{article.impact.map((x,i)=><li key={x} className={x.startsWith('Dr')?'debit':x.startsWith('Cr')?'credit':''}><span>{x}</span>{i===0&&<small>Example mapping</small>}</li>)}</ul></section><section className="hcBlock"><h2>Common questions</h2>{article.faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section></main><aside><section className="hcSide"><h3>Related settings</h3>{article.settings.map(x=><button key={x} onClick={()=>onNavigate('Settings Center')}>{x}<IconChevronRight/></button>)}</section><section className="hcSide"><h3>Related modules</h3>{article.related.map(x=><button key={x} onClick={()=>onNavigate(x)}>{x}<IconExternalLink/></button>)}</section><section className="hcSide hcTrouble"><IconAlertTriangle/><div><h3>Still blocked?</h3><p>Check approval status, period lock, permissions, required master mappings and the transaction date.</p></div></section></aside></div></section>}
function StatusGuide({onBack}){return <section className="hc hcStatus"><button className="hcBack" onClick={onBack}><IconArrowLeft/>Back to Help Center</button><header className="hcArticleHead"><span>GLOBAL GUIDE</span><h1>Status guide</h1><p>Understand what each status means, its accounting effect and what to do next.</p></header><div className="hcStatusTable"><table><thead><tr><th>Status</th><th>Meaning</th><th>Accounting effect</th><th>What you can do</th></tr></thead><tbody>{helpStatuses.map(s=><tr key={s.name}><td><b className={`hcPill ${s.name.toLowerCase().replaceAll(' ','-')}`}>{s.name}</b></td><td>{s.meaning}</td><td>{s.accounting}</td><td>{s.actions}</td></tr>)}</tbody></table></div></section>}
