import DocumentPreview from './DocumentPreview.jsx';
import {useEffect,useState} from 'react';
import {IconPlus,IconArrowLeft,IconTrash,IconFileInvoice,IconSettings,IconX,IconPrinter,IconSend,IconCashBanknote,IconBan,IconChevronRight,IconDotsVertical,IconBook,IconReceipt,IconLink} from '@tabler/icons-react';
import {KEY,initial,seedAccounts,command,calculate,money,today,outstanding,paymentStatus,ledger,reports} from './invoice-engine';
import './invoice-workspace.css';
import './invoice-detail.css';
import {QUICK_CREATE_KEY} from './quick-create.js';
import {customerSeeds,customerStates} from './Customers.jsx';
import {itemSeeds} from './Items.jsx';
import {ItemSearch,TaxSelection} from './InvoiceLineControls.jsx';
import JournalEntriesPro from './JournalEntriesPro.jsx';
import GeneralLedgerPro from './GeneralLedgerPro.jsx';
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
const blankLine=()=>({description:'',qty:'1',unit:'pcs',rate:'0',discount:'0',discountType:'%',tax:'18',cess:'0',income:''});
const due=(date,days)=>{const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+Number(days));return d.toISOString().slice(0,10)};
export default function InvoiceWorkspace({accounts,page,notify,onNavigate}){
 const [printDoc,setPrintDoc]=useState(null);
 const [db,setDb]=useState(()=>seedAccounts(read(KEY,initial()),accounts)),[selected,setSelected]=useState(()=>page==='Invoices'?sessionStorage.getItem('wayvida-open-invoice'):null),[form,setForm]=useState(null),[tab,setTab]=useState('Overview'),[query,setQuery]=useState(''),[filter,setFilter]=useState(()=>page==='Invoices'?(sessionStorage.getItem('wayvida-resolve-status')||''):''),[error,setError]=useState(''),[payment,setPayment]=useState(null),[config,setConfig]=useState(null),[cancel,setCancel]=useState(null),[moreActions,setMoreActions]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState(''),[side,setSide]=useState('All');
 const customers=read('wayvida-customers',customerSeeds);const items=read('finance-erp-items',itemSeeds);
 const invoice=db.invoices.find(x=>x.id===selected),report=reports(db);
 useEffect(()=>{if(page==='Invoices'&&sessionStorage.getItem(QUICK_CREATE_KEY)==='invoice'){sessionStorage.removeItem(QUICK_CREATE_KEY);create()}},[page]);
 if(page==='Journal Entries')return <JournalEntriesPro seed={accounts} notify={notify} onNavigate={onNavigate}/>;
 if(page==='General Ledger')return <GeneralLedgerPro accounts={accounts} notify={notify} onNavigate={onNavigate}/>;
 function run(action,p){try{const current=seedAccounts(read(KEY,initial()),accounts);const output=command(current,action,p);localStorage.setItem(KEY,JSON.stringify(output.state));setDb(output.state);setError('');notify(action==='post'?'Invoice posted. Accounting updated automatically.':'Saved successfully');return output.result}catch(e){setError(e.message);return null}}
 function create(demo=false){setError('');setForm({number:'',date:today(),customerId:demo?customers[0]?.id:'',customerName:demo?customers[0]?.name:'',billing:demo?customers[0]?.billing:'',shipping:demo?customers[0]?.shipping:'',place:demo?customers[0]?.state||'Kerala':'',terms:'30',dueDate:due(today(),30),reference:'',lines:[demo?{...blankLine(),description:'Website Development',unit:'service',rate:'100000'}:blankLine()]})}
 function chooseCustomer(id){const c=customers.find(x=>x.id===id);setForm({...form,customerId:id,customerName:c?.name||'',billing:c?.billing||'',shipping:c?.shipping||'',place:c?.state||'',terms:c?.days||'30',dueDate:due(form.date,c?.days||30)})}
 const field=(name,label,type='text')=><label>{label}<input type={type} value={form[name]||''} onChange={e=>setForm({...form,[name]:e.target.value,...(name==='date'&&e.target.value?{dueDate:due(e.target.value,form.terms)}:{})})}/></label>;
 const updateLine=(index,key,value)=>setForm({...form,lines:form.lines.map((l,n)=>n===index?{...l,[key]:value}:l)});
 let preview,previewError;try{preview=form?calculate(form,db.config):null}catch(e){previewError=e.message}
 function startPayment(i){sessionStorage.setItem('wayvida-receive-invoice',i.id);onNavigate('Payments Received')}
 function openSource(id,creditNoteId,receiptId){if(receiptId){sessionStorage.setItem('wayvida-open-receipt',receiptId);onNavigate('Payments Received');return}if(creditNoteId){sessionStorage.setItem('wayvida-open-credit',creditNoteId);onNavigate('Credit Notes');return}sessionStorage.setItem('wayvida-open-invoice',id);setSelected(id);setTab('Accounting');onNavigate('Invoices')}
 const totals=t=><dl className="ivTotals">{[['Subtotal',t.subtotal],['Discount',t.discount],['Taxable amount',t.taxable],...(t.intra?[['CGST',t.cgst],['SGST',t.sgst]]:[['IGST',t.igst]]),...(t.cess?[['Cess',t.cess]]:[]),['Tax',t.cgst+t.sgst+t.igst+t.cess],['Round off',t.roundOff],['Grand total',t.total]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{money(v)}</dd></div>)}</dl>;
 const journalTable=rows=><div className="ivScroll"><table><thead><tr><th>Date / journal</th><th>Source</th><th>Account</th><th>Debit</th><th>Credit</th><th>Balance (Dr − Cr)</th></tr></thead><tbody>{rows.map((r,n)=><tr key={r.id||n}><td>{r.date}<small>{r.number}</small></td><td><button className="ivLink" onClick={()=>openSource(r.invoiceId,r.creditNoteId,r.receiptId)}>{r.reference}</button><small>{r.source}</small></td><td>{r.account} · {db.accounts.find(a=>a.code===r.account)?.name}</td><td>{r.debit?money(r.debit):'—'}</td><td>{r.credit?money(r.credit):'—'}</td><td>{money(r.balance||0)}</td></tr>)}</tbody></table>{!rows.length&&<p className="ivEmpty">No posted entries yet.</p>}</div>;
 const heading=(title,sub,actions)=><div className="ivHeading"><div><h2>{title}</h2><p>{sub}</p></div><div className="ivActions">{actions}</div></div>;
 return <section className="invoiceWorkspace">
 {printDoc&&<DocumentPreview kind="Invoice" initialMode={printDoc.__builder?'builder':'preview'} doc={printDoc} db={db} onClose={()=>setPrintDoc(null)}/>}
 {error&&<div className="ivError" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><IconX size={16}/></button></div>}
 {form?<><div className="ivHeading"><div><button className="ivLink" onClick={()=>setForm(null)}><IconArrowLeft size={16}/> Invoices</button><h2>{form.id?'Edit invoice':'New sales invoice'}</h2><p>Save a draft, then post to update your books automatically.</p></div></div><form onSubmit={e=>{e.preventDefault();const saved=run('save',form);if(saved){setForm(null);setSelected(saved.id)}}}>
 <SalesDocumentFields form={form} setForm={setForm} customers={customers} items={items} config={db.config}/>
 <div className="ivFooter"><button type="button" onClick={()=>setForm(null)}>Cancel</button><button className="primary">Save draft</button></div></form></>:
 page==='Invoices'? invoice?<>
 <div className="ivDetailTop"><button className="ivBack" onClick={()=>{setSelected(null);setTab('Overview')}}><IconArrowLeft size={17}/>Invoices</button><IconChevronRight size={14}/><span>{invoice.number}</span></div><div className="ivDocumentHead"><div className="ivDocumentIdentity"><span className="ivEyebrow">SALES INVOICE</span><div><h2>{invoice.number}</h2><b className={`ivStatus ivStatus-${String(invoice.status).toLowerCase().replaceAll(' ','-')}`}>{invoice.status}</b></div><p>{invoice.customerName}</p></div><div className="ivDocumentActions"><button onClick={()=>setPrintDoc(invoice)}><IconPrinter size={17}/>Preview &amp; print</button>{invoice.status==='Draft'&&<><button onClick={()=>setForm({...invoice})}>Edit</button><button onClick={()=>run('submit',{id:invoice.id})}>Submit for approval</button></>}{!invoice.posted&&invoice.status!=='Cancelled'&&<button className="primary" onClick={()=>run('post',{id:invoice.id})}>Approve &amp; post</button>}{invoice.posted&&invoice.status!=='Cancelled'&&<><button onClick={()=>run('send',{id:invoice.id})}><IconSend size={17}/>Mark as sent</button>{outstanding(db,invoice)>0&&<button className="primary" onClick={()=>startPayment(invoice)}><IconCashBanknote size={17}/>Receive payment</button>}</>}<div className="ivMoreActions"><button aria-expanded={moreActions} onClick={()=>setMoreActions(!moreActions)}><IconDotsVertical size={17}/>More actions</button>{moreActions&&<div><button onClick={()=>{setTab('Accounting');setMoreActions(false)}}>Accounting details</button><button onClick={()=>{onNavigate('Journal Entries');setMoreActions(false)}}>View journal</button><button onClick={()=>{onNavigate('General Ledger');setMoreActions(false)}}>View ledger</button></div>}</div>{invoice.status!=='Cancelled'&&<button className="ivDangerAction" onClick={()=>setCancel({id:invoice.id,reason:''})}><IconBan size={17}/>Cancel</button>}</div></div>
 <div className="ivSummary"><span><small>Invoice status</small><strong className={`ivStatusText ivStatusText-${String(invoice.status).toLowerCase()}`}>{invoice.status}</strong></span><span><small>Payment status</small><strong>{paymentStatus(db,invoice)}</strong></span><span><small>Invoice total</small><strong>{money(invoice.totals.total)}</strong></span><span className="ivOutstanding"><small>Outstanding balance</small><strong>{money(outstanding(db,invoice))}</strong></span></div><div className="ivTabs" role="tablist" aria-label="Invoice details">{['Overview','Items','Payments','Accounting','Activity'].map(t=><button role="tab" aria-selected={tab===t} key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}{t==='Items'&&<small>{invoice.totals.lines.length}</small>}{t==='Payments'&&<small>{db.payments.filter(p=>p.invoiceId===invoice.id).length+(db.receiptAllocations||[]).filter(a=>a.invoiceId===invoice.id&&!a.voided).length}</small>}</button>)}</div><div className={`ivCard ivDetailCard ivDetailCard-${tab.toLowerCase()}`}>
 {tab==='Overview'?<InvoiceOverview invoice={invoice} db={db} totals={totals} onNavigate={onNavigate} onReceipt={()=>{const allocation=(db.receiptAllocations||[]).find(a=>a.invoiceId===invoice.id&&!a.voided);if(allocation){sessionStorage.setItem('wayvida-open-receipt',allocation.receiptId);onNavigate('Payments Received')}}}/>:tab==='Items'?<div className="ivScroll"><table><thead><tr><th>Item</th><th>Quantity</th><th>Unit</th><th>Rate</th><th>Taxable amount</th><th>With tax</th></tr></thead><tbody>{invoice.totals.lines.map((l,n)=><tr key={n}><td>{l.description}</td><td>{l.qty}</td><td>{l.unit}</td><td>₹{l.rate}</td><td>{money(l.taxable)}</td><td>{money(l.total)}</td></tr>)}</tbody></table></div>:tab==='Payments'?<div className="ivPaymentHistory"><div className="ivSectionTitle"><h3>Payment history</h3><p>Receipts and allocations recorded against this invoice</p></div>{db.payments.filter(p=>p.invoiceId===invoice.id).map(p=><p key={p.id}>{p.number} · {p.date} · {money(p.amount)} · {p.reference}</p>)}{(db.receiptAllocations||[]).filter(a=>a.invoiceId===invoice.id).map(a=><p key={a.id}><button className="ivLink" onClick={()=>{sessionStorage.setItem('wayvida-open-receipt',a.receiptId);onNavigate('Payments Received')}}>{db.receipts?.find(r=>r.id===a.receiptId)?.number||'Receipt'}</button> · {a.date} · {money(a.amount)} · {a.voided?'Reversed':'Allocated'}</p>)}{!db.payments.some(p=>p.invoiceId===invoice.id)&&!(db.receiptAllocations||[]).some(a=>a.invoiceId===invoice.id)&&<div className="ivTabEmpty"><IconCashBanknote/><h3>No payments received</h3><p>The outstanding balance remains {money(outstanding(db,invoice))}.</p></div>}</div>:tab==='Accounting'?<><div className="ivSectionTitle"><h3>{invoice.posted?'Posted automatic accounting':'Accounting impact'}</h3><p>{invoice.posted?'This invoice has updated the journal and ledger.':'No accounting entries exist until the invoice is posted.'}</p></div>{journalTable(ledger(db).filter(r=>r.invoiceId===invoice.id))}<div className="ivActions"><button onClick={()=>onNavigate('Journal Entries')}>View Journal Entries</button><button onClick={()=>onNavigate('General Ledger')}>View General Ledger</button></div><div className="ivAudit"><h3>Audit trail</h3>{db.audit.filter(e=>e.invoiceId===invoice.id).map(e=><p key={e.id}>{e.action} · {new Date(e.at).toLocaleString()} · {e.by}{e.reason?' · '+e.reason:''}</p>)}</div></>:<div className="ivActivity"><div className="ivSectionTitle"><h3>Activity</h3><p>Invoice lifecycle and audit history</p></div>{db.audit.filter(e=>e.invoiceId===invoice.id).map(e=><p key={e.id}>{e.action} · {new Date(e.at).toLocaleString()} · {e.by}{e.reason?' · '+e.reason:''}</p>)}{!db.audit.some(e=>e.invoiceId===invoice.id)&&<p>No activity recorded.</p>}</div>}</div></>:<>
 {heading('Sales invoices','Create invoices once. Accounting follows automatically.',<><button onClick={()=>setConfig({...db.config})}><IconSettings size={16}/>Account mapping</button><button onClick={()=>create(true)}>Use demo example</button><button className="primary" onClick={()=>create()}><IconPlus size={16}/>Create invoice</button></>)}<div className="ivCard"><div className="ivTools"><input aria-label="Search invoices" placeholder="Search invoice or customer" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Invoice status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option>{['Draft','Pending Approval','Approved','Sent','Partially Paid','Paid','Overdue','Cancelled'].map(s=><option key={s}>{s}</option>)}</select></div><div className="ivScroll"><table><thead><tr>{['Invoice','Customer','Date','Due date','Total','Outstanding','Status','Payment',''].map((s,n)=><th key={n}>{s}</th>)}</tr></thead><tbody>{db.invoices.filter(i=>(i.number+' '+i.customerName).toLowerCase().includes(query.toLowerCase())&&(!filter||i.status===filter||(i.posted&&paymentStatus(db,i)===filter))).map(i=><tr key={i.id}><td><button className="ivLink" onClick={()=>{setSelected(i.id);setTab('Overview')}}>{i.number}</button></td><td>{i.customerName}</td><td>{i.date}</td><td>{i.dueDate}</td><td>{money(i.totals.total)}</td><td>{money(outstanding(db,i))}</td><td>{i.status}</td><td>{paymentStatus(db,i)}</td><td><button onClick={()=>{setSelected(i.id);setTab('Overview')}}>View</button></td></tr>)}</tbody></table></div>{!db.invoices.length&&<div className="ivEmpty"><IconFileInvoice/><h3>Your first invoice starts here</h3><p>Create a draft or use the ₹1,18,000 demo example.</p></div>}</div></>:
 page==='Payments Received'?<>{heading('Payments received','Payments automatically update your bank and customer receivables.')}<div className="ivCard"><h3>Outstanding invoices</h3>{db.invoices.filter(i=>i.posted&&i.status!=='Cancelled'&&outstanding(db,i)>0).map(i=><div className="ivPaymentRow" key={i.id}><span>{i.number} · {i.customerName} · {money(outstanding(db,i))}</span><button className="primary" onClick={()=>startPayment(i)}>Receive Payment</button></div>)}<h3>Payment history</h3>{db.payments.map(p=><div className="ivPaymentRow" key={p.id}><span>{p.number} · {p.date} · {money(p.amount)}</span><button onClick={()=>openSource(p.invoiceId)}>View invoice & accounting</button></div>)}{!db.payments.length&&<p>No payments recorded yet.</p>}</div></>:
 ['General Ledger','Journal Entries'].includes(page)?<>{heading(page,'Live entries from posted invoices, receipts and reversals.')}<div className="ivCard"><div className="ivTools"><input aria-label="Search reference" placeholder="Search reference / account" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Account filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All accounts</option>{db.accounts.map(a=><option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><select aria-label="Debit credit filter" value={side} onChange={e=>setSide(e.target.value)}>{['All','Debit','Credit'].map(x=><option key={x}>{x}</option>)}</select></div>{journalTable(ledger(db).filter(r=>(!filter||r.account===filter)&&(!from||r.date>=from)&&(!to||r.date<=to)&&(side==='All'||(side==='Debit'?r.debit:r.credit)>0)&&(r.reference+' '+r.account+' '+db.accounts.find(a=>a.code===r.account)?.name).toLowerCase().includes(query.toLowerCase())))}</div></>:
 <>{heading(page==='Trial Balance'?'Trial Balance':'Financial Statements','Live invoice ledger only · historical prototype sample balances are excluded.')}<div className="ivCard">{page==='Trial Balance'?<><table><thead><tr><th>Account</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{report.rows.filter(r=>r.balance).map(r=><tr key={r.code}><td>{r.code} · {r.name}</td><td>{money(r.debit)}</td><td>{money(r.credit)}</td></tr>)}<tr><th>Total</th><th>{money(report.debit)}</th><th>{money(report.credit)}</th></tr></tbody></table><p>{report.debit===report.credit?'✓ Trial Balance is balanced':'Trial Balance is out of balance'}</p></>:<><h3>Profit & Loss</h3><dl className="ivTotals">{[['Revenue (excluding GST)',report.revenue],['Expenses',report.expenses],['Net profit',report.profit]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{money(v)}</dd></div>)}</dl><h3>Balance Sheet</h3><dl className="ivTotals">{[['Assets',report.assets],['Liabilities',report.liabilities],['Equity',report.equity],['Current profit',report.profit],['Liabilities + equity + profit',report.liabilities+report.equity+report.profit]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{money(v)}</dd></div>)}</dl><p>{report.assets===report.liabilities+report.equity+report.profit?'✓ Balance Sheet is balanced':'Balance Sheet mismatch'}</p></>}</div></>}
 {payment&&<div className="ivOverlay"><form className="ivModal" role="dialog" aria-modal="true" onSubmit={e=>{e.preventDefault();if(run('pay',payment))setPayment(null)}}><h2>Record payment</h2><p>{db.invoices.find(i=>i.id===payment.id)?.number} · Outstanding {money(outstanding(db,db.invoices.find(i=>i.id===payment.id)))}</p>{['amount','date','reference'].map(k=><label key={k}>{k}<input required={k!=='reference'} type={k==='date'?'date':'text'} value={payment[k]} onChange={e=>setPayment({...payment,[k]:e.target.value})}/></label>)}<label>Deposit to<select value={payment.bank} onChange={e=>setPayment({...payment,bank:e.target.value})}>{db.accounts.filter(a=>a.active&&a.type==='Assets'&&/cash|bank/i.test(a.name)).map(a=><option key={a.code} value={a.code}>{a.name}</option>)}</select></label>{error&&<p role="alert" className="ivError">{error}</p>}<div className="ivActions"><button type="button" onClick={()=>setPayment(null)}>Cancel</button><button className="primary">Receive Payment</button></div></form></div>}
 {config&&<div className="ivOverlay"><form className="ivModal" role="dialog" aria-modal="true" onSubmit={e=>{e.preventDefault();if(run('config',config))setConfig(null)}}><h2>Accounting configuration</h2><p>Domestic regular GST supplies. Rates and place of supply must be verified for your transaction.</p><label>Company state<select value={config.state} onChange={e=>setConfig({...config,state:e.target.value})}>{customerStates.map(s=><option key={s}>{s}</option>)}</select></label>{['sales','ar','cgst','sgst','igst','cess','round'].map(k=><label key={k}>{({sales:'Sales / service income',ar:'Accounts receivable',round:'Round off'})[k]||k.toUpperCase()+' payable'}<select value={config[k]} onChange={e=>setConfig({...config,[k]:e.target.value})}><option value="">Not configured</option>{db.accounts.filter(a=>a.active&&a.type===(k==='sales'?'Income':k==='ar'?'Assets':k==='round'?'Expenses':'Liabilities')).map(a=><option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select></label>)}<label>Round grand total<select value={String(config.roundRupee)} onChange={e=>setConfig({...config,roundRupee:e.target.value==='true'})}><option value="false">Keep paise</option><option value="true">Nearest rupee</option></select></label><div className="ivActions"><button type="button" onClick={()=>setConfig(null)}>Cancel</button><button className="primary">Save configuration</button></div></form></div>}
 {cancel&&<div className="ivOverlay"><form className="ivModal" role="dialog" aria-modal="true" onSubmit={e=>{e.preventDefault();if(run('cancel',cancel))setCancel(null)}}><h2>Cancel invoice?</h2><p>Posted entries will be reversed, never deleted. Invoices with receipts require a separate credit note/refund.</p><label>Reason<textarea required value={cancel.reason} onChange={e=>setCancel({...cancel,reason:e.target.value})}/></label>{error&&<p role="alert" className="ivError">{error}</p>}<div className="ivActions"><button type="button" onClick={()=>setCancel(null)}>Go back</button><button className="primary">Confirm cancellation</button></div></form></div>}
 </section>
}
function InvoiceOverview({invoice,db,totals,onNavigate,onReceipt}){
 const entries=ledger(db).filter(row=>row.invoiceId===invoice.id),payments=[...db.payments.filter(row=>row.invoiceId===invoice.id),...(db.receiptAllocations||[]).filter(row=>row.invoiceId===invoice.id&&!row.voided)],received=payments.reduce((sum,row)=>sum+(row.amount||0),0),lastPayment=payments.at(-1),accountSummary=entries.reduce((map,row)=>{const key=row.account,mapRow=map.get(key)||{account:key,debit:0,credit:0};mapRow.debit+=row.debit||0;mapRow.credit+=row.credit||0;map.set(key,mapRow);return map},new Map());
 const related=[['Quotation',invoice.quotationNumber],['Sales order',invoice.salesOrderNumber||invoice.sourceOrderNumber],['Payment receipt',lastPayment?.number||lastPayment?.receiptId],['Credit note',(db.creditNotes||[]).find(row=>row.originalInvoiceId===invoice.id)?.number],['Attachments',invoice.attachments?.length?`${invoice.attachments.length} file(s)`:null]];
 return <div className="ivOverviewPage"><section className="ivOverviewInformation"><div className="ivSectionTitle"><h3>Invoice information</h3><p>Document, delivery and payment details</p></div><div className="ivFields">{[['Invoice date',invoice.date],['Due date',invoice.dueDate],['Reference',invoice.reference||'—'],['Billing address',invoice.billing],['Shipping address',invoice.shipping],['Place of supply',invoice.place],['Currency',invoice.currency||'INR'],['Payment terms',Number(invoice.terms)?'Net '+invoice.terms:'Due on receipt']].map(([key,value])=><div key={key}><small>{key}</small><p>{value||'—'}</p></div>)}</div></section><div className="ivOverviewCards"><section className="ivOverviewCard"><div className="ivSectionTitle"><h3>Amount summary</h3><p>Saved invoice and tax totals</p></div>{totals(invoice.totals)}</section><section className="ivOverviewCard"><div className="ivSectionTitle"><h3>Accounting summary</h3><p>{invoice.posted?'Posted impact from the journal':'Available after posting'}</p></div>{invoice.posted?[...accountSummary.values()].map(row=><p className="ivImpactRow" key={row.account}><span>{db.accounts.find(a=>a.code===row.account)?.name||row.account}<small>{row.account}</small></span><b>{row.debit?`Dr ${money(row.debit)}`:`Cr ${money(row.credit)}`}</b></p>):<p>No accounting entry has been created.</p>}<div className="ivCardActions"><button onClick={()=>onNavigate('Journal Entries')}><IconBook size={16}/>View Journal</button><button onClick={()=>onNavigate('General Ledger')}>View Ledger</button></div></section><section className="ivOverviewCard"><div className="ivSectionTitle"><h3>Payment summary</h3><p>Receipts allocated to this invoice</p></div><dl className="ivCompactFacts"><div><dt>Payment status</dt><dd>{paymentStatus(db,invoice)}</dd></div><div><dt>Payment received</dt><dd>{money(received)}</dd></div><div><dt>Payment date</dt><dd>{lastPayment?.date||'—'}</dd></div><div><dt>Payment method</dt><dd>{lastPayment?.method||lastPayment?.paymentMode||'—'}</dd></div></dl>{lastPayment&&<div className="ivCardActions"><button onClick={onReceipt}><IconReceipt size={16}/>View receipt</button></div>}</section><section className="ivOverviewCard"><div className="ivSectionTitle"><h3>Related documents</h3><p>Documents connected to this invoice</p></div>{related.map(([label,value])=><p className="ivRelatedRow" key={label}><span>{label}</span><b>{value||'Not linked'}</b></p>)}</section></div></div>
}
import SalesDocumentFields from './SalesDocumentFields.jsx';
