import {useState} from 'react';
import {IconArrowLeft,IconEdit,IconInfoCircle,IconPackage,IconPlus,IconSearch} from '@tabler/icons-react';
import {blankItem,generateSku,ITEM_CATEGORIES,ITEM_UNITS,openingValue,validateItem} from './item-master.js';
import {readAccounts,writeAccounts} from './account-store.js';
import {journal,minor} from './invoice-engine.js';
import './items.css';

const base=blankItem({salesAccount:'4000',purchaseAccount:'5000',inventoryAccount:'1200',cogsAccount:'5000'});
const seed=[{...base,id:'item-1',name:'Office stationery box',sku:'ITEM-0001',unit:'box',category:'Products',hsnSac:'4820',price:'850',cost:'600'},{...base,id:'item-2',name:'Consulting service',sku:'ITEM-0002',type:'Service',unit:'hour',category:'Services',hsnSac:'9983',price:'2500',salesAccount:'4100',purchase:false,trackInventory:false}];
export {seed as itemSeeds};
const currentContext=()=>({organizationId:localStorage.getItem('wayvida-demo-company')||'abc',warehouseId:localStorage.getItem('wayvida-demo-branch')||'Kochi Branch',currency:'INR'});
const firstMatch=(rows,pattern)=>rows.find(row=>pattern.test(row[1]))?.[0]||rows[0]?.[0]||'';
const itemDefaults=(accounts,type='Goods')=>({...currentContext(),taxRate:'18',salesAccount:firstMatch(accounts.Income||[],type==='Service'?/service/i:/sales|income/i),purchaseAccount:firstMatch(accounts.Expenses||[],type==='Service'?/professional|service|expense/i:/cost of goods|purchase|direct/i),inventoryAccount:firstMatch(accounts.Assets||[],/inventory|stock/i),cogsAccount:firstMatch(accounts.Expenses||[],/cost of goods|purchase|direct/i)});
const legacyItem=(item,defaults)=>({...blankItem(defaults),...item,taxPreference:item.taxPreference||(item.taxApplicable===false?'Non-taxable':'Taxable')});
function Section({title,description,children}){return <section className="itemSection"><header><h3>{title}</h3>{description&&<p>{description}</p>}</header>{children}</section>}

export default function Items({accounts,seed:accountSeed,notify}){
 const defaults=itemDefaults(accounts);
 const [items,setItems]=useState(()=>{try{return (JSON.parse(localStorage.getItem('finance-erp-items'))||seed).map(item=>legacyItem(item,defaults))}catch{return seed.map(item=>legacyItem(item,defaults))}}),[query,setQuery]=useState(''),[filter,setFilter]=useState('All types'),[form,setForm]=useState(null),[errors,setErrors]=useState({}),[uploadBusy,setUploadBusy]=useState(false);
 const set=(key,value)=>setForm(current=>({...current,[key]:value}));
 const start=(item=null)=>{setForm(item?legacyItem(item,defaults):blankItem(defaults));setErrors({})};
 const changeType=type=>setForm(current=>({...current,type,unit:type==='Service'?'hour':'pcs',category:type==='Service'?'Services':'General',hsnSac:'',trackInventory:type==='Goods',...itemDefaults(accounts,type)}));
 async function upload(e){const file=e.target.files?.[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024){setErrors(x=>({...x,image:'Choose a JPG, PNG or WebP image up to 2 MB.'}));e.target.value='';return}setUploadBusy(true);const reader=new FileReader();reader.onload=()=>{set('image',reader.result);setErrors(x=>({...x,image:''}));setUploadBusy(false)};reader.onerror=()=>{setErrors(x=>({...x,image:'Unable to read image. Try another file.'}));setUploadBusy(false)};reader.readAsDataURL(file)}
 function save(e){e.preventDefault();const nextErrors=validateItem(form,items,accounts);setErrors(nextErrors);if(Object.keys(nextErrors).length)return;const isNew=!form.id,id=form.id||crypto.randomUUID(),taxable=form.taxPreference==='Taxable';const item={...form,id,name:form.name.trim(),sku:form.sku.trim(),taxApplicable:taxable,taxRate:taxable?String(form.taxRate):'0',cessRate:taxable?String(form.cessRate||0):'0',mappingEffectiveFrom:new Date().toISOString()};delete item.vendor;const next=form.id?items.map(x=>x.id===form.id?item:x):[item,...items];let accounting=null;try{if(isNew&&form.type==='Goods'&&form.trackInventory&&openingValue(form)>0){accounting=structuredClone(readAccounts(accountSeed||accounts));const amount=minor(openingValue(form).toFixed(2));const offset=accounting.accounts.find(a=>a.active&&!a.isGroup&&a.type==='Equity');if(!offset)throw Error('An active Equity account is required to post the opening stock value.');const entry=journal(accounting,{id,number:item.sku||item.name,organizationId:item.organizationId,branchId:item.warehouseId,role:'Admin',periodModule:'Inventory'},'Inventory Opening Balance',[{account:item.inventoryAccount,debit:amount,credit:0,branch:item.warehouseId},{account:offset.code,debit:0,credit:amount,branch:item.warehouseId}],item.openingDate,'item-opening:'+id);item.openingJournalId=entry.id;}localStorage.setItem('finance-erp-items',JSON.stringify(next));if(accounting)writeAccounts(accounting)}catch(error){setErrors({save:error.message||'Unable to save this item.'});return}setItems(next);setForm(null);notify(form.id?'Item updated':'Item created')}
 const visible=items.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())&&(filter==='All types'||x.type===filter)),money=value=>Number(value).toLocaleString('en-IN',{style:'currency',currency:'INR'});
 const priceField=(label,key,required=false)=><label>{label}{required?' *':''}<input type="number" min="0" step="0.01" value={form[key]} onChange={e=>set(key,e.target.value)} aria-invalid={!!errors[key]}/>{errors[key]&&<small className="itemError">{errors[key]}</small>}</label>;
 const accountField=(label,group,key,pattern)=>{const all=accounts[group]||[],preferred=all.filter(row=>pattern.test(row[1])),rows=preferred.length?preferred:all;return <label>{label} *<select value={form[key]} onChange={e=>set(key,e.target.value)} aria-invalid={!!errors[key]}><option value="">Select an account</option>{rows.map(x=><option value={x[0]} key={x[0]}>{x[0]} — {x[1]}</option>)}</select><small className={errors[key]?'itemError':''}>{errors[key]||'From your Chart of Accounts'}</small></label>};
 return <section className="itemsPage"><div className="itemsHeading"><div><h1>Items</h1><p>Manage the goods and services you sell and purchase.</p></div><button className="primary" onClick={()=>start()}><IconPlus size={18}/>Create Item</button></div><div className="itemsCard"><div className="itemsTools"><label><IconSearch size={18}/><input aria-label="Search items" placeholder="Search items by name…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter item type" value={filter} onChange={e=>setFilter(e.target.value)}><option>All types</option><option>Goods</option><option>Service</option></select><span>{visible.length} items</span></div><div className="itemsTableWrap"><table><thead><tr><th>Item name</th><th>Type</th><th>Unit</th><th>Selling price</th><th>Purchase price</th><th>Default tax</th><th>Actions</th></tr></thead><tbody>{visible.map(item=><tr key={item.id}><td><div className="itemIdentity">{item.image?<img src={item.image} alt=""/>:<span><IconPackage size={20}/></span>}<b>{item.name}</b></div></td><td><span className="itemType">{item.type}</span></td><td>{item.unit}</td><td>{item.sales?money(item.price):'—'}</td><td>{item.purchase&&item.cost!==''?money(item.cost):'—'}</td><td>{item.taxPreference==='Exempt'?'Exempt':item.taxApplicable===false?'Non-taxable':`GST ${item.taxRate||18}% · ${item.priceTaxMode==='inclusive'?'Inclusive':'Exclusive'}`}</td><td><button className="itemEdit" onClick={()=>start(item)}><IconEdit size={16}/>Edit</button></td></tr>)}</tbody></table>{!visible.length&&<div className="itemsEmpty"><IconPackage size={32}/><h3>No items found</h3><p>{query?'Try another search.':'Create your first item to get started.'}</p></div>}</div></div>{form&&<form className="itemCreatePage" aria-labelledby="itemDialogTitle" onSubmit={save} noValidate><div className="itemDialogHead"><button type="button" className="itemBack" aria-label="Back to Items" onClick={()=>setForm(null)}><IconArrowLeft size={19}/></button><div><h2 id="itemDialogTitle">{form.id?'Edit item':'Create item'}</h2><p>Add the item details and choose how it can be used.</p></div></div><div className="itemDialogBody">
 <Section title="Basic information" description="What this item is."><div className="itemFormGrid"><label>Item name *<input autoFocus value={form.name} onChange={e=>set('name',e.target.value)} aria-invalid={!!errors.name}/>{errors.name&&<small className="itemError">{errors.name}</small>}</label><label>Item type *<select value={form.type} onChange={e=>changeType(e.target.value)}><option>Goods</option><option>Service</option></select></label><label>SKU <span className="itemInputAction"><input value={form.sku} onChange={e=>set('sku',e.target.value)} placeholder="Optional unique code" aria-invalid={!!errors.sku}/><button type="button" onClick={()=>set('sku',generateSku(items,form.organizationId))}>Generate</button></span>{errors.sku&&<small className="itemError">{errors.sku}</small>}</label><label>Category<select value={form.category} onChange={e=>set('category',e.target.value)}>{ITEM_CATEGORIES.map(value=><option key={value}>{value}</option>)}</select></label><label>Unit *<select value={form.unit} onChange={e=>set('unit',e.target.value)}>{ITEM_UNITS.map(value=><option key={value}>{value}</option>)}</select></label><label>{form.type==='Goods'?'HSN':'SAC'} code<input inputMode="numeric" value={form.hsnSac} onChange={e=>set('hsnSac',e.target.value.replace(/\D/g,''))} placeholder="Optional" aria-invalid={!!errors.hsnSac}/>{errors.hsnSac&&<small className="itemError">{errors.hsnSac}</small>}</label></div></Section>
 <Section title="Sales information" description="Defaults used when you sell this item."><label className="itemCheck"><input type="checkbox" role="switch" checked={form.sales} onChange={e=>set('sales',e.target.checked)}/><span><b>Sell this item</b><small>Show it in sales invoices and credit notes.</small></span></label>{form.sales&&<div className="itemFormGrid">{priceField(`Selling price (${form.currency})`,'price',true)}{accountField('Sales Account','Income','salesAccount',/sales|service|income/i)}</div>}</Section>
 <Section title="Purchase information" description="Defaults used when you buy this item."><label className="itemCheck"><input type="checkbox" role="switch" checked={form.purchase} onChange={e=>set('purchase',e.target.checked)}/><span><b>Purchase this item</b><small>Show it in purchase bills and expenses.</small></span></label>{form.purchase&&<div className="itemFormGrid">{priceField(`Purchase price (${form.currency})`,'cost')}{accountField('Purchase Account','Expenses','purchaseAccount',form.type==='Service'?/professional|service|expense/i:/cost of goods|purchase|direct/i)}</div>}</Section>
 {form.type==='Goods'&&<Section title="Inventory information" description="Track stock and its accounting value."><label className="itemCheck"><input type="checkbox" role="switch" checked={form.trackInventory} onChange={e=>set('trackInventory',e.target.checked)}/><span><b>Track inventory</b><small>Keep quantity and stock value up to date.</small></span></label>{form.trackInventory&&<><div className="itemFormGrid">{accountField('Inventory Asset Account','Assets','inventoryAccount',/inventory|stock/i)}{accountField('Cost of Goods Sold Account','Expenses','cogsAccount',/cost of goods|purchase|direct/i)}</div>{!form.id&&<details className="itemSubDetails"><summary>Opening stock <span>Optional</span></summary><div className="itemFormGrid"><label>Quantity<input type="number" min="0" step="0.001" value={form.openingQuantity} onChange={e=>set('openingQuantity',e.target.value)} aria-invalid={!!errors.openingQuantity}/>{errors.openingQuantity&&<small className="itemError">{errors.openingQuantity}</small>}</label><label>Rate ({form.currency})<input type="number" min="0" step="0.01" value={form.openingRate} onChange={e=>set('openingRate',e.target.value)} aria-invalid={!!errors.openingRate}/>{errors.openingRate&&<small className="itemError">{errors.openingRate}</small>}</label><label>Opening value<output>{money(openingValue(form))}</output><small>Quantity × rate, calculated automatically</small></label><label>Branch / warehouse *<input value={form.warehouseId} onChange={e=>set('warehouseId',e.target.value)} aria-invalid={!!errors.warehouseId}/>{errors.warehouseId&&<small className="itemError">{errors.warehouseId}</small>}</label><label>As of date<input type="date" value={form.openingDate} onChange={e=>set('openingDate',e.target.value)}/></label></div><p className="itemNotice"><IconInfoCircle size={16}/>A balanced inventory opening journal is posted only when quantity and rate create a value.</p></details>}</>}</Section>}
 <Section title="Tax information" description="Set the default tax treatment."><div className="itemFormGrid"><label>Tax preference *<select value={form.taxPreference} onChange={e=>set('taxPreference',e.target.value)}><option>Taxable</option><option>Non-taxable</option><option>Exempt</option></select></label>{form.taxPreference==='Taxable'&&<><label>GST rate *<select value={form.taxRate} onChange={e=>set('taxRate',e.target.value)}>{['0','5','12','18','28'].map(rate=><option key={rate} value={rate}>{rate}%</option>)}</select>{errors.taxRate&&<small className="itemError">{errors.taxRate}</small>}</label><label>Cess rate<select value={form.cessRate} onChange={e=>set('cessRate',e.target.value)}>{['0','1','5','12'].map(rate=><option key={rate} value={rate}>{rate}%</option>)}</select></label><label>Price includes tax?<select value={form.priceTaxMode} onChange={e=>set('priceTaxMode',e.target.value)}><option value="exclusive">No, add tax separately</option><option value="inclusive">Yes, tax is included</option></select></label></>}</div></Section>
 <details className="itemAdvanced"><summary>Advanced settings <span>Optional</span></summary><div className="itemImageField"><label>Item image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></label><small>JPG, PNG or WebP · Maximum 2 MB</small>{form.image&&<div className="itemPreview"><img src={form.image} alt="Item preview"/><button type="button" onClick={()=>set('image','')}>Remove image</button></div>}{errors.image&&<small className="itemError">{errors.image}</small>}</div></details>{errors.save&&<p role="alert" className="itemError itemSaveError">{errors.save}</p>}</div><footer className="itemDialogFooter"><button type="button" onClick={()=>setForm(null)}>Cancel</button><button className="primary" disabled={uploadBusy}>{uploadBusy?'Processing image…':form.id?'Save changes':'Create Item'}</button></footer></form>}</section>;
}
