import {initial,journal,KEY,minor} from './invoice-engine.js';

export const OPERATIONS_KEY='wayvida-operations-v1';
const today='2026-09-07';
export const seedOperations=()=>({version:1,categories:[
 {id:'cat-software',name:'Software & subscriptions',account:'5600',tax:'GST 18%',description:'Cloud tools and recurring software',status:'Active'},
 {id:'cat-travel',name:'Travel & conveyance',account:'5400',tax:'GST 5%',description:'Business travel and local conveyance',status:'Active'},
 {id:'cat-utilities',name:'Utilities',account:'5300',tax:'GST 18%',description:'Electricity, internet and utilities',status:'Active'}],expenses:[
 {id:'exp-1',number:'EXP-00041',date:'2026-09-05',name:'Cloud hosting',category:'Software & subscriptions',payee:'Cloudstack Services',amount:118000,account:'5600',paidThrough:'1010',method:'UPI',tax:'GST 18%',status:'Posted',journalId:'JE-DEMO-EXP-41',description:'September hosting subscription'},
 {id:'exp-2',number:'EXP-00042',date:'2026-09-06',name:'Client visit',category:'Travel & conveyance',payee:'Metro Cabs',amount:245000,account:'5400',paidThrough:'1010',method:'Card',tax:'GST 5%',status:'Pending',description:'Travel for customer implementation'},
 {id:'exp-3',number:'EXP-00043',date:today,name:'Internet charges',category:'Utilities',payee:'FiberNet India',amount:177000,account:'5300',paidThrough:'1010',method:'Bank transfer',tax:'GST 18%',status:'Draft',description:'Branch broadband charges'}],assets:[
 {id:'asset-1',code:'AST-0001',name:'Dell Latitude laptops',category:'Computer equipment',purchaseDate:'2025-04-01',cost:60000000,accumulated:18000000,bookValue:42000000,status:'Active',vendor:'Kerala Office Supplies',location:'Kochi Office',method:'Straight line',life:5,residual:0},
 {id:'asset-2',code:'AST-0002',name:'Office furniture',category:'Furniture',purchaseDate:'2024-04-01',cost:32000000,accumulated:12800000,bookValue:19200000,status:'Active',vendor:'Metro Furnishings',location:'Kannur Office',method:'Straight line',life:5,residual:0},
 {id:'asset-3',code:'AST-0003',name:'Delivery vehicle',category:'Vehicles',purchaseDate:'2026-04-10',cost:95000000,accumulated:9500000,bookValue:85500000,status:'Active',vendor:'South Motors',location:'Kochi Office',method:'Written down value',life:8,residual:5000000}],assetTransactions:[
 {id:'at-1',date:'2026-09-01',asset:'Dell Latitude laptops',type:'Depreciation',reference:'DEP-SEP-001',amount:1000000,status:'Posted'},
 {id:'at-2',date:'2026-09-02',asset:'Office furniture',type:'Transfer',reference:'ATR-00012',amount:0,status:'Completed'},
 {id:'at-3',date:'2026-09-05',asset:'Delivery vehicle',type:'Capitalization',reference:'BILL-00031',amount:95000000,status:'Posted'}],gst:[
 {id:'gst-1',date:'2026-09-04',party:'ABC Retail Pvt Ltd',reference:'INV-000021',type:'Output GST',taxable:10000000,tax:1800000,status:'Posted'},
 {id:'gst-2',date:'2026-09-05',party:'Kerala Office Supplies',reference:'BILL-000031',type:'Input GST',taxable:5000000,tax:900000,status:'Posted'}],tds:[
 {id:'tds-1',date:'2026-09-03',party:'Cloudstack Services',section:'194J',taxable:5000000,amount:500000,status:'Pending'},
 {id:'tds-2',date:'2026-08-28',party:'Metro Maintenance Works',section:'194C',taxable:8000000,amount:80000,status:'Deposited'}],budgets:[
 {id:'bud-1',name:'Operating Expenses FY27',account:'Operating Expenses',period:'Yearly',branch:'All branches',amount:300000000,actual:142000000,status:'On track'},
 {id:'bud-2',name:'Marketing FY27',account:'Marketing',period:'Yearly',branch:'Kochi Branch',amount:60000000,actual:38000000,status:'On track'},
 {id:'bud-3',name:'Travel FY27',account:'Travel',period:'Yearly',branch:'All branches',amount:25000000,actual:22500000,status:'Watch'}],audit:[]});

const clone=v=>JSON.parse(JSON.stringify(v));
export function readOperations(){try{const value=JSON.parse(localStorage.getItem(OPERATIONS_KEY)||'null');return value?.expenses?value:seedOperations()}catch{return seedOperations()}}
export function saveOperations(value){localStorage.setItem(OPERATIONS_KEY,JSON.stringify(value));return value}
export function accountingState(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||initial()}catch{return initial()}}
const ensure=(state,code,name,type,nature)=>{let row=state.accounts.find(x=>x.code===code);if(!row){row={id:`operations:${code}`,code,name,type,nature,group:type==='Assets'?'Fixed Assets':'Operating Expenses',active:true,isGroup:false,system:true,revision:1};state.accounts.push(row)}if(!row.active||row.isGroup)throw Error(`Configure active posting account ${code}.`);return code};
export function createExpense(store,accounting,input){const next=clone(store),state=clone(accounting),amount=minor(input.amount);if(!input.name?.trim()||!input.date||!input.category||amount<=0)throw Error('Enter the date, expense, category, and a valid amount.');ensure(state,input.account||'5900','Other Expenses','Expenses','Debit');ensure(state,input.paidThrough||'1010','Bank','Assets','Debit');const record={...input,id:crypto.randomUUID(),number:`EXP-${String(next.expenses.length+44).padStart(5,'0')}`,amount,status:'Posted',createdAt:new Date().toISOString()};const entry=journal(state,record,'Expense',[{account:record.account||'5900',debit:amount,credit:0,description:record.name},{account:record.paidThrough||'1010',debit:0,credit:amount,description:`Paid to ${record.payee||'payee'}`}],record.date,`expense:${record.id}`);record.journalId=entry.id;next.expenses.unshift(record);next.audit.push({id:crypto.randomUUID(),action:'expense posted',recordId:record.id,journalId:entry.id,at:new Date().toISOString(),by:'Admin'});return {store:next,accounting:state,record}}
export function createCategory(store,input){if(!input.name?.trim()||!input.account)throw Error('Category name and default account are required.');const next=clone(store),record={...input,id:crypto.randomUUID(),status:input.status||'Active'};next.categories.unshift(record);return next}
export function createAsset(store,input,accounting){const next=clone(store),cost=minor(input.cost);if(!input.name?.trim()||!input.category||!input.purchaseDate||cost<=0)throw Error('Enter the asset name, category, purchase date, and cost.');const record={...input,id:crypto.randomUUID(),code:input.code||`AST-${String(next.assets.length+1).padStart(4,'0')}`,cost,accumulated:0,bookValue:cost,status:'Active'};next.assets.unshift(record);const transaction={id:crypto.randomUUID(),date:record.purchaseDate,asset:record.name,type:'Purchase',reference:record.invoice||record.code,amount:cost,status:accounting?'Posted':'Recorded'};next.assetTransactions.unshift(transaction);if(!accounting)return next;const state=clone(accounting),assetAccount=ensure(state,input.assetAccount||'1300','Fixed Assets','Assets','Debit'),creditAccount=input.purchaseMode==='On credit'?ensure(state,input.payableAccount||'2000','Accounts Payable','Liabilities','Credit'):ensure(state,input.paymentAccount||'1010','Bank','Assets','Debit'),entry=journal(state,{...record,number:transaction.reference},'Asset Acquisition',[{account:assetAccount,debit:cost,credit:0,description:`Acquire ${record.name}`},{account:creditAccount,debit:0,credit:cost,description:input.purchaseMode==='On credit'?`Payable to ${record.vendor||'vendor'}`:`Paid for ${record.name}`}],record.purchaseDate,`asset-acquisition:${record.id}`);Object.assign(transaction,{journalId:entry.id});record.journalId=entry.id;next.audit.push({id:crypto.randomUUID(),action:'asset acquisition posted',recordId:record.id,journalId:entry.id,at:entry.createdAt,by:'Admin'});return {store:next,accounting:state,record,journal:entry}}
export function postDepreciation(store,accounting,assetId,amount,date=today){const next=clone(store),state=clone(accounting),asset=next.assets.find(x=>x.id===assetId),value=minor(amount);if(!asset||value<=0||value>asset.bookValue)throw Error('Enter a valid depreciation amount.');ensure(state,'5800','Depreciation','Expenses','Debit');ensure(state,'1350','Accumulated Depreciation','Assets','Credit');const ref={id:crypto.randomUUID(),number:`DEP-${asset.code}-${date}`},entry=journal(state,ref,'Depreciation',[{account:'5800',debit:value,credit:0,description:`Depreciation · ${asset.name}`},{account:'1350',debit:0,credit:value,description:`Accumulated depreciation · ${asset.name}`}],date,`depreciation:${asset.id}:${date}`);asset.accumulated+=value;asset.bookValue-=value;next.assetTransactions.unshift({id:crypto.randomUUID(),date,asset:asset.name,type:'Depreciation',reference:ref.number,amount:value,status:'Posted',journalId:entry.id});return {store:next,accounting:state,journal:entry}}
export function createBudget(store,input){const amount=minor(input.amount);if(!input.name?.trim()||!input.account||amount<=0)throw Error('Budget name, account, and amount are required.');const next=clone(store);next.budgets.unshift({...input,id:crypto.randomUUID(),amount,actual:0,status:'On track'});return next}
