import {Fragment,useDeferredValue,useEffect,useMemo,useState} from 'react';
import {IconAdjustments,IconAlertTriangle,IconChevronDown,IconChevronRight,IconFileSpreadsheet,IconFileTypePdf,IconInfoCircle,IconRefresh,IconSearch,IconLayoutSidebar} from '@tabler/icons-react';
import {readAccounts} from './account-store.js';
import {money,today} from './invoice-engine.js';
import {profitAndLoss,profitLossExportRows,PROFIT_LOSS_TYPES,financialYearStart} from './profit-loss.js';
import {downloadReport,excelReport} from './daybook-export.js';
import {demoOrganizations} from './demo-organisations.js';
import {useExperienceMode} from './ExperienceModeContext.jsx';
import EmptyState from './EmptyState.jsx';
import './profit-loss.css';
import {DateRangeSelect,ReportExportMenu} from './ReportToolbar.jsx';

const reportSeed={Income:[['4000','Sales'],['4100','Service Income']],Expenses:[['5000','Purchase'],['5100','Salary'],['5200','Rent']]};
const ALL='All';

function formatMoney(amount){
  if(amount<0)return `(${money(Math.abs(amount))})`;
  return money(amount);
}

export default function ProfitLoss({seed,notify,onNavigate}){
  const {isEasy} = useExperienceMode();
  const [revision,setRevision]=useState(0);
  const [from,setFrom]=useState(financialYearStart);
  const [to,setTo]=useState(today);
  const [branch,setBranch]=useState(ALL);
  const [type,setType]=useState(ALL);
  const [account,setAccount]=useState(ALL);
  const [accountGroup,setAccountGroup]=useState(ALL);
  const [search,setSearch]=useState('');
  const [includeZero,setIncludeZero]=useState(false);
  const [filtersOpen,setFiltersOpen]=useState(false);
  const [stamp,setStamp]=useState(()=>new Date());
  
  /* Presentation controls state */
  const [viewMode,setViewMode]=useState('vertical');
  const [panelOpen,setPanelOpen]=useState(true);
  const [collapsedMap,setCollapsedMap]=useState({});

  const deferredSearch=useDeferredValue(search),busy=deferredSearch!==search;
  const organization=demoOrganizations.find(x=>x.id===localStorage.getItem('wayvida-demo-company'))||demoOrganizations[0],branches=organization.branches||[];

  useEffect(()=>{
    const refresh=()=>setRevision(x=>x+1);
    window.addEventListener('wayvida-accounts-updated',refresh);
    window.addEventListener('storage',refresh);
    return()=>{
      window.removeEventListener('wayvida-accounts-updated',refresh);
      window.removeEventListener('storage',refresh);
    }
  },[]);

  const {book,error}=useMemo(()=>{
    try{return {book:readAccounts(seed||reportSeed),error:''}}
    catch(e){return {book:{accounts:[],journals:[]},error:e.message}}
  },[seed,revision]);

  const report=useMemo(()=>profitAndLoss(book,{from,to,branch,account,accountType:type,accountGroup,search:deferredSearch,includeZero}),[book,from,to,branch,account,type,accountGroup,deferredSearch,includeZero]);
  const selected=(()=>{try{return sessionStorage.getItem('wayvida-open-account')||''}catch{return ''}})();
  const groups=[...new Set(report.chart.map(item=>item.group))].sort();

  function reset(){setFrom(financialYearStart());setTo(today());setBranch(ALL);setType(ALL);setAccount(ALL);setAccountGroup(ALL);setSearch('');setIncludeZero(false)}
  function refresh(){setRevision(x=>x+1);setStamp(new Date())}
  
  /* Drill-down preserving filter context */
  function openLedger(row){
    if(!row||!row.code)return;
    try{
      sessionStorage.setItem('wayvida-open-account',row.code);
      sessionStorage.setItem('wayvida-ledger-from',from);
      sessionStorage.setItem('wayvida-ledger-to',to);
      sessionStorage.setItem('wayvida-ledger-branch',branch);
    }catch{}
    if(onNavigate)onNavigate('General Ledger');
  }

  function exportExcel(){
    downloadReport(excelReport(profitLossExportRows(report,{from,to,branch:branch===ALL?'All branches':branch,accountType:type===ALL?'All account types':type,accountGroup:accountGroup===ALL?'All account groups':accountGroup,account:account===ALL?'All accounts':account,search:search||'None',includeZero})),'wayvida-profit-and-loss.xml','application/xml;charset=utf-8');
  }

  function print(){setStamp(new Date());setTimeout(()=>window.print(),50)}

  function printMeta(){
    return [
      ['Wayvida Books · Profit & Loss',`For ${from} to ${to}`],
      ['Organisation',organization.name],
      ['Branch',branch===ALL?'All branches':branch],
      ['Accounting basis','Accrual'],
      ['Total revenue',money(report.totalRevenue)],
      ['Gross profit',money(report.grossProfit)],
      ['Total expenses',money(report.totalExpenses)],
      [report.finalProfitLabel||(report.loss?'Net Loss Before Tax':'Profit Before Tax'),money(report.netProfit)],
      ['Profit Margin',report.margin===null?'N/A':report.margin.toFixed(2)+'%'],
      ['Generated by Local user',stamp.toLocaleString()]
    ];
  }

  const activeFilters=[branch!==ALL,type!==ALL,account!==ALL,accountGroup!==ALL,includeZero].filter(Boolean).length;

  /* Accordion collapse helpers */
  function toggleSection(key){
    setCollapsedMap(prev=>({...prev,[key]:!prev[key]}));
  }

  const allKeys=useMemo(()=>{
    return report.statement.filter(item=>item.kind==='section').map(item=>item.key);
  },[report.statement]);

  const isAllCollapsed=useMemo(()=>{
    if(!allKeys.length)return false;
    return allKeys.every(k=>collapsedMap[k]);
  },[allKeys,collapsedMap]);

  function toggleExpandAll(){
    if(isAllCollapsed){
      setCollapsedMap({});
    }else{
      const next={};
      allKeys.forEach(k=>{next[k]=true});
      setCollapsedMap(next);
    }
  }

  /* Revenue Breakdown calculations for "Where Revenue Goes" Panel */
  const revBreakdown=useMemo(()=>{
    const rev=report.totalRevenue||0;
    if(rev<=0){
      return {cogsPct:0,opExPct:0,otherExPct:0,profitPct:0};
    }
    const cogsPct=Math.max(0,Math.min(100,(report.totalCogs/rev)*100));
    const opExPct=Math.max(0,Math.min(100,(report.totalOperatingExpenses/rev)*100));
    const otherExPct=Math.max(0,Math.min(100,(report.totalOtherExpenses/rev)*100));
    const profitPct=Math.max(0,Math.min(100,(report.netProfit/rev)*100));
    return {cogsPct,opExPct,otherExPct,profitPct};
  },[report]);

  /* Two-sided T-Account data derivation */
  const twoSidedData=useMemo(()=>{
    const revRows=report.revenueSection?.rows||[];
    const cogsRows=report.cogsSection?.rows||[];
    const opExRows=report.opExSection?.rows||[];
    const otherIncRows=report.otherIncomeSection?.rows||[];
    const otherExRows=report.otherExpensesSection?.rows||[];

    const tradingDebitRows=cogsRows.filter(r=>r.amount>0).map(r=>({name:r.name,code:r.code,amount:r.amount}));
    const tradingCreditRows=[
      ...revRows.map(r=>({name:r.name,code:r.code,amount:r.amount})),
      ...cogsRows.filter(r=>r.amount<0).map(r=>({name:`Less: ${r.name}`,code:r.code,amount:Math.abs(r.amount)}))
    ];

    const grossProfit=report.grossProfit;
    if(grossProfit>=0){
      tradingDebitRows.push({name:'Gross Profit c/o',code:'',amount:grossProfit,isDerived:true});
    }else{
      tradingCreditRows.push({name:'Gross Loss c/o',code:'',amount:Math.abs(grossProfit),isDerived:true});
    }

    const tradingDebitTotal=tradingDebitRows.reduce((sum,r)=>sum+r.amount,0);
    const tradingCreditTotal=tradingCreditRows.reduce((sum,r)=>sum+r.amount,0);
    const tradingTotal=Math.max(tradingDebitTotal,tradingCreditTotal);

    const pnlCreditRows=[];
    if(grossProfit>=0){
      pnlCreditRows.push({name:'Gross Profit b/f',code:'',amount:grossProfit,isDerived:true});
    }
    otherIncRows.forEach(r=>pnlCreditRows.push({name:r.name,code:r.code,amount:r.amount}));

    const pnlDebitRows=[];
    if(grossProfit<0){
      pnlDebitRows.push({name:'Gross Loss b/f',code:'',amount:Math.abs(grossProfit),isDerived:true});
    }
    opExRows.forEach(r=>pnlDebitRows.push({name:r.name,code:r.code,amount:r.amount}));
    otherExRows.forEach(r=>pnlDebitRows.push({name:r.name,code:r.code,amount:r.amount}));

    const netProfit=report.netProfit;
    const finalLabel=report.finalProfitLabel||(report.loss?'Net Loss Before Tax':'Profit Before Tax');

    if(netProfit>=0){
      pnlDebitRows.push({name:finalLabel,code:'',amount:netProfit,isDerived:true});
    }else{
      pnlCreditRows.push({name:finalLabel,code:'',amount:Math.abs(netProfit),isDerived:true});
    }

    const pnlDebitTotal=pnlDebitRows.reduce((sum,r)=>sum+r.amount,0);
    const pnlCreditTotal=pnlCreditRows.reduce((sum,r)=>sum+r.amount,0);
    const pnlTotal=Math.max(pnlDebitTotal,pnlCreditTotal);

    return {
      tradingDebitRows,
      tradingCreditRows,
      tradingTotal,
      pnlDebitRows,
      pnlCreditRows,
      pnlTotal
    };
  },[report]);

  /* Render functions for Vertical View */
  const renderAccountRow=(item,index)=>(
    <tr key={item.code||index} className={'plAccountRow '+(selected===item.code?'selected':'')}>
      <td className="plAccountCell">
        <button type="button" className="plAccountBtn" onClick={()=>openLedger(item)} aria-label={`Open General Ledger for ${item.name}`}>
          {!isEasy && item.code && (
            <>
              <span className="plCode">{item.code}</span>
              <span className="plSep"> · </span>
            </>
          )}
          <span className="plAccountName">{item.name}</span>
        </button>
      </td>
      <td className="plMoney">
        <button type="button" className="plMoneyBtn" onClick={()=>openLedger(item)} aria-label={`View ledger for ${money(item.amount)}`}>
          {formatMoney(item.amount)}
        </button>
      </td>
    </tr>
  );

  const renderGroupBlock=group=>(
    <Fragment key={group.name}>
      {group.name!==group.sectionLabel && (
        <tr className="plGroupHeader">
          <th colSpan="2" scope="rowgroup">{group.name}</th>
        </tr>
      )}
      {group.rows.map(renderAccountRow)}
      <tr className="plGroupTotal">
        <td className="plSubtotalLabel">{group.name} subtotal</td>
        <td className="plMoney">{formatMoney(group.total)}</td>
      </tr>
    </Fragment>
  );

  const renderStatementItem=item=>{
    if(item.kind==='derived'){
      const isNet=item.key==='netProfit';
      const isGross=item.key==='grossProfit';
      return (
        <tr key={item.key} className={'plDerived '+(isNet?'plNetResult':isGross?'plGrossResult':'plOpResult')}>
          <td className="plDerivedLabel">{item.label.toUpperCase()}</td>
          <td className="plMoney">{formatMoney(item.amount)}</td>
        </tr>
      );
    }

    const isCollapsed=Boolean(collapsedMap[item.key]);
    return (
      <Fragment key={item.key}>
        <tr className="plSectionHeader" onClick={()=>toggleSection(item.key)} tabIndex={0} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggleSection(item.key);}}} aria-expanded={!isCollapsed}>
          <th colSpan="2" scope="rowgroup">
            <div className="plSectionHeaderContent">
              <span className="plChevron" aria-hidden="true">
                {isCollapsed ? <IconChevronRight size={16}/> : <IconChevronDown size={16}/>}
              </span>
              <span className="plSectionTitle">{item.label.toUpperCase()}</span>
            </div>
          </th>
        </tr>
        {!isCollapsed && (
          <>
            {item.collapsed ? item.groups[0].rows.map(renderAccountRow) : item.groups.map(group=>({...group,sectionLabel:item.label})).map(renderGroupBlock)}
            <tr className="plSectionTotal">
              <td className="plMajorTotalLabel">TOTAL {item.label.toUpperCase()}</td>
              <td className="plMoney">{formatMoney(item.total)}</td>
            </tr>
          </>
        )}
      </Fragment>
    );
  };

  const finalCardTitle=report.finalProfitLabel
    ? report.finalProfitLabel.toUpperCase()
    : (report.loss ? 'NET LOSS BEFORE TAX' : 'PROFIT BEFORE TAX');

  return (
    <section className="plPage" aria-busy={busy}>
      {/* 1. Page Header */}
      <header className="plHead">
        <div className="plHeadTitle">
          <h1>Profit &amp; Loss</h1>
          <p>View income, expenses and net profit for the selected period.</p>
        </div>
        <div className="plHeadActions">
          <DateRangeSelect from={from} to={to} onChange={(start,end)=>{setFrom(start);setTo(end)}} onCustom={()=>setFiltersOpen(true)}/>
          <details className="plFiltersMore" open={filtersOpen} onToggle={e=>setFiltersOpen(e.currentTarget.open)}>
            <summary aria-label="Open filters">
              <IconAdjustments size={18} aria-hidden="true"/>Filters{activeFilters>0&&<span>{activeFilters}</span>}
            </summary>
            <div className="plFilters">
              <label>From date<input type="date" aria-label="From date" value={from} onChange={e=>setFrom(e.target.value)}/></label>
              <label>To date<input type="date" aria-label="To date" value={to} onChange={e=>setTo(e.target.value)}/></label>
              <label>Branch
                <select aria-label="Branch" value={branch} onChange={e=>setBranch(e.target.value)}>
                  <option value={ALL}>All branches</option>
                  {branches.map(item=><option key={item.id} value={item.name}>{item.name}</option>)}
                </select>
              </label>
              <label>Account type
                <select aria-label="Account type" value={type} onChange={e=>setType(e.target.value)}>
                  <option value={ALL}>All account types</option>
                  {PROFIT_LOSS_TYPES.map(item=><option key={item} value={item}>{item}</option>)}
                </select>
              </label>
              <label>Account Group
                <select aria-label="Account Group" value={accountGroup} onChange={e=>setAccountGroup(e.target.value)}>
                  <option value={ALL}>All account groups</option>
                  {groups.map(item=><option key={item} value={item}>{item}</option>)}
                </select>
              </label>
              <label>Account
                <select aria-label="Account" value={account} onChange={e=>setAccount(e.target.value)}>
                  <option value={ALL}>All accounts</option>
                  {report.chart.map(item=><option key={item.code} value={item.code}>{item.code} · {item.name}</option>)}
                </select>
              </label>
              <label className="plCheck">
                <input type="checkbox" checked={includeZero} onChange={e=>setIncludeZero(e.target.checked)}/>
                Include zero-balance accounts
              </label>
              <div className="plFilterActions">
                <button type="button" onClick={refresh}><IconRefresh size={15} aria-hidden="true"/>Refresh</button>
                <button type="button" onClick={reset}>Clear filters</button>
              </div>
            </div>
          </details>
          <ReportExportMenu items={[
            {key:'excel',label:'Export Excel',icon:<IconFileSpreadsheet size={18} aria-hidden="true"/>,onClick:exportExcel,disabled:!report.accounts},
            {key:'pdf',label:'Export PDF',icon:<IconFileTypePdf size={18} aria-hidden="true"/>,onClick:print,disabled:!report.accounts}
          ]}/>
        </div>
      </header>

      {error&&<div className="plError" role="alert"><IconAlertTriangle size={18} aria-hidden="true"/><span>{error}</span></div>}
      <div className="plPrintMeta">{printMeta().map(([label,value])=><p key={label}><b>{label}:</b> {value}</p>)}</div>

      {/* 2. Report View Switch & Presentation Controls Bar (Grouped on Left) */}
      <div className="plViewSwitchBar">
        <div className="plSwitchControls">
          <div className="plSegmented" role="tablist" aria-label="Report View">
            <button type="button" role="tab" aria-selected={viewMode==='vertical'} className={'plSegmentBtn '+(viewMode==='vertical'?'active':'')} onClick={()=>setViewMode('vertical')}>
              Vertical
            </button>
            <button type="button" role="tab" aria-selected={viewMode==='twosided'} className={'plSegmentBtn '+(viewMode==='twosided'?'active':'')} onClick={()=>setViewMode('twosided')}>
              Two-sided
            </button>
          </div>
          {viewMode==='vertical' && (
            <button type="button" className="plControlBtn" onClick={toggleExpandAll}>
              {isAllCollapsed?'Expand all':'Collapse all'}
            </button>
          )}
          <button type="button" className={'plControlBtn '+(panelOpen?'active':'')} onClick={()=>setPanelOpen(!panelOpen)} aria-label="Toggle Insights Panel">
            <IconLayoutSidebar size={15} aria-hidden="true"/>
            <span>{panelOpen ? 'Hide Insights' : 'Show Insights'}</span>
          </button>
        </div>
      </div>

      {/* 4. Report Content Grid Layout */}
      <div className={'plReportLayout '+(panelOpen?'withPanel':'')}>
        <div className="plMainColumn">
          {viewMode==='vertical' ? (
            /* VERTICAL VIEW */
            <div className="plStatementCard">
              <div className="plTableScroll">
                <table>
                  <thead>
                    <tr>
                      <th scope="col" className="plAccountHead">PARTICULARS</th>
                      <th scope="col" className="plMoneyHead">AMOUNT (₹)</th>
                    </tr>
                  </thead>
                  <tbody>
                    {report.accounts ? (
                      report.statement.map(renderStatementItem)
                    ) : (
                      <tr className="emptyStateRow">
                        <td colSpan="2" className="emptyStateCell">
                          <EmptyState variant="journal" title={report.periodActivity?'No accounts match the current filters.':'No income or expense transactions were posted for this period.'} description="Try changing the date range or filters." actionLabel="Reset filters" onAction={reset}/>
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
              <div className="plDrillHint">
                <IconInfoCircle size={15} aria-hidden="true"/>
                <span>Click an amount or account to view underlying ledger transactions.</span>
              </div>
            </div>
          ) : (
            /* TWO-SIDED T-ACCOUNT VIEW */
            <div className="plStatementCard">
              <div className="plTableScroll">
                <table className="plTwoSidedTable">
                  <thead>
                    <tr className="plTwoSidedHeaderRow">
                      <th colSpan="2" className="plDebitHeader">EXPENSES / DEBIT</th>
                      <th colSpan="2" className="plCreditHeader">INCOME / CREDIT</th>
                    </tr>
                    <tr className="plSubHeaderRow">
                      <th scope="col" className="plColParticulars">Particulars</th>
                      <th scope="col" className="plColAmount">Amount (₹)</th>
                      <th scope="col" className="plColParticulars">Particulars</th>
                      <th scope="col" className="plColAmount">Amount (₹)</th>
                    </tr>
                  </thead>
                  <tbody>
                    {/* TRADING ACCOUNT SECTION */}
                    <tr className="plTAccountSectionHeader">
                      <td colSpan="2" className="plTSecTitle">TRADING ACCOUNT</td>
                      <td colSpan="2" className="plTSecTitle">TRADING ACCOUNT</td>
                    </tr>
                    {Array.from({length:Math.max(twoSidedData.tradingDebitRows.length,twoSidedData.tradingCreditRows.length)}).map((_,idx)=>{
                      const deb=twoSidedData.tradingDebitRows[idx];
                      const cred=twoSidedData.tradingCreditRows[idx];
                      return (
                        <tr key={'trd-'+idx} className="plTAccRow">
                          <td className="plColParticulars">
                            {deb ? (
                              deb.isDerived ? <strong>{deb.name}</strong> : (
                                <button type="button" className="plAccountBtn" onClick={()=>openLedger(deb)}>
                                  {deb.code&&<span className="plCode">{deb.code} · </span>}{deb.name}
                                </button>
                              )
                            ) : ''}
                          </td>
                          <td className="plColAmount">{deb ? <strong>{formatMoney(deb.amount)}</strong> : ''}</td>
                          <td className="plColParticulars">
                            {cred ? (
                              cred.isDerived ? <strong>{cred.name}</strong> : (
                                <button type="button" className="plAccountBtn" onClick={()=>openLedger(cred)}>
                                  {cred.code&&<span className="plCode">{cred.code} · </span>}{cred.name}
                                </button>
                              )
                            ) : ''}
                          </td>
                          <td className="plColAmount">{cred ? <strong>{formatMoney(cred.amount)}</strong> : ''}</td>
                        </tr>
                      );
                    })}
                    <tr className="plTradingTotalRow">
                      <td className="plTotalLabel">Trading Total</td>
                      <td className="plTotalAmount">{formatMoney(twoSidedData.tradingTotal)}</td>
                      <td className="plTotalLabel">Trading Total</td>
                      <td className="plTotalAmount">{formatMoney(twoSidedData.tradingTotal)}</td>
                    </tr>

                    {/* PROFIT & LOSS ACCOUNT SECTION */}
                    <tr className="plTAccountSectionHeader">
                      <td colSpan="2" className="plTSecTitle">PROFIT &amp; LOSS ACCOUNT</td>
                      <td colSpan="2" className="plTSecTitle">PROFIT &amp; LOSS ACCOUNT</td>
                    </tr>
                    {Array.from({length:Math.max(twoSidedData.pnlDebitRows.length,twoSidedData.pnlCreditRows.length)}).map((_,idx)=>{
                      const deb=twoSidedData.pnlDebitRows[idx];
                      const cred=twoSidedData.pnlCreditRows[idx];
                      return (
                        <tr key={'pnl-'+idx} className="plTAccRow">
                          <td className="plColParticulars">
                            {deb ? (
                              deb.isDerived ? <strong className="plNetResultLabel">{deb.name}</strong> : (
                                <button type="button" className="plAccountBtn" onClick={()=>openLedger(deb)}>
                                  {deb.code&&<span className="plCode">{deb.code} · </span>}{deb.name}
                                </button>
                              )
                            ) : ''}
                          </td>
                          <td className="plColAmount">{deb ? <strong>{formatMoney(deb.amount)}</strong> : ''}</td>
                          <td className="plColParticulars">
                            {cred ? (
                              cred.isDerived ? <strong className="plNetResultLabel">{cred.name}</strong> : (
                                <button type="button" className="plAccountBtn" onClick={()=>openLedger(cred)}>
                                  {cred.code&&<span className="plCode">{cred.code} · </span>}{cred.name}
                                </button>
                              )
                            ) : ''}
                          </td>
                          <td className="plColAmount">{cred ? <strong>{formatMoney(cred.amount)}</strong> : ''}</td>
                        </tr>
                      );
                    })}
                    <tr className="plPnlTotalRow">
                      <td className="plTotalLabel">P&amp;L Total</td>
                      <td className="plTotalAmount">{formatMoney(twoSidedData.pnlTotal)}</td>
                      <td className="plTotalLabel">P&amp;L Total</td>
                      <td className="plTotalAmount">{formatMoney(twoSidedData.pnlTotal)}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div className="plDrillHint">
                <IconInfoCircle size={15} aria-hidden="true"/>
                <span>Click an amount or account to view underlying ledger transactions.</span>
              </div>
            </div>
          )}
        </div>

        {/* 5. Collapsible Right Context Panel ("Where Revenue Goes") */}
        {panelOpen && (
          <div className="plContextPanel" role="region" aria-label="Revenue Breakdown">
            <div className="plContextHead">
              <h3>Where Revenue Goes</h3>
              <p className="plContextSub">Distribution of total income ({formatMoney(report.totalRevenue)})</p>
            </div>

            <div className="plCompBar" aria-hidden="true">
              {revBreakdown.cogsPct>0 && <div className="plCompSeg segCogs" style={{width:`${revBreakdown.cogsPct}%`}} title={`COGS: ${revBreakdown.cogsPct.toFixed(1)}%`}/>}
              {revBreakdown.opExPct>0 && <div className="plCompSeg segOpEx" style={{width:`${revBreakdown.opExPct}%`}} title={`Operating Expenses: ${revBreakdown.opExPct.toFixed(1)}%`}/>}
              {revBreakdown.otherExPct>0 && <div className="plCompSeg segOtherEx" style={{width:`${revBreakdown.otherExPct}%`}} title={`Other Expenses: ${revBreakdown.otherExPct.toFixed(1)}%`}/>}
              {revBreakdown.profitPct>0 && <div className="plCompSeg segProfit" style={{width:`${revBreakdown.profitPct}%`}} title={`Profit Before Tax: ${revBreakdown.profitPct.toFixed(1)}%`}/>}
            </div>

            <ul className="plCompList">
              <li className="plCompItem">
                <span className="plCompLabel"><span className="plCompDot dotCogs"/>Cost of Goods Sold</span>
                <span className="plCompPct">{revBreakdown.cogsPct.toFixed(2)}%</span>
                <strong className="plCompVal">{formatMoney(report.totalCogs)}</strong>
              </li>
              <li className="plCompItem">
                <span className="plCompLabel"><span className="plCompDot dotOpEx"/>Operating Expenses</span>
                <span className="plCompPct">{revBreakdown.opExPct.toFixed(2)}%</span>
                <strong className="plCompVal">{formatMoney(report.totalOperatingExpenses)}</strong>
              </li>
              {report.totalOtherExpenses>0 && (
                <li className="plCompItem">
                  <span className="plCompLabel"><span className="plCompDot dotOtherEx"/>Other Expenses</span>
                  <span className="plCompPct">{revBreakdown.otherExPct.toFixed(2)}%</span>
                  <strong className="plCompVal">{formatMoney(report.totalOtherExpenses)}</strong>
                </li>
              )}
              <li className="plCompItem highlight">
                <span className="plCompLabel"><span className="plCompDot dotProfit"/>{report.hasTaxExpense?(report.loss?'Net Loss After Tax':'Net Profit After Tax'):(report.loss?'Net Loss Before Tax':'Profit Before Tax')}</span>
                <span className="plCompPct">{revBreakdown.profitPct.toFixed(2)}%</span>
                <strong className="plCompVal">{formatMoney(report.netProfit)}</strong>
              </li>
            </ul>

            <div className="plContextDivider"/>

            <div className="plReportNotes">
              <span className="plNotesTitle">REPORT NOTES</span>
              <ul>
                <li>• Accrual basis accounting</li>
                <li>• Recoverable GST excluded</li>
                <li>• Inventory valued at cost</li>
                <li>• Posted journal entries only</li>
              </ul>
            </div>
          </div>
        )}
      </div>

      {/* 6. Footer / About Report Section */}
      <details className="plAboutReport">
        <summary>
          <span>ⓘ About this report</span>
          <IconChevronDown size={16} className="plAboutChevron" aria-hidden="true"/>
        </summary>
        <div className="plAboutContent">
          <p>Based on posted accounting entries for the selected period. Draft and cancelled transactions are excluded.</p>
          <p>• Revenue and expense accounts are included for the selected period.</p>
          <p>• Gross Profit = Revenue − Cost of Goods Sold.</p>
          <p>• Operating Profit = Gross Profit − Operating Expenses.</p>
          <p>• Profit Before Tax is calculated from the applicable income and expense categories in the report (Operating Profit + Other Income − Other Expenses).</p>
          <p>• Net Profit Margin: {report.margin===null?'N/A':report.margin.toFixed(2)+'%'}</p>
        </div>
      </details>
    </section>
  );
}
