import {useMemo,useState} from 'react';
import {IconArrowLeft,IconCheck,IconFileInvoice,IconPackageImport,IconPrinter,IconCashBanknote,IconX,IconInfoCircle,IconListDetails} from '@tabler/icons-react';
import DocumentPreview from './DocumentPreview.jsx';
import StatusPill from './StatusPill.jsx';
import {money} from './invoice-engine.js';

/* The purchase document reads its lifecycle on the one shared pill, the way every other
   register and detail screen does. */
const TONE=value=>{const s=String(value||'').toLowerCase();if(/cancel|overdue|reject|blocked/.test(s))return 'danger';if(/pending|awaiting/.test(s))return 'warn';if(/partial/.test(s))return 'info';if(/paid|completed|received|closed/.test(s))return 'ok';if(/sent|approved|open|billed/.test(s))return 'info';return 'neutral'};

export default function PurchaseDetails({isBill,record,error,onDismissError,onBack,onOpen,onReceive,onConvert,onPost,onPayment,onCancel}){
 const [preview,setPreview]=useState(false),[payment,setPayment]=useState(false),[cancel,setCancel]=useState(false),[amount,setAmount]=useState(((record.total-(record.paidAmount||0))/100).toFixed(2)),[date,setDate]=useState(new Date().toLocaleDateString('en-CA')),[reason,setReason]=useState(''),[tab,setTab]=useState('Overview');
 const previewDoc=useMemo(()=>({...record,billing:record.vendorAddress,shipping:record.deliveryAddress,reference:record.reference||record.referenceOrder}),[record]);
 const balance=record.total-(record.paidAmount||0);
 const tabs=['Overview','Accounting','Activity'];
 const stats=isBill?[['Bill status',record.status],['Vendor invoice',record.vendorInvoice||'Not recorded'],['Bill date',record.date],['Due date',record.dueDate],['Grand total',money(record.total)],['Balance due',money(balance)]]:[['Order status',record.status],['Order date',record.date],['Expected delivery',record.expectedDate||'Not recorded'],['Grand total',money(record.total)],['Received',record.receivedAt?String(record.receivedAt).slice(0,10):'Not received'],['Place of supply',record.placeOfSupply||'Kerala']];
 return <section className="invoiceWorkspace purchaseWorkspace ivDetailOpen">
  {preview&&<DocumentPreview kind={isBill?'Purchase Bill':'Purchase Order'} doc={previewDoc} onClose={()=>setPreview(false)}/>}
  <div className="ivDetailHead"><button type="button" className="ivDetailBack" aria-label={'Back to '+(isBill?'Purchase Bills':'Purchase Orders')} onClick={onBack}><IconArrowLeft size={19}/></button><div className="ivDetailHeadText"><h2>{isBill?'Purchase bill details':'Purchase order details'}</h2><small>{record.number} &middot; {record.vendorName}</small></div></div>
  <div className="ivDetailBody"><section className="ivDetailSheet">
   {error&&<div role="alert" className="ivError">{error}<button type="button" aria-label="Dismiss error" onClick={onDismissError}><IconX size={16}/></button></div>}
   <div className="ivDetailIdentityRow">
    <div className="ivDetailIdentity"><div className="ivDetailNumber"><h3>{record.number}</h3><StatusPill status={record.status} tone={TONE(record.status)}/></div><p>{record.vendorName}{record.vendorInvoice?' &middot; '+record.vendorInvoice:''} &middot; {record.date}</p></div>
    <div className="ivDocumentActions">
     <button onClick={()=>setPreview(true)}><IconPrinter size={16}/>Preview</button>
     {!isBill&&['Draft','Pending Approval','Approved'].includes(record.status)&&<button className="primary" onClick={onOpen}><IconCheck size={16}/>Open order</button>}
     {!isBill&&['Open','Sent To Vendor','Partially Received'].includes(record.status)&&<button className="primary" onClick={onReceive}><IconPackageImport size={16}/>Receive goods</button>}
     {!isBill&&['Received','Partially Received','Partially Billed'].includes(record.status)&&<button className="primary" onClick={onConvert}><IconFileInvoice size={16}/>Convert received quantity</button>}
     {isBill&&!record.posted&&record.status!=='Cancelled'&&<button className="primary" onClick={onPost}><IconCheck size={16}/>Post bill</button>}
     {isBill&&record.posted&&record.status!=='Cancelled'&&balance>0&&<button className="primary" onClick={()=>setPayment(true)}><IconCashBanknote size={16}/>Record payment</button>}
     {isBill&&record.status!=='Cancelled'&&<button onClick={()=>setCancel(true)}>Cancel bill</button>}
    </div>
   </div>
   <div className="ivDetailStats">{stats.map(([k,v])=><span key={k}><small>{k}</small><strong>{v}</strong></span>)}</div>
   <nav className="itemDetailTabs ivDetailTabs" aria-label="Purchase document sections">{tabs.map(t=><button key={t} type="button" className={tab===t?'active':''} aria-current={tab===t?'page':undefined} onClick={()=>setTab(t)}>{t}</button>)}</nav>
   {tab==='Overview'?<div className="ivOverviewPage">
    <div className="ivOverviewGrid">
     <section className="itemDetailCard"><div className="itemDetailSectionTitle"><IconInfoCircle size={18}/><h2>Vendor details</h2></div><dl className="itemDetailFacts">{[['Vendor',record.vendorName],['Contact',record.vendorContact],['GSTIN',record.vendorGstin||'Not registered'],['Place of supply',record.placeOfSupply||'Kerala'],['Payment terms',record.paymentTerms],['Billing address',record.vendorAddress]].map(([k,v])=><div key={k} className={k.endsWith('address')?'ivFactWide':undefined}><dt>{k}</dt><dd>{v||'Not recorded'}</dd></div>)}</dl></section>
     <section className="itemDetailCard"><div className="itemDetailSectionTitle"><IconListDetails size={18}/><h2>{isBill?'Bill summary':'Order summary'}</h2></div><dl className="itemDetailFacts">{[['Subtotal',money(record.totals?.subtotal)],['Discount',money(record.totals?.discount)],['CGST',money(record.totals?.cgst)],['SGST',money(record.totals?.sgst)],['IGST',money(record.totals?.igst)],['Cess',money(record.totals?.cess)],['Grand total',money(record.total)],...(isBill?[['Paid',money(record.paidAmount||0)],['Balance due',money(balance)],['Journal',record.journalId||'Not posted']]:[]) ].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section>
    </div>
    <section className="itemDetailCard"><div className="itemDetailSectionTitle"><IconFileInvoice size={18}/><h2>Items and services</h2></div><div className="ivScroll"><table className="ivInvoiceTable purchaseDetailLines"><thead><tr>{['Item','Ordered','Received','Bill quantity','Rate','Tax','Amount'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{(record.totals?.lines||[]).map(line=><tr key={line.id}><td>{line.description}</td><td>{line.orderedQty||line.qty} {line.unit}</td><td>{line.receivedQty??'-'}</td><td>{line.qty} {line.unit}</td><td>{money(Number(line.rate)*100)}</td><td>{money(line.tax+line.cess)}</td><td>{money(line.total)}</td></tr>)}</tbody></table></div></section>
   </div>:tab==='Accounting'?<div className="purchaseTabBody">{isBill?<><p className="ivMutedNote">{record.posted?'Posting created the journal below from the accounts mapped on the bill.':'Post the bill to create its Accounts Payable journal.'}</p><dl className="itemDetailFacts">{[['Journal',record.journalId||'Not posted'],['Posted at',record.postedAt||'Not recorded'],['Posted by',record.postedBy||'Not recorded'],['Reversal journal',record.reversalJournalId||'Not reversed'],['Purchase account',record.purchaseAccount],['Payable account',record.payableAccount],['Input tax account',record.inputTaxAccount]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Not recorded'}</dd></div>)}</dl></>:<><p className="ivMutedNote">A purchase order does not post accounting. It becomes a bill through Convert received quantity.</p><dl className="itemDetailFacts">{[['Document','Purchase order'],['Accounting entry','None'],['Converted bill',record.billNumber||'Not converted']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></>}</div>:<div className="purchaseTabBody"><dl className="itemDetailFacts">{[['Created',record.createdAt||'Not recorded'],['Last modified',record.updatedAt||'Not recorded'],['Status',record.status],['Vendor',record.vendorName]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div>}
  </section></div>
  {payment&&<div className="ivOverlay"><form className="ivModal" role="dialog" aria-modal="true" aria-label="Record vendor payment" onSubmit={event=>{event.preventDefault();if(onPayment({amount,date,reference:'PAY-'+Date.now()}))setPayment(false)}}><h2>Record vendor payment</h2><p>Creates the payment journal and updates the bill balance automatically.</p><label>Amount<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Payment date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div className="ivActions"><button type="button" onClick={()=>setPayment(false)}>Cancel</button><button className="primary">Record payment</button></div></form></div>}
  {cancel&&<div className="ivOverlay"><form className="ivModal" role="dialog" aria-modal="true" aria-label="Cancel purchase bill" onSubmit={event=>{event.preventDefault();if(onCancel({reason,date,role:'Admin'}))setCancel(false)}}><h2>Cancel purchase bill</h2><p>Posted accounting will be reversed. Bills with payments must be settled first.</p><label>Cancellation reason<input required value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Reversal date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div className="ivActions"><button type="button" onClick={()=>setCancel(false)}>Go back</button><button className="primary">Reverse &amp; cancel</button></div></form></div>}
 </section>;
}
