import {useEffect,useMemo,useState} from 'react';
import {IconPlus,IconSearch,IconArrowLeft,IconTrash,IconX,IconFilter} from '@tabler/icons-react';
import StatusPill from './StatusPill.jsx';
import PurchaseRowActions from './PurchaseRowActions.jsx';
import {KEY,initial,money} from './invoice-engine.js';
import {itemSeeds} from './Items.jsx';
import {readVendors} from './vendor-store.js';
import {PURCHASE_ORDER_KEY,PURCHASE_BILL_KEY,calculatePurchase,savePurchaseOrder,savePurchaseBill,convertPurchaseOrder,postPurchaseBill} from './purchase-service.js';
import {advancePurchaseOrder,recordPurchasePayment,cancelPurchaseBill} from './purchase-service.js';
import PurchaseDetails from './PurchaseDetails.jsx';
import './purchases.css';

import {QUICK_CREATE_KEY} from './quick-create.js';

const read=(key,fallback=[])=>{try{const value=JSON.parse(localStorage.getItem(key));return Array.isArray(value)?value:fallback}catch{return fallback}};
const today=()=>new Date().toLocaleDateString('en-CA');
const plusDays=(date,terms)=>{const days=Number(String(terms).match(/\d+/)?.[0]||0),value=new Date(date+'T12:00:00');value.setDate(value.getDate()+days);return value.toISOString().slice(0,10)};
const blankLine=()=>({id:crypto.randomUUID(),itemId:'',description:'',qty:'1',unit:'pcs',rate:'0',discount:'0',taxRate:'0',cessRate:'0',priceTaxMode:'exclusive',purchaseAccount:'5000'});

export default function Purchases({page='Purchase Orders',onNavigate=()=>{}}){
 const isBill=page==='Purchase Bills';
 const [orders,setOrders]=useState(()=>read(PURCHASE_ORDER_KEY)),[bills,setBills]=useState(()=>read(PURCHASE_BILL_KEY)),[query,setQuery]=useState(''),[filter,setFilter]=useState('All statuses'),[form,setForm]=useState(null),[view,setView]=useState(null),[error,setError]=useState(''),[vendorFilter,setVendorFilter]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[sort,setSort]=useState('newest'),[current,setCurrent]=useState(1);
 const vendors=readVendors().filter(v=>v.status==='Active'),items=read('finance-erp-items',itemSeeds).filter(item=>item.purchase!==false),rows=isBill?bills:orders;
 useEffect(()=>{const action=sessionStorage.getItem(QUICK_CREATE_KEY);if((isBill&&action==='purchase-bill')||(!isBill&&action==='purchase-order')){sessionStorage.removeItem(QUICK_CREATE_KEY);open()}},[]);
 /* The register reads its lifecycle on the one shared pill, the way every other register does. */
 const PURCHASE_TONES=value=>{const s=String(value||'').toLowerCase();if(/cancel|overdue|reject|blocked/.test(s))return 'danger';if(/pending|awaiting/.test(s))return 'warn';if(/partial/.test(s))return 'info';if(/paid|completed|received|active|closed/.test(s))return 'ok';if(/sent|approved|open/.test(s))return 'info';return 'neutral'};
 const statusOptions=useMemo(()=>['All statuses',...new Set([...(isBill?['Draft','Pending Approval','Unpaid','Partially Paid','Paid','Overdue','Cancelled']:['Draft','Pending Approval','Approved','Sent To Vendor','Partially Received','Received','Completed','Cancelled']),...rows.map(row=>row.status).filter(Boolean)])],[rows,isBill]);
 const activeFilters=[filter!=='All statuses',vendorFilter,from,to,sort!=='newest'].filter(Boolean).length;
 const clearFilters=()=>{setFilter('All statuses');setVendorFilter('');setFrom('');setTo('');setSort('newest');setQuery('');setCurrent(1)};
 const visible=useMemo(()=>{const list=rows.filter(row=>[row.number,row.vendorName,row.vendorInvoice,row.reference].join(' ').toLowerCase().includes(query.toLowerCase())&&(filter==='All statuses'||row.status===filter)&&(!vendorFilter||row.vendorId===vendorFilter)&&(!from||(row.date||'')>=from)&&(!to||(row.date||'')<=to));if(sort==='amount')return [...list].sort((a,b)=>(b.total||0)-(a.total||0));if(sort==='number')return [...list].sort((a,b)=>String(a.number||'').localeCompare(String(b.number||'')));return [...list].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))},[rows,query,filter,vendorFilter,from,to,sort]);
 const pageCount=Math.max(1,Math.ceil(visible.length/10)),pageIndex=Math.min(current,pageCount),paged=visible.slice((pageIndex-1)*10,pageIndex*10);
 const set=(key,value)=>setForm(current=>({...current,[key]:value}));
 const totals=(()=>{try{return form?calculatePurchase(form.lines):null}catch{return null}})();
 function selectVendor(id){const vendor=vendors.find(v=>v.id===id);setForm(current=>({...current,vendorId:id,vendorName:vendor?.displayName||vendor?.name||'',vendorContact:vendor?.contactName||vendor?.phone||'',vendorAddress:[vendor?.billing?.line1,vendor?.billing?.city,vendor?.billing?.state].filter(Boolean).join(', '),vendorGstin:vendor?.gstin||'',placeOfSupply:vendor?.billing?.state||'Kerala',paymentTerms:vendor?.paymentTerms||'30 Days',dueDate:isBill?plusDays(current.date,vendor?.paymentTerms):current.dueDate,payableAccount:vendor?.payableAccountId||'2000',purchaseAccount:vendor?.purchaseAccountId||current.purchaseAccount||'5000'}));}
 function selectItem(index,id){const item=items.find(row=>row.id===id);setForm(current=>({...current,lines:current.lines.map((line,i)=>i===index?{...line,itemId:id,description:item?.name||'',unit:item?.unit||'pcs',rate:String(item?.cost||0),taxRate:item?.taxApplicable===false?'0':String(item?.taxRate||0),cessRate:String(item?.cessRate||0),priceTaxMode:item?.priceTaxMode||'exclusive',purchaseAccount:item?.purchaseAccount||'5000'}:line)}));}
 function line(index,key,value){setForm(current=>({...current,lines:current.lines.map((row,i)=>i===index?{...row,[key]:value}:row)}));}
 function open(row=null){setView(null);setError('');if(row){setForm(structuredClone(row));return}const date=today();setForm(isBill?{number:'',vendorId:'',vendorName:'',vendorInvoice:'',date,dueDate:date,referenceOrder:'',reference:'',status:'Draft',paymentTerms:'30 Days',vendorAddress:'',vendorContact:'',vendorGstin:'',lines:[blankLine()],purchaseAccount:'5000',inputTaxAccount:'1400',payableAccount:'2000',attachments:[],notes:''}:{number:'',date,vendorId:'',vendorName:'',expectedDate:'',reference:'',status:'Draft',paymentTerms:'30 Days',vendorAddress:'',vendorContact:'',vendorGstin:'',lines:[blankLine()],deliveryAddress:'Kochi Branch',shippingMethod:'',deliveryTerms:'',warranty:'',notes:'',attachments:[]});}
 function persist(event,status){event.preventDefault();try{if(isBill){const output=savePurchaseBill(bills,form,status);localStorage.setItem(PURCHASE_BILL_KEY,JSON.stringify(output.rows));setBills(output.rows)}else{const output=savePurchaseOrder(orders,form,status);localStorage.setItem(PURCHASE_ORDER_KEY,JSON.stringify(output.rows));setOrders(output.rows)}setForm(null);setError('')}catch(reason){setError(reason.message)}}
 function convert(order){try{const output=convertPurchaseOrder(orders,bills,order);setOrders(output.orders);setBills(output.bills);localStorage.setItem(PURCHASE_ORDER_KEY,JSON.stringify(output.orders));localStorage.setItem(PURCHASE_BILL_KEY,JSON.stringify(output.bills));onNavigate('Purchase Bills')}catch(reason){setError(reason.message)}}
 function post(bill){try{const accounting=JSON.parse(localStorage.getItem(KEY)||'null')||initial();const output=postPurchaseBill(accounting,bill);localStorage.setItem(KEY,JSON.stringify(output.state));const next=bills.map(row=>row.id===bill.id?output.bill:row);setBills(next);localStorage.setItem(PURCHASE_BILL_KEY,JSON.stringify(next));setView(output.bill);return output.bill}catch(reason){setError(reason.message)}}
 function advance(order,action){try{const output=advancePurchaseOrder(orders,order,action);setOrders(output.rows);setView(output.order);localStorage.setItem(PURCHASE_ORDER_KEY,JSON.stringify(output.rows))}catch(reason){setError(reason.message)}}
 function pay(bill,payment){try{const accounting=JSON.parse(localStorage.getItem(KEY)||'null')||initial();const output=recordPurchasePayment(accounting,bill,payment);localStorage.setItem(KEY,JSON.stringify(output.state));const next=bills.map(row=>row.id===bill.id?output.bill:row);setBills(next);setView(output.bill);localStorage.setItem(PURCHASE_BILL_KEY,JSON.stringify(next));return output.bill}catch(reason){setError(reason.message)}}
 function cancelBill(bill,data){try{const accounting=JSON.parse(localStorage.getItem(KEY)||'null')||initial();const output=cancelPurchaseBill(accounting,bill,data);localStorage.setItem(KEY,JSON.stringify(output.state));const next=bills.map(row=>row.id===bill.id?output.bill:row);setBills(next);setView(output.bill);localStorage.setItem(PURCHASE_BILL_KEY,JSON.stringify(next));return output.bill}catch(reason){setError(reason.message)}}
 if(view)return <PurchaseDetails isBill={isBill} record={view} error={error} onDismissError={()=>setError('')} onBack={()=>setView(null)} onOpen={()=>advance(view,'open')} onReceive={()=>onNavigate('Goods Receipts')} onConvert={()=>convert(view)} onPost={()=>post(view)} onPayment={payment=>pay(view,payment)} onCancel={data=>cancelBill(view,data)}/>;
 if(form)return <section className="invoiceWorkspace purchaseWorkspace soCreatePage ivCreatePage">
  <div className="soCreateHead"><div className="soHeadIdentity"><button type="button" className="soBack" aria-label={'Back to '+page} onClick={()=>setForm(null)}><IconArrowLeft size={19}/></button><div className="soHeadText"><h2>{form.id?'Edit':'Create'} {isBill?'Purchase Bill':'Purchase Order'}</h2><small className="soHeadHint">{form.number?form.number:(isBill?'Vendor invoice · Accounts Payable follows posting':'Purchase request · no accounting entry')}</small></div></div></div>
  <form className="ivCreateForm" onSubmit={event=>persist(event,isBill?'Draft':'Pending Approval')}>
   {error&&<div role="alert" className="ivError">{error}<button type="button" aria-label="Dismiss error" onClick={()=>setError('')}><IconX size={16}/></button></div>}
   <div className="ivCard soFormSection">
    <div className="soSectionHead"><div className="soSectionHeadText"><h3>{isBill?'Bill details':'Order details'}</h3></div></div>
    <div className="ivFields">
     <label>{isBill?'Bill number':'PO number'}<input value={form.number} placeholder="Auto generated" onChange={e=>set('number',e.target.value)}/></label>
     <label>Vendor *<select value={form.vendorId} onChange={e=>selectVendor(e.target.value)}><option value="">Select vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.displayName||v.name}</option>)}</select></label>
     {isBill&&<label>Vendor invoice number *<input value={form.vendorInvoice} onChange={e=>set('vendorInvoice',e.target.value)} placeholder="Vendor document number"/></label>}
     <label>{isBill?'Bill date *':'PO date *'}<input type="date" value={form.date} onChange={e=>setForm(x=>({...x,date:e.target.value,dueDate:isBill?plusDays(e.target.value,x.paymentTerms):x.dueDate}))}/></label>
     <label>{isBill?'Due date':'Expected delivery date'}<input type="date" value={isBill?form.dueDate:form.expectedDate} onChange={e=>set(isBill?'dueDate':'expectedDate',e.target.value)}/></label>
     <label>{isBill?'Reference purchase order':'Reference number'}{isBill?<select value={form.referenceOrder||''} onChange={e=>{const po=orders.find(x=>x.number===e.target.value);if(po){const converted=convertPurchaseOrder(orders,bills,po).bill;setForm({...converted,id:form.id,vendorInvoice:form.vendorInvoice})}else set('referenceOrder','')}}><option value="">No purchase order</option>{orders.filter(o=>o.status!=='Cancelled').map(o=><option key={o.id}>{o.number}</option>)}</select>:<input value={form.reference} onChange={e=>set('reference',e.target.value)} placeholder="Vendor quotation number"/>}</label>
    </div>
    {form.vendorId&&<dl className="soFactList"><div className="soFactItem soFactWide"><dt>Vendor</dt><dd>{form.vendorName}</dd></div><div className="soFactItem"><dt>GSTIN</dt><dd>{form.vendorGstin||'Not registered'}</dd></div><div className="soFactItem"><dt>Payment terms</dt><dd>{form.paymentTerms}</dd></div><div className="soFactItem soFactWide"><dt>Billing address</dt><dd>{form.vendorAddress||'Not recorded'}</dd></div></dl>}
   </div>
   <div className="ivCard">
    <div className="ivHeading"><h3>Items and services</h3><button type="button" onClick={()=>set('lines',[...form.lines,blankLine()])}><IconPlus size={16}/>Add line</button></div>
    <div className="ivScroll"><table className="ivLineTable"><thead><tr>{['Item / service','Quantity','Unit','Rate','Discount','Tax','Amount',''].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{form.lines.map((row,index)=>{let amount=0;try{amount=calculatePurchase([row]).total}catch{}return <tr key={row.id}><td><select aria-label={'Item '+(index+1)} value={row.itemId} onChange={e=>selectItem(index,e.target.value)}><option value="">Select item</option>{items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></td><td><input aria-label={'qty '+(index+1)} type="number" min="0.01" step="0.01" value={row.qty} onChange={e=>line(index,'qty',e.target.value)}/></td><td><input aria-label={'unit '+(index+1)} value={row.unit} onChange={e=>line(index,'unit',e.target.value)}/></td><td><input aria-label={'rate '+(index+1)} type="number" min="0" step="0.01" value={row.rate} onChange={e=>line(index,'rate',e.target.value)}/></td><td><input aria-label={'discount '+(index+1)} type="number" min="0" max="100" value={row.discount} onChange={e=>line(index,'discount',e.target.value)}/></td><td><select aria-label={'tax '+(index+1)} value={row.taxRate} onChange={e=>line(index,'taxRate',e.target.value)}>{['0','5','12','18','28'].map(rate=><option key={rate} value={rate}>GST {rate}%</option>)}</select></td><td><strong>{money(amount)}</strong></td><td><button type="button" aria-label="Remove line" disabled={form.lines.length===1} onClick={()=>set('lines',form.lines.filter((_,i)=>i!==index))}><IconTrash size={16}/></button></td></tr>})}</tbody></table></div>
    <section className="soBillingSummary"><div className="soSummaryHead"><h3>Billing summary</h3></div>{totals?<dl className="ivTotals"><div><dt>Subtotal</dt><dd>{money(totals.subtotal)}</dd></div><div><dt>Discount</dt><dd>- {money(totals.discount)}</dd></div><div><dt>Tax</dt><dd>{money((totals.tax||0)+(totals.cess||0))}</dd></div><div><dt>Grand total</dt><dd>{money(totals.total)}</dd></div></dl>:<p role="status">Add an item and quantity to calculate totals.</p>}</section>
   </div>
   {isBill&&<details className="ivCard soMoreCard"><summary><span className="soMoreTitle">Accounting mapping</span><span className="soMoreHint">Accountant / Admin</span></summary><div className="soMoreBody"><div className="ivFields"><label>Purchase account<select value={form.purchaseAccount} onChange={e=>set('purchaseAccount',e.target.value)}><option value="5000">5000 - Purchase</option><option value="5600">5600 - Purchase Returns</option></select></label><label>Input tax account<select value={form.inputTaxAccount} onChange={e=>set('inputTaxAccount',e.target.value)}><option value="1400">1400 - Input GST</option><option value="1500">1500 - Current Assets (Input GST)</option></select></label><label>Payable account<select value={form.payableAccount} onChange={e=>set('payableAccount',e.target.value)}><option value="2000">2000 - Accounts Payable</option></select></label></div></div></details>}
   <details className="ivCard soMoreCard"><summary><span className="soMoreTitle">Delivery, terms and attachments</span><span className="soMoreHint">Optional</span></summary><div className="soMoreBody"><div className="ivFields"><label>Notes<textarea value={form.notes||''} onChange={e=>set('notes',e.target.value)}/></label>{!isBill&&<><label>Delivery address<textarea value={form.deliveryAddress||''} onChange={e=>set('deliveryAddress',e.target.value)}/></label><label>Shipping method<input value={form.shippingMethod||''} onChange={e=>set('shippingMethod',e.target.value)}/></label><label>Delivery terms<input value={form.deliveryTerms||''} onChange={e=>set('deliveryTerms',e.target.value)}/></label><label>Warranty details<input value={form.warranty||''} onChange={e=>set('warranty',e.target.value)}/></label></>}<label>Attachments<input type="file" multiple onChange={e=>set('attachments',Array.from(e.target.files).map(file=>file.name))}/><small>File names are stored in this prototype.</small></label></div></div></details>
   <div className="ivFooter soActionBar"><dl className="soBarTotals"><div><dt>Grand total</dt><dd>{money(totals?.total)}</dd></div></dl><div className="soBarActions"><button type="button" onClick={()=>setForm(null)}>Cancel</button><button type="button" onClick={event=>persist(event,'Draft')}>Save draft</button><button className="primary">{isBill?'Save bill':'Submit for approval'}</button></div></div>
  </form>
 </section>;
 return <section className="invoiceWorkspace purchaseWorkspace">
  {error&&<div role="alert" className="ivError">{error}<button type="button" aria-label="Dismiss error" onClick={()=>setError('')}><IconX size={16}/></button></div>}
  <div className="ivHeading"><div><h2>{page}</h2><p>{isBill?'Record vendor invoices, payment status, and Accounts Payable.':'Manage vendor orders before bills are received.'}</p></div><div className="ivActions"><button className="primary" onClick={()=>open()}><IconPlus size={16}/>Create {isBill?'Purchase Bill':'Purchase Order'}</button></div></div>
  <div className="ivCard ivRegisterCard">
   <div className="ivTools"><label className="ivToolSearch"><IconSearch size={17}/><input aria-label={'Search '+page.toLowerCase()} placeholder="Search number, vendor or reference" value={query} onChange={e=>{setQuery(e.target.value);setCurrent(1)}}/></label><details className="soFiltersMore"><summary aria-label="Open filters"><IconFilter size={17}/>Filters{activeFilters>0&&<i>{activeFilters}</i>}</summary><div className="soFiltersPanel"><label>Status<select aria-label="Filter status" value={filter} onChange={e=>{setFilter(e.target.value);setCurrent(1)}}>{statusOptions.map(x=><option key={x}>{x}</option>)}</select></label><label>Vendor<select aria-label="Filter vendor" value={vendorFilter} onChange={e=>{setVendorFilter(e.target.value);setCurrent(1)}}><option value="">All vendors</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.displayName||v.name}</option>)}</select></label><label>From<input type="date" aria-label="Filter from" value={from} onChange={e=>{setFrom(e.target.value);setCurrent(1)}}/></label><label>To<input type="date" aria-label="Filter to" value={to} onChange={e=>{setTo(e.target.value);setCurrent(1)}}/></label><label>Sort<select aria-label="Sort records" value={sort} onChange={e=>{setSort(e.target.value);setCurrent(1)}}><option value="newest">Newest first</option><option value="amount">Highest amount</option><option value="number">Number</option></select></label><button type="button" className="soClearFilters" onClick={clearFilters}>Clear filters</button></div></details></div>
   <div className="ivScroll"><table className="ivInvoiceTable"><thead><tr>{(isBill?['Bill & date','Vendor','Vendor invoice','Amount','Balance due','Payment status','Actions']:['Order & date','Vendor','Reference','Amount','Status','Expected delivery','Actions']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{paged.map(row=><tr key={row.id}>{isBill?<><td><button className="ivLink" onClick={()=>setView(row)}>{row.number}</button><small>{row.date}</small></td><td>{row.vendorName}<small>{row.vendorContact||'Contact not recorded'}</small></td><td>{row.vendorInvoice||'-'}</td><td>{money(row.total)}</td><td>{money(row.total-(row.paidAmount||0))}<small>Paid {money(row.paidAmount||0)}</small></td><td><StatusPill status={row.status} tone={PURCHASE_TONES(row.status)}/></td></>:<><td><button className="ivLink" onClick={()=>setView(row)}>{row.number}</button><small>{row.date}</small></td><td>{row.vendorName}<small>{row.vendorContact||'Contact not recorded'}</small></td><td>{row.reference||'-'}</td><td>{money(row.total)}</td><td><StatusPill status={row.status} tone={PURCHASE_TONES(row.status)}/></td><td>{row.expectedDate||'-'}</td></>}<td><div className="ivRowActions"><button onClick={()=>setView(row)}>View</button><PurchaseRowActions doc={row} isBill={isBill} onView={()=>setView(row)} onEdit={()=>open(row)} onPost={()=>post(row)} onJournal={()=>onNavigate('Journal Entries')} onSend={()=>{const next=rows.map(x=>x.id===row.id?{...x,status:'Sent To Vendor'}:x);setOrders(next);localStorage.setItem(PURCHASE_ORDER_KEY,JSON.stringify(next))}} onConvert={()=>convert(row)} onCancel={()=>{const next=rows.map(x=>x.id===row.id?{...x,status:'Cancelled'}:x);if(isBill){setBills(next);localStorage.setItem(PURCHASE_BILL_KEY,JSON.stringify(next))}else{setOrders(next);localStorage.setItem(PURCHASE_ORDER_KEY,JSON.stringify(next))}}}/></div></td></tr>)}</tbody></table>{!visible.length&&<div className="ivEmpty"><h3>No {page.toLowerCase()} found</h3><p>{rows.length?'Adjust the search or filters to find a record.':'Create the first record to begin the purchase workflow.'}</p></div>}</div>
   <div className="ivActions purchaseRegisterFoot"><span>{visible.length} of {rows.length} records</span>{pageCount>1&&<><button disabled={pageIndex===1} onClick={()=>setCurrent(pageIndex-1)}>Previous</button><span>Page {pageIndex} of {pageCount}</span><button disabled={pageIndex===pageCount} onClick={()=>setCurrent(pageIndex+1)}>Next</button></>}</div>
  </div>
 </section>;
}
