import {journal,minor} from './invoice-engine.js';
import {validatePostingDate} from './period-locking.js';

export const PURCHASE_ORDER_KEY='wayvida-purchase-orders-v1';
export const PURCHASE_BILL_KEY='wayvida-purchase-bills-v1';
export const VENDOR_PAYMENT_KEY='wayvida-vendor-payments-v1';
export const GOODS_RECEIPT_KEY='wayvida-goods-receipts-v1';
export const DEBIT_NOTE_KEY='wayvida-debit-notes-v1';
const clone=value=>JSON.parse(JSON.stringify(value));
const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value||'')&&!Number.isNaN(Date.parse(value));
const nextNumber=(rows,prefix)=>{let number=1;while(rows.some(row=>row.number===`${prefix}-${String(number).padStart(5,'0')}`))number++;return `${prefix}-${String(number).padStart(5,'0')}`};
const ensureDefaultPurchaseAccount=state=>{
 const current=state.accounts.find(account=>String(account.code)==='5000');
 if(!current){state.accounts.push({id:'system:5000',code:'5000',name:'Purchase',type:'Expenses',nature:'Debit',group:'Operating Expenses',parent:'',active:true,isGroup:false,system:true,controlAccount:false,revision:1});return '5000'}
 if(!current.active||current.isGroup||current.type!=='Expenses')Object.assign(current,{name:current.name||'Purchase',type:'Expenses',nature:'Debit',group:current.group||'Operating Expenses',active:true,isGroup:false,system:true,controlAccount:false,revision:(current.revision||0)+1});
 return '5000';
};
const ensureDefaultPayableAccount=state=>{
 const current=state.accounts.find(account=>String(account.code)==='2000');
 if(!current){state.accounts.push({id:'system:2000',code:'2000',name:'Accounts Payable',type:'Liabilities',nature:'Credit',group:'Current Liabilities',parent:'',active:true,isGroup:false,system:true,controlAccount:true,revision:1});return '2000'}
 if(!current.active||current.isGroup||current.type!=='Liabilities')Object.assign(current,{name:current.name||'Accounts Payable',type:'Liabilities',nature:'Credit',group:current.group||'Current Liabilities',active:true,isGroup:false,system:true,controlAccount:true,revision:(current.revision||0)+1});
 return '2000';
};
const ensureDefaultBankAccount=state=>{
 const current=state.accounts.find(account=>String(account.code)==='1010');
 if(!current){state.accounts.push({id:'system:1010',code:'1010',name:'Bank',type:'Assets',nature:'Debit',group:'Cash and Bank',parent:'',active:true,isGroup:false,system:true,controlAccount:false,revision:1});return '1010'}
 if(!current.active||current.isGroup||current.type!=='Assets')Object.assign(current,{name:current.name||'Bank',type:'Assets',nature:'Debit',group:current.group||'Cash and Bank',active:true,isGroup:false,system:true,controlAccount:false,revision:(current.revision||0)+1});
 return '1010';
};

export function calculatePurchase(lines,{companyState='Kerala',placeOfSupply=companyState}={}){
 if(!lines?.length)throw Error('Add at least one item or service.');
 const calculated=lines.map(line=>{const qty=Number(line.qty),rate=minor(line.rate||'0'),discount=Number(line.discount||0),taxRate=Number(line.taxRate||0),cessRate=Number(line.cessRate||0);if(!line.itemId||!line.description?.trim()||!line.unit||!Number.isFinite(qty)||qty<=0)throw Error('Each line needs an item, unit, and positive quantity.');if(!Number.isFinite(discount)||discount<0||discount>100)throw Error('Discount must be between 0 and 100%.');if(!Number.isFinite(taxRate)||taxRate<0||taxRate>100||!Number.isFinite(cessRate)||cessRate<0)throw Error('Choose valid tax rates.');const entered=Math.round(qty*rate),combined=taxRate+cessRate,gross=line.priceTaxMode==='inclusive'&&combined?Math.round(entered*100/(100+combined)):entered,discountAmount=Math.round(gross*discount/100),taxable=gross-discountAmount,tax=Math.round(taxable*taxRate/100),cess=Math.round(taxable*cessRate/100);return {...line,gross,discountAmount,taxable,tax,cess,total:taxable+tax+cess}});
 const sum=key=>calculated.reduce((total,line)=>total+line[key],0),tax=sum('tax'),intra=String(companyState).trim().toLowerCase()===String(placeOfSupply).trim().toLowerCase(),cgst=intra?Math.floor(tax/2):0,sgst=intra?tax-Math.floor(tax/2):0,igst=intra?0:tax;return {lines:calculated,subtotal:sum('gross'),discount:sum('discountAmount'),taxable:sum('taxable'),tax,cgst,sgst,igst,cess:sum('cess'),adjustment:0,total:sum('total')};
}

export function savePurchaseOrder(rows,input,status='Draft'){
 const form=clone(input),existing=rows.find(row=>row.id===form.id);if(existing&&['Completed','Cancelled'].includes(existing.status))throw Error('Completed or cancelled purchase orders cannot be edited.');if(!['Draft','Pending Approval','Approved','Sent To Vendor'].includes(status))throw Error('Invalid purchase order status.');if(!form.vendorId||!form.vendorName)throw Error('Select an active vendor.');if(!validDate(form.date))throw Error('Choose a valid PO date.');if(form.expectedDate&&(!validDate(form.expectedDate)||form.expectedDate<form.date))throw Error('Expected delivery cannot be before the PO date.');const totals=calculatePurchase(form.lines),number=form.number?.trim()||nextNumber(rows,'PO');if(rows.some(row=>row.id!==form.id&&row.number.toLowerCase()===number.toLowerCase()))throw Error('PO number must be unique.');const order={...form,id:form.id||crypto.randomUUID(),number,status,totals,total:totals.total,updatedAt:new Date().toISOString(),createdAt:existing?.createdAt||new Date().toISOString()};return {order,rows:existing?rows.map(row=>row.id===order.id?order:row):[order,...rows]};
}

const receivedFor=(receipts,orderId,lineId)=>receipts.filter(r=>r.orderId===orderId&&r.status!=='Cancelled').reduce((n,r)=>n+Number(r.lines.find(l=>l.orderLineId===lineId)?.receivedQty||0),0);
const billedFor=(bills,orderId,lineId)=>bills.filter(b=>b.sourceOrderId===orderId&&b.status!=='Cancelled').reduce((n,b)=>n+Number(b.lines.find(l=>l.orderLineId===lineId||l.id===lineId)?.qty||0),0);

export function createGoodsReceipt(orders,receipts,input){
 const order=orders.find(row=>row.id===input.orderId);if(!order)throw Error('Purchase order not found.');if(!['Open','Sent To Vendor','Partially Received','Partially Billed'].includes(order.status))throw Error('Only an open purchase order can receive goods.');if(!validDate(input.date))throw Error('Choose a valid receipt date.');const lines=order.lines.map(line=>{const already=receivedFor(receipts,order.id,line.id),requested=Number(input.lines?.find(x=>x.orderLineId===line.id)?.receivedQty||0),pending=Number(line.qty)-already;if(!Number.isFinite(requested)||requested<0||requested>pending)throw Error(`Received quantity for ${line.description} cannot exceed ${pending}.`);return {orderLineId:line.id,itemId:line.itemId,description:line.description,unit:line.unit,orderedQty:Number(line.qty),previouslyReceived:already,receivedQty:requested,pendingQty:pending-requested}}).filter(line=>line.receivedQty>0);if(!lines.length)throw Error('Enter at least one received quantity.');const receipt={id:crypto.randomUUID(),number:input.number?.trim()||nextNumber(receipts,'GRN'),orderId:order.id,orderNumber:order.number,vendorId:order.vendorId,vendorName:order.vendorName,date:input.date,reference:input.reference||'',notes:input.notes||'',lines,status:'Posted',createdBy:input.user||'Admin',createdAt:new Date().toISOString()};const allReceipts=[receipt,...receipts],updatedLines=order.lines.map(line=>({...line,orderedQty:Number(line.qty),receivedQty:receivedFor(allReceipts,order.id,line.id)})),complete=updatedLines.every(line=>line.receivedQty>=Number(line.qty)),updated={...order,lines:updatedLines,status:complete?'Received':'Partially Received',updatedAt:new Date().toISOString()};return {receipt,receipts:allReceipts,order:updated,orders:orders.map(row=>row.id===order.id?updated:row)};
}

export function savePurchaseBill(rows,input,status='Draft'){
 const form=clone(input),existing=rows.find(row=>row.id===form.id);if(existing?.posted)throw Error('Posted bills are immutable. Create a debit note or reversal instead.');if(!form.vendorId||!form.vendorName)throw Error('Select an active vendor.');if(!form.vendorInvoice?.trim())throw Error('Vendor invoice number is required.');if(rows.some(row=>row.id!==form.id&&row.vendorId===form.vendorId&&row.vendorInvoice.trim().toLowerCase()===form.vendorInvoice.trim().toLowerCase()))throw Error('This vendor invoice number already exists.');if(!validDate(form.date)||!validDate(form.dueDate)||form.dueDate<form.date)throw Error('Due date must be on or after the bill date.');if(form.lines.some(line=>line.maxQty!=null&&Number(line.qty)>Number(line.maxQty)))throw Error('Billed quantity cannot exceed the received quantity available.');const totals=calculatePurchase(form.lines,{placeOfSupply:form.placeOfSupply}),number=form.number?.trim()||nextNumber(rows,'BILL');if(rows.some(row=>row.id!==form.id&&row.number.toLowerCase()===number.toLowerCase()))throw Error('Bill number must be unique.');const now=new Date().toISOString(),bill={...form,id:form.id||crypto.randomUUID(),number,status,posted:false,paidAmount:existing?.paidAmount||0,totals,total:totals.total,modifiedBy:'Admin',modifiedAt:now,updatedAt:now,createdBy:existing?.createdBy||'Admin',createdAt:existing?.createdAt||now};return {bill,rows:existing?rows.map(row=>row.id===bill.id?bill:row):[bill,...rows]};
}

export function convertPurchaseOrder(orders,bills,order){
 if(!['Received','Partially Received','Partially Billed','Completed'].includes(order.status))throw Error('Receive goods before converting this purchase order to a bill.');const lines=order.lines.map(line=>{const received=Number(line.receivedQty||0),billed=billedFor(bills,order.id,line.id),available=received-billed;return available>0?{...clone(line),orderLineId:line.id,qty:String(available),maxQty:available}:null}).filter(Boolean);if(!lines.length)throw Error('All received quantities have already been billed.');const totals=calculatePurchase(lines,{placeOfSupply:order.placeOfSupply}),bill={...clone(order),lines,id:crypto.randomUUID(),number:nextNumber(bills,'BILL'),vendorInvoice:'',date:order.date,dueDate:order.dueDate||order.expectedDate||order.date,referenceOrder:order.number,sourceOrderId:order.id,status:'Draft',posted:false,paidAmount:0,totals,total:totals.total,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},nextBills=[bill,...bills],fullyBilled=order.lines.every(line=>billedFor(nextBills,order.id,line.id)>=Number(line.receivedQty||0)&&Number(line.receivedQty||0)>=Number(line.qty));const updated={...order,status:fullyBilled?'Completed':'Partially Billed',billIds:[...(order.billIds||[]),bill.id]};return {orders:orders.map(row=>row.id===order.id?updated:row),bills:nextBills,bill};
}

export function advancePurchaseOrder(rows,order,action){
 const allowed={open:['Draft','Pending Approval','Approved'],receive:['Open','Sent To Vendor','Partially Received']},next={open:'Open',receive:'Received'};
 if(!allowed[action]?.includes(order.status))throw Error(action==='open'?'Only a draft or approved purchase order can be opened.':'Open the purchase order before receiving goods.');
 const updated={...order,status:next[action],updatedAt:new Date().toISOString()};
 return {order:updated,rows:rows.map(row=>row.id===order.id?updated:row)};
}

export function postPurchaseBill(accountingState,bill,{role='Admin',periodOptions={}}={}){
 const state=clone(accountingState),stored=(state.purchaseBills||[]).find(row=>row.id===bill.id);if(stored?.posted)return {state,bill:stored,journal:state.journals.find(row=>row.id===stored.journalId)};const lock=validatePostingDate(bill.date,role,periodOptions);if(!lock.allowed)throw Error(lock.message);const totals=calculatePurchase(bill.lines,{companyState:state.config?.state||'Kerala',placeOfSupply:bill.placeOfSupply||state.config?.state||'Kerala'}),ensure=(code,name)=>{if(!state.accounts.some(a=>a.code===code))state.accounts.push({code,name,type:'Assets',active:true,system:true,controlAccount:true})};ensureDefaultPurchaseAccount(state);ensureDefaultPayableAccount(state);ensure(bill.inputCgstAccount||'1410','Input CGST');ensure(bill.inputSgstAccount||'1420','Input SGST');ensure(bill.inputIgstAccount||'1430','Input IGST');ensure(bill.inputCessAccount||'1440','Input Cess');const lines=[];for(const line of totals.lines)lines.push({account:line.purchaseAccount||bill.purchaseAccount||'5000',debit:line.taxable,credit:0,description:line.description});for(const [key,accountKey,fallback,label] of [['cgst','inputCgstAccount','1410','Input CGST'],['sgst','inputSgstAccount','1420','Input SGST'],['igst','inputIgstAccount','1430','Input IGST'],['cess','inputCessAccount','1440','Input Cess']])if(totals[key])lines.push({account:bill[accountKey]||fallback,debit:totals[key],credit:0,description:label});const payableAccount=bill.payableAccount==='2100'?'2000':bill.payableAccount||'2000';lines.push({account:payableAccount,debit:0,credit:totals.total,description:'Vendor payable'});const entry=journal(state,{...bill,number:bill.number},'Purchase Bill',lines,bill.date,'purchase-bill:'+bill.id);entry.vendorId=bill.vendorId;entry.purchaseBillId=bill.id;const posted={...bill,payableAccount,totals,total:totals.total,posted:true,status:'Unpaid',journalId:entry.id,postedBy:role,postedAt:entry.createdAt};state.purchaseBills=[...(state.purchaseBills||[]).filter(row=>row.id!==bill.id),posted];state.audit.push({id:crypto.randomUUID(),action:'post purchase bill',purchaseBillId:bill.id,journalId:entry.id,at:entry.createdAt,by:role});return {state,bill:posted,journal:entry};
}

export function recordPurchasePayment(accountingState,bill,{amount,date,bankAccount='1010',reference='',role='Admin',periodOptions={}}={}){
 const state=clone(accountingState);if(!bill.posted)throw Error('Post the purchase bill before recording payment.');if(!validDate(date)||date<bill.date)throw Error('Payment date must be on or after the bill date.');const value=minor(amount),token=`purchase-payment:${bill.id}:${reference||date}:${value}`;const existing=(state.vendorPayments||[]).find(p=>p.token===token);if(existing)return {state,bill:(state.purchaseBills||[]).find(row=>row.id===bill.id)||bill,journal:state.journals.find(j=>j.id===existing.journalId),payment:existing};const balance=bill.total-(bill.paidAmount||0)-(bill.creditApplied||0);if(value<=0||value>balance)throw Error('Payment must be greater than zero and cannot exceed the balance due.');const lock=validatePostingDate(date,role,periodOptions);if(!lock.allowed)throw Error(lock.message);if(bankAccount==='1010')ensureDefaultBankAccount(state);const payable=bill.payableAccount||'2000',entry=journal(state,{number:reference||bill.number},'Vendor Payment',[{account:payable,debit:value,credit:0,description:`Payment for ${bill.number}`},{account:bankAccount,debit:0,credit:value,description:`Payment to ${bill.vendorName}`}],date,token);entry.vendorId=bill.vendorId;entry.purchaseBillId=bill.id;const paidAmount=(bill.paidAmount||0)+value,updated={...bill,paidAmount,status:paidAmount+(bill.creditApplied||0)===bill.total?'Paid':'Partially Paid',updatedAt:new Date().toISOString()},payment={id:crypto.randomUUID(),number:nextNumber(state.vendorPayments||[],'VPAY'),billId:bill.id,vendorId:bill.vendorId,amount:value,date,reference,bankAccount,journalId:entry.id,token,status:'Posted',createdBy:role,createdAt:entry.createdAt};state.purchaseBills=[...(state.purchaseBills||[]).filter(row=>row.id!==bill.id),updated];state.vendorPayments=[...(state.vendorPayments||[]),payment];state.audit.push({id:crypto.randomUUID(),action:'record vendor payment',purchaseBillId:bill.id,journalId:entry.id,at:entry.createdAt,by:role});return {state,bill:updated,journal:entry,payment};
}

export function cancelPurchaseBill(accountingState,bill,{reason,date,role='Admin',periodOptions={}}={}){
 const state=clone(accountingState),stored=(state.purchaseBills||[]).find(row=>row.id===bill.id)||bill;
 if(stored.status==='Cancelled')return {state,bill:stored};
 if(!reason?.trim())throw Error('Cancellation reason is required.');
 const lock=validatePostingDate(date,role,periodOptions);if(!lock.allowed)throw Error(lock.message);
 const paymentReversals=[];
 for(const payment of (state.vendorPayments||[]).filter(row=>row.billId===stored.id&&row.status==='Posted')){
  const originalPayment=state.journals.find(row=>row.id===payment.journalId);if(!originalPayment)throw Error(`Original journal for payment ${payment.number} was not found.`);
  if(payment.bankAccount==='1010')ensureDefaultBankAccount(state);
  const refund=journal(state,{...stored,number:payment.number},'Vendor Payment Refund',originalPayment.lines.map(line=>({...line,debit:line.credit,credit:line.debit,description:`Refund reversal: ${line.description||payment.number}`})),date,'vendor-payment-refund:'+payment.id);
  refund.vendorId=stored.vendorId;refund.purchaseBillId=stored.id;refund.vendorPaymentId=payment.id;paymentReversals.push(refund);
  Object.assign(payment,{status:'Reversed',reversedAt:refund.createdAt,reversedBy:role,reversalJournalId:refund.id,reversalReason:reason.trim()});
  state.audit.push({id:crypto.randomUUID(),action:'reverse vendor payment for bill cancellation',purchaseBillId:stored.id,vendorPaymentId:payment.id,journalId:refund.id,at:refund.createdAt,by:role,reason:reason.trim()});
 }
 let reversal;
 if(stored.posted){const original=state.journals.find(j=>j.id===stored.journalId);if(!original)throw Error('Original purchase journal not found.');reversal=journal(state,{...stored,number:stored.number},'Purchase Bill Reversal',original.lines.map(line=>({...line,debit:line.credit,credit:line.debit})),date,'purchase-bill-reversal:'+stored.id);reversal.vendorId=stored.vendorId;reversal.purchaseBillId=stored.id;}
 const cancelled={...stored,status:'Cancelled',paidAmount:0,cancelledAt:new Date().toISOString(),cancelledBy:role,cancellationReason:reason.trim(),reversalJournalId:reversal?.id||null,paymentReversalJournalIds:paymentReversals.map(row=>row.id)};
 state.purchaseBills=[...(state.purchaseBills||[]).filter(row=>row.id!==stored.id),cancelled];state.audit.push({id:crypto.randomUUID(),action:'cancel purchase bill',purchaseBillId:stored.id,journalId:reversal?.id||null,at:cancelled.cancelledAt,by:role,reason:reason.trim()});return {state,bill:cancelled,reversal,paymentReversals};
}

export function saveDebitNote(rows,bills,input,status='Draft'){
 const form=clone(input),existing=rows.find(row=>row.id===form.id),bill=bills.find(row=>row.id===form.billId);
 if(existing?.posted)throw Error('Issued debit notes are immutable. Void the note with a reversal instead.');
 if(bill){form.vendorId=form.vendorId||bill.vendorId;form.vendorName=form.vendorName||bill.vendorName;}
 if(!form.vendorId||!form.vendorName)throw Error('Please select a vendor before creating a debit note.');
 if(form.billId&&(!bill?.posted||bill.status==='Cancelled'))throw Error('Select a posted, active purchase bill.');
 if(bill&&form.vendorId!==bill.vendorId)throw Error('The debit note vendor must match the purchase bill vendor.');
 if(!validDate(form.date)||(bill&&form.date<bill.date))throw Error(bill?'Debit note date must be on or after the bill date.':'Enter a valid debit note date.');
 if(!form.lines?.length)throw Error('Add at least one debit note line.');
 const totals=calculatePurchase(form.lines,{placeOfSupply:bill?.placeOfSupply||form.placeOfSupply});
 if(totals.total<=0)throw Error('Debit note amount must be greater than zero.');
 const previous=bill?rows.filter(row=>row.id!==form.id&&row.billId===bill.id&&row.status!=='Voided').reduce((sum,row)=>sum+row.total,0):0;
 if(bill&&previous+totals.total>bill.total)throw Error('Debit notes cannot exceed the purchase bill total.');
 const financialYear=Number(form.date.slice(5,7))<4?Number(form.date.slice(0,4))-1:Number(form.date.slice(0,4)),number=form.number?.trim()||`DN-${financialYear}-${String(rows.length+1).padStart(4,'0')}`;
 if(rows.some(row=>row.id!==form.id&&row.number.toLowerCase()===number.toLowerCase()))throw Error('Debit note number must be unique.');
 const now=new Date().toISOString(),note={...form,id:form.id||crypto.randomUUID(),number,status,posted:false,billNumber:bill?.number||'',vendorId:bill?.vendorId||form.vendorId,vendorName:bill?.vendorName||form.vendorName,vendorGstin:bill?.vendorGstin||form.vendorGstin||'',placeOfSupply:bill?.placeOfSupply||form.placeOfSupply,payableAccount:bill?.payableAccount||form.payableAccount||'2000',totals,total:totals.total,appliedAmount:existing?.appliedAmount||0,reason:form.reason?.trim()||'',createdBy:existing?.createdBy||'Admin',createdAt:existing?.createdAt||now,updatedAt:now};
 return {note,rows:existing?rows.map(row=>row.id===note.id?note:row):[note,...rows]};
}

export function issueDebitNote(accountingState,note,{role='Admin',periodOptions={}}={}){
 const state=clone(accountingState),stored=(state.debitNotes||[]).find(row=>row.id===note.id);
 if(stored?.posted)return {state,note:stored,bill:(state.purchaseBills||[]).find(row=>row.id===stored.billId),journal:state.journals.find(row=>row.id===stored.journalId)};
 if(!['Approved'].includes(note.status))throw Error('Approve the debit note before posting.');
 const bill=(state.purchaseBills||[]).find(row=>row.id===note.billId);if(note.billId&&(!bill?.posted||bill.status==='Cancelled'))throw Error('The linked purchase bill must be posted and active.');
 const lock=validatePostingDate(note.date,role,periodOptions);if(!lock.allowed)throw Error(lock.message);
 const totals=calculatePurchase(note.lines,{companyState:state.config?.state||'Kerala',placeOfSupply:note.placeOfSupply||state.config?.state||'Kerala'}),available=bill?bill.total-(bill.paidAmount||0)-(bill.creditApplied||0):Infinity;
 if(bill&&totals.total>available)throw Error('Debit note cannot exceed the bill balance available for credit.');
 ensureDefaultPurchaseAccount(state);ensureDefaultPayableAccount(state);
 const ensureTaxAccount=(code,name)=>{const current=state.accounts.find(account=>String(account.code)===code);if(!current)state.accounts.push({id:`system:${code}`,code,name,type:'Assets',nature:'Debit',group:'Current Assets',parent:'',active:true,isGroup:false,system:true,controlAccount:true,revision:1});else if(!current.active||current.isGroup||current.type!=='Assets')Object.assign(current,{name:current.name||name,type:'Assets',nature:'Debit',active:true,isGroup:false,system:true,controlAccount:true,revision:(current.revision||0)+1});};
 ensureTaxAccount('1410','Input CGST');ensureTaxAccount('1420','Input SGST');ensureTaxAccount('1430','Input IGST');ensureTaxAccount('1440','Input Cess');
 const lines=[{account:note.payableAccount||bill?.payableAccount||'2000',debit:totals.total,credit:0,description:`Debit note${bill?.number?' for '+bill.number:''}`}];
 for(const item of totals.lines)lines.push({account:item.purchaseAccount||bill?.purchaseAccount||'5000',debit:0,credit:item.taxable,description:item.description});
 for(const [key,accountKey,fallback,label] of [['cgst','inputCgstAccount','1410','Input CGST reversal'],['sgst','inputSgstAccount','1420','Input SGST reversal'],['igst','inputIgstAccount','1430','Input IGST reversal'],['cess','inputCessAccount','1440','Input Cess reversal']])if(totals[key])lines.push({account:bill?.[accountKey]||fallback,debit:0,credit:totals[key],description:label});
 const entry=journal(state,{...note,number:note.number},'Purchase Debit Note',lines,note.date,'purchase-debit-note:'+note.id);entry.vendorId=note.vendorId;entry.purchaseBillId=bill?.id||null;entry.debitNoteId=note.id;
 const issued={...note,totals,total:totals.total,posted:true,status:'Posted',appliedAmount:0,journalId:entry.id,issuedBy:role,issuedAt:entry.createdAt};
 state.debitNotes=[...(state.debitNotes||[]).filter(row=>row.id!==issued.id),issued];if(bill)state.purchaseBills=[...(state.purchaseBills||[]).filter(row=>row.id!==bill.id),bill];state.audit.push({id:crypto.randomUUID(),action:'post purchase debit note',debitNoteId:issued.id,purchaseBillId:bill?.id||null,journalId:entry.id,at:entry.createdAt,by:role});return {state,note:issued,bill,journal:entry};
}

export function submitDebitNote(rows,note){if(note.status!=='Draft')throw Error('Only a draft debit note can be submitted.');const updated={...note,status:'Pending Approval',updatedAt:new Date().toISOString()};return {note:updated,rows:rows.map(row=>row.id===note.id?updated:row)}}
export function approveDebitNote(rows,note,{role='Admin'}={}){if(!['Admin','Accountant'].includes(role))throw Error('You do not have permission to approve debit notes.');if(note.status!=='Pending Approval')throw Error('Only a pending debit note can be approved.');const updated={...note,status:'Approved',approvedBy:role,approvedAt:new Date().toISOString(),updatedAt:new Date().toISOString()};return {note:updated,rows:rows.map(row=>row.id===note.id?updated:row)}}
export function applyDebitNote(accountingState,note){const state=clone(accountingState),stored=(state.debitNotes||[]).find(row=>row.id===note.id)||note;if(stored.status!=='Posted')throw Error('Post the debit note before applying it.');const bill=(state.purchaseBills||[]).find(row=>row.id===stored.billId);if(!bill)throw Error('Linked purchase bill not found.');const available=bill.total-(bill.paidAmount||0)-(bill.creditApplied||0);if(stored.total>available)throw Error('Debit note cannot exceed the bill balance available for credit.');const creditApplied=(bill.creditApplied||0)+stored.total,balance=bill.total-(bill.paidAmount||0)-creditApplied,updatedBill={...bill,creditApplied,status:balance===0?'Paid':bill.paidAmount?'Partially Paid':'Unpaid',updatedAt:new Date().toISOString()},adjusted={...stored,status:'Adjusted',appliedAmount:stored.total,adjustedAt:new Date().toISOString(),updatedAt:new Date().toISOString()};state.purchaseBills=[...(state.purchaseBills||[]).filter(row=>row.id!==bill.id),updatedBill];state.debitNotes=[...(state.debitNotes||[]).filter(row=>row.id!==stored.id),adjusted];state.audit.push({id:crypto.randomUUID(),action:'apply purchase debit note',debitNoteId:stored.id,purchaseBillId:bill.id,at:adjusted.adjustedAt,by:'Admin'});return {state,note:adjusted,bill:updatedBill}}
export function cancelDebitNote(rows,note){if(note.posted)throw Error('Reverse a posted debit note instead of cancelling it.');const cancelled={...note,status:'Cancelled',cancelledAt:new Date().toISOString(),updatedAt:new Date().toISOString()};return {note:cancelled,rows:rows.map(row=>row.id===note.id?cancelled:row)}}

export function voidDebitNote(accountingState,note,{reason,date,role='Admin',periodOptions={}}={}){
 const state=clone(accountingState),stored=(state.debitNotes||[]).find(row=>row.id===note.id)||note;if(stored.status==='Voided')return {state,note:stored};if(!stored.posted)throw Error('Only an issued debit note can be voided.');if(!reason?.trim())throw Error('Void reason is required.');const lock=validatePostingDate(date,role,periodOptions);if(!lock.allowed)throw Error(lock.message);const original=state.journals.find(row=>row.id===stored.journalId);if(!original)throw Error('Original debit note journal not found.');const reversal=journal(state,{...stored,number:stored.number},'Purchase Debit Note Reversal',original.lines.map(line=>({...line,debit:line.credit,credit:line.debit,description:`Void: ${line.description}`})),date,'purchase-debit-note-void:'+stored.id);reversal.vendorId=stored.vendorId;reversal.purchaseBillId=stored.billId;reversal.debitNoteId=stored.id;const voided={...stored,status:'Voided',appliedAmount:0,voidReason:reason.trim(),voidedBy:role,voidedAt:reversal.createdAt,reversalJournalId:reversal.id},bill=(state.purchaseBills||[]).find(row=>row.id===stored.billId),creditApplied=Math.max(0,(bill?.creditApplied||0)-stored.total),balance=(bill?.total||0)-(bill?.paidAmount||0)-creditApplied,updatedBill=bill&&{...bill,creditApplied,status:balance===0?'Paid':bill.paidAmount?'Partially Paid':'Unpaid',updatedAt:new Date().toISOString()};state.debitNotes=[...(state.debitNotes||[]).filter(row=>row.id!==stored.id),voided];if(updatedBill)state.purchaseBills=[...(state.purchaseBills||[]).filter(row=>row.id!==bill.id),updatedBill];state.audit.push({id:crypto.randomUUID(),action:'void purchase debit note',debitNoteId:stored.id,purchaseBillId:stored.billId,journalId:reversal.id,at:reversal.createdAt,by:role,reason:reason.trim()});return {state,note:voided,bill:updatedBill,reversal};
}

export function vendorOutstanding(state,vendorId){const gross=(state.purchaseBills||[]).filter(b=>b.vendorId===vendorId&&b.posted&&b.status!=='Cancelled').reduce((n,b)=>n+b.total-(b.paidAmount||0),0),credits=(state.debitNotes||[]).filter(n=>n.vendorId===vendorId&&n.posted&&!['Voided','Reversed','Cancelled'].includes(n.status)).reduce((sum,n)=>sum+n.total,0);return gross-credits}
export function vendorLedger(state,vendorId){let balance=0;return [...(state.journals||[])].filter(j=>j.vendorId===vendorId&&j.status==='Posted').sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt.localeCompare(b.createdAt)).flatMap(j=>j.lines.filter(l=>l.account===((state.purchaseBills||[]).find(b=>b.id===j.purchaseBillId)?.payableAccount||'2000')).map(l=>({...j,lines:undefined,debit:l.debit,credit:l.credit,balance:balance+=l.credit-l.debit}))) }
export function purchaseTaxDocuments(state){return [...(state.purchaseBills||[]).filter(b=>b.posted).map(b=>({id:b.id,kind:'Purchase Bill',number:b.number,date:b.date,vendorId:b.vendorId,vendorName:b.vendorName,vendorGstin:b.vendorGstin,placeOfSupply:b.placeOfSupply,status:b.status,totals:b.totals,sign:b.status==='Cancelled'?0:1})),...(state.debitNotes||[]).filter(n=>n.posted).map(n=>({id:n.id,kind:'Purchase Debit Note',number:n.number,date:n.date,vendorId:n.vendorId,vendorName:n.vendorName,vendorGstin:n.vendorGstin,placeOfSupply:n.placeOfSupply,status:n.status,totals:n.totals,sign:n.status==='Voided'?0:-1}))]}
