import DocumentPreview from './DocumentPreview.jsx';
import {useEffect,useState} from 'react';
import {IconPlus,IconArrowLeft,IconDotsVertical,IconEye,IconEdit,IconArrowsExchange,IconHistory,IconPrinter,IconSettings,IconUpload,IconX,IconCheck,IconArrowBackUp,IconFileDownload,IconBook,IconListDetails} from '@tabler/icons-react';
import {readAccounts,writeAccounts} from './account-store.js';
import {money,today,outstanding} from './invoice-engine.js';
import {MODES,receiptRows,receiptCommand,receiptAllocations,receiptAvailable,allocationStatus,RECEIPT_ROLES,receiptAllowed} from './receipt-engine.js';
import {customerSeeds} from './Customers.jsx';
import './invoice-workspace.css';
import './receipts.css';
import {parseBankCSV} from './receipt-import.js';
import ReceiptImpact,{AccountingImpact} from './ReceiptImpact.jsx';
import {receiptBankSuggestions} from './receipt-insights.js';
const tabs=['Overview','Allocation','Accounting Impact','Ledger Impact','Audit Trail'];
const readCustomers=()=>{const raw=localStorage.getItem('wayvida-customers');return raw?JSON.parse(raw):customerSeeds};
export const withBankingLines=state=>{try{const banking=JSON.parse(localStorage.getItem('wayvida-banking-v1')||'null');if(!banking?.bankTransactions?.length)return state;const existing=new Set((state.receiptBankLines||[]).map(line=>line.id)),accounts=new Map((banking.bankAccounts||[]).map(account=>[account.id,account.accountCode])),lines=banking.bankTransactions.filter(line=>line.credit>0&&!['Excluded','Reconciled'].includes(line.status)&&!existing.has(line.id)&&accounts.get(line.bankAccountId)).map(line=>({id:line.id,date:line.date,amount:line.credit,bank:accounts.get(line.bankAccountId),reference:line.reference||line.description||'',status:line.status||'Unmatched',source:'Banking module'}));return lines.length?{...state,receiptBankLines:[...(state.receiptBankLines||[]),...lines]}:state}catch{return state}};
export default function Receipts({seed,onNavigate,notify}){
 const [printDoc,setPrintDoc]=useState(null);
 const [db,setDb]=useState(()=>withBankingLines(readAccounts(seed))),[customers]=useState(readCustomers),[selected,setSelected]=useState(()=>sessionStorage.getItem('wayvida-open-receipt')),[form,setForm]=useState(null),[error,setError]=useState(''),[tab,setTab]=useState('Overview'),[query,setQuery]=useState(''),[status,setStatus]=useState('All'),[role,setRole]=useState('Admin'),[accountingView,setAccountingView]=useState(false),[ledgerTab,setLedgerTab]=useState('Customer Ledger'),[dialog,setDialog]=useState(null),[alloc,setAlloc]=useState({}),[allocDate,setAllocDate]=useState(today()),[settings,setSettings]=useState(null),[bankView,setBankView]=useState(false),[bankForm,setBankForm]=useState({id:'',date:today(),amount:'',bank:'',reference:''}),[match,setMatch]=useState({bankLineId:'',amount:''});
 const rows=receiptRows(db),r=rows.find(x=>x.id===selected),banks=db.accounts.filter(a=>a.active&&!a.isGroup&&a.type==='Assets'&&(/cash|bank/i.test(a.name)||['Cash','Bank'].includes(a.subType))),ctx={customers:readCustomers(),actor:'Local '+role,role,canApprove:['Finance Manager','Admin'].includes(role)};
 const openInvoices=id=>db.invoices.filter(i=>i.customerId===id&&i.posted&&i.status!=='Cancelled'&&outstanding(db,i)>0);
 function create(invoiceId,bankLine){const i=db.invoices.find(i=>i.id===invoiceId);setError('');setBankView(false);setForm({date:today(),customerId:i?.customerId||'',amount:i?String(outstanding(db,i)/100):bankLine?String(bankLine.amount/100):'',bank:bankLine?.bank||banks[0]?.code||'',mode:'Bank Transfer',reference:bankLine?.reference||'',notes:'',kind:bankLine?'Advance':'Normal',attachment:null,allocations:i?[{invoiceId:i.id,amount:String(outstanding(db,i)/100)}]:[],bankLineId:bankLine?.id});}
 useEffect(()=>{const id=sessionStorage.getItem('wayvida-receive-invoice');if(id){sessionStorage.removeItem('wayvida-receive-invoice');create(id)}sessionStorage.removeItem('wayvida-open-receipt');const refresh=()=>{try{setDb(withBankingLines(readAccounts(seed)))}catch(e){setError(e.message)}};window.addEventListener('storage',refresh);return()=>window.removeEventListener('storage',refresh)},[]);
 function run(action,p){try{const result=receiptCommand(withBankingLines(readAccounts(seed)),action,p,ctx);writeAccounts(result.state);setDb(result.state);setError('');notify('Receipt '+({save:'saved',post:'posted',allocate:'allocated',reverse:'reversed'}[action]||'updated'));return result}catch(e){setError(e.message);return null}}
 const can=action=>receiptAllowed(role,action);
 function open(x,t='Overview'){if(!['Overview','Allocation'].includes(t))setAccountingView(true);setSelected(x.id);setTab(t);setAlloc({});setError('');setBankView(false)}
 function edit(x){setForm({...x,amount:String(x.amount/100),allocations:x.plannedAllocations||[]})}
 function field(k,label,type='text'){return <label>{label}<input type={type} required={['date','amount'].includes(k)} step={k==='amount'?'0.01':undefined} min={k==='amount'?'0.01':undefined} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>}
 function allocationInputs(invoices,values,change){return <div className="ivScroll"><table><thead><tr><th>Invoice</th><th>Date</th><th>Invoice amount</th><th>Outstanding</th><th>Allocate ₹</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td>{i.number}</td><td>{i.date}</td><td>{money(i.totals.total)}</td><td>{money(outstanding(db,i))}</td><td><input className="receiptAmount" aria-label={'Allocate to '+i.number} type="number" min="0" step="0.01" value={values[i.id]||''} onChange={e=>change(i.id,e.target.value)}/></td></tr>)}</tbody></table>{!invoices.length&&<p>No outstanding invoices for this customer. Use Customer advance to record a prepayment.</p>}</div>}
 const header=(title,description,actions)=><div className="ivHeading receiptNoPrint"><div><h2>{title}</h2><p>{description}</p></div><div className="ivActions">{actions}</div></div>;
 const accountName=code=>db.accounts.find(a=>a.code===code)?.name||code||'Not recorded';
 function printReceipt(x){setPrintDoc(x)}
 const actionMenu=x=><details className="receiptMore"><summary aria-label={'More actions for '+x.number}><IconDotsVertical size={18}/></summary><div>{[[IconEye,'View',()=>open(x)],[IconEye,'Preview & templates',()=>setPrintDoc(x)],...(x.status==='Draft'&&can('save')?[[IconEdit,'Edit draft',()=>edit(x)]]:[]),...(x.status==='Posted'&&!x.legacy&&receiptAvailable(db,x)>0?[[IconArrowsExchange,'Allocate',()=>open(x,'Allocation')]]:[]),...(x.status==='Posted'&&can('reverse')?[[IconArrowBackUp,'Reverse',()=>{open(x);setDialog({action:'reverse',id:x.id,date:today(),reason:''})}]]:[]),[IconPrinter,'Print receipt',()=>printReceipt(x)],[IconFileDownload,'Save as PDF',()=>printReceipt(x,true)],[IconBook,'View journal',()=>{setLedgerTab('Journal Entry View');open(x,'Ledger Impact')}],[IconListDetails,'View ledger',()=>{setLedgerTab('Customer Ledger');open(x,'Ledger Impact')}],[IconHistory,'Audit history',()=>open(x,'Audit Trail')]].map(([Icon,label,fn])=><button key={label} onClick={e=>{e.currentTarget.closest('details').open=false;fn()}}><Icon size={16}/>{label}</button>)}</div></details>;
 return <section className="invoiceWorkspace receiptWorkspace">
 {error&&<div role="alert" className="ivError receiptNoPrint">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><IconX size={16}/></button></div>}
 {form?<form onSubmit={e=>{e.preventDefault();const out=run('save',form);if(out){setForm(null);open(out.result)}}}>
 {header(form.id?'Edit receipt draft':'New receipt','Record money received independently of your invoices.',<button type="button" onClick={()=>setForm(null)}><IconArrowLeft size={16}/>Back</button>)}
 <div className="ivCard"><h3>Payment details</h3><div className="ivFields"><label>Receipt number<input readOnly value={form.number||'Auto-generated on save'}/></label>{field('date','Receipt date','date')}<label>Customer<select required value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value,allocations:[]})}><option value="">Select customer</option>{customers.filter(c=>c.status!=='Inactive').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{field('amount','Received amount ₹','number')}<label>Received into account<select required value={form.bank} onChange={e=>setForm({...form,bank:e.target.value})}><option value="">Select cash / bank</option>{banks.map(a=><option key={a.code} value={a.code}>{a.name}</option>)}</select></label><label>Payment mode<select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})}>{MODES.map(m=><option key={m}>{m}</option>)}</select></label>{field('reference','Reference number')}<label>Receipt type<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="Normal">Customer payment</option><option value="Advance">Customer advance / excess payment</option></select></label><label>Attachment (PDF / JPG / PNG, up to 1 MB)<input type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1048576){setError('Attachment must be at most 1 MB.');return}const reader=new FileReader();reader.onload=()=>setForm(f=>({...f,attachment:{name:file.name,size:file.size,type:file.type,data:reader.result}}));reader.readAsDataURL(file)}}/>{form.attachment&&<span>{form.attachment.name} <button type="button" onClick={()=>setForm({...form,attachment:null})}>Remove</button></span>}</label></div><label className="receiptNotes">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div>
 <div className="ivCard"><h3>Allocate to invoices <small>Optional · leave blank to allocate later</small></h3>{allocationInputs(openInvoices(form.customerId),Object.fromEntries(form.allocations.map(a=>[a.invoiceId,a.amount])),(id,amount)=>setForm({...form,allocations:[...form.allocations.filter(a=>a.invoiceId!==id),...(Number(amount)>0?[{invoiceId:id,amount}]:[])]}))}<p>Allocated: {money(form.allocations.reduce((n,a)=>n+Math.round(Number(a.amount||0)*100),0))} · Received: {money(Math.round(Number(form.amount||0)*100))}</p>{form.kind==='Advance'&&<p>Advance funds credit the configured Customer Advance liability. Allocation transfers the applied amount to customer receivables. GST on advances requires a separate verified tax workflow.</p>}</div><footer className="ivFooter"><button type="button" onClick={()=>setForm(null)}>Cancel</button><button className="primary" type="submit">Save draft</button></footer></form>:
 bankView?<>{header('Bank receipt matching','Import incoming statement lines, create a receipt, then match and reconcile.',<button onClick={()=>setBankView(false)}><IconArrowLeft size={16}/>Receipts</button>)}<div className="ivCard"><h3>Import bank statement</h3><label>CSV file · id,date,amount,bank,reference<input type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>1048576)throw Error("CSV must be under 1 MB.");run("import-bank",{lines:parseBankCSV(await file.text())})}catch(err){setError(err.message)}e.target.value=""}}/></label><h3>Add statement line</h3><form onSubmit={e=>{e.preventDefault();if(run('import-bank',{lines:[bankForm]}))setBankForm({...bankForm,id:'',amount:'',reference:''})}}><div className="ivFields">{['id','date','amount','reference'].map(k=><label key={k}>{{id:'Unique bank transaction ID',date:'Date',amount:'Incoming amount ₹',reference:'Reference'}[k]}<input required={k!=='reference'} type={k==='date'?'date':'text'} value={bankForm[k]} onChange={e=>setBankForm({...bankForm,[k]:e.target.value})}/></label>)}<label>Bank account<select required value={bankForm.bank} onChange={e=>setBankForm({...bankForm,bank:e.target.value})}><option value="">Select bank</option>{banks.map(a=><option key={a.code} value={a.code}>{a.name}</option>)}</select></label></div><p><button className="primary"><IconUpload size={16}/>Import statement line</button></p></form><p>Local statement-line import. Live bank feeds and payment gateways are not connected.</p><div className="ivScroll"><table><thead><tr><th>Transaction</th><th>Date</th><th>Account</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{(db.receiptBankLines||[]).map(b=><tr key={b.id}><td>{b.id}<small>{b.reference}</small></td><td>{b.date}</td><td>{accountName(b.bank)}</td><td>{money(b.amount)}</td><td>{b.status}</td><td><button disabled={rows.some(r=>r.bankLineId===b.id&&r.status!=='Cancelled'&&r.status!=='Reversed')} onClick={()=>create(null,b)}>Create unallocated receipt</button></td></tr>)}</tbody></table></div></div></>:
 r?<>{header(r.number,r.customerName,<><button onClick={()=>setPrintDoc(r)}><IconEye size={16}/>Print preview</button><button onClick={()=>setSelected(null)}><IconArrowLeft size={16}/>Receipts</button>{r.status==='Draft'&&<><button onClick={()=>edit(r)}><IconEdit size={16}/>Edit draft</button><button className="primary" onClick={()=>run('submit',{id:r.id})}>Submit</button></>}{r.status==='Submitted'&&<button disabled={!can('approve')} className="primary" onClick={()=>run('approve',{id:r.id})}>Approve</button>}{r.status==='Approved'&&<button disabled={!can('post')} title={!can('post')?'Finance Manager or Admin required':undefined} className="primary" onClick={()=>run('post',{id:r.id})}>Post receipt</button>}{!r.posted&&r.status!=='Cancelled'&&<button onClick={()=>setDialog({id:r.id,action:'cancel',reason:''})}>Cancel receipt</button>}{actionMenu(r)}</>)}<div className="receiptPrintHeader"><h2>Wayvida Books · Customer Receipt</h2><h3>{r.number} · {r.customerName}</h3><p>{r.date} · {money(r.amount)} · {r.status}</p></div>
 <div className="ivSummary"><span>Received<strong>{money(r.amount)}</strong></span><span>Available to allocate<strong>{money(receiptAvailable(db,r))}</strong></span><span>Status<strong>{r.status}</strong></span><span>Allocation<strong>{allocationStatus(db,r)}</strong></span></div><div className="receiptContext"><span>Receipt date<strong>{r.date}</strong></span><span>Payment mode<strong>{r.mode}</strong></span><span>Received into<strong>{accountName(r.bank)}</strong></span></div><div className="receiptViewSwitch receiptNoPrint"><label><input type="checkbox" checked={accountingView} onChange={e=>{setAccountingView(e.target.checked);if(!e.target.checked)setTab('Overview')}}/>Show accounting details</label></div><div className="ivTabs receiptNoPrint">{tabs.filter(t=>accountingView||['Overview','Allocation'].includes(t)).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 <div className="ivCard">
 {tab==='Overview'?<><div className="ivFields">{[['Receipt date',r.date],['Payment mode',r.mode],['Received account',accountName(r.bank)],['Reference',r.reference],['Type',r.kind==='Advance'?'Customer advance':'Customer payment'],['Created by',r.createdBy],['Customer email',customers.find(c=>c.id===r.customerId)?.email],['Notes',r.notes],['Reconciliation',r.reconciliation||'Unmatched']].map(([k,v])=><div key={k}><small>{k}</small><p>{v||'Not recorded'}</p></div>)}</div>{r.attachment&&<a download={r.attachment.name} href={r.attachment.data}>Download {r.attachment.name}</a>}{r.status==='Posted'&&<div className="receiptNoPrint"><h3>Bank matching</h3>{receiptBankSuggestions(db,r).map(b=><div className="receiptSuggestion" key={b.id}><div><strong>{b.id} · {money(b.available)}</strong><small>{b.reason} · {b.date}</small></div><button onClick={()=>setMatch({bankLineId:b.id,amount:String(b.suggestedAmount/100)})}>Use suggestion</button></div>)}{(db.receiptBankLines||[]).some(b=>b.bank===r.bank)?<><p>Select an incoming bank transaction and confirm the amount. Matching does not post another journal.</p><div className="ivTools"><select aria-label="Bank transaction" value={match.bankLineId} onChange={e=>setMatch({...match,bankLineId:e.target.value})}><option value="">Select imported transaction</option>{(db.receiptBankLines||[]).filter(b=>b.bank===r.bank).map(b=><option key={b.id} value={b.id}>{b.date} · {b.reference||b.id} · {money(b.amount)}</option>)}</select><input aria-label="Match amount" placeholder="Match amount ₹" value={match.amount} onChange={e=>setMatch({...match,amount:e.target.value})}/><button disabled={!match.bankLineId||!Number(match.amount)} onClick={()=>run('match',{id:r.id,...match})}>Confirm match</button><button disabled={!can('reconcile')||r.reconciliation!=='Matched'} onClick={()=>run('reconcile',{id:r.id})}>Reconcile</button><button disabled={!can('unmatch')||(r.reconciliation||'Unmatched')==='Unmatched'} onClick={()=>setDialog({id:r.id,action:'unmatch',reason:''})}>Remove matches</button></div></>:<div className="receiptBankEmpty"><IconArrowsExchange size={22}/><div><strong>No imported incoming transactions for this bank account</strong><p>Import the bank statement first. Then return to this receipt to select and confirm the matching transaction.</p><button onClick={()=>setBankView(true)}><IconUpload size={16}/>Import bank transaction</button></div></div>}{(db.receiptMatches||[]).filter(m=>m.receiptId===r.id&&!m.voided).map(m=><p key={m.id}>{m.bankLineId} · {money(m.amount)} · {m.reconciled?'Reconciled':'Matched'}</p>)}</div>}</>:
 tab==='Allocation'?<><h3>Allocation history</h3><div className="ivScroll"><table><thead><tr><th>Invoice</th><th>Invoice date</th><th>Invoice amount</th><th>Allocated</th><th>Remaining balance</th><th>Status</th></tr></thead><tbody>{receiptAllocations(db,r).map(a=>{const i=db.invoices.find(i=>i.id===a.invoiceId);return <tr key={a.id}><td><button className="ivLink" onClick={()=>{sessionStorage.setItem('wayvida-open-invoice',a.invoiceId);onNavigate('Invoices')}}>{i?.number||'Missing invoice'}</button></td><td>{i?.date}</td><td>{money(i?.totals.total)}</td><td>{money(a.amount)}</td><td>{i?money(outstanding(db,i)):'—'}</td><td>{a.voided?'Voided':'Applied'}</td></tr>})}</tbody></table></div>{r.status==='Posted'&&!r.legacy&&receiptAvailable(db,r)>0&&<div className="receiptNoPrint"><h3>Allocate available funds</h3><label>Allocation date<input type="date" value={allocDate} onChange={e=>setAllocDate(e.target.value)}/></label>{allocationInputs(openInvoices(r.customerId),alloc,(id,amount)=>setAlloc({...alloc,[id]:amount}))}<button className="primary" onClick={()=>{if(run('allocate',{id:r.id,date:allocDate,token:crypto.randomUUID(),allocations:Object.entries(alloc).filter(([,v])=>Number(v)>0).map(([invoiceId,amount])=>({invoiceId,amount}))}))setAlloc({})}}>Apply allocation</button></div>}</>:
 tab==='Accounting Impact'?<AccountingImpact db={db} receipt={r} context={ctx}/> :
 tab==='Ledger Impact'?<ReceiptImpact key={r.id+ledgerTab} db={db} receipt={r} initialTab={ledgerTab} onNavigate={onNavigate}/> :
 <><div className="ivFields">{[['Created',r.createdAt,r.createdBy],['Modified',r.modifiedAt,r.modifiedBy],['Submitted',r.submittedAt,r.submittedBy],['Cancelled',r.cancelledAt,r.cancelledBy],['Approved',r.approvedAt,r.approvedBy],['Posted',r.postedAt,r.postedBy],['Reversed',r.reversedAt,r.reversedBy]].map(([label,at,by])=><div key={label}><small>{label}</small><p>{by||'Not recorded'}<small>{at||'Not recorded'}</small></p></div>)}</div>{db.audit.filter(a=>a.receiptId===r.id||(a.journalId&&a.journalId===r.journalId)).map(a=><p key={a.id}>{a.action} · {a.at} · {a.by}{a.reason?' · '+a.reason:''}</p>)}</>}
 </div></>:
 <>{header('Customer receipts','Record, allocate and reconcile customer payments.',<><button onClick={()=>setBankView(true)}><IconArrowsExchange size={16}/>Bank matching</button><button onClick={()=>setSettings({threshold:String((db.config.receipts?.threshold??5000000)/100),advanceAccount:db.config.receipts?.advanceAccount||'',closedThrough:db.config.receipts?.closedThrough||''})}><IconSettings size={16}/>Settings</button><button className="primary" onClick={()=>create()}><IconPlus size={16}/>New receipt</button></>)}<div className="ivSummary"><span>Posted receipts<strong>{rows.filter(x=>x.status==='Posted').length}</strong></span><span>Money received<strong>{money(rows.filter(x=>x.status==='Posted').reduce((n,x)=>n+x.amount,0))}</strong></span><span>Unallocated / advance<strong>{money(rows.filter(x=>x.status==='Posted').reduce((n,x)=>n+receiptAvailable(db,x),0))}</strong></span><span>Awaiting approval<strong>{rows.filter(x=>x.status==='Submitted').length}</strong></span></div><div className="ivCard"><div className="ivTools"><input aria-label="Search receipts" placeholder="Search receipt, customer or reference" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Receipt status" value={status} onChange={e=>setStatus(e.target.value)}>{['All','Draft','Submitted','Approved','Posted','Cancelled','Reversed'].map(s=><option key={s}>{s}</option>)}</select></div><div className="ivScroll"><table><thead><tr>{['Receipt number','Date','Customer','Amount','Payment mode','Received account','Allocation','Status','Created by','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.filter(x=>(status==='All'||x.status===status)&&(x.number+' '+x.customerName+' '+x.reference).toLowerCase().includes(query.toLowerCase())).map(x=><tr key={x.id}><td><button className="ivLink" onClick={()=>open(x)}>{x.number}</button></td><td>{x.date}</td><td>{x.customerName}</td><td>{money(x.amount)}</td><td>{x.mode}</td><td>{accountName(x.bank)}</td><td>{allocationStatus(db,x)}</td><td><span className={'receiptStatus '+x.status}>{x.status}</span></td><td>{x.createdBy}</td><td>{actionMenu(x)}</td></tr>)}</tbody></table>{!rows.length&&<div className="ivEmpty"><h3>No receipts yet</h3><p>Record a payment or customer advance to get started.</p><button className="primary" onClick={()=>create()}>New receipt</button></div>}</div></div></>}
 <div className="receiptRole receiptNoPrint"><label>Receipt role — local simulation<select value={role} onChange={e=>setRole(e.target.value)}>{RECEIPT_ROLES.map(v=><option key={v}>{v}</option>)}</select></label><small>Accountant: create and allocate. Finance Manager: approve and post. Admin: reverse and configure. Local simulation only; production requires authenticated server permissions.</small></div>
 {dialog&&<div className="ivOverlay"><form className="ivModal" role="dialog" aria-modal="true" aria-label="Confirm receipt action" onSubmit={e=>{e.preventDefault();if(run(dialog.action,dialog))setDialog(null)}}><h2>{dialog.action==='reverse'?'Reverse receipt':dialog.action==='unmatch'?'Remove bank matches':'Cancel receipt'}</h2><p>Original records remain in the audit history. Reversal also voids invoice allocations.</p>{dialog.action==='reverse'&&<label>Reversal date<input required type="date" value={dialog.date} onChange={e=>setDialog({...dialog,date:e.target.value})}/></label>}<label>Reason<textarea required value={dialog.reason} onChange={e=>setDialog({...dialog,reason:e.target.value})}/></label>{error&&<p role="alert">{error}</p>}<div className="ivActions"><button type="button" onClick={()=>setDialog(null)}>Go back</button><button className="primary">Confirm</button></div></form></div>}
 {settings&&<div className="ivOverlay"><form className="ivModal" role="dialog" aria-modal="true" aria-label="Receipt settings" onSubmit={e=>{e.preventDefault();if(run('settings',settings))setSettings(null)}}><h2>Receipt settings</h2><label>Manager approval threshold ₹<input required type="number" min="0" step="0.01" value={settings.threshold} onChange={e=>setSettings({...settings,threshold:e.target.value})}/></label><p>Amounts below this value are automatically approved on submission. Amounts at or above it need manager approval.</p><label>Customer advance liability account<select value={settings.advanceAccount} onChange={e=>setSettings({...settings,advanceAccount:e.target.value})}><option value="">Not configured</option>{db.accounts.filter(a=>a.type==='Liabilities'&&a.active&&!a.isGroup).map(a=><option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select></label><label>Receipts closed through<input type="date" value={settings.closedThrough} onChange={e=>setSettings({...settings,closedThrough:e.target.value})}/></label><p>Applies to receipt posting, allocation and reversal dates. Does not change other modules’ period controls.</p>{error&&<p role="alert">{error}</p>}<div className="ivActions"><button type="button" onClick={()=>setSettings(null)}>Cancel</button><button disabled={!can('settings')} className="primary">Save settings</button></div></form></div>}
 {printDoc&&<DocumentPreview kind="Receipt" initialMode={printDoc.__builder?'builder':'preview'} doc={printDoc} db={db} onClose={()=>setPrintDoc(null)}/>}
 </section>;
}
