import {minor,account,journal,outstanding,today,ledger} from './invoice-engine.js';
export const MODES=['Bank Transfer','UPI','Cheque','Cash','Card','Other'];
export const RECEIPT_ROLES=['Accountant','Finance Manager','Admin'];
const permissions={Accountant:['save','submit','allocate','cancel','import-bank','match'],'Finance Manager':['save','submit','allocate','cancel','import-bank','match','approve','post','reconcile'],Admin:['save','submit','allocate','cancel','import-bank','match','approve','post','reconcile','reverse','unmatch','settings']};
export const receiptAllowed=(role,action)=>(permissions[role]||[]).includes(action);
const copy=x=>JSON.parse(JSON.stringify(x)),sum=(a,k)=>a.reduce((n,x)=>n+(x[k]||0),0);
const validDate=d=>/^\d{4}-\d{2}-\d{2}$/.test(d)&&!isNaN(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d;
function period(s,date){if(!validDate(date))throw Error('Enter a valid accounting date.');if(s.config.receipts?.closedThrough&&date<=s.config.receipts.closedThrough)throw Error('This accounting period is closed. Choose an open date.');}
export function receiptRows(s){return [...(s.receipts||[]),...s.payments.filter(p=>!(s.receipts||[]).some(r=>r.id===p.id)).map(p=>({...p,legacy:true,status:p.reversed?'Reversed':'Posted',posted:true,kind:'Normal',mode:p.mode||'Not recorded',customerName:s.invoices.find(i=>i.id===p.invoiceId)?.customerName||'Unknown customer',arAccount:s.invoices.find(i=>i.id===p.invoiceId)?.arAccount,createdBy:s.journals.find(j=>j.id===p.journalId)?.createdBy||'Not recorded',reconciliation:'Unmatched'}))];}
export function receiptAllocations(s,r){return r.legacy?[{id:r.id,receiptId:r.id,invoiceId:r.invoiceId,amount:r.amount,date:r.date,voided:r.status==='Reversed'}]:(s.receiptAllocations||[]).filter(a=>a.receiptId===r.id);}
export function receiptAvailable(s,r){return r.status==='Reversed'?0:r.amount-sum(receiptAllocations(s,r).filter(a=>!a.voided),'amount');}
export function allocationStatus(s,r){const used=sum(receiptAllocations(s,r).filter(a=>!a.voided),'amount');return r.status==='Reversed'?'Voided':used===r.amount?'Fully allocated':used?'Partially allocated':r.kind==='Advance'?'Customer advance':'Unallocated';}
export function receiptCustomerLedger(s,id){const codes=new Set([...s.invoices.filter(i=>i.customerId===id).map(i=>i.arAccount),...receiptRows(s).filter(r=>r.customerId===id).flatMap(r=>[r.arAccount,r.advanceAccount])].filter(Boolean));let balance=0;return ledger(s).filter(l=>l.customerId===id&&codes.has(l.account)).map(l=>({...l,balance:balance+=l.debit-l.credit}));}
function bankAccount(s,code){const a=s.accounts.find(a=>a.code===code);if(!a||!(/bank|cash/i.test(a.name)||['Bank','Cash'].includes(a.subType)))throw Error('Select a cash or bank account.');return account(s,code,['Assets']);}
function addJournal(s,r,source,lines,date,token){const j=journal(s,{...r,id:undefined},source,lines,date,token);Object.assign(j,{receiptId:r.id,sourceId:r.id,reference:r.number,customerId:r.customerId,companyId:r.companyId});return j;}
function audit(s,r,action,ctx,now,extra={}){s.audit.push({id:crypto.randomUUID(),receiptId:r?.id,action:'receipt-'+action,at:now,by:ctx.actor||'Local user',...extra});}
function validateAllocations(s,r,rows,date){period(s,date);if(date<r.date)throw Error('Allocation date cannot precede the receipt.');const seen=new Set();const parsed=(rows||[]).map(a=>{const i=s.invoices.find(i=>i.id===a.invoiceId);if(!i||!i.posted||i.status==='Cancelled'||i.customerId!==r.customerId)throw Error('Choose posted invoices belonging to this customer.');if(date<i.date)throw Error('Allocation cannot precede an invoice.');if(i.arAccount!==r.arAccount)throw Error('Invoice receivable mapping differs from this receipt. Review the customer mapping.');if(seen.has(i.id))throw Error('Select each invoice once.');seen.add(i.id);const amount=minor(a.amount);if(!amount||amount>outstanding(s,i))throw Error('Allocation exceeds the invoice outstanding balance.');return {invoiceId:i.id,amount};});if(sum(parsed,'amount')>receiptAvailable(s,r))throw Error('Allocations exceed the available receipt amount.');return parsed;}
function allocate(s,r,rows,date,token,ctx){if(s.receiptAllocations.some(a=>a.token===token)){if(s.receiptAllocations.some(a=>a.token===token&&a.receiptId!==r.id))throw Error('Allocation request belongs to another receipt.');return;}if(!token)throw Error('Allocation request ID is required.');const parsed=validateAllocations(s,r,rows,date);if(!parsed.length)throw Error('Enter an allocation amount.');let j;if(r.kind==='Advance')j=addJournal(s,r,'Advance Allocation',[{account:account(s,r.advanceAccount,['Liabilities']),debit:sum(parsed,'amount'),credit:0},{account:account(s,r.arAccount,['Assets']),debit:0,credit:sum(parsed,'amount')}],date,'receipt-allocation:'+token);for(const a of parsed)s.receiptAllocations.push({...a,id:crypto.randomUUID(),receiptId:r.id,date,token,journalId:j?.id,createdBy:ctx.actor,createdAt:new Date().toISOString()});}
export function receiptCommand(state,action,payload={},ctx={}){
 // Explicit roles are enforced at the command boundary, not just by buttons.
 // Role-less trusted adapters retain their existing contract; this is not authentication.
 if(ctx.role){if(!receiptAllowed(ctx.role,action))throw Error('Your receipt role cannot perform this action. Ask a finance manager or admin.');ctx={...ctx,canApprove:['Finance Manager','Admin'].includes(ctx.role)};}
 const s=copy(state),p=copy(payload),now=new Date().toISOString();s.receipts||=[];s.receiptAllocations||=[];s.receiptBankLines||=[];s.receiptMatches||=[];s.receiptRequests||=[];let r=s.receipts.find(r=>r.id===p.id);
 if(action==='settings'){if(!ctx.canApprove)throw Error('Manager approval is required for receipt settings.');const threshold=minor(p.threshold);if(p.closedThrough&&!validDate(p.closedThrough))throw Error('Invalid period lock date.');if(p.advanceAccount)account(s,p.advanceAccount,['Liabilities']);s.config.receipts={threshold,closedThrough:p.closedThrough||'',advanceAccount:p.advanceAccount||''};audit(s,null,action,ctx,now);return {state:s,result:s.config.receipts};}
 if(action==='import-bank'){const seen=new Set(s.receiptBankLines.map(b=>b.id));for(const b of p.lines||[]){if(!b.id||seen.has(b.id))throw Error('Bank transaction ID is missing or duplicated.');seen.add(b.id);period(s,b.date);bankAccount(s,b.bank);const amount=minor(b.amount);if(!amount)throw Error('Bank receipt amount must be positive.');s.receiptBankLines.push({...b,amount,status:'Unmatched',importedAt:now});}audit(s,null,action,ctx,now);return {state:s,result:null};}
 if(action==='save'){
  if(r&&(r.status!=='Draft'||p.revision!==r.revision))throw Error('Only the latest draft can be edited.');period(s,p.date);const c=(ctx.customers||[]).find(c=>c.id===p.customerId);if(!c||c.status==='Inactive'||c.active===false)throw Error('Select an active customer.');const amount=minor(p.amount);if(!amount)throw Error('Received amount must be positive.');bankAccount(s,p.bank);if(!MODES.includes(p.mode))throw Error('Select a payment mode.');if(!['Normal','Advance'].includes(p.kind))throw Error('Select a receipt type.');if(p.attachment&&(!['application/pdf','image/png','image/jpeg'].includes(p.attachment.type)||p.attachment.size>1048576||!/^data:(application\/pdf|image\/(png|jpeg));base64,[A-Za-z0-9+/=]+$/.test(p.attachment.data||'')))throw Error('Attach a PDF, PNG or JPEG up to 1 MB.');
  let n=1;while(receiptRows(s).some(x=>x.number===`RCPT-${String(n).padStart(5,'0')}`))n++;const number=r?.number||p.number?.trim()||`RCPT-${String(n).padStart(5,'0')}`;if(receiptRows(s).some(x=>x.id!==p.id&&x.number.toLowerCase()===number.toLowerCase()))throw Error('Receipt number already exists.');
  if(p.bankLineId){const b=s.receiptBankLines.find(b=>b.id===p.bankLineId);if(!b||b.bank!==p.bank||amount>b.amount||s.receipts.some(x=>x.id!==p.id&&x.bankLineId===p.bankLineId&&!['Cancelled','Reversed'].includes(x.status)))throw Error('Bank line is missing, already linked or does not match this receipt.');}
  const arAccount=account(s,c.account||s.config.ar,['Assets']);const old=r;r={id:r?.id||crypto.randomUUID(),number,date:p.date,customerId:c.id,customerName:c.name,amount,bank:p.bank,mode:p.mode,reference:p.reference||'',notes:p.notes||'',attachment:p.attachment||null,kind:p.kind,arAccount,advanceAccount:s.config.receipts?.advanceAccount||'',branch:c.branch||c.branchId||s.config.branch,companyId:c.companyId,revision:(r?.revision||0)+1,status:'Draft',posted:false,createdAt:r?.createdAt||now,createdBy:r?.createdBy||ctx.actor||'Local user',modifiedAt:now,modifiedBy:ctx.actor||'Local user',plannedAllocations:p.allocations||[],reconciliation:'Unmatched',bankLineId:p.bankLineId||null,customerType:c.type||'Business',branchId:p.branchId||r?.branchId||c.branch||c.branchId||s.config.branch||'',branchName:p.branchName||r?.branchName||c.branch||'',organizationId:p.organizationId||r?.organizationId||c.companyId||'',organizationName:p.organizationName||r?.organizationName||''};validateAllocations(s,r,r.plannedAllocations,p.date);s.receipts=old?s.receipts.map(x=>x.id===r.id?r:x):[...s.receipts,r];
 }else{
  if(!r){const legacy=receiptRows(s).find(x=>x.id===p.id);if(!legacy)throw Error('Receipt not found.');r=copy(legacy);s.receipts.push(r);}
  if(action==='submit'){if(r.status!=='Draft')throw Error('Only drafts can be submitted.');r.status=r.amount<(s.config.receipts?.threshold??5000000)?'Approved':'Submitted';if(r.status==='Approved')Object.assign(r,{approvedBy:'Automatic threshold rule',approvedAt:now});}
  else if(action==='approve'){if(!ctx.canApprove||r.status!=='Submitted')throw Error('A manager must approve a submitted receipt.');Object.assign(r,{status:'Approved',approvedBy:ctx.actor,approvedAt:now});}
  else if(action==='post'){
   if(r.posted)return {state:s,result:r};if(r.status!=='Approved')throw Error('Approve the receipt before posting.');period(s,r.date);bankAccount(s,r.bank);account(s,r.arAccount,['Assets']);validateAllocations(s,r,r.plannedAllocations,r.date);
   if(r.kind==='Normal'){const due=sum(s.invoices.filter(i=>i.posted&&i.status!=='Cancelled'&&i.customerId===r.customerId).map(i=>({amount:outstanding(s,i)})),'amount');const unallocated=receiptRows(s).filter(x=>x.id!==r.id&&x.customerId===r.customerId&&x.kind==='Normal'&&x.status==='Posted').reduce((n,x)=>n+receiptAvailable(s,x),0);if(r.amount>due-unallocated)throw Error('Receipt exceeds customer outstanding. Use Customer advance for excess or prepayments.');}
   const credit=r.kind==='Advance'?account(s,r.advanceAccount,['Liabilities']):r.arAccount;if(credit===r.bank)throw Error('Bank and receivable accounts must differ.');const j=addJournal(s,r,'Customer Receipt',[{account:r.bank,debit:r.amount,credit:0},{account:credit,debit:0,credit:r.amount}],r.date,'receipt:'+r.id);Object.assign(r,{status:'Posted',posted:true,journalId:j.id,postedBy:ctx.actor,postedAt:now});if(r.plannedAllocations.length)allocate(s,r,r.plannedAllocations,r.date,'initial:'+r.id,ctx);
  }else if(action==='allocate'){if(r.status!=='Posted'||r.legacy)throw Error('Only posted receipts with available funds can be allocated.');allocate(s,r,p.allocations,p.date,p.token,ctx);}
  else if(action==='cancel'){if(r.posted)throw Error('Posted receipts must be reversed, not cancelled.');if(!p.reason?.trim())throw Error('Enter a cancellation reason.');r.status='Cancelled';r.reason=p.reason;}
  else if(action==='reverse'){
   if(r.status==='Reversed')return {state:s,result:r};if(r.status!=='Posted'||!ctx.canApprove)throw Error('A manager must reverse a posted receipt.');if(!p.reason?.trim())throw Error('Enter a reversal reason.');period(s,p.date);const allocations=receiptAllocations(s,r);if(p.date<r.date||allocations.some(a=>a.date>p.date))throw Error('Reversal cannot precede receipt or allocation dates.');if(s.receiptMatches.some(m=>m.receiptId===r.id&&!m.voided))throw Error('Remove the bank match before reversing.');const ids=new Set([r.journalId,...allocations.map(a=>a.journalId).filter(Boolean)]);for(const id of ids){const j=s.journals.find(j=>j.id===id);if(!j)throw Error('Original journal is missing.');const reverse=addJournal(s,r,id===r.journalId?'Receipt Reversal':'Advance Allocation Reversal',j.lines.map(l=>({...l,debit:l.credit,credit:l.debit})),p.date,'receipt-reverse:'+r.id+':'+id);reverse.reversalOf=id;}
   s.receiptAllocations.filter(a=>a.receiptId===r.id).forEach(a=>Object.assign(a,{voided:true,voidedAt:now}));if(r.legacy){const legacy=s.payments.find(x=>x.id===r.id);legacy.reversed=true;legacy.reversedAt=now;}Object.assign(r,{status:'Reversed',reversedAt:now,reversedBy:ctx.actor,reason:p.reason});
  }else if(action==='match'){
   if(r.status!=='Posted')throw Error('Only posted receipts can be matched.');const b=s.receiptBankLines.find(b=>b.id===p.bankLineId);if(!b||b.bank!==r.bank)throw Error('Select a transaction for the received bank account.');const amount=minor(p.amount);if(!amount||amount>b.amount-sum(s.receiptMatches.filter(m=>m.bankLineId===b.id&&!m.voided),'amount')||amount>r.amount-sum(s.receiptMatches.filter(m=>m.receiptId===r.id&&!m.voided),'amount'))throw Error('Match exceeds the available bank or receipt amount.');s.receiptMatches.push({id:crypto.randomUUID(),receiptId:r.id,bankLineId:b.id,amount,at:now,by:ctx.actor});r.reconciliation=sum(s.receiptMatches.filter(m=>m.receiptId===r.id&&!m.voided),'amount')===r.amount?'Matched':'Partially Matched';b.status=sum(s.receiptMatches.filter(m=>m.bankLineId===b.id&&!m.voided),'amount')===b.amount?'Matched':'Partially Matched';
  }else if(action==='reconcile'){if(!ctx.canApprove||r.reconciliation!=='Matched')throw Error('A manager can reconcile a fully matched receipt.');r.reconciliation='Reconciled';s.receiptMatches.filter(m=>m.receiptId===r.id&&!m.voided).forEach(m=>{m.reconciled=true;const b=s.receiptBankLines.find(b=>b.id===m.bankLineId);if(b&&sum(s.receiptMatches.filter(x=>x.bankLineId===b.id&&!x.voided&&x.reconciled),'amount')===b.amount)b.status='Reconciled'});}
  else if(action==='unmatch'){if(!ctx.canApprove||!p.reason?.trim())throw Error('A manager and reason are required to remove matches.');s.receiptMatches.filter(m=>m.receiptId===r.id&&!m.voided).forEach(m=>{m.voided=true;const b=s.receiptBankLines.find(b=>b.id===m.bankLineId);if(b){const used=sum(s.receiptMatches.filter(x=>x.bankLineId===b.id&&!x.voided),'amount');b.status=used===0?'Unmatched':used===b.amount?'Matched':'Partially Matched'}});r.reconciliation='Unmatched';}
  else throw Error('Unknown receipt action.');
 }
 const before=receiptRows(state).find(x=>x.id===r.id);
 Object.assign(r,{modifiedAt:now,modifiedBy:ctx.actor||'Local user'});
 if(action==='submit')Object.assign(r,{submittedAt:now,submittedBy:ctx.actor||'Local user'});
 if(action==='cancel')Object.assign(r,{cancelledAt:now,cancelledBy:ctx.actor||'Local user'});
 const oldJournals=new Set(state.journals.map(j=>j.id));
 for(const j of s.journals)if(!oldJournals.has(j.id))j.createdBy=ctx.actor||'Local user';
 audit(s,r,action,ctx,now,{reason:p.reason||'',journalId:r.journalId,fromStatus:before?.status||null,toStatus:r.status,snapshot:action==='save'?copy(r):undefined});return {state:s,result:r};
}
