import {useState,useEffect,useRef} from 'react';
import {createPortal} from 'react-dom';
import {IconDotsVertical,IconX,IconFileInvoice,IconEye,IconCircleCheck,IconCircleX,IconShare,IconPrinter} from '@tabler/icons-react';
import './sales-order-actions.css';
import {KEY,initial,seedAccounts,command} from './invoice-engine.js';
const cash=n=>Number(n||0).toLocaleString('en-IN',{style:'currency',currency:'INR'});
export default function SalesOrderActions({order,onUpdate,notify,accounts,onNavigate,onPreview}){
 const [menu,setMenu]=useState(null),[confirm,setConfirm]=useState(null),[shareText,setShareText]=useState('');const root=useRef(null),trigger=useRef(null);
 useEffect(()=>{if(!menu)return;const close=e=>{if(!root.current?.contains(e.target)&&!trigger.current?.contains(e.target))setMenu(null)};const escape=e=>{if(e.key==='Escape'){setMenu(null);trigger.current?.focus()}};window.addEventListener('pointerdown',close);window.addEventListener('keydown',escape);window.addEventListener('resize',close);return()=>{window.removeEventListener('pointerdown',close);window.removeEventListener('keydown',escape);window.removeEventListener('resize',close)}},[menu]);
 function convert(){setMenu(null);try{const state=seedAccounts(JSON.parse(localStorage.getItem(KEY))||initial(),accounts);const output=convertSalesOrder(state,order);localStorage.setItem(KEY,JSON.stringify(output.state));const invoice=output.result;onUpdate({...order,invoice:{id:invoice.id,number:invoice.number}});sessionStorage.setItem('wayvida-open-invoice',invoice.id);onNavigate('Invoices');notify('Invoice draft opened. Accounting starts only when it is posted.')}catch(e){notify(e.message)}}
 async function share(){setMenu(null);const text=`Wayvida Books — Sales Order ${order.number}\nCustomer: ${order.customerName}\nDate: ${order.date}\nStatus: ${order.status}\nTotal: ${cash(order.total)}\n${order.lines.map(l=>`${l.description} · ${l.qty} × ${cash(l.rate)}`).join('\n')}`;try{if(navigator.share){await navigator.share({title:order.number,text});return}await navigator.clipboard.writeText(text);notify('Order summary copied for sharing')}catch(e){if(e.name!=='AbortError')setShareText(text)}}
 return <><button ref={trigger} type="button" className="soMoreButton" aria-label={'More actions for '+order.number} aria-haspopup="menu" aria-expanded={!!menu} onClick={()=>{const r=trigger.current.getBoundingClientRect();setMenu(menu?null:{top:Math.max(8,Math.min(r.bottom+5,window.innerHeight-250)),left:Math.max(8,Math.min(r.right-210,window.innerWidth-218))})}}><IconDotsVertical size={18}/></button>{menu&&createPortal(<div ref={root} className="soActionMenu" role="menu" style={menu}><button role="menuitem" disabled={!order.invoice&&order.status==='Cancelled'} onClick={convert}>{order.invoice?<IconEye size={17} aria-hidden="true"/>:<IconFileInvoice size={17} aria-hidden="true"/>}<span>{order.invoice?'Show Invoice':'Convert to Invoice'}</span></button><button role="menuitem" disabled={['Completed','Cancelled'].includes(order.status)} onClick={()=>{setMenu(null);setConfirm('Completed')}}><IconCircleCheck size={17} aria-hidden="true"/><span>Complete Order</span></button><button role="menuitem" disabled={['Completed','Cancelled'].includes(order.status)} onClick={()=>{setMenu(null);setConfirm('Cancelled')}}><IconCircleX size={17} aria-hidden="true"/><span>Cancel Order</span></button><button role="menuitem" onClick={share}><IconShare size={17} aria-hidden="true"/><span>Share</span></button><button role="menuitem" onClick={()=>{setMenu(null);onPreview()}}><IconPrinter size={17} aria-hidden="true"/><span>Print</span></button></div>,window.document.body)}{confirm&&createPortal(<div className="soActionOverlay"><div className="soConfirm" role="dialog" aria-modal="true" aria-label="Update order status"><h2>{confirm==='Completed'?'Complete':'Cancel'} {order.number}?</h2><p>{confirm==='Completed'?'Mark this order as fulfilled.':'This order will remain in the grid with Cancelled status.'}{order.invoice?' Its linked invoice will remain unchanged.':''}</p><footer><button onClick={()=>setConfirm(null)}>Go back</button><button className="primary" onClick={()=>{if(onUpdate({...order,status:confirm})){setConfirm(null);notify('Order '+confirm.toLowerCase())}}}>Confirm</button></footer></div></div>,window.document.body)}{shareText&&createPortal(<div className="soActionOverlay"><div className="soConfirm" role="dialog" aria-modal="true" aria-label="Share order"><h2>Share order summary</h2><p>Copy this summary into your preferred app.</p><textarea readOnly value={shareText} onFocus={e=>e.target.select()}/><button onClick={()=>setShareText('')}>Close</button></div></div>,window.document.body)}</>;
}
import {convertSalesOrder} from './sales-order-service.js';
