import {IconPlus,IconTrash} from '@tabler/icons-react';
import {ItemSearch,TaxSelection} from './InvoiceLineControls.jsx';
import {calculate,money} from './invoice-engine.js';
import {customerStates} from './Customers.jsx';
import './sales-document-tax.css';
export const blankDocumentLine=()=>({description:'',qty:'1',unit:'pcs',rate:'0',discount:'0',discountType:'%',tax:'18',cess:'0',income:'',priceTaxMode:'exclusive'});
export const due=(date,days)=>{const d=new Date(date+'T12:00:00Z');if(Number.isNaN(d.getTime()))return '';d.setUTCDate(d.getUTCDate()+Number(days));return d.toISOString().slice(0,10)};
export default function SalesDocumentFields({form,setForm,customers,items,config,kind='invoice'}){
 const blankLine=blankDocumentLine;
 function chooseCustomer(id){const c=customers.find(x=>x.id===id);setForm({...form,customerId:id,customerName:c?.name||'',billing:c?.billing||'',shipping:c?.shipping||'',place:c?.state||'',terms:c?.days||'30',dueDate:due(form.date,c?.days||30)})}
 const field=(name,label,type='text')=><label>{label}<input type={type} value={form[name]||''} onChange={e=>setForm({...form,[name]:e.target.value,...(name==='date'&&e.target.value?{dueDate:due(e.target.value,form.terms)}:{})})}/></label>;
 const updateLine=(index,key,value)=>setForm({...form,lines:form.lines.map((l,n)=>n===index?{...l,[key]:value}:l)});
 const itemDefaults=item=>{const rate=item.taxApplicable===false?0:Number(item.taxRate??18),cess=Number(item.cessRate||0),intra=form.place.trim().toLowerCase()===config.state.trim().toLowerCase();return {item:item.id,description:item.name,unit:item.unit,rate:item.price||'0',income:item.salesAccount||'',priceTaxMode:item.priceTaxMode||'exclusive',taxes:intra?{cgst:rate/2,sgst:rate/2,igst:0,cess}:{cgst:0,sgst:0,igst:rate,cess}}};
 let preview,previewError;try{preview=calculate(form,config)}catch(e){previewError=e.message}
 const totals=t=><dl className="ivTotals">{[['Subtotal',t.subtotal],['Discount',t.discount],['Taxable amount',t.taxable],...(t.intra?[['CGST',t.cgst],['SGST',t.sgst]]:[['IGST',t.igst]]),...(t.cess?[['Cess',t.cess]]:[]),['Tax',t.cgst+t.sgst+t.igst+t.cess],['Round off',t.roundOff],['Grand total',t.total]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{money(v)}</dd></div>)}</dl>;
 return <>
 <div className="ivCard ivFields">{field('number',kind==='order'?'Sales order number · automatic if blank':'Invoice number · automatic if blank')}{field('date',kind==='order'?'Sales order date':'Invoice date','date')}<label>Customer *<select required value={form.customerId} onChange={e=>chooseCustomer(e.target.value)}><option value="">Select customer</option>{customers.filter(c=>c.status!=='Inactive').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{field('reference','Reference number')}{field('billing','Billing address')}{field('shipping','Shipping address')}<label>Place of supply (state)<select required value={form.place} onChange={e=>setForm({...form,place:e.target.value})}><option value="">Select state</option>{customerStates.map(s=><option key={s}>{s}</option>)}</select></label><label>Payment terms<select value={form.terms} onChange={e=>setForm({...form,terms:e.target.value,dueDate:due(form.date,e.target.value)})}>{[0,7,15,30,45].map(d=><option key={d} value={d}>{d?'Net '+d:'Due on receipt'}</option>)}</select></label>{field('dueDate','Due date','date')}</div>
 <div className="ivCard"><div className="ivHeading"><h3>{kind==='order'?'Order items':'Invoice items'}</h3><button type="button" onClick={()=>setForm({...form,lines:[...form.lines,blankLine()]})}><IconPlus size={16}/>Add line</button></div><div className="ivScroll"><table className="ivLineTable"><thead><tr>{['Item','Quantity','Unit','Rate ₹','Discount','Tax','Amount',''].map((s,n)=><th key={n}>{s}</th>)}</tr></thead><tbody>{form.lines.map((l,n)=><tr key={n}><td><ItemSearch items={items} line={l} index={n} onSelect={item=>setForm(f=>({...f,lines:f.lines.map((x,k)=>k===n?{...x,...itemDefaults(item)}:x)}))}/></td>{['qty','unit','rate'].map(k=><td key={k}><input aria-label={k+' '+(n+1)} value={l[k]} onChange={e=>updateLine(n,k,e.target.value)}/></td>)}<td><div className="ivDiscount"><input aria-label={'Discount '+(n+1)} value={l.discount} onChange={e=>updateLine(n,'discount',e.target.value)}/><select aria-label={'Discount type '+(n+1)} value={l.discountType} onChange={e=>updateLine(n,'discountType',e.target.value)}><option>%</option><option value="fixed">₹</option></select></div></td><td><div className="ivLineTax"><TaxSelection line={l} index={n} intra={form.place.trim().toLowerCase()===config.state.trim().toLowerCase()} onChange={taxes=>updateLine(n,'taxes',taxes)}/><select aria-label={'Price tax treatment '+(n+1)} value={l.priceTaxMode||'exclusive'} onChange={e=>updateLine(n,'priceTaxMode',e.target.value)}><option value="exclusive">Tax exclusive</option><option value="inclusive">Tax inclusive</option></select></div></td><td>{preview?money(preview.lines[n].taxable):'—'}</td><td><button type="button" aria-label="Remove line" disabled={form.lines.length===1} onClick={()=>setForm({...form,lines:form.lines.filter((_,k)=>k!==n)})}><IconTrash size={16}/></button></td></tr>)}</tbody></table></div>{preview?totals(preview):<p role="status">{previewError||'Select an item and place of supply to calculate totals.'}</p>}<small>Item tax and price treatment are filled from the Item master. You can change them on this document.</small></div>
 </>;
}
