import {useMemo,useState} from 'react';
import {IconSearch,IconBuilding,IconBook,IconShoppingCart,IconBuildingBank,IconReceipt,IconPackage,IconShieldCheck,IconUsers,IconGitBranch,IconFileDescription,IconBell,IconBolt,IconPlug,IconAdjustments,IconDatabase,IconHistory,IconCheck,IconExternalLink} from '@tabler/icons-react';
import {applyAccountingSettings,numberingPreview,readSettings,validateSettings,writeSettings} from './settings-store.js';
import AccountingSettingsPanel from './AccountingSettingsPanel.jsx';
import './settings-workspace.css';
const groups=[['home','Settings home',IconAdjustments,'Central configuration and controls'],['organization','Organization',IconBuilding,'Company, regional settings and financial year'],['accounting','Accounting',IconBook,'Accounting preferences and transaction controls'],['sales','Sales & Purchases',IconShoppingCart,'Document defaults and workflow behavior'],['banking','Banking',IconBuildingBank,'Transactions, statements and reconciliation'],['expenses','Expenses',IconReceipt,'Claims, approvals and limits'],['inventory','Inventory',IconPackage,'Stock tracking and valuation'],['assets','Assets',IconBuilding,'Depreciation and disposal'],['tax','Taxes & Compliance',IconShieldCheck,'GST and TDS configuration'],['users','Users & Security',IconUsers,'Roles, access and security policy'],['approval','Approvals & Workflows',IconGitBranch,'Approval and period controls'],['documents','Documents & Templates',IconFileDescription,'Numbering and customer documents'],['notifications','Notifications',IconBell,'Delivery channels and events'],['automation','Automation',IconBolt,'Rules and recurring transactions'],['integrations','Integrations',IconPlug,'External services and API readiness'],['limits','Limits & Controls',IconAdjustments,'Transaction limits and precedence'],['data','Data & Maintenance',IconDatabase,'Import, export and storage'],['audit','Audit & Activity',IconHistory,'Settings change history']];
const words=v=>v.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());
const Page=({title,text})=><header className="swHead"><span>Settings</span><h1>{title}</h1><p>{text}</p></header>;
const Section=({title,description,children})=><section className="swSection"><header><h2>{title}</h2>{description&&<p>{description}</p>}</header><div className="swSectionBody">{children}</div></section>;
const Field=({label,help,children})=><label className="swField"><span>{label}</span>{children}{help&&<small>{help}</small>}</label>;
const Toggle=({label,description,value,onChange,disabled=false})=><label className={`swToggle ${disabled?'disabled':''}`}><span><b>{label}</b><small>{description}</small></span><input type="checkbox" checked={value} disabled={disabled} onChange={e=>onChange(e.target.checked)}/><i/></label>;
export default function SettingsWorkspace({onNavigate,notify=()=>{}}){
 const [saved,setSaved]=useState(readSettings),[draft,setDraft]=useState(readSettings),[active,setActive]=useState(()=>{try{return sessionStorage.getItem('wayvida-settings-section')||'home'}catch{return 'home'}}),[query,setQuery]=useState(''),[error,setError]=useState('');
 const dirty=JSON.stringify(saved)!==JSON.stringify(draft),set=(area,key,value)=>setDraft(x=>({...x,[area]:{...x[area],[key]:value}}));
 const visible=useMemo(()=>groups.filter(x=>(x[1]+' '+x[3]).toLowerCase().includes(query.toLowerCase())),[query]);
 function save(){const errors=validateSettings(draft);if(errors.length)return setError(errors[0]);try{applyAccountingSettings(draft);const next=writeSettings(draft);setSaved(next);setDraft(next);setError('');notify('Settings saved successfully.')}catch(e){setError(e.message)}}
 const footer=<div className="swSave"><span>{dirty?'You have unsaved changes.':'All changes saved.'}</span><button disabled={!dirty} onClick={()=>{setDraft(saved);setError('')}}>Cancel</button><button className="primary" disabled={!dirty} onClick={save}><IconCheck/>Save changes</button></div>;
 const toggles=(area)=><><div className="swToggleGrid">{Object.entries(draft[area]).filter(([,v])=>typeof v==='boolean').map(([key,value])=><Toggle key={key} label={words(key)} description={`${value?'Enabled':'Disabled'} for this company.`} value={value} onChange={v=>set(area,key,v)}/>)}</div><div className="swGrid">{Object.entries(draft[area]).filter(([,v])=>typeof v!=='boolean').map(([key,value])=><Field key={key} label={words(key)}><input type={typeof value==='number'?'number':'text'} value={value} onChange={e=>set(area,key,typeof value==='number'?Number(e.target.value):e.target.value)}/></Field>)}</div></>;
 function content(){
  if(active==='home')return <><div className="swIntro"><span>SETTINGS</span><h1>Control center</h1><p>Configure future ERP behavior without rewriting posted accounting history.</p></div><div className="swCards">{groups.slice(1).map(([id,title,Icon,desc])=><button key={id} onClick={()=>setActive(id)}><i><Icon/></i><span><b>{title}</b><small>{desc}</small></span><IconExternalLink/></button>)}</div></>;
  if(active==='organization')return <><Page title="Organization" text="Company identity, reporting calendar and regional presentation."/><Section title="Company profile"><div className="swGrid"><Field label="Company name *"><input value={draft.organization.companyName} onChange={e=>set('organization','companyName',e.target.value)}/></Field><Field label="Legal name"><input value={draft.organization.legalName} onChange={e=>set('organization','legalName',e.target.value)}/></Field><Field label="Email"><input type="email" value={draft.organization.email} onChange={e=>set('organization','email',e.target.value)}/></Field><Field label="Phone"><input value={draft.organization.phone} onChange={e=>set('organization','phone',e.target.value)}/></Field></div></Section><Section title="Financial year & region" description="Overlapping-year protection needs a production backend."><div className="swGrid"><Field label="Financial year start"><input type="date" value={draft.organization.financialYearStart} onChange={e=>set('organization','financialYearStart',e.target.value)}/></Field><Field label="Financial year end"><input type="date" value={draft.organization.financialYearEnd} onChange={e=>set('organization','financialYearEnd',e.target.value)}/></Field><Field label="Time zone"><select value={draft.organization.timezone} onChange={e=>set('organization','timezone',e.target.value)}><option>Asia/Kolkata</option><option>UTC</option></select></Field><Field label="Date format"><select value={draft.organization.dateFormat} onChange={e=>set('organization','dateFormat',e.target.value)}><option>DD/MM/YYYY</option><option>DD MMM YYYY</option><option>YYYY-MM-DD</option></select></Field><Field label="Currency"><select value={draft.organization.currency} onChange={e=>set('organization','currency',e.target.value)}><option>INR</option><option>USD</option></select></Field><Field label="Decimal places"><input type="number" min="0" max="4" value={draft.organization.decimalPlaces} onChange={e=>set('organization','decimalPlaces',Number(e.target.value))}/></Field></div><button onClick={()=>onNavigate('Branches')}>Manage branches <IconExternalLink/></button></Section>{footer}</>;
  if(active==='accounting')return <AccountingSettingsPanel draft={draft} set={set} setDraft={setDraft} onNavigate={onNavigate} footer={footer}/>;
  if(active==='documents')return <><Page title="Documents & Templates" text="Configure future identifiers and customer-facing output."/><Section title="Document numbering" description="Existing posted document numbers remain unchanged."><div className="swNumbering">{Object.entries(draft.numbering).map(([key,item])=><div key={key}><header><b>{words(key)}</b><span>{numberingPreview(item)}</span></header><Field label="Pattern"><input value={item.pattern} onChange={e=>setDraft(x=>({...x,numbering:{...x.numbering,[key]:{...item,pattern:e.target.value}}}))}/></Field><Field label="Reset frequency"><select value={item.reset} onChange={e=>setDraft(x=>({...x,numbering:{...x.numbering,[key]:{...item,reset:e.target.value}}}))}><option>Never</option><option>Financial Year</option><option>Yearly</option><option>Monthly</option></select></Field></div>)}</div><p className="swHint">Tokens: {'{FY} {YYYY} {YY} {MM} {DD} {BRANCH_CODE} {COMPANY} {SERIES}'}</p></Section>{footer}</>;
  const mapped={sales:'sales',banking:'banking',expenses:'expenses',inventory:'inventory',assets:'assets',tax:'tax',notifications:'notifications',automation:'automation'};
  if(mapped[active])return <><Page title={groups.find(x=>x[0]===active)[1]} text="Changes apply to future activity; posted history remains unchanged."/><Section title="Preferences">{toggles(mapped[active])}{active==='inventory'&&!draft.inventory.enabled&&<p className="swHint">Enable Inventory before using stock tracking and valuation controls.</p>}</Section>{footer}</>;
  return <><Page title={groups.find(x=>x[0]===active)[1]} text={groups.find(x=>x[0]===active)[3]}/><Section title={active==='data'?'Prototype data controls':'Configuration status'}><div className="swUnavailable"><IconShieldCheck/><div><b>{active==='data'?'Local prototype storage':'Backend capability required'}</b><p>{active==='data'?'Data is stored in this browser. Server backups and recoverable imports are required before production.':'This area is intentionally not simulated because secure identity, authorization, delivery, integrations, or immutable audit infrastructure is not connected.'}</p></div></div>{active==='approval'&&<button onClick={()=>onNavigate('Period Closing')}>Manage period approvals <IconExternalLink/></button>}</Section></>;
 }
 return <section className="sw"><aside><div className="swSearch"><IconSearch/><input aria-label="Search settings" placeholder="Search settings" value={query} onChange={e=>setQuery(e.target.value)}/></div><nav aria-label="Settings navigation">{visible.map(([id,title,Icon])=><button className={active===id?'active':''} key={id} onClick={()=>setActive(id)}><Icon/><span>{title}</span></button>)}</nav></aside><main>{error&&<div className="swError" role="alert">{error}</div>}{content()}</main></section>;
}
