import {useDeferredValue,useEffect,useMemo,useState} from 'react';
import {IconAdjustments,IconAlertTriangle,IconCheck,IconFileSpreadsheet,IconFileTypePdf,IconRefresh,IconSearch} from '@tabler/icons-react';
import {readAccounts} from './account-store.js';
import {initial,money,today} from './invoice-engine.js';
import {readVendors} from './vendor-store.js';
import {AGING_BUCKETS,AGING_LABELS,BILL_STATUSES,supplierOutstanding,supplierOutstandingExportRows} from './supplier-outstanding.js';
import {downloadReport,excelReport} from './daybook-export.js';
import {demoOrganizations} from './demo-organisations.js';
import EmptyState from './EmptyState.jsx';
import './supplier-outstanding.css';
import {AsOfDateSelect,ReportExportMenu} from './ReportToolbar.jsx';

const ALL='All';
const DASH='—';

const readSuppliers=()=>{try{return readVendors()||[]}catch{return []}};

export default function SupplierOutstanding({notify,onNavigate}){
  const [revision,setRevision]=useState(0),[asOf,setAsOf]=useState(today()),[branch,setBranch]=useState(ALL),[supplier,setSupplier]=useState(ALL),[status,setStatus]=useState(ALL),[aging,setAging]=useState(ALL),[search,setSearch]=useState(''),[filtersOpen,setFiltersOpen]=useState(false),[stamp,setStamp]=useState(()=>new Date());
  const deferredSearch=useDeferredValue(search),busy=deferredSearch!==search;
  const organization=demoOrganizations.find(item=>item.id===localStorage.getItem('wayvida-demo-company'))||demoOrganizations[0];

  useEffect(()=>{const refresh=()=>setRevision(x=>x+1);window.addEventListener('wayvida-accounts-updated',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('wayvida-accounts-updated',refresh);window.removeEventListener('storage',refresh)}},[]);

  const {book,suppliers,error}=useMemo(()=>{try{return {book:readAccounts(),suppliers:readSuppliers(),error:''}}catch(e){return {book:initial(),suppliers:[],error:e.message}}},[revision]);
  const report=useMemo(()=>supplierOutstanding(book,suppliers,{asOf,branch,supplier,status,aging,search:deferredSearch}),[book,suppliers,asOf,branch,supplier,status,aging,deferredSearch]);
  const branches=[...new Set([...(organization.branches||[]).map(item=>item.name),...report.branchOptions])];

  function reset(){setAsOf(today());setBranch(ALL);setSupplier(ALL);setStatus(ALL);setAging(ALL);setSearch('')}
  function refresh(){setRevision(x=>x+1);setStamp(new Date())}
  function exportExcel(){const content=excelReport(supplierOutstandingExportRows(report,{organisation:organization.name,generatedBy:'Local user',generatedAt:stamp.toISOString()}));downloadReport(content,'wayvida-supplier-outstanding.xml','application/xml;charset=utf-8')}
  function print(){setStamp(new Date());setTimeout(()=>window.print(),50)}
  function printMeta(){return [['Wayvida Books · Supplier Outstanding','See what you currently owe your suppliers.'],['Organisation',organization.name],['Branch',branch===ALL?'All branches':branch],['As of',asOf],['Supplier',supplier===ALL?'All suppliers':(report.suppliers.find(entry=>entry.id===supplier)?.name||supplier)],['Status',status===ALL?'All':status],['Aging',aging===ALL?'All':AGING_LABELS[aging]||aging],['Search',search||'None'],['Documents',status===ALL?'Outstanding only':status],['Total payable',money(report.totals.outstanding)],['Accounts Payable control',report.reconciliation.control===null?'Not configured':money(report.reconciliation.control)],['Difference',report.reconciliation.difference===null?'Unknown':money(Math.abs(report.reconciliation.difference))],['Generated by Local user',stamp.toLocaleString()]]}

  const activeFilters=[branch!==ALL,supplier!==ALL,status!==ALL,aging!==ALL].filter(Boolean).length;

  const supplierRow=entry=>(
    <tr key={entry.id} className="spoSupplier">
      <th scope="row" className="spoNameCell"><span>{entry.name}</span></th>
      <td className="spoCodeCol">{entry.code||DASH}</td>
      <td className="spoMoney spoCountCol">{entry.bills}</td>
      <td className="spoMoney spoStrong spoOutCol">{money(entry.outstanding)}{aging!==ALL&&<em className="spoAgingHint">{AGING_LABELS[aging]}: {money(entry.agingAmount)}</em>}</td>
      <td className="spoMoney spoDueCol">{money(entry.overdue)}</td>
      <td className="spoMoney spoDueCol">{money(entry.notYetDue)}</td>
    </tr>
  );

  const reconciliation=report.reconciliation;

  return (
    <section className="spoPage" aria-busy={busy}>
      <header className="spoHead">
        <div><h1>Supplier Outstanding</h1><p>See what you currently owe your suppliers.</p></div>
        <div className="spoHeadActions">
          <AsOfDateSelect date={asOf} onChange={value=>setAsOf(value)} onCustom={()=>setFiltersOpen(true)}/>
          <details className="spoFiltersMore" open={filtersOpen} onToggle={e=>setFiltersOpen(e.currentTarget.open)}>
            <summary aria-label="Open filters"><IconAdjustments size={17}/>Filters{activeFilters>0&&<span>{activeFilters}</span>}</summary>
            <div className="spoFilters">
              <label>As of Date<input type="date" aria-label="As of Date" value={asOf} onChange={e=>setAsOf(e.target.value)}/></label>
              <label>Branch<select aria-label="Branch" value={branch} onChange={e=>setBranch(e.target.value)}><option value={ALL}>All branches</option>{branches.map(item=><option key={item} value={item}>{item}</option>)}</select></label>
              <label>Status<select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option value={ALL}>All</option>{BILL_STATUSES.map(item=><option key={item} value={item}>{item}</option>)}</select></label>
              <label>Aging<select aria-label="Aging" value={aging} onChange={e=>setAging(e.target.value)}><option value={ALL}>All</option>{AGING_BUCKETS.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></label>
              <label>Supplier<select aria-label="Supplier" value={supplier} onChange={e=>setSupplier(e.target.value)}><option value={ALL}>All suppliers</option>{report.supplierOptions.map(item=><option key={item.id} value={item.id}>{item.code?item.code+' · '+item.name:item.name}</option>)}</select></label>
              <div className="spoFilterActions"><button type="button" onClick={refresh}><IconRefresh size={15}/>Refresh</button><button type="button" onClick={reset}>Clear filters</button></div>
            </div>
          </details>
          <ReportExportMenu items={[{key:'excel',label:'Export Excel',icon:<IconFileSpreadsheet size={17}/>,onClick:exportExcel,disabled:!report.suppliers.length},{key:'pdf',label:'Export PDF',icon:<IconFileTypePdf size={17}/>,onClick:print,disabled:!report.suppliers.length}]}/>
        </div>
      </header>

      {error&&<div className="spoError" role="alert"><IconAlertTriangle size={18}/><span>{error}</span></div>}
      <div className="spoPrintMeta">{printMeta().map(([label,value])=><p key={label}><b>{label}:</b> {value}</p>)}</div>

      <div className="spoSummary">
        <div><span>Total Payable</span><strong>{money(report.totals.outstanding)}</strong></div>
        <div><span>Overdue</span><strong>{money(report.totals.overdue)}</strong></div>
        <div><span>Due Today</span><strong>{money(report.totals.dueToday)}</strong></div>
        <div><span>Not Yet Due</span><strong>{money(report.totals.notYetDue)}</strong></div>
      </div>

      <div className="spoStatementCard">
        <div className="spoTableScroll">
          <table>
            <thead><tr><th className="spoNameCol">Supplier</th><th className="spoCodeCol">Supplier ID</th><th className="spoCountCol">Bills</th><th className="spoOutCol">Outstanding</th><th className="spoDueCol">Overdue</th><th className="spoDueCol">Not Yet Due</th></tr></thead>
            <tbody>
              {report.suppliers.map(supplierRow)}
              {!report.suppliers.length&&<tr className="emptyStateRow"><td colSpan="6" className="emptyStateCell"><EmptyState variant="customer" title="No outstanding supplier balances found." description="Try changing the date or filters." actionLabel="Reset filters" onAction={reset}/></td></tr>}
            </tbody>
            {report.suppliers.length>0&&(
              <tfoot>
                <tr className="spoGrandTotal">
                  <th colSpan="2" className="spoNameCol" scope="row">Total</th>
                  <th className="spoMoney spoCountCol">{report.totals.bills}</th>
                  <th className="spoMoney spoOutCol">{money(report.totals.outstanding)}</th>
                  <th className="spoMoney spoDueCol">{money(report.totals.overdue)}</th>
                  <th className="spoMoney spoDueCol">{money(report.totals.notYetDue)}</th>
                </tr>
              </tfoot>
            )}
          </table>
        </div>
      </div>

      <div className={'spoEquation spoStickyBalance '+(reconciliation.difference===null?'unknown':reconciliation.reconciled?'balanced':'mismatch')} role="status">
        {reconciliation.difference===null?<IconAlertTriangle size={19}/>:reconciliation.reconciled?<IconCheck size={19}/>:<IconAlertTriangle size={19}/>}
        <b>{reconciliation.difference===null?'No Accounts Payable control account is configured':(reconciliation.reconciled?'Reconciles':'Does not reconcile')}</b>
        <span>{reconciliation.difference===null?'Control: not configured':'Difference: '+money(Math.abs(reconciliation.difference))}</span>
      </div>
    </section>
  );
}
